### ISSUE TITLE
Lỗi mất chữ tiếng việt khi gõ in hoa

### ISSUE THREAD

**Issue by vinhtq115** [BambooEngine/ibus-bamboo#100]
**Mô tả lỗi**
Lỗi mất chữ tiếng việt khi gõ in hoa

**Các bước tái hiện lỗi**
Ví dụ:
1. Mở Firefox
2. Gõ Đ bằng cách giữ Shift và nhấn D 2 lần vào thanh địa chỉ
3. Mất Đ

**Kết quả mong muốn**
Phải thấy Đ chứ không phải bị mất chữ

**Ảnh chụp màn hình, hoặc clip quay màn hình**
N/a

**Môi trường**
 - OS và version: Ubuntu 19.10
 - Desktop: **mặc định**
 - Phiên bản ibus-bamboo: 0.6.2 (commit từ master@bc445e3)

**Thông tin thêm**
Khi gõ backspace thì D lại hiện ra.
Lỗi áp dụng cho ê hoa, â hoa, ă hoa, ư hoa, ...
Ngoài ra, gõ lỗ (ỗ viết hoa, do máy mình đang bị lỗi này nên không viết đuợc) thì bị mất từ đang gõ.

**Comment by luongthanhlam** [comment]
Cảm ơn bạn, lỗi đã được fix ở bản v0.6.2 rồi nhé!
