### ISSUE TITLE
Layout default khác với qwerty v0.62

### ISSUE THREAD

**Issue by long21wt** [BambooEngine/ibus-bamboo#101]
Layout bị chuyển thành English US mặc dù mình đang dùng layout DE, phiên bản 0.61 không có vấn đề này, nhưng khi cập nhật lên 0.62 thì bị.
Ở thanh lựa chọn layout gõ thì ShowKeyboardLayout là English US ở v0.62 còn các bản trước đó không hiện gì. 
Hiện tại mình đang dùng lại bản 0.60 và không có vấn đề gì cả. 

**Môi trường**
 - OS : Fedora 31
 - Desktop: GNOME 3.34
 - Phiên bản ibus-bamboo: v0.62

**Thông tin thêm**
Ibus-bamboo được mình tải từ git trước đó mình đang dùng bản tải từ OpenBuildService

**Comment by luongthanhlam** [comment]
Tạm thời bạn có thể khắc phục bằng cách sửa `layout` trong file `/usr/share/ibus/component/bamboo.xml` từ `us` thành `default`
