### ISSUE TITLE
[Manjaro Deepin] Android Studio không detect Ibus

### ISSUE THREAD

**Issue by vmtran123** [BambooEngine/ibus-bamboo#102]
> Mình cài Android Studio từ snap nhưng không nhận được Ibus. 
---
Đây là thông tin OS và config của mình:
> -OS: Manjaro Deepin 18.1.3
> -Ibus-Bamboo  0.6.2-1
> -Android Studio 3.5.2.0
> -config trong .bashrc:
> export XMODIFIERS="@im=ibus"
> export GTK_IM_MODULE=ibus
> export QT_IM_MODULE=ibus
> export QT4_IM_MODULE=ibus
> export IBUS_ENABLE_SYNC_MODE=1
---
Mong được giúp đỡ!

**Comment by luongthanhlam** [comment]
bạn xem ở đây nhé https://github.com/bambooengine/ibus-bamboo/wiki/T%E1%BA%A1i-sao-kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-Vi%E1%BB%87t-trong-%E1%BB%A9ng-d%E1%BB%A5ng-snap%3F
