### ISSUE TITLE
không gõ đuợc tiếng việt trên Kali Linux 2019.3

### ISSUE THREAD

**Issue by oldman20** [BambooEngine/ibus-bamboo#104]
**Mô tả lỗi**
không gõ đuợc tiếng việt trên Kali Linux 2019.3 trong bất kỳ trình gõ văn bản hay trình duyệt nào, không rõ do OS hay bug của bamboo 

**Các bước tái hiện lỗi**
đã bật ibus bằng lệnh ibus-setup và chọn các kiểu gõ TELEX x, y, z...
1. Mở textedit, firefox
2. Gõ oo, aw
...
4. Thấy xyz

**Kết quả mong muốn**
ô, ă
Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Ví dụ: Gõ oo, aw thì phải thấy ô, ă chứ không phải oo, aw

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: (Kali 2019.3 64bit)
![Screenshot-20191129154419-1366x768](https://user-images.githubusercontent.com/39668756/69899724-216ff500-139d-11ea-835f-694138ea23e5.png)

 - Desktop: ( **mặc định**)
 - Phiên bản ibus-bamboo: (bản mới nhất v0.6.2)
![Screenshot-20191129154307-1366x768](https://user-images.githubusercontent.com/39668756/69899723-20d75e80-139d-11ea-97ae-eb3c1903dd87.png)

**Comment by luongthanhlam** [comment]
bạn gửi mình output 3 lệnh này nhé
```
env | grep "IM_MODULE\|XMODIFERS"
ps -ef | grep ibus
cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
```

**Comment by oldman20** [comment]
đây bạn ơi, mình gửi 3 kq nhé, k bt làm sao để sd đc nữa :( thanks bạn
chuctran@chuc:~$ env | grep "IM_MODULE\|XMODIFERS"
GTK_IM_MODULE=ibus
QT4_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
QT_IM_MODULE=ibus
chuctran@chuc:~$ ps -ef | grep ibus
Debian-+     995     981  0 01:50 tty1     00:00:00 ibus-daemon --xim --panel disable
Debian-+     998     995  0 01:50 tty1     00:00:00 /usr/lib/ibus/ibus-memconf
Debian-+    1000     995  0 01:50 tty1     00:00:01 /usr/lib/ibus/ibus-extension-gtk3
Debian-+    1003       1  0 01:50 tty1     00:00:00 /usr/lib/ibus/ibus-x11 --kill-daemon
Debian-+    1007     803  0 01:50 ?        00:00:00 /usr/lib/ibus/ibus-portal
Debian-+    1142     995  0 01:50 tty1     00:00:00 /usr/lib/ibus/ibus-engine-simple
chuctran    1288       1  0 01:51 ?        00:00:00 /usr/bin/ibus-daemon --daemonize --xim
chuctran    1309    1288  0 01:51 ?        00:00:00 /usr/lib/ibus/ibus-memconf
chuctran    1310    1288  0 01:51 ?        00:00:00 /usr/lib/ibus/ibus-ui-gtk3
chuctran    1315    1288  0 01:51 ?        00:00:01 /usr/lib/ibus/ibus-extension-gtk3
chuctran    1318       1  0 01:51 ?        00:00:00 /usr/lib/ibus/ibus-x11 --kill-daemon
chuctran    1321    1166  0 01:51 ?        00:00:00 /usr/lib/ibus/ibus-portal
chuctran    1366    1288  0 01:51 ?        00:00:00 /usr/lib/ibus/ibus-engine-simple
chuctran    1668    1288  0 01:51 ?        00:00:01 /usr/lib/ibus-engine-bamboo --ibus
chuctran    2352    1801  0 02:06 pts/0    00:00:00 grep ibus
chuctran@chuc:~$ cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
{
  "InputMethod": "Telex",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex W": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode",
  "Flags": 7,
  "IBflags": 282992,
  "JupiterFlags": 0,
  "DefaultInputMode": 1,
  "InputModeMapping": {},
  "ExceptedList": null,
  "PreeditWhiteList": null,
  "X11ClipboardWhiteList": null,
  "ForwardKeyWhiteList": null,
  "SLForwardKeyWhiteList": null,
  "DirectForwardKeyWhiteList": null,
  "SurroundingTextWhiteList": null
}chuctran@chuc:~$

**Comment by oldman20** [comment]
mình đã cài thành công rồi ad ạ, lệnh bị thiếu file gtk3
