### ISSUE TITLE
Bị lộ password khi bộ gõ tiếng việt kích hoạt trong màn hình Lock Screen

### ISSUE THREAD

**Issue by apkcombodev** [BambooEngine/ibus-bamboo#105]
**Mô tả lỗi**
Ở màn hình Lock Screen khi gõ password bị lộ mật khẩu do preedit.

**Các bước tái hiện lỗi**
1. Ctrl + Alt + L để hiện màn hình Lock Screen.
2. Gõ mật khẩu sẽ bị lộ mật khẩu nhìn thấy khi chưa bấm Ctrl để commit.

**Kết quả mong muốn**
- Không kích hoạt gõ tiếng việt trong màn hình Lock Screen.
- Hướng dẫn bổ sung màn hình Lock Screen vào danh sách loại trừ

**Môi trường**
 - OS và version: Ubuntu Mate 18.04

**Comment by luongthanhlam** [comment]
Bạn đang gặp vấn đề với tính năng Thêm vào danh sách loại trừ trong màn hình khóa của Ubuntu Mate? Bạn có thể gửi ảnh chụp màn hình để mô tả rõ hơn được không?

**Comment by phingocchi** [comment]
Ảnh chụp màn hình đây bạn nhé: https://imgur.com/pAA1DKT
Ubuntu Mate và Linux Mint Mate đều gặp vấn đề này.
Mình không biết process name và window name của màn hình Lock Screen này là gì nên không add vào thủ công được. Dùng Shift + ~ trong màn hình Lockscreen cũng không hiện để thêm vào danh sách loại trừ.

**Comment by Someone8859** [comment]
Bạn có thấy phần bị gạch chân mà để lộ mật khẩu của bạn không? Đó là một lỗi có trên ibus-unikey và ibus-bamboo hàng đời rồi. Phần đã được che thì nó đã ở trên chỗ đánh mật khẩu của lock screen, còn phần chữ chưa bị che và có gạch chân thì mặc dù bạn nhìn thấy ở đó nhưng nó chưa thực sự ở trên chỗ nhập mật khẩu ở lock screen đâu. Thực ra lỗi này bị cả trên sudo nữa và một số chỗ khác.

**Comment by xdorro** [comment]
Em mới cài bản mới nhất và xác nhận lỗi này vẫn tồn tại. Nhiều khi bị lỗi lộ mật khẩu rất khó chịu

**Comment by goatastronaut0212** [comment]
Mình thắc mắc chuyện gì đã và đang xảy ra với lỗi này và nó vẫn còn tồn tại mà không có 1 cách giải quyết nào khác? Về cơ bản mình không xài lockscreen nhưng việc lộ 1 vài chữ trên terminal sudo cũng hơi khó chịu dù nó không phải quá to tát. Mình không nghĩ được 1 cách giải quyết nào hay ho cho lắm nhưng mình vẫn chưa hình dung là chúng ta sẽ phải làm thế nào để có thể giải quyết triệt để báo cáo lỗi này.

**Comment by hahahahacker2009** [comment]
nó được gọi là preedit... cái từ bạn vừa nhập vào thì phần mềm hoàn toàn
chưa nhận được
và sẽ hiện lên như thế

Vào Th 7, 11 thg 5, 2024 vào lúc 21:57 The Little Waltz <
***@***.***> đã viết:

**Comment by goatastronaut0212** [comment]
> nó được gọi là preedit... cái từ bạn vừa nhập vào thì phần mềm hoàn toàn chưa nhận được và sẽ hiện lên như thế Vào Th 7, 11 thg 5, 2024 vào lúc 21:57 The Little Waltz < ***@***.***> đã viết:

Thế thì có vẻ chỉ cần chuyển sang mode  2 sửa lỗi gạch chân nghe có vẻ hợp lý mà.

**Comment by goatastronaut0212** [comment]
Mình thấy các lock screen phiên bản mới đều có thể ngăn chặn việc này. Mình đã test thử nhưng có vẻ không thể gõ tiếng việt và hiện chữ trên Ubuntu Mate phiên bản 24.04 nữa.

Còn cái việc gõ hiện password trên terminal khá đơn giản. Chỉ cần switch sang tiếng anh là xong hay thêm vào danh sách loại trừ. 1 số terminal như wezterm đã có 1 vài tính năng ngăn chặn hiển thị rồi nên cũng không cần thiết. Mình thấy việc để mở issue này không còn ý nghĩa gì nữa lắm. Tốt nhất nên đóng lại sẽ tốt hơn.

**Comment by goatastronaut0212** [comment]
Nếu vẫn còn có lỗi hãy mở lại 1 báo cáo lỗi mới. Mình sẽ đóng lại cái này
