### ISSUE TITLE
Phím Super không nhận khi đang keyboard focus ở textbox đang gõ Tiếng Việt

### ISSUE THREAD

**Issue by kuroni** [BambooEngine/ibus-bamboo#106]
**Mô tả lỗi**
Khi mình gõ tiếng Việt ở một textbox bất kì (ví dụ như gedit), thì phím Super không đem mình về GNOME Shell. Mình phải click chuột vào đâu đó (kể cả lên phần textbox như nêu trên) thì phím Super mới nhận.

**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
Ví dụ:
1. Mở gedit
2. Gõ bất kì 
3. Nhấn phím Super

**Kết quả mong muốn**
Phím Super phải đem mình trở về GNOME Shell.

**Môi trường**
 - OS và version: Arch Linux
 - Desktop: GNOME
 - Phiên bản ibus-bamboo: 0.6.3

**Comment by luongthanhlam** [comment]
Với Gnome bạn chỉ cần vào cài đặt của bộ gõ tắt tùy chọn Capture mouse events là được nhé.

**Comment by kuroni** [comment]
Cảm ơn bạn nhé!
