### ISSUE TITLE
Không gõ được tiếng việt trên kali linux

### ISSUE THREAD

**Issue by phatbs21** [BambooEngine/ibus-bamboo#107]
Tình hình là em đã chạy ngược xuôi trên mấy trang web cũng như group
cài đặt theo hướng dẫn kể cả reboot máy nhiều lần nhưng vẫn không gõ được tiếng việt
Có cách nào khắc phục được không ạ ?

**Comment by luongthanhlam** [comment]
Bạn thử cài thêm gói ibus-gtk3 xem `sudo apt install ibus-gtk3`
