### ISSUE TITLE
làm sao thêm terminal vào chế độ thêm vào danh sách loại trừ?

### ISSUE THREAD

**Issue by oldman20** [BambooEngine/ibus-bamboo#108]
Chào bạn, mình có đọc HDSD của ibus bamboo thấy có mục chế độ thêm vào danh sách loại trừ, nhưng mình không biết ở mục nào cả? mình muốn khi gõ trên terminal thì sẽ luôn gõ tiếng anh chứ không phải tiếng việt (khi ibus bamboo đang chạy!)
Cám ơn tác giả

**Comment by luongthanhlam** [comment]
bạn nhấn Shift+~ nhấn tiếp phím 7 để thêm ứng dụng bạn đang gõ vào danh sách loại trừ nhé.

**Comment by oldman20** [comment]
thanks bạn nhé! Nhưng bạn ơi, trên terminal thì không làm như vậy đc bạn ạ?

**Comment by oldman20** [comment]
và nếu muốn xóa ứng dụng khỏi danh sách loại trừ thì sao vậy bạn?

**Comment by luongthanhlam** [comment]
> thanks bạn nhé! Nhưng bạn ơi, trên terminal thì không làm như vậy đc bạn ạ?

bạn đang dùng terminal nào? 

> và nếu muốn xóa ứng dụng khỏi danh sách loại trừ thì sao vậy bạn?

nhấn phím 1 :)

**Comment by oldman20** [comment]
> > thanks bạn nhé! Nhưng bạn ơi, trên terminal thì không làm như vậy đc bạn ạ?
> 
> bạn đang dùng terminal nào?
> 
> > và nếu muốn xóa ứng dụng khỏi danh sách loại trừ thì sao vậy bạn?
> 
> nhấn phím 1 :)

mình dùng terminal mặc định trên kali 2019.4 gnome bạn ạ!
![Screenshot 2019-12-26 21:50:48](https://user-images.githubusercontent.com/39668756/71480058-d0cbaa80-2829-11ea-95f4-9fe7fe185701.png)

**Comment by luongthanhlam** [comment]
bạn gửi mình output lệnh này nhé `env | grep "IM_MODULE\|XMODIFERS"`

**Comment by oldman20** [comment]
đây bạn ạ!
chuctran@chuc:~$ env | grep "IM_MODULE\|XMODIFERS"
GTK_IM_MODULE=ibus
QT4_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
QT_IM_MODULE=ibus

**Comment by ngcngmnh** [comment]
nếu Shift+~ không được thì bạn chỉnh trong `~/.config/ibus-bamboo/ibus-bamboo.config.json` nhé

**Comment by ndgnuh** [comment]
Bạn set thiếu biến XMODIFERS kìa. Với cả chạy ibus bằng `ibus-daemon -rdx`, thiếu cái `x` là 1 số ứng dụng sẽ không dùng ibus

**Comment by oldman20** [comment]
> ~/.config/ibus-bamboo/ibus-bamboo.config.json

case cuả mình à bạn?

**Comment by ndgnuh** [comment]
Bạn vào menu của Bamboo, phần phím tắt và chọn sử dụng `Shift + ~` để chuyển chế độ xem có được không

**Comment by luongthanhlam** [comment]
mình test thử thì tính năng thêm vào ds loại trừ vẫn hoạt động bình thường trên kali 2019.4 gnome

![Screenshot from 2020-03-18 14-15-24](https://user-images.githubusercontent.com/26364140/76935059-fba63600-6922-11ea-8919-63b88dd5f80b.png)

**Comment by trandathust** [comment]
@luongthanhlam  mình lại gặp lỗi không gõ được tiếng việt trên VS code Ubuntu 20.04. file cấu hình không hề set vscode vào danh sách loại trừ. Đã thử remove ibus và vscode đi cài lại nhưng không được. Nhấn Shift + ~ nhưng vscode chỉ hiện ~ mà không hiện menu lựa chọn. 
File config: 
  "OutputCharset": "Unicode",
  "Flags": 7,
  "IBflags": 184688,
  "JupiterFlags": 0,
  "DefaultInputMode": 1,
  "InputModeMapping": {
    "gnome-terminal-server:Gnome-terminal": 1,
  }

**Comment by luongthanhlam** [comment]
@tranvdat @oldman20 mọi người vào cài đặt, đặt lại phím tắt khác xem có còn bị không nhé
