### ISSUE TITLE
Hoàn trả ký tự khi gõ chữ "sạc"

### ISSUE THREAD

**Issue by ncdduy** [BambooEngine/ibus-bamboo#109]
**Mô tả lỗi**
Khi gõ chữ "sạc", bộ kiểm tra chính tả hoàn tác thành "sajc" hoặc "sacj" hoặc "sacjj".

**Các bước tái hiện lỗi**
Ở 2 trường hợp đầu là gõ thường, với trường hợp ra "sacjj":
1. Chọn bộ gõ "telex", mã "Unicode"
2. Bật "Bật kiểm tra chính tả" và "Sử dụng từ điển".
3. Bật bỏ "Dấu tự do", "Dấu thanh chuẩn" và "Ẩn gạch chân".
4. Gõ lần lượt s - a - c - j
5. Gõ j một lần nữa
6. Gõ backspace (xóa).
7. Gõ j sau đó gõ space (dấu cách).

**Kết quả mong muốn**
Gõ s - a - c - j phải cho ra "sạc".

**Môi trường**
 - OS và version: Manjaro 19.2
 - Desktop: KDE
 - Phiên bản ibus-bamboo: v0.6.3

**Thông tin thêm**
Cài đặt từ AUR repos.

p/s: mình đã update lại các bước tái hiện nhé

**Comment by luongthanhlam** [comment]
bạn có đang bật tính năng Kiểm tra chính tả bằng từ điển không?

**Comment by ncdduy** [comment]
mình có, có vẻ là từ điển check thiếu

**Comment by ndgnuh** [comment]
Theo mình nhận thấy là nếu gõ sai mà không xoá kí tự đi (nhưng không xoá đến dấu cách), thì sẽ không gõ được tiếp tiếng Việt vào từ đó nữa. Vậy nên gõ sai thì mình toàn `Ctrl + W` xoá cả từ đi gõ lại.

**Comment by luongthanhlam** [comment]
> mình có, có vẻ là từ điển check thiếu

hoặc `xạc` mới là từ đúng :|

> Theo mình nhận thấy là nếu gõ sai mà không xoá kí tự đi (nhưng không xoá đến dấu cách), thì sẽ không gõ được tiếp tiếng Việt vào từ đó nữa. Vậy nên gõ sai thì mình toàn `Ctrl + W` xoá cả từ đi gõ lại.

tái hiện thế nào nhỉ?

**Comment by ncdduy** [comment]
> hoặc `xạc` mới là từ đúng :|

Mình tra lại từ điển cồ việt thì cả 2 từ này đều tồn tại. `xạc` là mắng chửi, còn `sạc` là nạp :v 
http://tratu.coviet.vn/hoc-tieng-anh/tu-dien/lac-viet/V-V/x%e1%ba%a1c.html
http://tratu.coviet.vn/hoc-tieng-anh/tu-dien/lac-viet/V-V/s%e1%ba%a1c.html
Hy vọng từ điển của bamboo đủ bộ từ :D

**Comment by ndgnuh** [comment]
> tái hiện thế nào nhỉ?

Sorry, có vẻ như cái này do dạo này lười không chạy update, khi update bản mới thì nó hết rồi :v (gói downstream mình vẫn update nhé)

**Comment by luongthanhlam** [comment]
@ndgnuh mình kiểm tra lại thì vẫn còn lỗi ở chế độ gõ số 2 và 6 https://github.com/BambooEngine/ibus-bamboo/commit/754e22ee343dea740ed9eefb0804f08d8a8e115e
@nopain2110 đã cập nhật lại từ điển :D
