### ISSUE TITLE
Lỗi không gõ được phím số ở kiểu gõ VNI, dấu cách bị chèn bên trái từ đang gõ...

### ISSUE THREAD

**Issue by hiepvu91945** [BambooEngine/ibus-bamboo#11]
**Mô tả lỗi**
**Lỗi 1**: Không gõ được phím số ở kiểu gõ VNI cả 4 chế độ Pre-edit (default), Surrounding text, IBus Forward key event, X11 Clipboard
Sử dụng bộ gõ ở kiểu gõ VNI (hoặc VNI kết hợp với kiểu gõ khác), hàng phím số chỉ có tác dụng để bỏ dấu, còn gõ vậy phím số thì không hiển thị gì.
**Lỗi 2**: Chế độ gõ: Pre-edit (default)
Khi gõ 1 từ (từ này hiện đang bị gạch chân), sau đó bấm phím SPACE, thì dấu cách này lại chèn ở phía trái, đứng trước từ này.
Bên cạnh đó, vẫn còn hiện tượng gạch chân dù có chế độ xóa gạch chân.
Lưu ý:
Lỗi 2 chỉ xảy ra trong những phần mềm nền Java, GTK như: XDM downloader, gedit, Libreoffice, Firefox, Chrome, phần mềm nền Qt như FeatherPad, Kid3, Kdenlive...không bị.
Khắc phục bằng cách phải bấm Ctrl trước khi bấm phím SPACE.
**Lỗi 3**: Chế độ gõ:  Surrounding text
Bị lặp lại chữ cái cấu thành lên từ tiếng Việt đó. Ví dụ: Gõ từ "Sắc" thì sẽ hiển thị là "Saăắc"
Lưu ý:
Lỗi 3 chỉ xảy ra trong những phần mềm nền Java, GTK như: XDM downloader, gedit, Libreoffice, Firefox, Chrome, phần mềm nền Qt như FeatherPad, Kid3, Kdenlive...không bị.
**Lỗi 4**: Chế độ gõ:  IBus Forward key event
Bị lặp lại chữ cái cấu thành lên từ tiếng Việt đó. Ví dụ: Gõ từ "Sắc" thì sẽ hiển thị là "Saăắc" trong phần mềm nền Qt.
Phần mềm nền Java, GTK thì Libreoffice không gõ được tiếng Việt. Chrome không gõ được vần "ươ" nếu gõ "uo7" (kiểu VNI) hay "uow" (Telex) ở thanh địa chỉ sẽ ra "uư". Phải gõ "u7o7" (vni) hay "uwow" (telex) thì mới được. Chrome khi gõ "uô" và dấu huyền ở thanh địa chỉ sẽ ra "uù".
**Lỗi 5**: Chế độ gõ:  X11 Clipboard
Trong Libreoffice, bấm đè BACKSPACE ngay khi gõ xong 1 từ để xóa từ đó đi thì xuất hiện bảng thông báo lỗi: "Requested clipboard format is not available."
Không bấm đè BACKSPACE để xóa liên tục ngay khi vừa gõ xong được, sẽ bị dừng lại.

**Các bước tái hiện lỗi**
Video mô tả
**Kết quả mong muốn**
Video mô tả
**Ảnh chụp màn hình, hoặc clip quay màn hình**
link youtube [quay lại màn hình]
https://www.youtube.com/watch?v=uj9puNNiqik&feature=youtu.be
**Môi trường**
 - OS và version: MX Linux 18.1 Continuum x86_64; Kernel: 4.19.0-1-amd64
 - Desktop: Xfce
 - Phiên bản ibus-bamboo: v0.3.0

**Thông tin thêm**
Video mô tả

**Comment by hiepvu91945** [comment]
### Cập nhật: ibus-bamboo v0.3.2

**Lỗi 1: Không gõ được phím số ở kiểu gõ VNI**
Đã khắc phục.
**Lỗi 2: Pre-edit (default)**
**Trên môi trường:**

- OS và version: MX Linux 18.1 Continuum x86_64; Kernel: 4.19.0-1-amd64

- Desktop: Xfce

Vẫn xuất hiện.
Lưu ý:
**Trên môi trường:** 

- OS và version: Manjaro Linux x86_64; Kernel: 4.19.28-1-MANJARO

- Desktop: Deepin

Phần mềm GTK như gedit, nautilus gõ hoàn toàn bình thường ở chế độ mặc định, không bị dấu cách chèn phía trước, cũng không bị hiện tượng gạch chân khi mở ẩn gạch chân.
Libreoffice, Firefox, Chrome thì không bị dấu cách chèn phía trước, nhưng lại bị hiện tượng gạch chân dù mở ẩn gạch chân.
Riêng phần mềm java XDM downloader trên cả 2 môi trường vẫn bị dấu cách chèn phía trước và hiện tượng gạch chân.
**Lỗi 3: Surrounding text**
**Trên môi trường:  MX Linux**
Vẫn xuất hiện.
**Trên môi trường:  Manjaro**
Phần mềm GTK như Gedit, Nautilus, Libreoffice gõ hoàn toàn bình thường với chế độ này.
Phần mềm Firefox (cùng version 65.0.2 như trên MX Linux), không bị lặp lại chữ cái cấu thành lên từ tiếng Việt đó. Ví dụ: Gõ từ "Sắc" thì sẽ hiển thị là "Saăắc" nhưng gõ ở khung nhập văn bản trong trang web như google.com, youtube.com, yahoo.com… thì bấm Backspace sẽ bị hiện tượng xóa từ phía trước từ cần xóa, khi gõ ở Google Docs lại bị hiện tượng lặp lại chữ cái cấu thành lên từ tiếng Việt đó. Ví dụ: Gõ từ "Sắc" thì sẽ hiển thị là "Saăắc"
Phần mềm Chrome thì gõ bất kỳ đâu vẫn bị hiện tượng lặp lại chữ cái cấu thành lên từ tiếng Việt đó. Ví dụ: Gõ từ "Sắc" thì sẽ hiển thị là "Saăắc".
**Lỗi 4: Forward key event**
**MX Linux:**
Vẫn còn.
Lưu ý:
**Manjaro:** Libreoffice gõ hoàn toàn bình thường chế độ này, sau khi xem số hiệu phiên bản thì Libreoffice trên Manjaro là 6.2, trong khi phiên bản trên MX là 6.0. Firefox (cùng version 65.0.2 như trên MX Linux) thì bị trường hợp y như Chrome trên MX.
Chrome trên cả MX và Manjaro vẫn bị.
**Lỗi 5: X11 Clipboard**
Libreoffice (6.0) trên MX Linux vẫn còn bị bảng thông báo: “Requested clipboard format is not available.". Libreoffice (6.2) trên Manjaro thì không bị bảng thông báo.
Xong vẫn còn hiện tượng lúc vừa gõ xong mà bấm đè phím Backspace để xóa thì dấu nháy chuột sẽ bị khựng lại, không xóa nữa và không chỉ ở Libreoffice, mà ở toàn bộ hệ thống, bao gồm phần mềm Java, Qt, Gtk… trên cả 2 môi trường MX và Manjaro.
Cách khắc phục tình trạng này:
Bấm phím Ctrl trước khi đè phím Backspace để xóa.

**Comment by hiepvu91945** [comment]
### Tổng kết
Sau quá trình trải nghiệm bộ gõ ibus-bamboo, ở bản v0.3.2 này theo tui cảm nhận đã tốt lên. Bản thân đã dùng qua ibus-unikey, teni, bogo... thì với tui, đánh giá hiện bamboo xếp trên.
Các lỗi tui viết ở trên ngoài lỗi không gõ được phím số với kiểu gõ VNI (đã fix ở v0.3.2 này), thì những lỗi còn lại hoàn toàn có thể dùng phím tắt đổi chế độ gõ sao cho phù hợp nhất với phần mềm.
Chẳng hạn như tui đang thực hiện như sau:
**Ở môi trường MX Linux:**
**Lỗi 2: Pre-edit (default)**
Với những phần mềm Java, GTK, gán cho chúng chế độ gõ Forward key event.
**Lỗi 3: Surrounding text**
Với những phần mềm Java, GTK, gán cho chúng chế độ gõ Forward key event.
**Lỗi 4: Forward key event**
Với những phần mềm Qt, sử dụng chế độ Pre-edit (default), hoặc Surrounding text.
Cập nhật lên Libreoffice 6.1 thì đã gõ được tiếng Việt ở chế độ này.
Hạn chế gõ tiếng Việt ở thanh địa chỉ của Chrome.
**Lỗi 5: X11 Clipboard**
Dù đã cập nhật Libreoffice 6.1, nhưng trên MX vẫn bị bảng thông báo “Requested clipboard format is not available.", tuy nhiên đã khắc phục bằng cách gán chế độ gõ Forward key event.
Riêng hiện tượng đè phím Backspace để xóa thì dấu nháy chuột sẽ bị khựng lại, không xóa nữa thì vẫn phải khắc phục bằng cách trên là bấm phím Ctrl trước khi đè phím Backspace để xóa, cũng không quá phiền toái hoặc đổi chế độ khác của bộ gõ.
**Ở môi trường Manjaro:**
Ở đây thì bộ gõ ibus bamboo hoạt động tốt hơn so với môi trường MX, nếu không để ý vụ gạch chân dưới chữ thì lỗi 2 không ảnh hưởng gì. Lỗi 3 chỉ cần gán cho Firefox hay Chrome chế độ gõ Forward key event là ổn. Lỗi 4 thì cũng như Chrome trên MX, tui hạn chế gõ tiếng Việt ở thanh địa chỉ của Firefox là được. Lỗi 5 thì vẫn thế, bấm Ctrl trước là được, hoặc sử dụng những chế độ khác của bộ gõ.
**Tựu chung lại là có thể đóng Topic báo lỗi này tại đây.
Chân thành cảm ơn tác giả đã nhanh chóng cải thiện bộ gõ bamboo ngày một hoàn thiện.**

**Comment by luongthanhlam** [comment]
Cám ơn bạn đã báo lỗi,
Mình đã nâng cấp bộ gõ bộ gõ lên phiên bản v0.4.0 với rất nhiều cải tiến, bạn cập nhật lại nhé

**Comment by hiepvu91945** [comment]
Tuyệt quá bác, bộ gõ bản mới tốt hơn trông thấy! Đặc biệt tui trải nghiệm gõ trên Libreoffice Version: 6.1.5.2 Build ID: 6.1.5-3, trên môi trường Manjaro KDE cả 4 chế độ đều có thể gõ được. Trên các ứng dụng khác thì đơn giản gán chế độ thích hợp là ổn.
À, có một tiểu tiết nhỏ tui ghi bên dưới, không rõ là  do môi trường hay do bộ gõ, bác xem thử coi.

**Comment by hiepvu91945** [comment]
Lỗi số thứ tự chỉ mục khi sử dụng phím tắt: Shift + ~

**Môi trường:** 
OS và version: KDE neon User Edition 5.15 x86_64; Kernel: 4.18.0-17-generic 
Desktop: KDE
Phiên bản ibus-bamboo: v0.4.0

**Mô tả lỗi:**
Ở lần đầu khi sử dụng bộ gõ mà cần phải sử dụng phím tắt để chuyền đổi chế độ gõ, thì số thứ tự (stt) để lựa chọn chế độ gõ bị lệch so với stt hướng dẫn chọn ở phía trên bảng chọn.
Cụ thể: 0/1/2/3/4 so với 1/2/3/4/5
Dẫn đến có thể chọn lựa sai chế độ mong muốn.
**Các bước tái hiện lỗi:**
Cách 1:
Lần đầu đăng nhập phiên làm việc và sử dụng bộ gõ với phím tắt chuyển đổi chế độ.
Cách 2:
Sử dụng lệnh "ibus restart" và sử dụng bộ gõ với phím tắt chuyển đổi chế độ.
**Kết quả mong muốn:**
Đồng bộ stt được khớp với nhau.
**Ảnh chụp màn hình, hoặc clip quay màn hình:**
https://www.youtube.com/watch?v=YdhX0ZdbTDE&feature=youtu.be
**Lưu ý:**
**Môi trường:**
OS và version: Manjaro Linux x86_64 ; Kernel: 4.19.32-1-MANJARO
Desktop: KDE
Phiên bản ibus-bamboo: v0.4.0
Không bị trường hợp trên.
Phiên bản trên KDE Neon được cài đặt từ PPA, phiên bản trên Manjaro được build từ git.

**Comment by luongthanhlam** [comment]
bạn chạy lệnh `apt-cache show ibus-bamboo -a` và gửi kết quả giúp mình nhé

**Comment by hiepvu91945** [comment]
Gửi bác:
```
[peih@peih-kdeneon ~]$ apt-cache show ibus-bamboo -a
Package: ibus-bamboo
Priority: extra
Section: utils
Installed-Size: 5926
Maintainer: Luong Thanh Lam <ltlam93@gmail.com>
Architecture: amd64
Version: 0.4.0ubuntu1-0~201904060303~ubuntu18.04.1
Depends: ibus
Filename: pool/main/i/ibus-bamboo/ibus-bamboo_0.4.0ubuntu1-0~201904060303~ubuntu18.04.1_amd64.deb
Size: 1261484
MD5sum: 5ae800d48750a2d82ee4d20a396ea80b
SHA1: 9558eb3d29b9595dab9f1369e155bbc2a3e645b0
SHA256: 78c6a97c0ee551dbcb87b02342dabeb703f7d7eb1197b025dbd31a361baf44c4
Description: A Vietnamese IME for IBus using BambooEngine.
Description-md5: 752e9d3f39909164738ad3d273b47ad7

[peih@peih-kdeneon ~]$ 

```

**Comment by luongthanhlam** [comment]
Lỗi này khá lạ, bạn thử nâng cấp lên bản 0.4.1 xem còn bị không

**Comment by hiepvu91945** [comment]
Vẫn còn bác ơi, tui mới mở issue riêng cho dễ nhìn rồi bác, kèm theo cả 1 lỗi khác tui mới thấy, bác thử coi như thế nào.
