### ISSUE TITLE
Không gõ được tiếng Việt trên  VSCode, Version 0.6.4

### ISSUE THREAD

**Issue by tranphuquy19** [BambooEngine/ibus-bamboo#111]
**Mô tả lỗi**
Như tiêu đề, khi mình gõ trong VSCode thì không thể gõ được tiếng Việt cũng như chuyển chế độ gõ [Shift+~]

**Môi trường**
 - OS và version: ubuntu 19.10
 - Desktop: GNome
 - Phiên bản ibus-bamboo: v0.6.4

**Comment by luongthanhlam** [comment]
bạn có cài VSCode từ snap/flatpak không? https://github.com/BambooEngine/ibus-bamboo/wiki/T%E1%BA%A1i-sao-kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-Vi%E1%BB%87t-trong-%E1%BB%A9ng-d%E1%BB%A5ng-snap%3F

**Comment by tranphuquy19** [comment]
có bạn, cài từ snap thì ko gõ được hay sao vậy bạn?

**Comment by luongthanhlam** [comment]
Uhm, chi tiết bạn xem link trên nhé.
