### ISSUE TITLE
install bamboo sau khi đã có ibus-unikey 

### ISSUE THREAD

**Issue by long-nguyenxuan** [BambooEngine/ibus-bamboo#113]
**Mô tả lỗi**
Đang có ibus-unikey, cài thử bamboo và giờ không biết cái bộ gõ đang dùng là ibus-unikey hay ibus-bamboo 

**Các bước tái hiện lỗi**
Ví dụ:
1. trên hệ thống có sẵn ibus-unikey 
2. cài thêm bamboo theo hướng dẫn 
3. try `sudo apt remove ibus-unikey` thi` het' go~ dc tiengviet luon. 

**Kết quả mong muốn**
không rõ hiện tại bộ gõ đang chạy là ibus-unikey hay ibus-bamboo 
nen co' them huong dan chuyen tu ibus-unikey sang ibus-bamboo 

**Môi trường**
 - OS và version: Ubuntu 1804 
 - Desktop: **mặc định **
 - Phiên bản ibus-bamboo: v0.6.0

**Comment by luongthanhlam** [comment]
Gnome không hiển thị logo bộ gõ trên thanh trạng thái, nếu muốn biết đang
dùng bộ gõ nào bạn cần click vào biểu tượng vi trên thanh trạng thái, tên
bộ gõ sẽ hiển thị bên dưới.

**Comment by vuminhcongvmc** [comment]
> **Mô tả lỗi**
> Đang có ibus-unikey, cài thử bamboo và giờ không biết cái bộ gõ đang dùng là ibus-unikey hay ibus-bamboo
> 
> **Các bước tái hiện lỗi**
> Ví dụ:
> 
> 1. trên hệ thống có sẵn ibus-unikey
> 2. cài thêm bamboo theo hướng dẫn
> 3. try `sudo apt remove ibus-unikey` thi` het' go~ dc tiengviet luon.
> 
> **Kết quả mong muốn**
> không rõ hiện tại bộ gõ đang chạy là ibus-unikey hay ibus-bamboo
> nen co' them huong dan chuyen tu ibus-unikey sang ibus-bamboo
> 
> **Môi trường**
> 
> * OS và version: Ubuntu 1804
> * Desktop: **mặc định **
> * Phiên bản ibus-bamboo: v0.6.0

Bạn đang sử dụng môi trường gnome thì bạn nên sử dụng duy nhất ibus-bamboo thôi, chế độ 3 của ibus-bamboo hoạt động tốt với hầu hết ứng dụng gtk, riêng với google-chrome và các ứng dụng sử dụng nhân chromium thì bạn sử dụng chế độ 4.

**Comment by long-nguyenxuan** [comment]
Cam' on 2 ban da~ tra loi, xin loi hom qua o que^ nen ko reply dc, 
minh gui thong tin da cai dat va anh loi~ nhe' 
trong `Settings/Regions & Language` van~ hien thi Unikey 
![Imgur](https://i.imgur.com/P9t4KA5.png)
click vao `Manage Installed Language` thi thay' bao' loi~ 
![Imgur](https://i.imgur.com/4WdpCgh.png?1) 
gio` lam sao de active ibus-bamboo len de su dung nhi? 

<details>
<summary>log uninstall ibus-unikey, ibus restart, install ibus-bamboo , ibus restart</summary> 

</detais>

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn này xem https://blogchiasekienthuc.com/linux/cach-cai-dat-bo-go-tieng-viet-tren-ubuntu.html

**Comment by long-nguyenxuan** [comment]
> bạn làm theo hướng dẫn này xem https://blogchiasekienthuc.com/linux/cach-cai-dat-bo-go-tieng-viet-tren-ubuntu.html

thanks, link kia ko hữu ích lắm, nên mình đã thử reboot, sau đó vào trong chỗ `Settings/Region & Language/Input Source` rồi thêm 1 input source, giờ đã thấy ibus-bamboo xuất hiện.

**Comment by vuminhcongvmc** [comment]
> Cám ơn 2 bạn đã trả lời @ltlam93 @vuminhcongvmc, xin lỗi hôm qua giờ ở quê mất net ko reply dc.
> Mình gửi thông tin đã cài đặt và ảnh lỗi nhé!
> Sau khi cài xong vẫn ko thể start ibus-bamboo lên dc :(
> mình đang dùng Ubuntu 1804
> 
> Ảnh lỗi
> Giờ làm sao để dùng dc ibus-bamboo nhỉ?
> log uninstall ibus-unikey, ibus restart, install ibus-bamboo , ibus restart

Bước 1: Mở terminal và gõ: ibus-setup
Bước 2: Chọn tab input method
Bước 3: Chọn add rồi tìm đến mục Vietnamese
Bước 4: Chọn Bamboo
Sau khi thực hiện bước 1 thì biểu tượng của ibus đã xuất hiện, sau khi hoàn thành bước 4 thì bạn nhấp vào đó và thiết lập theo nhu cầu của bạn, để chắc chắn bạn nên logout rồi login lại, bây giờ bạn có thể gõ tiếng việt bằng ibus-bamboo rồi.

**Comment by vuminhcongvmc** [comment]
> bạn làm theo hướng dẫn này xem https://blogchiasekienthuc.com/linux/cach-cai-dat-bo-go-tieng-viet-tren-ubuntu.html

Tui hi vọng bạn có thể sớm ra mắt chế độ gõ không gạch chân cho đa số ứng dụng Qt...huhu, hóng lắm rồi.

**Comment by luongthanhlam** [comment]
> > bạn làm theo hướng dẫn này xem https://blogchiasekienthuc.com/linux/cach-cai-dat-bo-go-tieng-viet-tren-ubuntu.html
> 
> Tui hi vọng bạn có thể sớm ra mắt chế độ gõ không gạch chân cho đa số ứng dụng Qt...huhu, hóng lắm rồi.

bạn gặp vấn đề gì vậy? mình vẫn dùng bình thường mà.
