### ISSUE TITLE
Không thể gõ Tiếng Việt trên Slack, Telegram

### ISSUE THREAD

**Issue by henryonsoftware** [BambooEngine/ibus-bamboo#114]
**Mô tả lỗi**
Hiện tại không thể gõ Tiếng Việt cho các phần mềm chat như Slack, Telegram với phiên bản trên Ubuntu 18.04

**Các bước tái hiện lỗi**
1. Mở Slack, Telegram
2. Gõ "anh yeeu em"
3. Thấy "anh yeeu em" chứ không phải "anh yêu em", dù đã chuyển qua Telex/Unicode

**Môi trường**
 - Ubuntu 18.04
 - Ibus bamboo bản mới nhất

**Comment by luongthanhlam** [comment]
bạn có đang cài slack, telegram từ snap/flatpak không? https://github.com/BambooEngine/ibus-bamboo/wiki/T%E1%BA%A1i-sao-kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-Vi%E1%BB%87t-trong-%E1%BB%A9ng-d%E1%BB%A5ng-snap%3F

**Comment by henryonsoftware** [comment]
@luongthanhlam không bạn nhé, mình cài qua Ubuntu Software

**Comment by luongthanhlam** [comment]
Trên ubuntu software là cài qua snap rồi đó bạn, bạn gỡ ra rồi vào trang chủ download và cài lại từ file .deb nhé

**Comment by henryonsoftware** [comment]
@luongthanhlam oh, mình làm được rồi. Cảm ơn bạn
