### ISSUE TITLE
Lỗi gõ password sau khi logout hoặc suspend

### ISSUE THREAD

**Issue by vuminhcongvmc** [BambooEngine/ibus-bamboo#115]
**Mô tả lỗi**
Tôi thỉnh thoảng cho máy ngủ (suspend) hoặc đơn giản là đăng xuất (logout) và khi tôi đăng nhập lại thì không thể nhập được password

**Các bước tái hiện lỗi**
Đăng xuất (logout) hoặc ngủ (suspend) rồi đăng nhập lại

**Kết quả mong muốn**
Tôi muốn việc nhập password không bị ảnh hưởng bởi ibus-bamboo

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Linux Mint 19.3
 - Desktop: Cinnamon
 - Phiên bản ibus-bamboo: 0.6.4

**Thông tin thêm**
Các nội dung khác có liên quan đến lỗi đang xảy ra.
Ví dụ: Chương trình XYZ được cài đặt từ: (apt-get, snap, flatpak, download từ trang chủ,...)

**Lưu ý**
Trước khi gửi issue lên github, xin bạn hãy đọc lại Hướng dẫn sử dụng và Các vấn đề thường
gặp trên trang chủ ít nhất một lần nữa. Sau khi đọc kỹ hướng dẫn sử dụng và thử mọi cách rồi
mà không được, thì hãy đặt câu hỏi lên đây. Khi gửi câu hỏi xin bạn hãy mô tả chi tiết các
bước bạn đã làm, và chi tiết kết quả bạn nhận được.

**Comment by luongthanhlam** [comment]
Khi bạn gõ mật khẩu của bạn trên text editor, kết quả có như bạn mong muốn không? Mật khẩu của bạn có chứa chữ `đ` hay kí tự đặc biệt không?

**Comment by vuminhcongvmc** [comment]
tui sử dụng mật khẩu với ký tự bình thường, không có dấu. tui đăng nhập lúc mở máy (tắt máy hoàn toàn rồi mở lại hoặc khởi động lại máy) hoặc gõ trên text editor hoặc terminal đều bình thường.

**Comment by luongthanhlam** [comment]
Hi, mình đã cài thử Mint Cinnamon trên máy ảo nhưng không tái hiện được lỗi của bạn. Ngoài ra theo mình quan sát thì màn hình login của Mint sử dụng bộ gõ mặc định (US) chứ không dùng ibus, bạn gỡ ibus-bamboo ra và thử lại xem.
