### ISSUE TITLE
Không gõ được khi dùng ibus-bamboo trong Android Studio

### ISSUE THREAD

**Issue by lequangit99** [BambooEngine/ibus-bamboo#116]
Chỉ đơn giản là mở Android Studio thì không gõ được gì cả. Các ứng dụng khác vẫn gõ bình thường. Mình không biết có thêm ứng dụng khác có bị như vậy không. 

Mong các bạn giúp mình :dancing_men: 

Manjaro 19.0
DE: KDE
ibus-bamboo v0.6.4

Cài từ AUR

**Comment by luongthanhlam** [comment]
Khi bạn gõ `aa` thì trên màn hình có hiển thị kí tự gì không? Bạn đã thử tắt đi bật lại Android Studio chưa? Nếu không đc, nhờ bạn chạy lệnh này trên termianl và gửi kết quả giúp mình `env | grep "IM_MODULE\|XMODIFERS"`

**Comment by lequangit99** [comment]
cảm ơn bạn. Mình không khắc phục được nên mình đã chuyển sang dùng Manjaro
Gnome và mọi thứ rất oke. Cảm ơn bạn rất nhiều vì đã hỗ trợ mình

Vào Th 4, 26 thg 2, 2020 vào lúc 14:00 luongthanhlam <
notifications@github.com> đã viết:
