### ISSUE TITLE
Lỗi gõ trên website Facebook bằng Firefox

### ISSUE THREAD

**Issue by kubj31196** [BambooEngine/ibus-bamboo#117]
**Mô tả lỗi**
Vị trí con trỏ dịch chuyển lung tung khi viết bình luận trên website Facebook bằng Firefox

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở Firefox 
2. Truy cập Facebook
3. Ấn vào khung nhập liệu đăng status, comment bài viết hoặc ô trả lời messenger
4. Khi gõ, sau khi ấn space, thay vì tạo dấu cách để tiếp tục từ mới, cursor nhảy lên đầu ô nhập liệu, trước từ đã gõ.

**Kết quả mong muốn**
Con trỏ hoạt động bình thường như tại các trang web và ứng dụng khác

**Ảnh chụp màn hình, hoặc clip quay màn hình**
[https://streamable.com/fsmmi](https://streamable.com/fsmmi)

**Môi trường**
 - OS và version: Pop OS 19.10
 - Desktop: Mặc định
 - Phiên bản ibus-bamboo: 0.6.3

**Thông tin thêm**
Đã thử tái hiện lỗi trên web browser Google Chrome và lỗi không tái hiện.

**Comment by luongthanhlam** [comment]
Bạn đang dùng chế độ gõ nào vậy? mình thử các chế độ gõ số 1, 3, 4 và 5 trên firefox khá ok đó

**Comment by kubj31196** [comment]
> Bạn đang dùng chế độ gõ nào vậy? mình thử các chế độ gõ số 1, 3, 4 và 5 trên firefox khá ok đó

À cảm ơn bạn, mình đã thử đổi lại chế độ gõ và việc comment đã trở lại bình thường rồi. Có lẽ ibus mới cài nên hoạt động chưa ổn, trước mình dùng fcitx.
