### ISSUE TITLE
Lỗi gõ (không preedit) trên QTerminal

### ISSUE THREAD

**Issue by ndgnuh** [BambooEngine/ibus-bamboo#118]
**Mô tả lỗi**
Chế độ duy nhất hoạt động tốt là chế độ 1, các chế độ còn lại sẽ lỗi như sau:
2. goõ tieêngếng vieêệt
3. go（õ tien（（êng（（（ếng vie（（ịe（（iệt
4. goｑõ tienｑｑênｑｑếng vieｑｑịeｑｑiệt 
5. go（õ tieng（（（êng（（（ếng vie（ê（ệt
6. gõ được tiếng Việt nhưng có delay và sẽ gây lỗi khi gõ nhanh

**Kết quả mong muốn**
1 chế độ gõ ổn định :(

**Môi trường**
 - OS và version: Debian 10 stable
 - Desktop: AwesomeWM
 - Phiên bản ibus-bamboo: 0.6.4, cài đặt từ open build service

**Thông tin thêm**
Mình thử trên một số ứng dụng QT khác như Kate, Tea, Konqueror thì chế độ 2 làm việc khá tốt và không bị delay. Trong trường hợp này thì chế độ 2 cũng chỉ chưa xóa những kí tự thừa chứ không phải fail hoàn toàn.

**Comment by luongthanhlam** [comment]
Chế độ gõ số 6 đã hoạt động khá ổn định trên các DE ngoài Gnome :)

**Comment by ndgnuh** [comment]
Mình còn không nhớ là có cái issue này. Mình dùng qterminal trên void mà còn không để ý luôn. Không hiểu tại sao trên một số distro thì ứng dụng QT gõ được, một số thì không. Mình nghi là do phiên bản QT có lỗi gì đó chưa được vá , vì lỗi này mình chỉ thấy trên NixOS và Debian, còn Void, Arch, bla.. kiểu rolling release thì không thấy :laughing:
