### ISSUE TITLE
Không thể viết tiếng việt trong phần reply cmt và tin nhắn Messeger !

### ISSUE THREAD

**Issue by tvminh19** [BambooEngine/ibus-bamboo#119]
**Mô tả lỗi**
Không thể viết được tiếng việt + Bị lag hoặc mất khung nhập kí tự

**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
Ví dụ:
1. Mở facebook, reply cmt
2. Gõ abc rồi bị lag không thể nhập được.
--
1. mở chorme => facebook => Messeger => trả lời tin nhắn
2. gõ abc rồi không hiển thị khung nhập kí tự
![error_bamboo_unikey](https://user-images.githubusercontent.com/56433333/76698997-45044480-66db-11ea-9a10-1e0cf491ec8a.png)

...
4. Thấy xyz

**Kết quả mong muốn**
cải thiện lỗi trên.

**Môi trường**
 - OS và version: (Ubuntu 19.04)
 - Desktop: (**mặc định**)
 - Phiên bản ibus-bamboo: (v.0.6.0)

**Comment by luongthanhlam** [comment]
Bạn vào cấu hình bộ gõ tắt tùy chọn Capture mouse events và thử lại xem, nếu bạn sử dụng laptop thì tắt touchpad trước nhé.

**Comment by tvminh19** [comment]
cảm ơn bạn !
