### ISSUE TITLE
Lỗi: Không thể copy, cut và paste trên terminal, vscode... khi bật bamboo.

### ISSUE THREAD

**Issue by f97** [BambooEngine/ibus-bamboo#12]
**Mô tả lỗi**

Không thể copy, cut và paste trên terminal, vscode... khi bật bamboo.

**Các bước tái hiện lỗi**
1. Chuyển ibus qua bamboo.
2. Mở terminal.
3. Nhập `git --vesion`.
4. Copy version vừa show ra. 
5. Không thể paste vào trình duyệt.

**Kết quả mong muốn**

Có thể copy được ở bước thứ 5.

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![deepin-screen-recorder_google-chrome_20190315153511](https://user-images.githubusercontent.com/35532964/54418664-1eae7080-4738-11e9-8bdb-6aeaccd5ca18.gif)

**Môi trường**
 - OS và version: Manjaro 18.0.4
 - Desktop: Deepin
 - Phiên bản ibus-bamboo:  v0.3.0

**Comment by luongthanhlam** [comment]
Bạn vui lòng cập nhật lên phiên bản v0.3.1 sẽ không còn bị lỗi này nữa nhé

**Comment by f97** [comment]
Yeah. Đã hết bị lỗi rồi ạ.

**Comment by hiimden** [comment]
![image](https://user-images.githubusercontent.com/100601647/167185365-fde3e61d-18c7-492b-b363-d2655ed46a83.png)


> em dùng window 11 cũng bị lỗi giống bạn kia. Em đã sửa được lỗi copy paste nhưng mỗi lần ấn copy xong nó lại hiện ra cái hình chữ nhật nhấp nháy kia, chỉ khi ấn liên tục nhiều chữ bất kì (vd: ahjgdaga) thì nó mới trở về bình thường để paste. Mọi người giúp em với ạ.

**Comment by thuphuong999999** [comment]
sửa được chưa b. mình cũng bị giống bạn

**Comment by Manh-hello** [comment]
tui cũng bị vậy, không copy được, mỗi lần mở vscode ra là không bị cái đó nx
