### ISSUE TITLE
ibus-bamboo for ubuntu arm

### ISSUE THREAD

**Issue by dichkv** [BambooEngine/ibus-bamboo#120]
**Mô tả lỗi**
Gói ibus-bamboo cho nền tảng ARM

**Các bước tái hiện lỗi**
Làm theo hướng dẫn để cài đặt ibus-bamboo cho Ubuntu 18.04 trên kiến trúc ARM. 
```
root@arm:~# apt install ibus-bamboo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ibus-bamboo
```

**Comment by ndgnuh** [comment]
Bạn build file deb từ mã nguồn xem

**Comment by luongthanhlam** [comment]
bạn thử lại nhé, mình đã bổ sung các gói ARM cho ubuntu rồi đó.
