### ISSUE TITLE
Không build được ibus-bamboo.

### ISSUE THREAD

**Issue by ghost** [BambooEngine/ibus-bamboo#121]
Output :
```
GOPATH=/home/ibus-bamboo-0.6.4 go build -ldflags="-s -w" -o ibus-engine-bamboo ibus-bamboo
# ibus-bamboo
src/ibus-bamboo/engine.go:113:16: undefined: x11GetFocusWindowClass
src/ibus-bamboo/engine.go:331:4: undefined: startMouseCapturing
src/ibus-bamboo/engine.go:334:4: undefined: stopMouseCapturing
src/ibus-bamboo/engine_backspace.go:255:3: undefined: x11SendBackspace
src/ibus-bamboo/engine_preedit.go:143:3: undefined: mouseCaptureUnlock
src/ibus-bamboo/engine_utils.go:76:3: undefined: startMouseCapturing
src/ibus-bamboo/engine_utils.go:78:2: undefined: startMouseRecording
src/ibus-bamboo/engine_utils.go:79:2: undefined: onMouseMove
src/ibus-bamboo/engine_utils.go:89:2: undefined: onMouseClick
src/ibus-bamboo/engine_utils.go:100:5: undefined: x11SendShiftR
src/ibus-bamboo/engine_utils.go:100:5: too many errors
make: *** [Makefile:34: build] Error 2
```

**Comment by ndgnuh** [comment]
Bạn cung cấp thêm thông tin về os của bạn được không? Bạn đã cài những gói phụ thuộc như phần wiki nói chưa?

**Comment by ixavoz** [comment]
> Bạn cung cấp thêm thông tin về os của bạn được không? Bạn đã cài những gói phụ thuộc như phần wiki nói chưa?
> 
> Theo như mình đọc được thì một hàm nào đó liên quan tới X11 chưa đc định nghĩa.

Mình hiện đang sử dụng Ataraxia Linux [](https://ataraxialinux.github.io) và đã cài đặt đầy đủ make, go, libx11 và libxtst rồi.

**Comment by ndgnuh** [comment]
Một số distro chia nhỏ gói ra, bạn xem cho mình xem có gói nào với tên như trên nhưng đuôi `*-devel` hoặc `-dev` không? Nếu có thì bạn cài rồi build lại hộ mình. Ngoài ra khi tìm một gói tên là libXi, lúc tìm cách build cho nixOS mình đã phải cài gói này mới build được.

**Comment by ixavoz** [comment]
> Một số distro chia nhỏ gói ra, bạn xem cho mình xem có gói nào với tên như trên nhưng đuôi `*-devel` hoặc `-dev` không? Nếu có thì bạn cài rồi build lại hộ mình. Ngoài ra khi tìm một gói tên là libXi, lúc tìm cách build cho nixOS mình đã phải cài gói này mới build được.

Distribution mình dùng không có chia nhỏ như thế. Còn về libxi thì mình có kiểm tra và thấy nó chưa được cài thật. Để mình cài rồi sẽ báo với bạn sau.

**Comment by ndgnuh** [comment]
Có vẻ giống một lỗi mình gặp khi build trên void, cái này hình như do một file C không build đc. Để mịn xem lại

**Comment by einsteinarbert** [comment]
build trên ubuntu thì như nào bác ơi ?

**Comment by nqhuytb99** [comment]
Mình cũng bị lỗi như bạn nhưng không có dòng liên quan đến X11. Hiện mình đã sửa được bằng cách ``export CGO_ENABLED=1``

**Comment by luongthanhlam** [comment]
@ghost nếu lỗi này còn xuất hiện, phiền bạn mở lại issue. Tks!

**Comment by hien-ngo29** [comment]
:)) không ngờ được gặp người nổi tiếng ở đây @ghost https://github.com/microsoft/vscode/issues/87268
