### ISSUE TITLE
Mất chữ khi input nhanh và không thể setup chế độ cho toàn bộ ứng dụng mà phải setup từng ứng dụng

### ISSUE THREAD

**Issue by trandinhchinh1995** [BambooEngine/ibus-bamboo#122]
**Mô tả lỗi**
Nhập chữ quá nhanh sẽ xảy ra tình trạng mất luôn chữ vừa nhập.
không thể setup chế độ cho các ứng dụng

**Kết quả mong muốn**
không bị mất chữ khi gõ nhanh
cài đặt chế độ gõ mặc định cho toàn bộ ứng dụng

**Comment by ndgnuh** [comment]
Ah, cái chế độ gõ mặc định có rồi, nhưng chưa đc document, rất xin lỗi.

Bạn thêm vào file JSON một cái option là `"DefaultInputMode": 3` ở mức ngoài cùng nhé, cái 3 chỉnh thành chế độ mà bạn muốn mặc định

**Comment by luongthanhlam** [comment]
Lỗi nhập chữ nhanh bị mất có thể do trong khi gõ bạn chạm tay vào touchpad và khiến bộ gõ commit sai vị trí, bạn có thể tắt touchpad và thử lại xem.

**Comment by trandinhchinh1995** [comment]
mình luôn tắt touchpad. bạn thử kiểm tra khi chat bằng skype. thường bị ở trên ứng dụng này.

**Comment by luongthanhlam** [comment]
với skype bạn nên dùng chế độ gõ số 1 hoặc 4

**Comment by goatastronaut0212** [comment]
Mình nghĩ lỗi này cũng khá là l6u rồi. Có vẻ như nên đóng nó lại. Nếu còn lỗi thì bạn hãy tạo 1 báo cáo lỗi mới mình sẽ đóng báo cáo lỗi này
