### ISSUE TITLE
Không cài đặt được ibus-bamboo

### ISSUE THREAD

**Issue by JunPham** [BambooEngine/ibus-bamboo#123]
Em không thể cài đặt được ibus ạ.
***Môi trường****
OS: Kali Linux 2020.1b
Desktop: Gnome
Sau khi đã chạy thành công các lệnh sau:
echo 'deb http://download.opensuse.org/repositories/home:/lamlng/Debian_9.0/ /' > /etc/apt/sources.list.d/home:lamlng.list
wget -nv https://download.opensuse.org/repositories/home:lamlng/Debian_9.0/Release.key -O Release.key
apt-key add - < Release.key
Nhưng khi đến phần update thì bị như này ạ
![image](https://user-images.githubusercontent.com/42670522/78790477-94593000-797c-11ea-9278-713bcc70dc44.png)

**Comment by luongthanhlam** [comment]
bạn chạy lệnh này để cập nhật public key rồi thử lại xem
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys XXXXXXXXXX`

**Comment by einsteinarbert** [comment]
Làm sao để build source trên ubuntu đấy bác ơi ?

**Comment by ndgnuh** [comment]
> Làm sao để build source trên ubuntu đấy bác ơi ?

Bạn đọc ở phần wiki có hướng dẫn về dependencies và cách build

https://github.com/BambooEngine/ibus-bamboo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-m%C3%A3-ngu%E1%BB%93n

**Comment by einsteinarbert** [comment]
Cảm ơn bác, app chạy ngon lắm <3

Vào Th 2, 13 thg 4, 2020 vào lúc 09:51 Hùng <notifications@github.com> đã
viết:

**Comment by JunPham** [comment]
> bạn chạy lệnh này để cập nhật public key rồi thử lại xem
> `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys XXXXXXXXXX`

E cài được rồi, thanks a. Nhưng lại không thể gõ tiếng việt được mặc dù đã setting trong file .bashrc và .profile rồi ạ

**Comment by JunPham** [comment]
> bạn chạy lệnh này để cập nhật public key rồi thử lại xem
> `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys XXXXXXXXXX`

E gõ được rồi thank a ạ. Bộ gõ hoạt động rất tốt nha a. À mà nếu a bỏ được cái lỗi khi nhấn Shift là mất dấu thì càng tốt ạ. Ví dụ như á:, nó sẽ thành as:

**Comment by luongthanhlam** [comment]
> E gõ được rồi thank a ạ. Bộ gõ hoạt động rất tốt nha a. À mà nếu a bỏ được cái lỗi khi nhấn Shift là mất dấu thì càng tốt ạ. Ví dụ như á:, nó sẽ thành as:

bạn gặp lỗi trong ứng dụng nào? bạn có cấu hình phím tắt nào ngoài mặc định không?

**Comment by JunPham** [comment]
> > E gõ được rồi thank a ạ. Bộ gõ hoạt động rất tốt nha a. À mà nếu a bỏ được cái lỗi khi nhấn Shift là mất dấu thì càng tốt ạ. Ví dụ như á:, nó sẽ thành as:
> 
> bạn gặp lỗi trong ứng dụng nào? bạn có cấu hình phím tắt nào ngoài mặc định không?

Tất cả phần mềm luôn ạ. Với lại trong Zoom, e gõ tiếng việt không được

**Comment by luongthanhlam** [comment]
bạn chạy lệnh này rồi gửi output lên đây nhé `cat ~/.config/ibus-bamboo/ibus-bamboo.config.json`. Ngoài ra, nếu có thể nhờ bạn gửi clip quay màn hìnhh để mô tả lỗi rõ hơn.
