### ISSUE TITLE
Không cài được ibus-bamboo Error: retrieving gpg key timed out

### ISSUE THREAD

**Issue by CSboob** [BambooEngine/ibus-bamboo#124]
**Mô tả lỗi**
![Screenshot from 2020-04-15 17-04-37](https://user-images.githubusercontent.com/61237821/79325580-9e120300-7f3b-11ea-922c-46d54ff8d3a3.png)

**Các bước tái hiện lỗi**
sau khi gõ: 'sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo' thì báo lỗi

**Môi trường**
 - OS:Ubuntu 18.04 LTS
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: bản mới nhất

**Thông tin thêm**
 - Em đã thử import public key của bamboo theo cách này rồi gõ lại câu trên vẫn looix
 - https://askubuntu.com/questions/1118175/ppas-are-completely-broken-in-18-04-1-any-possible-solutions

**Comment by luongthanhlam** [comment]
có vẻ lỗi kết nối mạng, bạn kiểm tra rồi thử lại nhé
