### ISSUE TITLE
Bỏ dấu gạch chân thì chữ bị nháy, mỗi loại bỏ dấu lại có 1 vấn đề 

### ISSUE THREAD

**Issue by ladylazy9x** [BambooEngine/ibus-bamboo#125]
**Mô tả lỗi**
Bỏ dấu gạch chân thì chữ bị nháy, mỗi loại bỏ dấu lại có 1 vấn đề 

**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
Ví dụ:
1. Mở gedit
2. Gõ abc
...
4. Thấy xyz

**Kết quả mong muốn**
Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Ví dụ: Gõ abc thì phải thấy abc chứ không phải xyz

**Ảnh chụp màn hình, hoặc clip quay màn hình**
https://youtu.be/3d5AnucnRgE

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 18.04)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus-bamboo: ( v0.6.4)

**Thông tin thêm**
Các nội dung khác có liên quan đến lỗi đang xảy ra.
Ví dụ: Chương trình XYZ được cài đặt từ: (apt-get, snap, flatpak, download từ trang chủ,...)

**Lưu ý**
Trước khi gửi issue lên github, xin bạn hãy đọc lại Hướng dẫn sử dụng và Các vấn đề thường
gặp trên trang chủ ít nhất một lần nữa. Sau khi đọc kỹ hướng dẫn sử dụng và thử mọi cách rồi
mà không được, thì hãy đặt câu hỏi lên đây. Khi gửi câu hỏi xin bạn hãy mô tả chi tiết các
bước bạn đã làm, và chi tiết kết quả bạn nhận được.

**Comment by ladylazy9x** [comment]
xem video sẽ hiểu

**Comment by luongthanhlam** [comment]
trên chrome bạn nên dùng kiểu gõ số 1 hoặc 4, các kiểu gõ còn lại chưa tương thích tốt vs chrome đâu.

**Comment by ladylazy9x** [comment]
Tất cả luôn kể cả app bạn ạ, bao gồm Slack. Mình thử r á.

**Comment by luongthanhlam** [comment]
Hiện tại, các chế độ gõ được xây dựng chủ yếu trên 2 api Surrounding Text và ForwardKeyEvent. Vì mỗi ứng dụng lại implement 2 api này theo cách khác nhau nên hiệu quả sẽ khác nhau, có ứng dụng hoạt động tốt với chế độ gõ này, không hoạt động với chế độ gõ khác và ngược lại. Vì thế bạn cần chọn đúng chế độ gõ không gạch chân phù hợp với từng ứng dụng.

**Comment by rimday** [comment]
`shift + ~` Để chuyển chế độ gõ cho từng ứng dụng nha
