### ISSUE TITLE
Không gõ tiếng Việt được trên ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by motmaytinh** [BambooEngine/ibus-bamboo#127]
Sau khi update lên ubuntu 20.04 LTS thì mình không thể gõ tiếng Việt bằng ibus-bamboo trên mọi ứng dụng dù đã cài đặt lại ibus-bamboo, dùng ibus-unikey thì gõ được.

**Môi trường**
 - OS và version: Ubuntu 20.04 LTS
 - Desktop: **mặc định**
 - Phiên bản ibus-bamboo: bản mới nhất

**Comment by vuminhcongvmc** [comment]
Bạn thử khởi động lại máy xem.

**Comment by motmaytinh** [comment]
Mình đã khởi động lại máy nhưng vẫn không được. Thực tế mình gặp tình trạng này trên 2 máy khác nhau rồi (một máy là 20.04 beta, máy kia là 20.04 LTS) nên mình nghĩ đây là lỗi do thay đổi trên ubuntu 20.04

**Comment by luongthanhlam** [comment]
bạn chạy 3 lệnh này trên terminal, gõ một vài từ tiếng Việt rồi gửi output giúp mình nhé
```
cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
ibus engine Bamboo
ibus-daemon -xrv
```

**Comment by motmaytinh** [comment]
@luongthanhlam output dday ban =))

<pre><font color="#C3D82C">cat</font> <u style="text-decoration-style:single">~/.config/ibus-bamboo/ibus-bamboo.config.json</u>
{
  &quot;InputMethod&quot;: &quot;Telex&quot;,
  &quot;InputMethodDefinitions&quot;: {
    &quot;Microsoft layout&quot;: {
      &quot;!&quot;: &quot;_Ă&quot;,
      &quot;#&quot;: &quot;_Ê&quot;,
      &quot;$&quot;: &quot;_Ô&quot;,
      &quot;)&quot;: &quot;_Đ&quot;,
      &quot;0&quot;: &quot;__đ&quot;,
      &quot;1&quot;: &quot;__ă&quot;,
      &quot;2&quot;: &quot;__â&quot;,
      &quot;3&quot;: &quot;__ê&quot;,
      &quot;4&quot;: &quot;__ô&quot;,
      &quot;5&quot;: &quot;DauHuyen&quot;,
      &quot;6&quot;: &quot;DauHoi&quot;,
      &quot;7&quot;: &quot;DauNga&quot;,
      &quot;8&quot;: &quot;DauSac&quot;,
      &quot;9&quot;: &quot;DauNang&quot;,
      &quot;@&quot;: &quot;_Â&quot;,
      &quot;[&quot;: &quot;__ư&quot;,
      &quot;]&quot;: &quot;__ơ&quot;,
      &quot;{&quot;: &quot;_Ư&quot;,
      &quot;}&quot;: &quot;_Ơ&quot;
    },
    &quot;Telex&quot;: {
      &quot;a&quot;: &quot;A_Â&quot;,
      &quot;d&quot;: &quot;D_Đ&quot;,
      &quot;e&quot;: &quot;E_Ê&quot;,
      &quot;f&quot;: &quot;DauHuyen&quot;,
      &quot;j&quot;: &quot;DauNang&quot;,
      &quot;o&quot;: &quot;O_Ô&quot;,
      &quot;r&quot;: &quot;DauHoi&quot;,
      &quot;s&quot;: &quot;DauSac&quot;,
      &quot;w&quot;: &quot;UOA_ƯƠĂ&quot;,
      &quot;x&quot;: &quot;DauNga&quot;,
      &quot;z&quot;: &quot;XoaDauThanh&quot;
    },
    &quot;Telex + VNI&quot;: {
      &quot;0&quot;: &quot;XoaDauThanh&quot;,
      &quot;1&quot;: &quot;DauSac&quot;,
      &quot;2&quot;: &quot;DauHuyen&quot;,
      &quot;3&quot;: &quot;DauHoi&quot;,
      &quot;4&quot;: &quot;DauNga&quot;,
      &quot;5&quot;: &quot;DauNang&quot;,
      &quot;6&quot;: &quot;AEO_ÂÊÔ&quot;,
      &quot;7&quot;: &quot;UO_ƯƠ&quot;,
      &quot;8&quot;: &quot;A_Ă&quot;,
      &quot;9&quot;: &quot;D_Đ&quot;,
      &quot;a&quot;: &quot;A_Â&quot;,
      &quot;d&quot;: &quot;D_Đ&quot;,
      &quot;e&quot;: &quot;E_Ê&quot;,
      &quot;f&quot;: &quot;DauHuyen&quot;,
      &quot;j&quot;: &quot;DauNang&quot;,
      &quot;o&quot;: &quot;O_Ô&quot;,
      &quot;r&quot;: &quot;DauHoi&quot;,
      &quot;s&quot;: &quot;DauSac&quot;,
      &quot;w&quot;: &quot;UOA_ƯƠĂ&quot;,
      &quot;x&quot;: &quot;DauNga&quot;,
      &quot;z&quot;: &quot;XoaDauThanh&quot;
    },
    &quot;Telex + VNI + VIQR&quot;: {
      &quot;&apos;&quot;: &quot;DauSac&quot;,
      &quot;(&quot;: &quot;A_Ă&quot;,
      &quot;*&quot;: &quot;UO_ƯƠ&quot;,
      &quot;+&quot;: &quot;UO_ƯƠ&quot;,
      &quot;.&quot;: &quot;DauNang&quot;,
      &quot;0&quot;: &quot;XoaDauThanh&quot;,
      &quot;1&quot;: &quot;DauSac&quot;,
      &quot;2&quot;: &quot;DauHuyen&quot;,
      &quot;3&quot;: &quot;DauHoi&quot;,
      &quot;4&quot;: &quot;DauNga&quot;,
      &quot;5&quot;: &quot;DauNang&quot;,
      &quot;6&quot;: &quot;AEO_ÂÊÔ&quot;,
      &quot;7&quot;: &quot;UO_ƯƠ&quot;,
      &quot;8&quot;: &quot;A_Ă&quot;,
      &quot;9&quot;: &quot;D_Đ&quot;,
      &quot;?&quot;: &quot;DauHoi&quot;,
      &quot;\\&quot;: &quot;D_Đ&quot;,
      &quot;^&quot;: &quot;AEO_ÂÊÔ&quot;,
      &quot;`&quot;: &quot;DauHuyen&quot;,
      &quot;a&quot;: &quot;A_Â&quot;,
      &quot;d&quot;: &quot;D_Đ&quot;,
      &quot;e&quot;: &quot;E_Ê&quot;,
      &quot;f&quot;: &quot;DauHuyen&quot;,
      &quot;j&quot;: &quot;DauNang&quot;,
      &quot;o&quot;: &quot;O_Ô&quot;,
      &quot;r&quot;: &quot;DauHoi&quot;,
      &quot;s&quot;: &quot;DauSac&quot;,
      &quot;w&quot;: &quot;UOA_ƯƠĂ&quot;,
      &quot;x&quot;: &quot;DauNga&quot;,
      &quot;z&quot;: &quot;XoaDauThanh&quot;,
      &quot;~&quot;: &quot;DauNga&quot;
    },
    &quot;Telex 2&quot;: {
      &quot;[&quot;: &quot;__ơ&quot;,
      &quot;]&quot;: &quot;__ư&quot;,
      &quot;a&quot;: &quot;A_Â&quot;,
      &quot;d&quot;: &quot;D_Đ&quot;,
      &quot;e&quot;: &quot;E_Ê&quot;,
      &quot;f&quot;: &quot;DauHuyen&quot;,
      &quot;j&quot;: &quot;DauNang&quot;,
      &quot;o&quot;: &quot;O_Ô&quot;,
      &quot;r&quot;: &quot;DauHoi&quot;,
      &quot;s&quot;: &quot;DauSac&quot;,
      &quot;w&quot;: &quot;UOA_ƯƠĂ__Ư&quot;,
      &quot;x&quot;: &quot;DauNga&quot;,
      &quot;z&quot;: &quot;XoaDauThanh&quot;,
      &quot;{&quot;: &quot;_Ơ&quot;,
      &quot;}&quot;: &quot;_Ư&quot;
    },
    &quot;Telex W&quot;: {
      &quot;a&quot;: &quot;A_Â&quot;,
      &quot;d&quot;: &quot;D_Đ&quot;,
      &quot;e&quot;: &quot;E_Ê&quot;,
      &quot;f&quot;: &quot;DauHuyen&quot;,
      &quot;j&quot;: &quot;DauNang&quot;,
      &quot;o&quot;: &quot;O_Ô&quot;,
      &quot;r&quot;: &quot;DauHoi&quot;,
      &quot;s&quot;: &quot;DauSac&quot;,
      &quot;w&quot;: &quot;UOA_ƯƠĂ__Ư&quot;,
      &quot;x&quot;: &quot;DauNga&quot;,
      &quot;z&quot;: &quot;XoaDauThanh&quot;
    },
    &quot;VIQR&quot;: {
      &quot;&apos;&quot;: &quot;DauSac&quot;,
      &quot;(&quot;: &quot;A_Ă&quot;,
      &quot;*&quot;: &quot;UO_ƯƠ&quot;,
      &quot;+&quot;: &quot;UO_ƯƠ&quot;,
      &quot;.&quot;: &quot;DauNang&quot;,
      &quot;0&quot;: &quot;XoaDauThanh&quot;,
      &quot;?&quot;: &quot;DauHoi&quot;,
      &quot;\\&quot;: &quot;D_Đ&quot;,
      &quot;^&quot;: &quot;AEO_ÂÊÔ&quot;,
      &quot;`&quot;: &quot;DauHuyen&quot;,
      &quot;~&quot;: &quot;DauNga&quot;
    },
    &quot;VNI&quot;: {
      &quot;0&quot;: &quot;XoaDauThanh&quot;,
      &quot;1&quot;: &quot;DauSac&quot;,
      &quot;2&quot;: &quot;DauHuyen&quot;,
      &quot;3&quot;: &quot;DauHoi&quot;,
      &quot;4&quot;: &quot;DauNga&quot;,
      &quot;5&quot;: &quot;DauNang&quot;,
      &quot;6&quot;: &quot;AEO_ÂÊÔ&quot;,
      &quot;7&quot;: &quot;UO_ƯƠ&quot;,
      &quot;8&quot;: &quot;A_Ă&quot;,
      &quot;9&quot;: &quot;D_Đ&quot;
    },
    &quot;VNI Bàn phím tiếng Pháp&quot;: {
      &quot;\&quot;&quot;: &quot;DauHuyen&quot;,
      &quot;\u0026&quot;: &quot;XoaDauThanh&quot;,
      &quot;&apos;&quot;: &quot;DauHoi&quot;,
      &quot;(&quot;: &quot;DauNga&quot;,
      &quot;-&quot;: &quot;DauNang&quot;,
      &quot;_&quot;: &quot;UO_ƯƠ&quot;,
      &quot;à&quot;: &quot;D_Đ&quot;,
      &quot;ç&quot;: &quot;A_Ă&quot;,
      &quot;è&quot;: &quot;AEO_ÂÊÔ&quot;,
      &quot;é&quot;: &quot;DauSac&quot;
    }
  },
  &quot;OutputCharset&quot;: &quot;Unicode&quot;,
  &quot;Flags&quot;: 7,
  &quot;IBflags&quot;: 266736,
  &quot;JupiterFlags&quot;: 0,
  &quot;DefaultInputMode&quot;: 1,
  &quot;InputModeMapping&quot;: {
    &quot;tilix:Tilix&quot;: 1
  },
  &quot;ExceptedList&quot;: null,
  &quot;PreeditWhiteList&quot;: null,
  &quot;X11ClipboardWhiteList&quot;: null,
  &quot;ForwardKeyWhiteList&quot;: null,
  &quot;SLForwardKeyWhiteList&quot;: null,
  &quot;DirectForwardKeyWhiteList&quot;: null,
  &quot;SurroundingTextWhiteList&quot;: null
}<span style="background-color:#A1B0B8"><font color="#263238"><b>%</b></font></span>   </pre>

<pre><font color="#C3D82C">ibus</font> engine Bamboo

(process:4200): IBUS-<font color="#FFC135"><b>WARNING</b></font> **: <font color="#42A5F5">11:52:58.012</font>: ibus_bus_call_sync: org.freedesktop.IBus.SetGlobalEngine: GDBus.Error:org.freedesktop.DBus.Error.Failed: Set global engine failed: Timeout was reached
Set global engine failed.</pre>

<pre><font color="#C3D82C">ibus-daemon</font> -xrv
panic: dial unix @/home/lap13482/.cache/ibus/dbus-v1HQlE0o: connect: connection refused

goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/github.com/BambooEngine/goibus/ibus/bus.go:14
github.com/BambooEngine/goibus/ibus.NewBus(0x6c6058)
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/github.com/BambooEngine/goibus/ibus/bus.go:19 +0x321
main.main()
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/ibus-bamboo/main.go:48 +0x37d
panic: dial unix @/home/lap13482/.cache/ibus/dbus-v1HQlE0o: connect: connection refused

goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/github.com/BambooEngine/goibus/ibus/bus.go:14
github.com/BambooEngine/goibus/ibus.NewBus(0x6c6058)
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/github.com/BambooEngine/goibus/ibus/bus.go:19 +0x321
main.main()
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/ibus-bamboo/main.go:48 +0x37d</pre>

**Comment by motmaytinh** [comment]
@luongthanhlam mình phát hiện ra lỗi mình gặp là do Wayland tương tự như issue #129

**Comment by ndgnuh** [comment]
Bạn bỏ `-x` khi chạy `ibus-daemon` xem sao

**Comment by motmaytinh** [comment]
@ndgnuh vẫn như vậy bạn
<pre><font color="#C3D82C">ibus-daemon</font> -rv
panic: dial unix @/home/lap13482/.cache/ibus/dbus-jyLbgNrr: connect: connection refused

goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/github.com/BambooEngine/goibus/ibus/bus.go:14
github.com/BambooEngine/goibus/ibus.NewBus(0x6c6058)
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/github.com/BambooEngine/goibus/ibus/bus.go:19 +0x321
main.main()
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/ibus-bamboo/main.go:48 +0x37d
panic: dial unix @/home/lap13482/.cache/ibus/dbus-jyLbgNrr: connect: connection refused

goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/github.com/BambooEngine/goibus/ibus/bus.go:14
github.com/BambooEngine/goibus/ibus.NewBus(0x6c6058)
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/github.com/BambooEngine/goibus/ibus/bus.go:19 +0x321
main.main()
	/build/ibus-bamboo-1JYxxT/ibus-bamboo-0.6.4/src/ibus-bamboo/main.go:48 +0x37d</pre>

**Comment by luongthanhlam** [comment]
bạn cập nhật lên bản 0.6.5 để khắc phục lỗi này nhé
