### ISSUE TITLE
Không sử dụng đuợc trên GNOME Wayland session

### ISSUE THREAD

**Issue by long21wt** [BambooEngine/ibus-bamboo#129]
**Mô tả lỗi**
Chưa sử dụng đuợc ibus-bamboo trên GNOME Wayland session

**Các bước tái hiện lỗi**
1. Sử dụng GNOME Wayland session
2. Cài đặt ibus-bamboo như huớng dẫn

**Kết quả mong muốn**
Gõ tiếng việt bình thuờng 
vd: dd -> đ

**Môi trường**
 - OS và version: Fedora [Rawhide, 32], Ubuntu 20.04
 - Desktop: GNOME
 - Phiên bản ibus-bamboo: v0.6.4

**Thông tin thêm**
Hiện tại thì có vẻ chưa gõ đuợc trên Wayland nhưng trên Xorg thì mọi thứ bình thuờng. Mình đang dùng tạm bản telex(m17n).

**Comment by luongthanhlam** [comment]
cám ơn bạn, lỗi đã được fix ở bản v0.6.5 :)
