### ISSUE TITLE
Phím Alt phản hồi chậm trong lúc sử dụng Bamboo

### ISSUE THREAD

**Issue by npkhang99** [BambooEngine/ibus-bamboo#130]
**Mô tả lỗi**
Lỗi chỉ xảy ra khi Bamboo được thêm vào một trong những Input Sources. Khi Bamboo được cài nhưng chưa được thêm vào Input Sources thì tình trạng này không hề xảy ra.
Một khi Bamboo đã được thêm vào danh sách Input Sources, cho dù mình đang dùng chế độ gõ tiếng Anh hoặc tiếng Việt thì đôi lúc phím Alt phản hồi chậm, dẫn đến việc phím tắt bị ghi nhận sai. (Không rõ những phím khác có bị hay không, tại vì mình chỉ đang gặp vấn đề này ở phím Alt)
Ví dụ:
- Khi Alt-Tab để chuyển cửa sổ thì phím Alt không được ghi nhận mà chỉ ghi nhận được phím Tab, dẫn tới việc thay vì chuyển cửa sổ thì ứng dụng đang được sử dụng sẽ thực hiện chức năng của phím Tab (chẳng hạn như thêm một ký tự tab trong những trình xử lý văn bản);
- Khi dùng Alt-PgUp/PgDn để chuyển Workspaces trong GNOME thì chỉ có phím PgUp và PgDn được ghi nhận, còn Alt thì không.

**Các bước tái hiện lỗi**
Thật sự mình không rõ có thể tái hiện lỗi một cách nhất quán hay không vì tình trạng này chỉ xảy ra một cách ngẫu nhiên và tần suất bắt gặp cũng khá nhiều.

**Kết quả mong muốn**
Phím Alt (và có thể có những phím khác) được ghi nhận một cách chính xác khi dùng phím tắt trên bàn phím.

**Môi trường**
 - OS: Arch Linux
 - Desktop: GNOME 3.36.2-1
 - Phiên bản ibus-bamboo: v0.6.5

**Một số thông tin thêm**
- Mình cũng có thử dùng qua fcitx-unikey và ibus-unikey thì cả hai cái này không hề xảy ra hiện tượng trên.
- Mình cũng đã có kiểm tra qua Typing Assist của GNOME thì mọi tính năng trong đó đều đã được tắt.
- Mình hiện đang dùng laptop và tình trạng này xảy ra cho cả bàn phím của laptop lẫn bàn phím rời.

**Comment by npkhang99** [comment]
Có một điều mà mình quên ghi ở issue đó là mình hiện đang dùng Xorg. Nếu mình chuyển qua dùng Wayland thì vấn đề này không còn tồn tại.
Tuy nhiên, một số ứng dụng mình dùng chỉ dùng được trên Xorg, còn nếu dùng trên Wayland thì sẽ có vấn đề nên mình không thể dùng Wayland để coi như là một biện pháp giải quyết vấn đề được.
Mong tác giả thông cảm vì mình bỏ sót chi tiết này trong issue.
Cảm ơn tác giả.

**Comment by luongthanhlam** [comment]
bạn vào cài đặt của bộ gõ, tắt tùy chọn `Capture mouse events` và thử lại xem

**Comment by npkhang99** [comment]
Vấn đề vẫn tồn tại bạn nhé.

**Comment by haoadoresorange** [comment]
Mình cũng bị lỗi này, trên manjaro. Bạn có nghĩ ra có những vde nào gây lỗi ko ? Mình có thể xem và fix.

**Comment by haoadoresorange** [comment]
@fx500ms

**Comment by fx500ms** [comment]
@haoadoresorange bạn debug thử hàm này xem https://github.com/BambooEngine/ibus-bamboo/blob/565c172dbd654e282c41325cc6cf1543fad5b461/src/ibus-bamboo/engine.go#L77
Nếu mọi thứ hoạt động bình thường thì khi nhấn Alt+Tab, hàm này luôn trả về `false, nil`

**Comment by luongthanhlam** [comment]
@npkhang99 @autn @haoadoresorange  mọi người vào cài đặt, xóa hết phím tắt xem có còn bị lỗi này không?

**Comment by haoadoresorange** [comment]
Mình vừa cập nhật bản mới nhất thì ko thấy hiện tượng này nữa. Arch linux latest.

**Comment by hanhlx** [comment]
Mình xác nhận là bản 0.8.2_RC3 vẫn bị lỗi này. Dùng phím alt + tab rất lag, lúc được lúc không. Đặc biệt khi sử dụng cùng vscode. Hiện tại mình đang chuyển qua fcitx5-unikey thì không còn hiện tượng này.

**Môi trường**
OS: Manjaro KDE
Phiên bản ibus-bamboo: 0.8.2_RC3

**Comment by luongthanhlam** [comment]
bạn thử chuyển sang bộ gõ BambooUs và xóa hết phím tắt của bộ gõ xem?

**Comment by lehien** [comment]
> bạn vào cài đặt của bộ gõ, tắt tùy chọn `Capture mouse events` và thử lại xem

Chuẩn cái này rồi. Mình bị bao lâu nay trên Ubuntu 20.04, mà cứ đổ lỗi cho Ubuntu. Kiểu thử nhấn Alt+Tab lần đầu tiên thì sẽ ko có phản hồi gì xảy ra cả, như kiểu bàn phím bị hỏng hay mình bấm trượt vậy. Từ lần thứ hai thì ok. Nhưng sau đó có thao tác chuột như di chuột, click thì tình trạng lại lặp lại như cũ. Sau khi tắt cái tùy chọn kia thì đã ngon lành.

**Comment by goatastronaut0212** [comment]
Lỗi nay có còn còn nữa không nhỉ? Chỉ là mọi thứ trên Gnome với mới mình có vẻ khá mượt. Alt + Tab không có lỗi nào như vậy lắm cũng không hề phản hồi chậm.

**Comment by ppvan** [comment]
Hiện tại thì lỗi này không còn trên GNOME 46 nữa. Và theo trí nhớ của mình, từ GNOME 42 có vẻ k có lỗi này nữa

Chi tiết:
- ArchLinux
- GNOME Shell 46.4 (Wayland)
- Google Chrome 128.0.6613.119 (AUR)
- ibus-bammbo 0.8.4_RC1-1
- Switch input individually for each window

và đã cố thử reproduce dựa theo các comment:
> Đọc issue của bác em mới để ý là em cũng bị, tình trạng như sau: đang sử dụng Chrome, mở 1 tab mới, sau đó sử dụng phím Alt (ví dụ Alt + Tab) thì không sử dụng được. Còn nếu không mở new tab thì dùng bình thường, em chưa test với các trường hợp khác, và xác suất bị đang là 100%. OS em đang dùng là Ubuntu 20.04.3 LTS

> Updated: thực ra hiện trạng đúng phải là con trỏ đang ở 1 ô nhập text, ở bất cứ app nào luôn. > Phía trên em bị khi new tab là do lúc new tab thì con trỏ nó trỏ về ô nhập address nên bị.

> Updated 2: Bây giờ em chỉ cần chuyển Chrome tab (click sang 1 tab khác) là cũng đã xảy ra hiện trạng này!

**Comment by goatastronaut0212** [comment]
Mình đóng lại báo cáo lỗi này vậy. Nếu các bạn vẫn còn bị có thể mở thêm 1 báo cáo lỗi mới.
