### ISSUE TITLE
Lỗi crash khi chuyển chế độ gõ

### ISSUE THREAD

**Issue by vuminhcongvmc** [BambooEngine/ibus-bamboo#132]
**Mô tả lỗi**
Mỗi khi tôi chuyển chế độ gõ thì bộ gõ bị crash.

**Môi trường**
 - OS và version: KDE neon 5.18.4
 - Desktop: KDE
 - Phiên bản ibus-bamboo: 0.6.5

**Comment by luongthanhlam** [comment]
bạn chạy 2 lệnh này trên terminal, gõ Shift+~ để chuyền chế độ gõ rồi gửi output giúp mình nhé
```
ibus engine Bamboo
ibus-daemon -xrv
```

**Comment by vuminhcongvmc** [comment]
> bạn chạy 2 lệnh này trên terminal, gõ Shift+~ để chuyền chế độ gõ rồi gửi output giúp mình nhé
> 
> ```
> ibus engine Bamboo
> ibus-daemon -xrv
> ```

**Comment by vuminhcongvmc** [comment]
![image](https://user-images.githubusercontent.com/45608242/80859821-c749c780-8c8d-11ea-92a1-ec7fe50429fb.png)

**Comment by luongthanhlam** [comment]
thêm lệnh này nhé
```
cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
```

**Comment by vuminhcongvmc** [comment]
Cái đó tui để mặc định, tui định thay đổi vì google chrome và libreoffice không chơi với chế độ 3 nhưng vì lỗi trên nên tui đã cho về mặc định.
![image](https://user-images.githubusercontent.com/45608242/80862042-5d84ea00-8c9c-11ea-8fa7-c3a8dd98bd55.png)

**Comment by luongthanhlam** [comment]
ok hiểu rồi, lỗi này bạn chỉ cần xóa file config hoặc xóa dòng chứa key `InputModeMapping` là chạy lại bình thường nhé

**Comment by vuminhcongvmc** [comment]
cảm ơn bạn, tui đã xử lý được.
