### ISSUE TITLE
Lỗi không thể gõ tiếng việt trong Androi Studio trên Kubuntu 20.04

### ISSUE THREAD

**Issue by duong-phuoc** [BambooEngine/ibus-bamboo#133]
**Mô tả lỗi**
khi gõ không hiện chữ dù đã đổi phương thức nhập (shift + ~)

**Các bước tái hiện lỗi**
lỗi xuất hiện khi nhập nội dung của 1 textview bằng tiếng việt

4. Thấy xyz

**Kết quả mong muốn**
VD: khi gõ chữ "chú chim non" trên android studio chỉ hiện "c" hoặc những kí tự "?" có khi không hiện bất kì kí tự nào dù nhập rất nhiều

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Nếu cần thiết, hãy [đính kèm hình ảnh](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) hoặc gửi link youtube [quay lại màn hình](https://www.youtube.com/watch?v=N8M4zsqTkr4) tái hiện lỗi.

**Môi trường**
 - OS và version: Kubuntu 20.04
 - Desktop: mặc định
 - Phiên bản ibus-bamboo: bản mới nhất v0.6.0

**Thông tin thêm**
Các nội dung khác có liên quan đến lỗi đang xảy ra.
Ví dụ: android studio được tải từ trang chủ và cài theo cách thông thường. Mọi apt đều được update đầy đủ

**Comment by luongthanhlam** [comment]
Bạn đang dùng chế độ gõ (Shift + ~) số mấy vậy? bạn đã thử chế độ gõ số 1 và 4 chưa?

**Comment by duong-phuoc** [comment]
Mình đã thử đổi cả 6 chế độ gõ và trên Ubuntu 20.04 cũng có tình trạng tương tự

**Comment by luongthanhlam** [comment]
Bạn cập nhật lên bản 0.6.5 và thử lại nhé

**Comment by duong-phuoc** [comment]
mình đang chạy ở bản mới nhất luôn rồi í

**Comment by duong-phuoc** [comment]
Đây là ảnh của lỗi. và tôi phát hiện thêm là nếu cố gắng gõ Tiếng Việt sẽ khiến ứng dụng bị treo và không thể tắt được ngay cả trong Terminal . cách duy nhất là restart máy
https://drive.google.com/file/d/17vR7c7MnfeRlpTuZY520ZvWnZ_bnZbuH/view?usp=sharing
https://drive.google.com/file/d/1pYCYIcoXvQTaYq59tnKk79z_xAtwQ4aw/view?usp=sharing

**Comment by duong-phuoc** [comment]
Sau bản cập nhật mới nhất từ Kubuntu thì đã gõ được rồi nha bạn ơi =))
