### ISSUE TITLE
Không mở được menu sửa gạch chân và loại trừ trong ST terminal

### ISSUE THREAD

**Issue by nguyenhai97** [BambooEngine/ibus-bamboo#134]
**Mô tả lỗi**
Shift +  ~ Không mở menu tùy chọn trong st terminal

**Các bước tái hiện lỗi**
1. Mở st
2. Gõ shift + ~
3. st chỉ hiện dấu ~ thay vì menu chọn kiểu gõ

**Hiện được menu chọn kiểu gõ**

**Môi trường**
 - OS và version: Archlinux
 - Desktop: dwm
 - Phiên bản ibus-bamboo: Bản mới nhất, vừa pull từ git về

**Thông tin thêm**
Mình đã chạy ibus bằng lệnh ibus-daemon -rdx và set đủ tên biến

![2020-05-16-105103_1366x768_scrot](https://user-images.githubusercontent.com/20857367/82109828-531a2400-9763-11ea-819f-b9494483c15d.png)

**Comment by luongthanhlam** [comment]
bạn đã cài các gói ibus-x11 ibus-gtk ibus-gtk3 ibus-qt chưa?

**Comment by nguyenhai97** [comment]
Mình dùng Archlinux (vì mấy gói kia là cho ubuntu) và mình khá chắc là đã cài đủ gói cần thiết, có lẽ vấn đề tới từ phía của st thôi vì mình vào ViM thì lại chọn được

**Comment by luongthanhlam** [comment]
mọi người cài đặt phím tắt khác và thử lại nhé
