### ISSUE TITLE
Không gõ được ký tự đặc biệt

### ISSUE THREAD

**Issue by minkmk94** [BambooEngine/ibus-bamboo#135]
**Mô tả lỗi**
Sau khi thêm vào danh sách loại trừ không gõ được Shift+1, Shift+2 ..v..v (! @...)
**Các bước tái hiện lỗi**
Mở HeidiSQL trên Wine (Ubuntu 20.04 LTS)

1. Gõ ~
2. Chọn 7 (Thêm vào danh sách loại trừ)
3. Sau đó...là không có sau đó nữa

**Kết quả mong muốn**
1. Gõ được các ký tự đặc biệt sau khi thêm vào danh sách loại trừ
2. Có thể loại bỏ ứng dụng khỏi danh sách loại trừ

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 20.04 LTS)
 - Phiên bản ibus-bamboo: mới nhất

**Comment by luongthanhlam** [comment]
1. Khi tắt bộ gõ, bạn có gõ được các kí tự đặc biệt trên HeidiSQL không?
2. Bạn nhấn ~ rồi chọn 1->6 để loại khỏi ds loại trừ

**Comment by minkmk94** [comment]
> 1. Khi tắt bộ gõ, bạn có gõ được các kí tự đặc biệt trên HeidiSQL không?
> 2. Bạn nhấn ~ rồi chọn 1->6 để loại khỏi ds loại trừ

Sau khi chuyển về `en` thì vẫn có thể gõ được các ký tự đặc biệt, chỉ khi chuyển sang `vi` thì không gõ được các ký tự đặc biệt

Update: Kể cả không thêm vào ds loại trừ thì ở chế độ `vi` cũng không gõ được các ký tự đặc biệt.

**Comment by luongthanhlam** [comment]
nhờ bạn [cài đặt bộ gõ từ mã nguồn](https://github.com/BambooEngine/ibus-bamboo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-m%C3%A3-ngu%E1%BB%93n) và kiểm tra lại giúp mình, tks!
