### ISSUE TITLE
Bấm shift + ~ không hiện menu ở danh sách ứng dụng Gnome

### ISSUE THREAD

**Issue by ngankvn** [BambooEngine/ibus-bamboo#136]
Bấm Super + A hiện lên danh sách toàn bộ ứng dụng, ở đây nếu ibus-bamboo đang ở "Vi" thì khi gõ tìm kiếm ứng dụng sẽ không hiện ra, vì thế mình muốn đưa nó vào danh sách loại trừ. 

Nhưng khi bấm Shift + ~ thì nó lại hiện menu để loại trừ "google chrome", "gnome-terminal" ...  (nói chung là tên của một ứng dụng nào đó đang mở ở ngoài). Nếu không có ứng dụng nào đang mở thì nó sẽ ko hiện bất cứ menu nào cả

Điều này tương tự với khung nhập command promt (Alt F2)
![Screenshot from 2020-05-22 18-19-06](https://user-images.githubusercontent.com/417473/82662922-eb7b4180-9c58-11ea-9241-06c6ca529552.png)

**Comment by luongthanhlam** [comment]
Lỗi này hiện chưa có hướng giải quyết, bạn có thể theo dõi thêm ở đây https://github.com/BambooEngine/ibus-bamboo/issues/80
