### ISSUE TITLE
Lỗi khi chat Facebook

### ISSUE THREAD

**Issue by mrskyit6** [BambooEngine/ibus-bamboo#137]
**Mô tả lỗi**
Khi gõ tiếng Việt trên bóng chat của Facebook bị lỗi khó chịu

**Các bước tái hiện lỗi**
1. Mở bóng chat trên Facebook. (Giao diện mới, không rõ giao diện cũ có sao không)
2. Khi gõ nó được vài từ thì mất hết chữ và không tương tác được với bóng chat nữa, phải reload lại cả trang.
3. Có khi gõ được cả dòng rồi không sao nhưng lúc enter thì lại bị như vậy tiếp, bóng chat tự tắt và hiện biểu tượng chấm than.

**Kết quả mong muốn**
Không lỗi, sử dụng bình thường.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Nếu cần thiết, hãy [đính kèm hình ảnh](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) hoặc gửi link youtube [quay lại màn hình](https://www.youtube.com/watch?v=N8M4zsqTkr4) tái hiện lỗi.

**Môi trường**
 - OS và version: Ubuntu 20.04 (Ubuntu 19.04 cũng bị)
 - Desktop: **mặc định**
 - Phiên bản ibus-bamboo: v0.6.5

**Comment by luongthanhlam** [comment]
hiện mình không thể tái hiện được lỗi này, tuy nhiên bạn có thể thử 1 trong các cách sau
- Tắt tùy chọn `Capture mouse events` trong cấu hình bộ gõ
- Nhấp `Shift ~` và chọn kiểu gõ số 4

**Comment by mrskyit6** [comment]
Cảm ơn bạn, làm theo cách trên thì gõ được bình thường rồi
