### ISSUE TITLE
Không thấy xuất hiện `ibus-bamboo` ở mục chọn.

### ISSUE THREAD

**Issue by minatu2d** [BambooEngine/ibus-bamboo#139]
**Mô tả lỗi**
Không thấy xuất hiện trong mục chọn input method sau khi cài và 

**Các bước tái hiện lỗi**
1. Cài đặt theo hướng dẫn bằng add PPA, rồi chạy apt: Không có lỗi gì xảy ra.
2. Gõ `ibus restart` : Không có lỗi
...
4. Không thấy ibus-bamboo xuất hiện trong mục chọn input method

**Kết quả mong muốn**
- Có thể chọn được từ input method mới phải

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2020-05-31 14-17-00](https://user-images.githubusercontent.com/9568154/83345255-0716d400-a34c-11ea-87b4-592c155cb542.png)

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Mặc định (Gnome-shell)
 - Phiên bản ibus-bamboo: 0.6.5-0~202004300215~ubuntu20.04.1

**Thông tin thêm**
Không có gì.

**Comment by zenfas** [comment]
Bạn có add bộ gõ chưa [Link](https://blogchiasekienthuc.com/linux/cach-cai-dat-bo-go-tieng-viet-tren-ubuntu.html)

**Comment by thangisme** [comment]
Minh dang su dung Fedora 34 va cung gap loi nay :(
