### ISSUE TITLE
Khi gài ibus-bamboo - The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 36ED424E9659D014

### ISSUE THREAD

**Issue by tng99** [BambooEngine/ibus-bamboo#140]
cam ơn ibus-bamboo, tôi thử gài  trên "Debian GNU/Linux 10 (buster)"
https://github.com/BambooEngine/ibus-bamboo

1) cần thêm: apt-get install software-properties-common  (để có  add-apt-repository)
 add-apt-repository ppa:bamboo-engine/ibus-bamboo

gpg: keybox '/tmp/tmpilds3pjg/pubring.gpg' created
gpg: /tmp/tmpilds3pjg/trustdb.gpg: trustdb created
gpg: key 36ED424E9659D014: public key "Launchpad PPA for bamboo-engine" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.

2) apt-get update  (cả với --allow-unauthenticated hay là --allow-insecure-repositories)
xai với:
W: GPG error: http://ppa.launchpad.net/bamboo-engine/ibus-bamboo/ubuntu groovy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 36ED424E9659D014
E: The repository 'http://ppa.launchpad.net/bamboo-engine/ibus-bamboo/ubuntu groovy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Xin hãy update chỉ dẫn tại https://github.com/BambooEngine/ibus-bamboo  lại.

thanks

**Comment by luongthanhlam** [comment]
Với debian, bạn nên cài từ OBS https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo, PPA hiện tại chỉ hỗ trợ Ubuntu và các distro base trên Ubuntu.
