### ISSUE TITLE
ibus-bamboo không thể gõ tiếng Việt hoặc chuyển từ English sang Vietnamese sau khi update ibus lên 1.5.22

### ISSUE THREAD

**Issue by nguyencuonghut** [BambooEngine/ibus-bamboo#141]
**Mô tả lỗi**
- Không chuyển được từ English sang Vietnamese.
- Không gõ được tiếng Việt.
**Các bước tái hiện lỗi**
- Update Manjaro OS, bao gồm  gói ibus lên 1.5.22.
- Khởi động lại máy.
- Mở ibus-bamboo, thấy input mặc định là English.
- Bấm phím tắt (Super + space) hoặc click và Vietnamese-Bamboo để chuyển sang tiếng Việt không được.
- Thử cài bộ gõ ibus-unikey thì gõ được bình thường (ibus-bamboo hoặc ibus-teni bị lỗi như nhau).

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://user-images.githubusercontent.com/26396504/83376688-5963fd80-a3fd-11ea-99df-63620dc15d5a.png)

**Môi trường**
 - OS và version: Manjaro 20.0.2 Lysia
 - Desktop: KDE
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.6.0)

**Comment by zenfas** [comment]
Ibus-bamboo mới nhất là 0.6.5, bạn update phiên bản mới nhất trước xem

**Comment by nguyencuonghut** [comment]
Cảm ơn @zenfas! Thật ra trước đó bản ibus-bamboo của mình là 0.6.4.
Mình đã update lên version 0.6.5 và đã hoạt động bình thường.

**Comment by teppyboy** [comment]
@nguyencuonghut nếu mà lỗi đã được fix bạn có thể đóng báo cáo lỗi này lại được ko?

**Comment by junkeythong** [comment]
mình hiện tại đang ở 0.6.5 nhưng phím tắt chuyển EN<->VN đôi khi chuyển được, đôi khi không được :(

**Comment by luongthanhlam** [comment]
> mình hiện tại đang ở 0.6.5 nhưng phím tắt chuyển EN<->VN đôi khi chuyển được, đôi khi không được :(

nếu đang sử dụng gnome, bạn nên tắt tùy chọn Capture mouse events
