### ISSUE TITLE
Không chuyển được từ EN sang VI bằng phím tắt

### ISSUE THREAD

**Issue by ledohoanglong** [BambooEngine/ibus-bamboo#142]
Chào bạn,

Hiện tại app không chuyển được chế độ gõ từ tiếng Việt sang tiếng Anh (và ngược lại) bằng Shift + "~". Vẫn có thể chuyển đươc bằng cách click chuột.

Ubuntu version: Ubuntu 18.04.4 LTS
ibus-bamboo:
  Installed: 0.6.5-0~202004300215~ubuntu18.04.1
  Candidate: 0.6.5-0~202004300215~ubuntu18.04.1
  Version table:
 *** 0.6.5-0~202004300215~ubuntu18.04.1 500
        500 http://ppa.launchpad.net/bamboo-engine/ibus-bamboo/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by zenfas** [comment]
Tổ hợp phím bạn gõ là để đổi chế độ gõ Tiếng Việt, không phải chuyển từ Việt sang Anh, muốn chuyển thì dùng Ctrl + Space (xem config trong Ibus)

**Comment by maisonhai3** [comment]
Hoặc super + cách.
Super là phím windows ấy. Ubuntu gọi phím này là super.

**Comment by ledohoanglong** [comment]
Thanks Mai_Hai!
