### ISSUE TITLE
Lỗi duplicate chữ trên Telegram

### ISSUE THREAD

**Issue by 27x2** [BambooEngine/ibus-bamboo#143]
**Mô tả lỗi**
Khi sử dụng Bamboo để nhắn tin trên telegram mình gặp hiện tượng sinh ra một chữ y hệt sau khi nhấn dấu cách. Chữ bị lặp không kể là chữ có dấu hay là không dấu.

**Môi trường**
 - OS và version: PopOS 20.04 LTS
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.6.5
 - Kiểu gõ: VNI

![Screenshot from 2020-06-06 17-57-43](https://user-images.githubusercontent.com/31063758/83942639-a2fa8100-a81f-11ea-89c9-24ec1a47105b.png)

**Comment by luongthanhlam** [comment]
Bạn đang sử dụng telegram phiên bản bao nhiêu? Nhờ bạn chạy lệnh sau trên terminal và gửi output giúp mình  `cat ~/.config/ibus-bamboo/ibus-bamboo.config.json`
