### ISSUE TITLE
Layout bàn phím mặc định

### ISSUE THREAD

**Issue by truongdo** [BambooEngine/ibus-bamboo#145]
**Mô tả lỗi**
Mình sử dụng layout bàn phím tiếng Nhật như hình dưới. Khi sử dụng input method "Ja" thì nó sử dụng layout tiếng Nhật ok rồi. Nhưng khi chuyển sang bamboo thì nó lại dùng bàn phím US.

Layout tiếng Nhật:
![Screenshot from 2020-06-16 21-37-46](https://user-images.githubusercontent.com/3356468/84788772-b4ab0800-b019-11ea-84ca-81a43117b80a.png)

Layout tiếng Việt:
![Screenshot from 2020-06-16 21-37-56](https://user-images.githubusercontent.com/3356468/84788796-bd9bd980-b019-11ea-958f-e0b20335bccf.png)

Mình đã thử xem cấu hình keyboard layout trong file configure như hình dưới thì nó đang để là default và bàn phím default của máy thì đã là layout Nhật mặc định.
https://i.imgur.com/9hHW0OE.png

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Mặc định
 - Phiên bản ibus-bamboo: 0.6.5-0 202004300215 ubuntu20.04.1

**Comment by truongdo** [comment]
resolved by: setxkbmap jp

**Comment by luongthanhlam** [comment]
theo hình trên thì bạn đang dùng ibus-unikey, bạn có thể tham khảo https://github.com/vn-input/ibus-unikey/issues/4 để khắc phục lỗi này
