### ISSUE TITLE
Không định nghĩa một số mục viết tắt được

### ISSUE THREAD

**Issue by zvtrung** [BambooEngine/ibus-bamboo#148]
**Mô tả lỗi**
Không thể định nghĩa một số ký tự/từ viết tắt được.

**Các bước tái hiện lỗi**
0. Bật thiết lập cho phép gõ tắt của chương trình
1. Mở tệp định nghĩa danh mục từ viết tắt
2. Bổ sung các mục từ viết tắt dưới đây vào cuối tệp
-->:→
->:→
--:ꟷ
theDash:ꟷ

3. Gõ thử các-->, -> --, theDash
4. Chỉ có theDash có tác dụng chuyển thành ký tự như định nghĩa, các mục mới thêm vào không chuyển được.

**Kết quả mong muốn**

Các định nghĩa viết tắt đều phải có tác dụng

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Ubuntu 16.04 LTS
 - Desktop: Mặc định
 - Phiên bản ibus-bamboo: bản mới nhất là v0.6.5

**Thông tin thêm**

Dự đoán có thể từ viết tắt chứa các ký tự đặc biệt, như "-" chẳng hạn.

**Comment by luongthanhlam** [comment]
hiện tại bộ gõ mặc định bỏ qua kí tự đặc biệt, nếu fix **có thể** ảnh hưởng đến một số ứng dụng như Facebook, Google Sheets https://github.com/BambooEngine/ibus-bamboo/issues/94

**Comment by luongthanhlam** [comment]
@zvtrung bản v0.7.4 đã fix được lỗi này!
