### ISSUE TITLE
Không gõ được tiếng Việt trên Chrome

### ISSUE THREAD

**Issue by huucp** [BambooEngine/ibus-bamboo#149]
**Mô tả lỗi**
Sau khi update chrome lên phiên  bản 83.0.4103.116 (Official Build) (64-bit) thì khi gõ tiếng Việt thì không hiển thị.

**Các bước tái hiện lỗi**
1. Mở chrome
2. Gõ "tiếng việt"
3. Hiển thị chữ "t" sau đó gõ tiếp thì mất cả chữ "t" và các chữ cái sau cũng không hiển thị.

**Kết quả mong muốn**
Gõ được tiếng việt

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.6.5

**Thông tin thêm**
Cài đặt từ apt. Firefox và các chương trình khác vẫn dùng bình thường.

**Comment by luongthanhlam** [comment]
bạn đang dùng chế độ gõ nào? thử cài thêm các gói ibus-gtk ibus-gtk3 xem

**Comment by huucp** [comment]
mình dùng chế độ gõ telex. Các gói ibus-gtk và ibus-gtk3 đều đã được cài trước đó.

**Comment by luongthanhlam** [comment]
bạn nhấn Shift+~ nhấn tiếp phím 4 và thử lại xem

**Comment by huucp** [comment]
Được rồi, cảm ơn bạn đã hỗ trợ. Mình tò mò chút là lý do bị lỗi này là gì được ko?

**Comment by luongthanhlam** [comment]
mình không tái hiện được lỗi của bạn nên cũng không chắc là lỗi gì, tuy nhiên trên Chrome thì chế độ gõ số 4 hoạt động khá ổn định
