### ISSUE TITLE
Nhảy dấu không chính xác 

### ISSUE THREAD

**Issue by HungFFC** [BambooEngine/ibus-bamboo#151]
Mình mới dùng bộ gõ, và có thử chuyển đôỉ các kiểu gõ và bảng mã. Bật dấu thanh chuẩn.
Nhưng bộ gõ vẫn bị tình trạng nhảy dấu linh tinh
Ví dụ "  chaò moị ngươì mình mơí dùng bộ gõ"
Mong được mọi người support cách sửa lỗi này

**Comment by luongthanhlam** [comment]
Bạn gặp lỗi này trên ứng dụng nào? kiểu gõ và bảng mã bạn đang dùng là gì? 
Nhờ bạn chạy lệnh này trên terminal và gửi kết quả giúp mình
```
cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
```

**Comment by HungFFC** [comment]
> cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
Đây là kết quả cuả mình
{
  "InputMethod": "Telex W",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex W": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode tổ hợp",
  "Flags": 6,
  "IBflags": 315890,
  "JupiterFlags": 0,
  "DefaultInputMode": 1,
  "InputModeMapping": {
    "gnome-terminal-server:Gnome-terminal": 7,
    "jetbrains-phpstorm:jetbrains-phpstorm": 3
  },
  "ExceptedList": null,
  "PreeditWhiteList": null,
  "X11ClipboardWhiteList": null,
  "ForwardKeyWhiteList": null,
  "SLForwardKeyWhiteList": null,
  "DirectForwardKeyWhiteList": null,
  "SurroundingTextWhiteList": null

**Comment by luongthanhlam** [comment]
bạn chuyển về bảng mã Unicode rồi thử lại nhé
