### ISSUE TITLE
Request dem ibus-bamboo len gentoo repo hay la gentoo overlay cung duoc

### ISSUE THREAD

**Issue by RefinedAnarchy** [BambooEngine/ibus-bamboo#152]
https://wiki.gentoo.org/wiki/Ebuild

**Comment by dynamotn** [comment]
@RefinedAnarchy bạn có thể thử ở overlay của mình:
https://github.com/dynamotn/gentoo-overlay/

**Comment by vuongtuha** [comment]
Ad Lâm nhớ up source tar.gz thường xuyên nhé. Mình toàn down thẳng source về cài thôi =))

**Comment by goatastronaut0212** [comment]
Thứ duy nhất mình có vẻ không thích về cái Gentoo repo đó chính là cái Proxy Maintainer của Gentoo nếu bạn không muốn phải trở thành 1 cộng tác viên chính hiệu trừ khi ai đó thực sự muốn đem ibus-bamboo lên đó.

Với lại issue này cũng khá là lâu rồi, mình cũng không rõ về vấn đề này có còn hiện hữu hay không mình thì không hứng thú với Gentoo nhiều lắm nhưng nếu bạn nào cần thì mình có thể thử cố gắng duy trì nó. Nhưng mà overlay của @dynamotn cũng có update thường xuyên.

Mà mình nghĩ nếu nên có giải pháp thích hợp thì chúng ta nên tạo 1 PR để chứa Ebuild trên ibus-bamboo cũng được.

**Comment by goatastronaut0212** [comment]
Đóng lại vì giờ chúng ta có 1 báo cáo lỗi chung ở đây.

https://github.com/BambooEngine/ibus-bamboo/issues/516
