### ISSUE TITLE
Không gõ được trên wps office

### ISSUE THREAD

**Issue by joker48936** [BambooEngine/ibus-bamboo#153]
Trên trình duyệt chuyển qua tiếng việt gõ bình thường. Tuy nhiên vào wps office thì chỉ gõ được tiếng anh. Chuyển bộ gõ tiếng việt nó vẫn ra tiếng anh. Đã chuyển shift + ngã mà vẫn không được.

**Comment by luongthanhlam** [comment]
bạn đang dùng distro nào? đã cài các gói ibus-gtk ibus-gtk3 chưa?

**Comment by joker48936** [comment]
Mình dùng ubuntu 20.04. Nay dùng lại thấy bình thường trở lại. Tuy nhiên muốn gõ tiếng việt trong wps thì dùng shift + ngã 7. Tốc độ thì hơi chậm chút. [https://youtu.be/hotAzGBszcE](url)

**Comment by luongthanhlam** [comment]
> Mình dùng ubuntu 20.04. Nay dùng lại thấy bình thường trở lại. Tuy nhiên muốn gõ tiếng việt trong wps thì dùng shift + ngã 6. Tốc độ thì hơi chậm chút. [https://youtu.be/hotAzGBszcE](url)

mình vừa tối ưu lại logic xử lý backspace nhưng chưa release, nếu bạn cài từ mã nguồn sẽ cải thiện tốc độ gõ khá nhiều đó :)

**Comment by natri23** [comment]
Mình cũng vừa cập nhật lên WPS 11.1.0.9662 từ flatpak thì hoàn toàn ko sử dụng được bamboo. Ko Shift+~ được luôn
Downgrade xuống bản 11.1.0.9522 trở xuống thì sử dụng bình thường.

Mình dùng Solus nên cũng ko thể tải .deb từ trang chủ được. Khi vọng ai đó tìm được cách giải quyết lâu dài cho flatpak

**Comment by luongthanhlam** [comment]
> Mình cũng vừa cập nhật lên WPS 11.1.0.9662 từ flatpak thì hoàn toàn ko sử dụng được bamboo. Ko Shift+~ được luôn
> Downgrade xuống bản 11.1.0.9522 trở xuống thì sử dụng bình thường.
> 
> Mình dùng Solus nên cũng ko thể tải .deb từ trang chủ được. Khi vọng ai đó tìm được cách giải quyết lâu dài cho flatpak

bạn theo dõi ở đây nhé https://github.com/flatpak/flatpak/issues/675
