### ISSUE TITLE
Bị dupe từ khi gõ trên Google Colab

### ISSUE THREAD

**Issue by vinhtq115** [BambooEngine/ibus-bamboo#154]
**Mô tả lỗi**
Khi gõ trên Google Colab, ibus-bamboo bị lỗi dupe từ.

**Các bước tái hiện lỗi**
1. Mở https://colab.research.google.com, tạo notebook mới để gõ
2. Gõ "abc" rồi nhấn cách
3. Thấy "abc abc " thay vì "abc "

Ngoài ra, lúc bấm enter để xuống dòng cũng bị. Thay vì hiện "abc" xong xuống dòng thì bị hiện "abcabc".

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: **mặc định**
 - Phiên bản ibus-bamboo: v0.6.5

**Comment by luongthanhlam** [comment]
bạn gặp lỗi này trên trình duyệt nào, các trang web khác có bị lỗi tương tự không?

**Comment by vinhtq115** [comment]
> bạn gặp lỗi này trên trình duyệt nào, các trang web khác có bị lỗi tương tự không?

Mình chỉ dùng firefox và hiện tại thì mỗi trang này bị thôi.

**Comment by luongthanhlam** [comment]
Mình kiểm tra thì lỗi này do xung đột giữa firefox vs trình soạn thảo trên colab https://microsoft.github.io/monaco-editor/, bạn liên hệ bên đó để báo lỗi nhé
