### ISSUE TITLE
Lỗi không ẩn được popup khi click vào icon

### ISSUE THREAD

**Issue by tamht298** [BambooEngine/ibus-bamboo#155]
![image](https://user-images.githubusercontent.com/46307504/88660744-8a149a80-d101-11ea-80e8-6f713e2346e1.png)
Hiện tại để ẩn cái popup như hình mình phải click vào Vietnamese - Bamboo phía cuối 2 lần thì mới ẩn được. Mong team cải thiện việc này (chỉ cần outclick khỏi cái popup đó hoặc click vào icon trên tray).
Hiện mình đang dùng Ubuntu Budgie 18.04

**Comment by luongthanhlam** [comment]
lỗi này bạn liên hệ team Budgie để fix nhé https://bugs.launchpad.net/ubuntubudgie, rất tiếc bộ gõ không thể làm gì đc
