### ISSUE TITLE
Lỗi Shift + ~ không hoạt động trên đa số ứng dụng ubuntu 20

### ISSUE THREAD

**Issue by namlem4u** [BambooEngine/ibus-bamboo#156]
Hiện nó đang không hoạt động được trên ubuntu 20.04 LTS  hoạt động không chính xác mong Ad fix lỗi này và đưa ra hướng dẫn có thể viết tiếng việt trên WPS office 2019 là nhu cầu cấp bách

**Comment by luongthanhlam** [comment]
bạn có thể mô tả lỗi rõ hơn không?

**Mô tả lỗi**


**Các bước tái hiện lỗi**

Ví dụ:
1. Mở gedit
2. Gõ abc
...
4. Thấy xyz

**Kết quả mong muốn**


**Ảnh chụp màn hình, hoặc clip quay màn hình**


**Môi trường**
 - OS và version: (ví dụ: Ubuntu 20.04)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.6.5)

**Thông tin thêm**

**Comment by namlem4u** [comment]
Tức là khi mình nhấn tổ hợp phím shift+ ~ trong ứng dụng thì nó không hiện bảng chọn để mình fix lỗi gõ như hướng dẫn mà nó không phản hồi. Nhưng khi thu ứng dụng xuống và nhấn tổ hợp phím thì nó lại bình thường. 
Mình bị trên Ubuntu 20.04 lts mới nhất.
Thứ 2 là ứng dụng wps không thể gõ được tiếng việt dù đã Shift + ~ tất cả tùy chọn. Tuy nhiên LibreOffice lại gõ ngon lành.
Tất cả bị trên Ubuntu 20.04 LTS mới nhất.

**Comment by namlem4u** [comment]
![Screenshot_20200802_172046](https://user-images.githubusercontent.com/68719961/89120927-88bde600-d4e4-11ea-81a6-ff60d908dbdb.png)

**Comment by thduong156** [comment]
![Screenshot_2020-08-03_02-17-08](https://user-images.githubusercontent.com/67492952/89122846-fb36c200-d4f4-11ea-9e98-50ca51852537.png)

**Comment by streetsamurai00mi** [comment]
@thduong156 Bạn cần tự build để làm gì vậy ạ?
Đây là lỗi khi build và không phải lỗi bạn open đề cập đến. Lần sau bạn vui lòng mở cái mới.
Sẵn mình giúp luôn về 2 cái lỗi trên nếu bạn muốn build: đầu tiên là lỗi `sudo` khá cơ bản bạn tìm trên mạng và man của sudo. sau đó là `go: not found` do bạn chưa cài package có `go` vào, bạn lưu ý cài đủ các packages phụ thuộc.

**Comment by streetsamurai00mi** [comment]
@namlem4u bạn đã thử [cái này](https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng) chưa?
và app bạn nói **cụ thể** là những app gì vậy ạ?

**Comment by namlem4u** [comment]
> @namlem4u bạn đã thử [cái này](https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng) chưa?
> và app bạn nói **cụ thể** là những app gì vậy ạ?

> [](url)

**Comment by namlem4u** [comment]
xin có video gửi ad
[loi_ibus_bamboo.zip](https://github.com/BambooEngine/ibus-bamboo/files/5013835/loi_ibus_bamboo.zip)

**Comment by namlem4u** [comment]
> bạn có thể mô tả lỗi rõ hơn không?
> 
> **Mô tả lỗi**
> 
> **Các bước tái hiện lỗi**
> 
> Ví dụ:
> 
> 1. Mở gedit
> 2. Gõ abc
>    ...
> 3. Thấy xyz
> 
> **Kết quả mong muốn**
> 
> **Ảnh chụp màn hình, hoặc clip quay màn hình**
> 
> **Môi trường**
> 
> * OS và version: (ví dụ: Ubuntu 20.04)
> * Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
> * Phiên bản ibus-bamboo: (bản mới nhất là v0.6.5)
> 
> **Thông tin thêm**

[loi_ibus_bamboo.zip](https://github.com/BambooEngine/ibus-bamboo/files/5013846/loi_ibus_bamboo.zip)

**Comment by luongthanhlam** [comment]
> xin có video gửi ad
> [loi_ibus_bamboo.zip](https://github.com/BambooEngine/ibus-bamboo/files/5013835/loi_ibus_bamboo.zip)

bạn đang dùng Gnome Wayland hay Xorg?

**Comment by namlem4u** [comment]
> > xin có video gửi ad
> > [loi_ibus_bamboo.zip](https://github.com/BambooEngine/ibus-bamboo/files/5013835/loi_ibus_bamboo.zip)
> 
> bạn đang dùng Gnome Wayland hay Xorg?

Mình dùng bản Gnome bản được được viết lại bởi Ubuntuvn. trang Github của bản ubuntuvn:https://github.com/vozinpro

**Comment by zenfas** [comment]
Bản Ubuntuvn này mình dùng thử thấy có nhiều lỗi vặt, có lúc thấy nó không mượt, nên dùng bản chính chủ hoặc các bản phân phối lớn khác
