### ISSUE TITLE
Khong go duoc tieng Viet tren LXLE ban moi nhat

### ISSUE THREAD

**Issue by kakangocthien109** [BambooEngine/ibus-bamboo#158]
------------------------------
Minh moi cai ibus-bamboo nhu huong dan, nhung lai khong go duoc du da thu nhieu cach. 
----------------------------------------------------------
Link: https://youtu.be/Zw9lz06D4Zo
----------------------------------------------------------
Su dung  LXLE ban moi nhat 64 bit

**Comment by luongthanhlam** [comment]
bạn đã cài các gói ibus-gtk ibus-gtk3 chưa? nếu không được, bạn chạy lệnh và gửi output cho mình
`ibus-daemon -xrv #gõ một vài từ tiếng Việt rồi nhấn Ctrl-C để thoát`
