### ISSUE TITLE
Không gõ được tiếng viêt trên VScode

### ISSUE THREAD

**Issue by huyhoang8398** [BambooEngine/ibus-bamboo#159]
**Mô tả lỗi**

Không thể gõ tiếng việt được trên vscode.
Nếu gõ tiếng việt thì khi ấn `spacebar` thì sẽ bị mất từ.

**Môi trường**
 - OS và version: Archlinux 5.8.1-arch1-1
 - Desktop: i3wm
 - Phiên bản ibus-bamboo: 0.6.5-1 AUR

**Comment by kthoang28** [comment]
Cũng bị lỗi k gõ được tiếng việt trên vs code. 
Tái hiện thì như hướng dẫn cài đặt thôi.
Khi chỉ mới 1 lần mà đã thử cài qua các máy khác nhau vẫn bị.
Ubuntu 2004 LTS 64bit.
![Screenshot from 2020-08-29 17-20-46](https://user-images.githubusercontent.com/45868439/91634638-ff82cc00-ea1b-11ea-8d34-7074e7fae8a7.png)

**Comment by kthoang28** [comment]
Cách chữa cháy hiện tại là dùng vscode tải file .deb. Bằng snap không gõ được.

**Comment by huyhoang8398** [comment]
Mình đang dùng bản `code (open-source release)` từ AUR, bản deb hình như là của m$ release đúng k nhỉ.
Lỗi là khi đánh dấu, chuyển tiếp sang từ khác thì sẽ bị mất từ trươc, mình dã thử tất cả các chế độ

env:
```
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx
```

**Comment by runlevel5** [comment]
Lỗi này có lẽ chỉ liên quan đến Arch, mình không gặp vấn đề này với VSCode 1.49 trên Fedora 31 và 32

**Comment by MrKindess** [comment]
> Mình đang dùng bản `code (open-source release)` từ AUR, bản deb hình như là của m$ release đúng k nhỉ.
> Lỗi là khi đánh dấu, chuyển tiếp sang từ khác thì sẽ bị mất từ trươc, mình dã thử tất cả các chế độ
> 
> env:
> 
> ```
> export GTK_IM_MODULE=ibus
> export XMODIFIERS=@im=ibus
> export QT_IM_MODULE=ibus
> ibus-daemon -drx
> ```

thay vì dùng **vietnamese (bamboo)** bạn hãy chuyển sang **vietnamese ((bamboo) us layout)** ở trong settings nhé b

**Comment by namlem4u** [comment]
Bản tải  cửa hàng của Ubuntu cũng không gõ được nhưng cài bản .deb trên trang chủ Microsoft thì được. Hình như bản cửa hàng có vấn đề với tiếng việt

**Comment by ledangtuanbk** [comment]
Gặp vấn đề tương tự vs skype, tải trên trang chủ của skype cũng không được.

**Comment by boydaihungst** [comment]
> Gặp vấn đề tương tự vs skype, tải trên trang chủ của skype cũng không được.
Cách này t dùng trên manjaro skype gõ tiếng việt bình thường 
![image](https://user-images.githubusercontent.com/38396158/128309537-eebc2cdf-ebad-4076-a015-ee7bc91bbc47.png)

Bạn tạo file .xprofile 
`sudo nano ~/.xprofile`
paste phần này vào
```
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus
export GLFW_IM_MODULE=ibus
```
Reset máy, sau khởi động lại ibus là được nhé.
`ibus-daemon -drx`

**Comment by hungpurdie** [comment]
> > Gặp vấn đề tương tự vs skype, tải trên trang chủ của skype cũng không được.
> 
> Cách này t dùng trên manjaro skype gõ tiếng việt bình thường. Cách này cũng fix cho libre luôn nhé ![image](https://user-images.githubusercontent.com/38396158/128309537-eebc2cdf-ebad-4076-a015-ee7bc91bbc47.png)
> 
> Bạn tạo file .xprofile `sudo nano ~/.xprofile` paste phần này vào
> 
> ```
> export GTK_IM_MODULE=ibus
> export QT_IM_MODULE=ibus
> export XMODIFIERS=@im=ibus
> export QT4_IM_MODULE=ibus
> export CLUTTER_IM_MODULE=ibus
> export GLFW_IM_MODULE=ibus
> ```
> 
> Reset máy, sau khởi động lại ibus là được nhé. `ibus-daemon -drx`

Mình làm theo vẫn không được là sao nhỉ :D?

**Comment by K4zoku** [comment]
Mình gõ được trên VSCode mà nhỉ, ổn nhất là mode 3 và 4

https://user-images.githubusercontent.com/34259386/152472492-1f9164c0-799b-481d-a773-8b5de7da7556.mp4

Thông tin máy mình: 
OS: Arch Linux
Kernel: 5.15.19-1-lts
WM: bspwm

VSCode: 1.63.2
