### ISSUE TITLE
Yêu cầu đưa Bamboo lên fcitx5

### ISSUE THREAD

**Issue by zenfas** [BambooEngine/ibus-bamboo#161]
Mình tạo yêu cầu này mong muốn tác giả phối hợp với team fctix5 để tạo fcitx5-bamboo
https://github.com/fcitx/fcitx5
Cảm ơn tác giả.

**Comment by hmtheboy154** [comment]
bên fcitx5 sử dụng core của bamboo và port được fcitx5-bamboo rồi nhé bạn
https://github.com/fcitx/fcitx5-bamboo

bạn có thể thử compile và feedback lại
