### ISSUE TITLE
Lỗi không gõ được Tiếng Việt trên trình duyệt Google Chrome và Firefox

### ISSUE THREAD

**Issue by blackhole365** [BambooEngine/ibus-bamboo#162]
Phiên bản HĐH mình đang sử dụng là Kali Linux 2020.3

Tiếng Việt vẫn gõ bình thường không vấn đề gì ở trên Text Editor của Kali.

Nhưng gõ không được trên Google Chrome và Firefox, dù đã gỡ ra cài lại nhưng lỗi vẫn không fix được.

**Comment by luongthanhlam** [comment]
bạn chạy lệnh dưới và paste kết quả ở đây nhé
`env | grep "IM_MODULE\|XMODIFERS"`

**Comment by songhanpoo** [comment]
> Phiên bản HĐH mình đang sử dụng là Kali Linux 2020.3
> 
> Tiếng Việt vẫn gõ bình thường không vấn đề gì ở trên Text Editor của Kali.
> 
> Nhưng gõ không được trên Google Chrome và Firefox, dù đã gỡ ra cài lại nhưng lỗi vẫn không fix được.

Minh cung bi loi tuong tu.
`❯ env | grep "IM_MODULE\|XMODIFERS"
QT_IM_MODULE=ibus
`

**Comment by luongthanhlam** [comment]
> > Phiên bản HĐH mình đang sử dụng là Kali Linux 2020.3
> > Tiếng Việt vẫn gõ bình thường không vấn đề gì ở trên Text Editor của Kali.
> > Nhưng gõ không được trên Google Chrome và Firefox, dù đã gỡ ra cài lại nhưng lỗi vẫn không fix được.
> 
> Minh cung bi loi tuong tu.
> `❯ env | grep "IM_MODULE\|XMODIFERS" QT_IM_MODULE=ibus `

bạn làm theo hướng dẫn ở đây nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
