### ISSUE TITLE
Lỗi không gõ được trên wps office

### ISSUE THREAD

**Issue by phatbs21** [BambooEngine/ibus-bamboo#163]
Ibus-bamboo hoàn toàn không chạy được ở phiên bản wps office mới 

Mình mở wps office write lên, sau đó gõ một vài từ nhưng không gõ được tiếng việt, nó còn không cho phép shift ~
Mình đã thử cài đặt lại wps office lẫn ibus
Trên opera, discord hay mọi ứng dụng khác thì nó vẫn hoạt động tốt
![image](https://user-images.githubusercontent.com/53256916/91655868-49cc8180-eade-11ea-95a4-860a2040f774.png)

Môi trường
 - OS và version: Pop Os 20.04
 - Wps office: 11.1.0.9615
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: v0.6.6

Hi vọng bạn có thể sớm khắc phục, mình đang rất cần nó :<

**Comment by luongthanhlam** [comment]
bạn có cài wps từ snap hay flatpak không?

**Comment by cyrilchau** [comment]
Mình cũng bị trường hợp tương tự, WPS mình cài trực tiếp = file deb từ trang web bản mới nhất
Chế độ gõ mình cũng đã thử hết nhưng chỉ có chế độ 1 và 6 là có thể viết dấu nhưng tốc độ chế độ 6 rất chậm và 1 thì không hiển thị chữ cái mình nhập vào

**Comment by phatbs21** [comment]
Mình cài thông qua Pop!_Os shop (flatpak)

**Comment by luongthanhlam** [comment]
@phatbs21 bạn cài wps từ trang chủ để khắc phục lỗi này nhé https://www.wps.com/download/
@cyrilchau WPS bản mới nhất đã vô hiệu hóa Foward key event nên các kiểu gõ khác không hoạt động nữa, bạn có thể cài đặt bộ gõ từ mã nguồn để cải thiện tốc độ gõ chế độ 6

**Comment by DurianDan** [comment]
> @phatbs21 bạn cài wps từ trang chủ để khắc phục lỗi này nhé https://www.wps.com/download/
> @cyrilchau WPS bản mới nhất đã vô hiệu hóa Foward key event nên các kiểu gõ khác không hoạt động nữa, bạn có thể cài đặt bộ gõ từ mã nguồn để cải thiện tốc độ gõ chế độ 6

Cảm ơn bạn nhé

**Comment by nhkphp** [comment]
> @phatbs21 bạn cài wps từ trang chủ để khắc phục lỗi này nhé https://www.wps.com/download/ @cyrilchau WPS bản mới nhất đã vô hiệu hóa Foward key event nên các kiểu gõ khác không hoạt động nữa, bạn có thể cài đặt bộ gõ từ mã nguồn để cải thiện tốc độ gõ chế độ 6

cài bộ gõ như thế nào bro

**Comment by phatbs21** [comment]
> nhkphp

Vào mục code xong kéo xuống có chỗ hướng dẫn cài đặt đó bạn
