### ISSUE TITLE
Không gõ được tiếng việt trên Viber [Fedora 32]

### ISSUE THREAD

**Issue by longhnguye** [BambooEngine/ibus-bamboo#164]
Trên Fedora 32 không gõ được tiếng việt trên Viber, còn lại đều hoạt động tốt
Distro: Fedora 32
DE: Gnome

**Comment by luongthanhlam** [comment]
bạn cài Viber từ snap hay apt? https://github.com/BambooEngine/ibus-bamboo/wiki/C%C3%A1c-v%E1%BA%A5n-%C4%91%E1%BB%81-th%C6%B0%E1%BB%9Dng-g%E1%BA%B7p

**Comment by longhnguye** [comment]
> bạn cài Viber từ snap hay apt? https://github.com/BambooEngine/ibus-bamboo/wiki/C%C3%A1c-v%E1%BA%A5n-%C4%91%E1%BB%81-th%C6%B0%E1%BB%9Dng-g%E1%BA%B7p

mình cài đặt từ mã nguồn luôn

**Comment by zenfas** [comment]
> > bạn cài Viber từ snap hay apt? https://github.com/BambooEngine/ibus-bamboo/wiki/C%C3%A1c-v%E1%BA%A5n-%C4%91%E1%BB%81-th%C6%B0%E1%BB%9Dng-g%E1%BA%B7p
> 
> mình cài đặt từ mã nguồn luôn

Viber sao có mã nguồn để build hay vậy 😂

**Comment by longhnguye** [comment]
Ý nhầm :)) viber mình cài từ trên trang chủ chứ, file rpm

**Comment by luongthanhlam** [comment]
bạn chạy lệnh này và paste kết quả lên đây nhé
`env | grep "IM_MODULE\|XMODIFERS"`

**Comment by longhnguye** [comment]
> bạn chạy lệnh này và paste kết quả lên đây nhé
> `env | grep "IM_MODULE\|XMODIFERS"`

mình về ubuntu rồi
trước đó có check thì nó 
QT_IM_MODULE=xim
XMODIFIERS=@im=xim
rồi mình có làm theo 
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60
để add thêm nhưng vẫn không được

**Comment by luongthanhlam** [comment]
sau khi add bạn cần restart máy và kiểm tra lại các biến môi trường, nếu hiện như này thì mới gõ được
```
QT_IM_MODULE=ibus
QT4_IM_MODULE=ibus
GTK_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
```
