### ISSUE TITLE
Hỗ trợ cho các ứng dụng cài qua snap????

### ISSUE THREAD

**Issue by KevinHN** [BambooEngine/ibus-bamboo#165]
Sau 1 hồi thử các bộ gõ thì thấy bamboo khá tốt, tuy nhiên hiện tại các ứng dụng mà cài qua snap thì không thể gõ được tiếng Việt. Không biết có hướng nào phát triển và khắc phục không?

**Comment by luongthanhlam** [comment]
bạn theo dõi ở đây nhé https://forum.snapcraft.io/t/compatibility-with-cjkv-input-method-frameworks/7788
