### ISSUE TITLE
Không gõ được trên Slack (Linux)

### ISSUE THREAD

**Issue by hai-nguyen-van** [BambooEngine/ibus-bamboo#166]
**Mô tả lỗi**

Không gõ được TELEX trên ứng dụng Slack.

**Các bước tái hiện lỗi**
1. Mở Slack 
2. Gõ `aa`
3. Thấy `aa`

**Kết quả mong muốn**
Hiện lên `â` (cách gõ TELEX)

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![Screenshot from 2020-09-15 10-32-41](https://user-images.githubusercontent.com/1613250/93186813-5805d900-f73f-11ea-9c6d-c12153534ba3.png)

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: GNOME
 - Phiên bản ibus-bamboo: `0.6.6-0~202008230821~ubuntu20.04.1`

**Thông tin thêm**

Có chạy với `ibus-unikey`.

**Comment by KevinHN** [comment]
Gỡ ra lên trang slack và tải slack-desktop về thì sẽ chạy đc. Hiện tại ko hỗ trợ gõ tiếng Việt khi cài qua snap!

**Comment by hai-nguyen-van** [comment]
OK. Đúng!

**Comment by npt-dev** [comment]
> **Mô tả lỗi**
> 
> Không gõ được TELEX trên ứng dụng Slack.
> 
> **Các bước tái hiện lỗi**
> 
> 1. Mở Slack
> 2. Gõ `aa`
> 3. Thấy `aa`
> 
> **Kết quả mong muốn**
> Hiện lên `â` (cách gõ TELEX)
> 
> **Ảnh chụp màn hình, hoặc clip quay màn hình**
> 
> ![Screenshot from 2020-09-15 10-32-41](https://user-images.githubusercontent.com/1613250/93186813-5805d900-f73f-11ea-9c6d-c12153534ba3.png)
> 
> **Môi trường**
> 
> * OS và version: Ubuntu 20.04
> * Desktop: GNOME
> * Phiên bản ibus-bamboo: `0.6.6-0~202008230821~ubuntu20.04.1`
> 
> **Thông tin thêm**
> 
> Có chạy với `ibus-unikey`.

Bác gõ Ctrl + ,
Trong phần spellcheck bác thêm Vietnamese vào là được
![image](https://user-images.githubusercontent.com/54330877/125025357-bc1dd300-e0ac-11eb-9d2e-b6cab020317d.png)
