### ISSUE TITLE
Gõ w không ra được chữ ư

### ISSUE THREAD

**Issue by LuckyLeeee** [BambooEngine/ibus-bamboo#168]
Mình đã quen với việc gõ w để ra ư luôn rồi nhưng ibus-bamboo mình thử các kiểu gõ đều không được, không biết có cách nào để sửa được không ạ.

**Comment by luongthanhlam** [comment]
bạn làm theo ở đây nhé 
https://github.com/BambooEngine/ibus-bamboo/wiki/G%C3%B5-%22%C6%B0%22-b%E1%BA%B1ng-c%C3%A1ch-g%C3%B5-%22w%22-ho%E1%BA%B7c-%22%5D%22
