### ISSUE TITLE
không sử dụng được trên skype

### ISSUE THREAD

**Issue by huyvu85** [BambooEngine/ibus-bamboo#169]
Ubuntu 20.4
Skype version 8.64.0.81

**Comment by luongthanhlam** [comment]
bạn xem ở đây nhé https://github.com/BambooEngine/ibus-bamboo/wiki/T%E1%BA%A1i-sao-kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-Vi%E1%BB%87t-trong-%E1%BB%A9ng-d%E1%BB%A5ng-snap%3F
