### ISSUE TITLE
Lỗi gõ không gạch chân trong Viber, Telegram bản .deb

### ISSUE THREAD

**Issue by manhnt9** [BambooEngine/ibus-bamboo#17]
**Mô tả lỗi**
Lỗi gõ dấu, ví dụ `đã` thì sẽ thành `dđaã`, không xóa được các ký tự.

Có vẻ khá giống lỗi trong GIMP của bạn này cũng gặp.

![Screenshot_2019-04-07_13-07-33](https://user-images.githubusercontent.com/11463928/55679456-28418780-5936-11e9-801e-40773300054f.png)

**Các bước tái hiện lỗi**
1. Mở Viber
2. Gõ tiếng việt trong khung chat

**Kết quả mong muốn**
Ví dụ: Gõ `đã` thì sẽ thấy `đã` thay vì `dđaã`, bấm backspace cần xóa được ký tự.

**Môi trường**
 - OS và version: Ubunty 18.04
 - Desktop: XFCE 4.12
 - Phiên bản ibus: IBus 1.5.17
 - Phiên bản ibus-bamboo: v0.4.0

**Ảnh chụp màn hình**
![Screenshot_2019-04-07_13-10-42](https://user-images.githubusercontent.com/11463928/55679490-a140df00-5936-11e9-80c4-b928b62103cf.png)

**Comment by ndgnuh** [comment]
Bạn đã thử chuyển sang những chế độ khác chưa, có 3 chế độ gõ không có gạch chân khác nhau đó?

**Comment by manhnt9** [comment]
Telex + VNI, Telex, Telext 2/3, đều bị, mình cũng đã thử đổi bảng mã.

**Comment by ndgnuh** [comment]
Không phải đổi bảng mã bạn ơi, có ba chế độ gõ không có gạch chân, bạn nhấn vào khung text input rồi nhấn tổ hợp phím Shift + ~, sau đó chọn và dùng thử các chế độ.

**Comment by manhnt9** [comment]
Đã thử hết 4 chế độ, chỉ có chế độ đầu tiên là còn ra tiếng Việt nhưng có lỗi.
3 chế độ còn lại không gõ dấu được, ra như tiếng Anh luôn.

Mình bật sang chế độ gạch chân thì gõ được. Vậy nên lỗi này chắc là do fix gạch chân.

**Comment by manhnt9** [comment]
Kiểu gõ gạch chân Telex có thể gõ trong Viber, nhưng lại lỗi gõ trong firefox, hoàn toàn không gõ được dấu.
Hướng fix mình nghĩ có 2 hướng sau:
- Fix telex gạch chân 
- Fix gõ không gạch chân trong Viber

**Comment by ndgnuh** [comment]
Ý bạn là 3 chế độ còn lại không gõ ra dấu mà chỉ như tiếng anh? Bạn thử mở terminal lên, chạy:
```sh
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS="@im=ibus"

ibus-daemon -rdx
ibus restart 

# bắt buộc chạy gimp từ terminal với mục đích test nhé
gimp
```

**Comment by manhnt9** [comment]
@@ Thần thánh vậy, 3 biến này fix luôn cả [lỗi high CPU](https://github.com/ibus/ibus/issues/2090) trong GIMP của mình và cả Viber.
Phải cho nó vào config user thôi. Thanks bạn nhé. Có vẻ ngon rồi.

**Comment by ndgnuh** [comment]
Thông tin thêm cho bạn là, nếu bạn thêm biến vào trong `.bashrc` hoặc `/etc/bash.bashrc` thì nó chỉ có hiệu lực khi chạy từ terminal, nếu bạn muốn nó có hiệu lực khi chạy từ menu hay launcher thì phải thêm vào `.profile` hoặc `/etc/profile`.

**Comment by manhnt9** [comment]
Mình đã thử thêm vào .profile lẫn /etc/profile.thì Firefox sẽ không chuyển được chế độ gõ sang bamboo.
Nếu làm như cách bạn viết ở trên thì Viber gõ được nhưng nãy mình chưa test kỹ, quay qua Firefox lại bị lỗi giống như ở mô tả issue và giống luôn lỗi #8.

**Comment by manhnt9** [comment]
Tức khi thằng Viber gõ được thì FF sẽ không và ngược lại, khi không gõ được thì lỗi của 1 trong hai thằng tương tự như #8.

**Comment by manhnt9** [comment]
Mình đã thử cả Telegram, cũng có lỗi này. Hình như nó ảnh hưởng tất cả các app Qt.

**Comment by manhnt9** [comment]
Thêm thông tin là Teni không bị lỗi này, mình không cần cài đặt gì thêm và vẫn gõ được trong Viber, Telegram.

**Comment by ndgnuh** [comment]
Bạn thử chạy ` ibus-daemon -rdx` xem, cái `x` khá quan trọng

**Comment by manhnt9** [comment]
Mình đã thử, Firefox sẽ không gõ được nếu chạy -rdx.

**Comment by ndgnuh** [comment]
Lúc bạn thêm biến xong bạn đã khởi động lại máy hay là logout rồi log in lại chưa?

**Comment by manhnt9** [comment]
Rồi bạn nhé.

**Comment by luongthanhlam** [comment]
Có vẻ fake backspace vẫn chưa thực sự ổn định, mình sẽ revert bộ gõ về pre-edit trong bản v0.4.1

**Comment by luongthanhlam** [comment]
Bản 0.4.1 bổ sung thêm chế độ backspace giả DirectForwardKeyevent khắc phục lỗi trên firefox và gimp

**Comment by luongthanhlam** [comment]
@manhnt9 bạn chạy 2 lệnh này 
rm -rf ~/.config/ibus-bamboo
ibus-daemon -drx
rồi bỏ chọn Fix lỗi gạch chân xem gõ đc bình thường không.

**Comment by ndgnuh** [comment]
Mình thấy trên telegram 3 chế độ sau không ổn, nhưng chế độ preedit gõ bình thường và không có gạch chân?

**Comment by manhnt9** [comment]
banản 0.4.1 goõ dđuoươợc viber nhuưng iừnuwnfire fox biị loôỗi roôồi, viber cunũng khoông xdungùng backspace dđuoươcợc, FF cunũng ko dunùng backsapace dđuoươc

**Comment by manhnt9** [comment]
ban 0.4.3 hoan toan khong go dau duoc o iFrefox va iVber va con bi loi nhay ky tu i ra dang truoc

**Comment by luongthanhlam** [comment]
bản 0.4.4 thì sao hả bạn?

**Comment by manhnt9** [comment]
apt chưa có, chắc cuối tuần hoặc tuần sau mình sẽ thử

**Comment by manhnt9** [comment]
Đã gõ được trong Viber/Telegram và Firefox, tuy nhiên nếu ẩn gạch chân thì Viber lỗi (bật Fix lỗi gạch chân).

**Comment by manhnt9** [comment]
Đã thử chuyển sang chế độ sửa lỗi gạch chân thứ 2. Hoạt động tốt, cảm ơn tác giả nhé :smile:
