### ISSUE TITLE
Không gõ được trên PhpStorm

### ISSUE THREAD

**Issue by darktaiga01** [BambooEngine/ibus-bamboo#170]
**Mô tả lỗi**
Khi bật PhpStorm gõ tiếng Việt thì bàn phím không nhận bất kỳ ký tự nào (tức gõ không ăn), sau đó mình có chuyển sang chế độ loại trừ thì bàn phím lại nhận như bình thường.
Bản PhpStorm mình tải từ trên AUR về, trước đó có sử dụng Manjaro, nhưng không gặp lỗi này, sau này mình mới chuyển về Arch và gặp lỗi trên, mình đã kiểm tra, các biến môi trường đều nhận đủ theo bài hướng dẫn.

**Các bước tái hiện lỗi**
1. Mở PhpStorm, mở 1 file bất kỳ
2. Gõ chữ bất kỳ
**Kết quả mong muốn**
VD: Khi gõ chữ "abc", phải xuất hiện chữ "abc", nhưng không xuất hiện gì cả, ngay cả nút backspace, space cũng không hoạt động.  Chuyển về chế độ loại trừ thì gõ bình thường

**Ảnh chụp màn hình, hoặc clip quay màn hình**
https://youtu.be/b3hvTT0rzPo

**Môi trường**
 - OS và version: Arch Linux x86_64 
 - Desktop: KDE
 - Phiên bản ibus-bamboo: v0.6.6 build từ mã nguồn

**Comment by luongthanhlam** [comment]
nhờ bạn chạy lệnh `ibus-daemon -xrv`, bật ibus-bamboo, gõ một vài từ tiếng Việt trong PhpStorm rồi gửi log lên đây nhé.

**Comment by darktaiga01** [comment]
> nhờ bạn chạy lệnh `ibus-daemon -xrv`, bật ibus-bamboo, gõ một vài từ tiếng Việt trong PhpStorm rồi gửi log lên đây nhé.

Có phải là như vậy không bạn?
https://pastebin.com/YebfHapW

**Comment by luongthanhlam** [comment]
Hmm, có vẻ bản PhpStorm bạn đang dùng xung đột với ibus.

**Comment by darktaiga01** [comment]
> Hmm, có vẻ bản PhpStorm bạn đang dùng xung đột với ibus.

Lúc đầu mình cũng nghĩ do bản PhpStorm trên AUR có vấn đề, nên mình tải trực tiếp từ trang chủ, hay sử dụng phiên bản cũ hơn (2019) để xem có vấn đề gì không nhưng vẫn thế.

**Comment by darktaiga01** [comment]
Cảm ơn bạn đã hỗ trợ, mình đã quay về xài lại Manjaro và gõ được như bình thường. Không hiểu bên Arch có vấn đề gì mà bị lỗi nữa.
