### ISSUE TITLE
Chữ bị popup khi gõ trong Sublime Text3

### ISSUE THREAD

**Issue by texervn** [BambooEngine/ibus-bamboo#173]
**Mô tả lỗi**
Khi gõ Tiếng Việt trong sublime text (v.3), các chữ bị popup trước khi được insert vào cửa sổ của làm việc.
Hệ điều hành đang dùng: Ubuntu 18.04.

**Các bước tái hiện lỗi**
1. Cài đặt ibus và ibus-bamboo trên Ubuntu 18.04
2. Mở cửa sổ làm việc của Sublime Text (v.3)
3. Gõ Tiếng Việt trong cửa sổ của Sublime Text.
4. Thấy xuất hiện popup chữ trước khi được chèn vào cửa sổ làm việc.

**Kết quả mong muốn**
Có thể gõ Tiếng Việt một cách bình thường mà không bị popup chữ.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
https://youtu.be/m-uw2rbjMIw

**Môi trường**
 - OS và version: Ubuntu 18.04
 - Desktop: Pantheon
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.6.5)

**Comment by luongthanhlam** [comment]
bạn gửi giúp mình output 2 lệnh sau
```
env | grep "IM_MODULE\|XMODIFERS"
apt list --installed|grep ibus
```

**Comment by texervn** [comment]
Mình gửi bạn thông tin log đây nhé:
`QT4_IM_MODULE=xim
QT_IM_MODULE=xim
GTK_IM_MODULE=ibus
`
`gir1.2-ibus-1.0/bionic,now 1.5.17-3ubuntu5.3+elementary6+r1~ubuntu5.1.2.1 amd64 [installed,automatic]
ibus/bionic,now 1.5.17-3ubuntu5.3+elementary6+r1~ubuntu5.1.2.1 amd64 [installed]
ibus-bamboo/bionic,now 0.6.6-0~202008230821~ubuntu18.04.1 amd64 [installed]
ibus-chewing/bionic,now 1.5.1-1 amd64 [installed,automatic]
ibus-gtk/bionic,now 1.5.17-3ubuntu5.3+elementary6+r1~ubuntu5.1.2.1 amd64 [installed,automatic]
ibus-gtk3/bionic,now 1.5.17-3ubuntu5.3+elementary6+r1~ubuntu5.1.2.1 amd64 [installed,automatic]
ibus-hangul/bionic,now 1.5.0+git20161231-1 amd64 [installed,automatic]
ibus-libpinyin/bionic-updates,now 1.11.0-1ubuntu0.18.04.1 amd64 [installed,automatic]
ibus-m17n/bionic,now 1.3.4-5 amd64 [installed,automatic]
ibus-mozc/bionic-updates,now 2.20.2673.102+dfsg-2ubuntu0.18.04.1 amd64 [installed,automatic]
ibus-table/bionic,bionic,now 1.9.14-3 all [installed,automatic]
ibus-table-cangjie/bionic,bionic,now 1.8.2-2 all [installed,automatic]
ibus-table-cangjie-big/bionic,bionic,now 1.8.2-2 all [installed,automatic]
ibus-table-cangjie3/bionic,bionic,now 1.8.2-2 all [installed,automatic]
ibus-table-cangjie5/bionic,bionic,now 1.8.2-2 all [installed,automatic]
ibus-table-quick-classic/bionic,bionic,now 1.8.2-2 all [installed,automatic]
ibus-table-wubi/bionic,bionic,now 1.8.2-2 all [installed,automatic]
libibus-1.0-5/bionic,now 1.5.17-3ubuntu5.3+elementary6+r1~ubuntu5.1.2.1 amd64 [installed,automatic]
libusageenvironment3/bionic,now 2018.02.18-1 amd64 [installed,automatic]
libusb-1.0-0/bionic,now 2:1.0.21-2 amd64 [installed]
libusbmuxd4/bionic,now 1.1.0~git20171206.c724e70f-0.1 amd64 [installed,automatic]
libusbredirparser1/bionic,now 0.7.1-1 amd64 [installed,automatic]
`

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn trên [wiki](https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng) nhé.

**Comment by texervn** [comment]
Cảm ơn bạn đã giúp. Mình sẽ đọc lại wiki và cấu hình lại xem sao.
