### ISSUE TITLE
Update bản build trên Arch AUR

### ISSUE THREAD

**Issue by zenfas** [BambooEngine/ibus-bamboo#175]
Phiên bản Ibus-bamboo ARCH AUR đang là 0.6.5-1
Mong sớm update lên 0.6.7
@nopain2110

**Comment by vanhtuan0409** [comment]
2nd this @nopain2110 ơi

**Comment by zenfas** [comment]
Mình thấy có bạn cập nhật ở link khác https://aur.archlinux.org/packages/bamboo-ibus-git/
Nếu @nopain2110 không rảnh để duy trì thì mình nghĩ đóng hoặc chuyển giao cho người khác

**Comment by zimhat** [comment]
I sent an email to @nopain2110 a week ago without answer. Maybe someone could submit a request to get the maintainer role for the AUR package.

**Comment by zenfas** [comment]
Repo đã được cập nhật
