### ISSUE TITLE
Không gõ được tiếng Việt trên Foxit Reader

### ISSUE THREAD

**Issue by zvtrung** [BambooEngine/ibus-bamboo#176]
**Mô tả lỗi**

Không thễ gõ được tiếng Việt trên Foxit Reader (các comment, notes, ...) 
Tổ hợp phím Shift-~ không có tác dụng.

**Môi trường**
 - OS và version::  Ubuntu 20.04
 - Desktop: Gnome,
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.6.5)
 - Foxit Reader: được tải tại https://www.foxitsoftware.com/downloads/pdf-reader-thanks.html?product=Foxit-Reader&platform=Linux-64-bit&version=&package_type=&language=&formId=download-reader

**Comment by luongthanhlam** [comment]
bạn xem ở đây nhé https://github.com/ibus/ibus/issues/1968
