### ISSUE TITLE
Lỗi không gõ tiếng Việt trên onlyoffice được

### ISSUE THREAD

**Issue by hacker010392** [BambooEngine/ibus-bamboo#178]
hi, add và các bạn
Mình mở only office lên gõ tiếng Việt nhưng không được. Mình đã thử nhiều cách nhưng vẫn không khắc phục được. Bạn nào biết cách khắc phục thì chỉ mình nhé. Mình cám ơn trước.
Thân 
Hùng

**Comment by luongthanhlam** [comment]
mình gõ bình thường mà, bạn đã làm theo hướng dẫn trên [wiki](https://github.com/BambooEngine/ibus-bamboo/wiki/C%C3%A1c-v%E1%BA%A5n-%C4%91%E1%BB%81-th%C6%B0%E1%BB%9Dng-g%E1%BA%B7p) chưa?
