### ISSUE TITLE
Không gõ được trong ô search ubuntu 20.04

### ISSUE THREAD

**Issue by minhtn-sudo** [BambooEngine/ibus-bamboo#179]
Mình đang sử dụng ubuntu 20.04 Gnome và ibus bamboo, tuy nhiên khi nhấn phím super và nhập ô tìm kiếm bằng tiếng việt thì không gõ được, phải chuyển qua tiếng anh.

Mong nhận được cách fix issue này. Thanks

**Comment by luongthanhlam** [comment]
Vì lý do kỹ thuật https://github.com/BambooEngine/ibus-bamboo/issues/80, hiện tại vẫn chưa có cách nào để fix hoàn toàn lỗi này. Tuy nhiên, bạn có thể khắc phục phần nào bằng một trong các cách sau:
- Chuyển sang tiếng anh khi search trong Gnome
- Chuyển tất cả các chế độ gõ 2, 3, 4, 5 trong tất cả ứng dụng sang chế độ gõ số 1 hoặc 6
- Minimize tất cả các ứng dụng trên màn hình (SUPER+D) trước khi mở search box

**Comment by vuminhcongvmc** [comment]
Bạn sử dụng trình hiển thị Wayland là được nhé (lỗi của Wayland: OBS sẽ lấy được hình ảnh full màn hình).

**Comment by chienhm** [comment]
Gnome 3.38.1 đã có thể gõ được bình thường bạn nhé.

**Comment by cao-nv** [comment]
Mình cũng gặp tình trạng tương tự. Khi nhấn ~ thì Ibus lại nhận thành cửa sổ mình đang mở trước khi nhấn Super

**Comment by thuanpham2311** [comment]
```js
OS: Pop!_OS 20.10
Kernel: 5.8.0-7642-generic
DE: GNOME 3.38.2
```

Ở cấu hình như trên mình gõ được bình thường, dù phải gõ xong một chữ thì nó mới nhận.
 
Ví dụ: gõ  "nvim" và gõ thêm một phím space nữa là nhận được chữ cái đó.
> bạn có thể fix tạm lỗi này bằng cách thêm vào danh sách loại trừ

**Comment by luongthanhlam** [comment]
Fixed: https://github.com/BambooEngine/ibus-bamboo/commit/cc6a7589f4481827e62d9ab814b2c7a906d47645
