### ISSUE TITLE
Lỗi sau khi ibus khởi động, ibus-bamboo không tự chạy nếu trước đó ta vẫn để ibus-bambo là bộ gõ (Đã hết ở v0.4.2) và lỗi số thứ tự chỉ mục bảng chọn chế độ gõ.

### ISSUE THREAD

**Issue by hiepvu91945** [BambooEngine/ibus-bamboo#18]
- **Môi trường:** 

OS và version: KDE neon User Edition 5.15 x86_64; Kernel: 4.18.0-17-generic
Desktop: KDE
Phiên bản ibus-bamboo: v0.4.1
Được cài đặt từ PPA.
OS và version: Manjaro Linux x86_64 ; Kernel: 4.19.32-1-MANJARO
Desktop: KDE
Phiên bản ibus-bamboo: v0.4.1
Được cài đặt từ github.

- **Mô tả lỗi:**

- **I: Lỗi sau khi ibus khởi động, ibus-bamboo không tự chạy nếu trước đó ta vẫn để ibus-bambo là bộ gõ**

Để ibus-bamboo là bộ gõ mặc định, nhưng vì lý do nào đó khiến ibus khởi động lại, chẳng hạn:
1. Log in-Log out
2. Restart máy tính
3. Dùng lệnh "ibus restart"
Những điều trên khiến ibus-bamboo không chạy lại sau đó.
Trong trường hợp đó, nếu muốn sử dụng ibus-bamboo:
Nếu chọn trực tiếp ibus-bamboo trên khay công cụ, sẽ KHÔNG chọn được, phải chọn sang 1 bộ gõ khác sau đó mới quay lại chọn ibus-bamboo được.
Sử dụng phím tắt cũng vậy, nếu chọn ngay ibus-bamboo sẽ không chọn được, phải chọn sang 1 bộ gõ khác sau đó mới quay lại chọn ibus-bamboo được.

- **II:  Lỗi số thứ tự chỉ mục bảng chọn chế độ gõ**

Ở lần đầu khi sử dụng bộ gõ mà cần phải sử dụng phím tắt để chuyền đổi chế độ gõ, thì số thứ tự (stt) để lựa chọn chế độ gõ bị lệch so với stt hướng dẫn chọn ở phía trên bảng chọn.
Cụ thể: 0/1/2/3/4/5 so với 1/2/3/4/5/6
Dẫn đến có thể chọn lựa sai chế độ mong muốn.
**Các bước tái hiện lỗi:**
Cách 1:
Lần đầu đăng nhập phiên làm việc và sử dụng bộ gõ với phím tắt chuyển đổi chế độ.
Cách 2:
Sử dụng lệnh "ibus restart" và sử dụng bộ gõ với phím tắt chuyển đổi chế độ.

- **Ảnh chụp màn hình, hoặc clip quay màn hình:**

**Lỗi I: (ibus-bamboo phiên bản 0.4.1, trên Manjaro)**
https://www.youtube.com/watch?v=Eb64ZSCUqg0&feature=youtu.be
**Lỗi II: (ibus-bamboo phiên bản 0.4.0, trên KDE Neon)**
https://www.youtube.com/watch?v=YdhX0ZdbTDE&feature=youtu.be

- **Lưu ý:**

Lỗi số thứ tự chỉ mục khi sử dụng phím tắt: Shift + ~ chọn chế độ hiện đã xuất hiện ở cả 2 môi trường KDE Neon và Manjaro, nhưng hiện là 0/1/2/3/4/5 so với 1/2/3/4/5/6 trong bản 0.4.1 này. Ở bản 0.4.0 trước đó, trên Manjaro không bị , còn KDE Neon bị ở cả 2 bản 0.4.0 lẫn 0.4.1.

**Comment by hiepvu91945** [comment]
**Cập nhật:**
Sau khi thử cài lại bản ibus-bamboo phiên bản 0.4.0 trên môi trường Manjaro thì  cũng bị lỗi số thứ tự chỉ mục khi sử dụng phím tắt để chọn chế độ gõ. Chắc chắc hôm trước chưa kiểm tra kỹ lưỡng. Rất xin lỗi.
Như vậy kết luận là cả bản 0.4.0 và bản 0.4.1 đều bị lỗi số thứ tự chỉ mục khi chọn  chế độ gõ.
Lỗi ibus-bamboo không tự chạy lại khi ibus khởi động lại cũng vậy, bị ở cả 2 bản 0.4.0 và 0.4.1 trên cả hai môi trường.
Trong ảnh dưới là ibus bamboo phiên bản 0.4.0 môi trường Manjaro.
![ibus bamboo 040 manjarokde](https://user-images.githubusercontent.com/48562187/55691432-4061e700-59c8-11e9-98a3-a8d6191b99cf.png)

**Comment by ndgnuh** [comment]
1. Bạn chạy lệnh 
```sh
loginctl show-session $(loginctl) -p Type
```
rồi đăng output lên xem
2. Bạn kiểm tra xem trong máy đã cài gói `ibus-qt` và `kimtoy` chưa (có thể tên khác với mỗi distro)

**Comment by hiepvu91945** [comment]
Tui chạy lệnh của bác thì báo như bên dưới, có vẻ không ra kết quả bác cần. Vì thế tui tách riêng 2 lệnh của bác ra xem như thế nào, thì ra kết quả này, không rõ có phải thông tin bác cần không, bác xem nhé.
Trên Manjaro:
```
[peih@peih-pc-kde ~]$ loginctl show-session $(loginctl) -p Type
Failed to get session path: No session 'SESSION' known
[peih@peih-pc-kde ~]$ loginctl -p Type
SESSION  UID USER SEAT  TTY
      1 1000 peih seat0    

1 sessions listed.
[peih@peih-pc-kde ~]$ loginctl show-session 1
Id=1
User=1000
Name=peih
Timestamp=Mon 2019-04-08 11:26:31 +07
TimestampMonotonic=30994964
VTNr=1
Seat=seat0
Display=:0
Remote=no
Service=sddm-autologin
Desktop=KDE
Scope=session-1.scope
Leader=655
Audit=1
Type=x11
Class=user
Active=yes
State=active
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
LockedHint=no
[peih@peih-pc-kde ~]$
```
Trên KDE Neon:
```
[peih@peih-kdeneon ~]$ loginctl -p Type
   SESSION        UID USER             SEAT             TTY             
         1       1000 peih             seat0                            

1 sessions listed.
[peih@peih-kdeneon ~]$ loginctl show-session 1
Id=1
User=1000
Name=peih
Timestamp=Mon 2019-04-08 11:34:13 +07
TimestampMonotonic=33139142
VTNr=1
Seat=seat0
Display=:0
Remote=no
Service=sddm-autologin
Desktop=KDE
Scope=session-1.scope
Leader=1064
Audit=1
Type=x11
Class=user
Active=yes
State=active
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
LockedHint=no
[peih@peih-kdeneon ~]$
```
Hai gói bác bảo tui xem thấy như sau:
Trên Manjaro, có cả hai gói trên nhưng chưa được cài đặt. Vậy nên tui cài đặt xem sao thì vẫn không khắc phục cả 2 lỗi.
Trên KDE Neon, tui tìm thấy có 2 gói liên quan tới ibus-qt được cài đặt rồi như ảnh bên dưới, nhưng không tìm thấy gói "kimtoy" nào cả.
![qt kdeneon](https://user-images.githubusercontent.com/48562187/55700037-ea0c9c80-59f7-11e9-813e-a4b43938995e.png)

**Comment by hiepvu91945** [comment]
Thêm 1 lưu ý nhỏ ở lỗi số 2 đó là:
Chỉ bị sai stt chỉ mục trong lần đầu tiên chọn chế độ, ở lần thứ 2,3...n mà ibus không bị khởi động lại, thì chúng sẽ khớp với nhau.

**Comment by luongthanhlam** [comment]
bạn cập nhật lên bản v0.4.2 xem còn bị không nhé

**Comment by hiepvu91945** [comment]
**Cập nhật:**
Phiên bản ibus-bamboo v0.4.2
Môi trường: Hai môi trường trên
Lần này đều được build từ github theo hướng dẫn ở mục wiki, do bên bản PPA trên KDE Neon tui cập nhật thì không thấy báo có bản mới.
**Lỗi 1: Lỗi sau khi ibus khởi động, ibus-bamboo không tự chạy nếu trước đó ta vẫn để ibus-bambo là bộ gõ**
Không còn nữa bác.
**Lỗi 2: Lỗi số thứ tự chỉ mục bảng chọn chế độ gõ**
Vẫn còn và có vẻ như theo chiều hướng xấu hơn trên cả hai môi trường.
Đó là:
Sai stt chỉ mục xuyên suốt toàn bộ những lần chọn chế độ gõ, bất kể ibus có bị khởi động lại hay không. Và bây giờ ở những lần chọn sau đó, tui không thấy dấu hoa thị đánh dấu hiện tại bộ gõ đang trong chế độ nào. 
Ở phiên bản trước: v0.4.0 hay v0.4.1, sau khi ibus restart, thì lỗi stt chỉ bị ở lần đầu tiên chọn, tui tạm khắc phục là bấm số 0 chọn chế độ mặc định, để bảng chọn tắt đi, sau đó mở lại thì stt sẽ chuẩn trở lại, và tất nhiên, có dấu hoa thị đánh dấu.
**Ảnh**
ibus-bamboo v0.4.2, môi trường KDE Neon:
![loi stt ibus bamboo 042 kde neon](https://user-images.githubusercontent.com/48562187/55742419-d7c34a80-5a59-11e9-86f2-d5a9f7d76000.png)
ibus-bamboo v.0.4.2, môi trường Manjaro:
![loi stt ibus bamboo 042 manjaro_2](https://user-images.githubusercontent.com/48562187/55742506-10fbba80-5a5a-11e9-9945-9d54865c8ecf.png)

**Comment by ndgnuh** [comment]
Bạn tìm `kimtoy` ở chỗ  khác rồi cài đặt thử, có thể là trên kde store hoặc cài từ git xem có hết lỗi không. Vì vấn đề này liên quan đến giao diện nên mình có linh cảm gói kia sẽ giải quyết :v

**Comment by hiepvu91945** [comment]
Vẫn không được bác, bên Manjaro tui cài đặt kimtoy từ Octopi, bên KDE Neon tui cài từ git. Nếu thông qua kimtoy để chạy ibus thì không sử dụng được bộ gõ nào cả, chọn Configure input method từ khay hệ thống của kimtoy vô tác dụng. Nếu chạy song song cả hai thì vẫn bị lỗi stt chỉ mục chọn chế độ. Lỗi số 1 thì bác luongthanhlam đã fix ở bản v0.4.2 rồi, nhưng cái lỗi stt lại có vẻ tiến triển không được tốt cho lắm.
Ảnh kimtoy trên KDE Neon:
![kimtoy kde neon](https://user-images.githubusercontent.com/48562187/55759596-f1798780-5a83-11e9-9bc1-b4af4bb80e22.png)

**Comment by hiepvu91945** [comment]
### **Cập nhật: ibus-bamboo v0.4.4**
Môi trường: Cả hai môi trường trên
**Lỗi 2: Lỗi số thứ tự chỉ mục bảng chọn chế độ gõ**
Đã hết. Stt đã đồng bộ với nhau và dấu hoa thị đánh dấu chế độ xuất hiện trở lại bất kể ibus có khởi động lại hay không.
Rất cảm ơn tác giả đã nhanh chóng cập nhật hoàn thiện bộ gõ ngày một tốt lên.
Xin phép được đóng bài báo lỗi này tại đây.

**Comment by luongthanhlam** [comment]
Lỗi này có vẻ lại quay lại rồi

**Comment by leanhtuanwru** [comment]
Hiện tại mình đang sử dụng Deepin 15.11 và iBus-Bamboo v0.6.2. Hiện tại mình đã gõ được Tiếng Việt ở hầu hết các App mình đang sử dụng nhưng mình cũng đang gặp một lỗi là khi mới khởi động máy lên thì không thế sử dụng Shortcuts Super+Space để chuyển bộ gõ (Next input method) được. Nhưng sau khi vào Preference chọn lại Shortcuts (Vẫn để mặc định phím tắt là Super+Space hoặc đổi Shortcuts khác) rồi OK thì sau đó Shorcuts này lại hoạt động bình thường. Hiện tại mình chưa có các khắc phục. Mỗi lần mở máy lại phải vào chọn lại Shorcuts khá mất thời gian. Rất mong nhận được hướng dẫn Fix của các bạn. Tks !!!
