### ISSUE TITLE
Thêm hướng dẫn cài đặt ibus-bamboo

### ISSUE THREAD

**Issue by rockpham** [BambooEngine/ibus-bamboo#180]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

1. Cài đặt theo hướng dẫn trên Linux Mint 20
2. Ibus ko tự khởi động theo OS
**Kết quả mong muốn**

Ibus nên khởi động với Linux

**Môi trường**
 - OS và version: Linux Mint 20 Ulyana
 - Desktop: Cinnamon
 - Phiên bản ibus-bamboo: mới nhất

**Thông tin thêm**

Đã sửa được khi thêm 6 dòng này vào .bashrc
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus
ibus-daemon -drx

Hướng dẫn tìm được từ forum của Manjaro
https://forum.manjaro.org/t/cai-d-t-ibus-bamboo-d-go-ti-ng-vi-t-tren-manjaro/7586

**Comment by vuminhcongvmc** [comment]
bạn vào terminal chạy lệnh:
$ im-config -n ibus
sau đó logout -> login lại là được nhé. nếu không được nữa thì cài lại linux mint rồi làm theo cách của mình thay vì cách được hướng dẫn bởi ad hay phần mềm. tui đã test và luôn thành công mới giám nói vậy.

**Comment by luongthanhlam** [comment]
Thanks, mình đã thêm hướng dẫn trên wiki :+1:
