### ISSUE TITLE
Không sử dụng ibus-bamboo trên phần mềm ICQ được!

### ISSUE THREAD

**Issue by firephx** [BambooEngine/ibus-bamboo#181]
Mình sử dụng ibus-bamboo, có thể gõ TV trên các phần mềm như telegram,.. nhưng phần mềm chat ICQ lại không gõ được. Nhờ b xem lại hướng dẫn hộ mình cách fix
Cảm ơn b

**Comment by luongthanhlam** [comment]
Bạn xem ở đây nhé https://github.com/BambooEngine/ibus-bamboo/wiki/C%C3%A1c-v%E1%BA%A5n-%C4%91%E1%BB%81-th%C6%B0%E1%BB%9Dng-g%E1%BA%B7p
