### ISSUE TITLE
Manjaro KDE Plasma Không gõ được tiếng việt trên libreoffice, scribus

### ISSUE THREAD

**Issue by oaitvt** [BambooEngine/ibus-bamboo#182]
Manjaro KDE Plasma  không gõ tiếng việt trên libreofice, scribus, trên web vẫn gõ tiếng việt bình thường

**Comment by luongthanhlam** [comment]
Bạn làm theo hướng dẫn trên [wiki](https://github.com/BambooEngine/ibus-bamboo/wiki/C%C3%A1c-v%E1%BA%A5n-%C4%91%E1%BB%81-th%C6%B0%E1%BB%9Dng-g%E1%BA%B7p) nhé.
