### ISSUE TITLE
Không gõ được trong vim terminal ubuntu 20.04

### ISSUE THREAD

**Issue by hhuuson97** [BambooEngine/ibus-bamboo#183]
Chào bạn, mình đang dùng ubuntu 20.04 và ibus bamboo. Mọi thứ đều hoạt động tốt trừ việc mình dùng lệnh vi để edit trong terminal thì bị lỗi. Mình gặp lỗi này ngay cả khi chuyển bộ gõ sang tiếng Anh.

**Comment by luongthanhlam** [comment]
Cụ thể bạn đang gặp lỗi gì vậy?

**Comment by hhuuson97** [comment]
https://drive.google.com/file/d/1zKXhSQUUBwjsSAgt6RQHOm-DIH0OdyoQ/view?usp=sharing
Cụ thể mình đang gặp lỗi trong video á. Mình cố gắng gõ tiếng việt trong vi editor nhưng lại bị lỗi.

**Comment by luongthanhlam** [comment]
> https://drive.google.com/file/d/1zKXhSQUUBwjsSAgt6RQHOm-DIH0OdyoQ/view?usp=sharing
> Cụ thể mình đang gặp lỗi trong video á. Mình cố gắng gõ tiếng việt trong vi editor nhưng lại bị lỗi.

Lỗi này của bạn không liên quan đến ibus, bạn thử kiểm tra lại có cài plugins hay phần mềm nào xung đột ko.
