### ISSUE TITLE
Khong go duoc Tieng Viet

### ISSUE THREAD

**Issue by meokisama** [BambooEngine/ibus-bamboo#186]
**Mô tả lỗi**

Khong go duoc Tieng Viet mac du da cai Bamboo theo dung cac buoc va khong gap loi nao. 
_(Da them Bamboo trong ibus-setup va Input Sources)_

**Môi trường**
 - OS và version: Kali Linux 2020.3
 - Desktop: GNOME
 - Phiên bản ibus-bamboo: 0.6.7

**Comment by luongthanhlam** [comment]
Bạn xem ở đây nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
