### ISSUE TITLE
Lỗi với aegisub

### ISSUE THREAD

**Issue by tuilakhanh** [BambooEngine/ibus-bamboo#187]
**Mô tả lỗi**

Không gõ được nếu trước đó không có khoảng trống (chi tiết xem ở video)

**Các bước tái hiện lỗi**

1. Mở aegisub
2. Làm như mô tả lỗi

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://photos.app.goo.gl/sHprP7PM4h4d3u9r7

**Môi trường**
 - OS và version: Arch Linux x86_64  | Kernel 5.9.3-arch1-1 
 - Desktop: Xfce
 - Phiên bản ibus-bamboo: v0.6.5

**Comment by luongthanhlam** [comment]
có vẻ lỗi này từ phía aegisub, bạn có thể khắc phục bằng cách nhấn Shift+~ và chọn phím 5.
