### ISSUE TITLE
Edit config file thủ công vì không có system tray

### ISSUE THREAD

**Issue by TrinhMinhVu** [BambooEngine/ibus-bamboo#188]
Mình không config được vì mình không sài system tray.
Config file nằm ở đâu vậy ạ mình xài fedora linux

**Comment by luongthanhlam** [comment]
> Mình không config được vì mình không sài system tray.
> Config file nằm ở đâu vậy ạ mình xài fedora linux

Bạn có thể cấu hình bằng cách chạy ibus-setup, trong `Font and Style` > `Show Property panel` chọn `Always` để hiện thanh cấu hình.

**Comment by luongthanhlam** [comment]
File config nằm ở `~/.config/ibus-bamboo/ibus-bamboo.config.json`

**Comment by vryy** [comment]
@luongthanhlam làm thế nào để chuyển bộ gõ trong file config nhỉ?
