### ISSUE TITLE
Lỗi không đúng layout phím khi chuyển từ bàn phím tiếng Pháp sang IBus-Bamboo

### ISSUE THREAD

**Issue by laiduy98** [BambooEngine/ibus-bamboo#189]
**Mô tả lỗi**
Sau khi sử dụng bàn phím tiếng Pháp (layout AZERTY) rồi chuyển sang Ibus bamboo thì layout bàn phím vẫn giữ nguyên là layout AZERTY. Nếu muốn đúng layout QWERTY thì phải chuyển qua bàn phím tiếng Anh rồi mới khi chuyển lại sang IBus-Bamboo.

**Các bước tái hiện lỗi**
1. Thêm bàn phím tiếng Pháp và Ibus-bamboo.
2. Chuyển qua layout tiếng Pháp, lúc này layout là AZERTY.
3. Chuyển qua ibus-bamboo, vẫn gõ đươc tiếng Việt nhưng layout vẫn là AZERTY chứ không phải là layout QWERTY.

**Kết quả mong muốn**
Khi chuyển trực tiếp từ bàn phím tiếng Pháp sang Ibus bamboo thì layout cũng chuyển từ AZERTY sang QWERTY.

**Môi trường**
 - OS và version: Ubuntu 20.04, Arch.
 - Desktop: Gnome, I3wm.
 - Phiên bản ibus-bamboo: v0.6.7.

**Comment by luongthanhlam** [comment]
làm sao để tái hiện lỗi này nhỉ? mình thêm bàn phím tiếng Pháp từ ibus nhưng layout vẫn là QWERTY

**Comment by laiduy98** [comment]
Video cách tái hiện lỗi đây ạ:
[https://www.youtube.com/watch?v=mEVulSi3Jbs&feature=youtu.be&ab_channel=DuyLai](Các bước tái hiện lỗi sai layout phím khi chuyển từ bàn phím tiếng Pháp sang Ibus-Bamboo)

**Comment by luongthanhlam** [comment]
Bạn cập nhật lên bản v0.6.8 rồi add bộ gõ Bamboo (US layout) như hình dưới sẽ fix được lỗi này nhé
![Screenshot from 2020-11-29 14-26-47](https://user-images.githubusercontent.com/26364140/100535835-f12c9200-324e-11eb-88c7-2955f9145a5c.png)
