### ISSUE TITLE
Không thể gõ tiếng Việt

### ISSUE THREAD

**Issue by vuminhcongvmc** [BambooEngine/ibus-bamboo#19]
Mình sử dụng Ubuntu 18.10 và cài đặt Ibus-bamboo 0.4.3 nhưng không thể gõ được tiếng Việt dù dùng bất kỳ chế độ nào
Mình đã sử dụng phiên bản 0.4.2 hoạt động rất tốt sau khi cập nhật thì bị vậy. Mong nhóm fix giúp mình.

**Comment by huyndnse63331** [comment]
Mình cũng bị tình trạng i chang, những bản update trước đều xài bình thường, sau khi update lên bản 0.4.3 thì không gõ được tiếng việt được dù chỉnh đủ bảng mã với kiểu gõ.

**Comment by vuminhcongvmc** [comment]
> Mình cũng bị tình trạng i chang, những bản update trước đều xài bình thường, sau khi update lên bản 0.4.3 thì không gõ được tiếng việt được dù chỉnh đủ bảng mã với kiểu gõ.
> Ubuntu 16.04.6
