### ISSUE TITLE
Không cài được ibus-bamboo trên Opensuse

### ISSUE THREAD

**Issue by dangqth** [BambooEngine/ibus-bamboo#191]
Như tiêu để để trên, khi mình cài bằng terminal thì nó báo lỗi sau : 
it@localhost:~> sudo zypper addrepo https://download.opensuse.org/repositories/home:lamlng/openSUSE_Tumbleweed/home:lamlng.repo

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for root: 
Adding repository 'Bamboo - A Vietnamese Input method editor (openSUSE_Tumbleweed[done]
Repository 'Bamboo - A Vietnamese Input method editor (openSUSE_Tumbleweed)' successfully added

URI         : https://download.opensuse.org/repositories/home:/lamlng/openSUSE_Tumbleweed/
Enabled     : Yes
GPG Check   : Yes
Autorefresh : No
Priority    : 99 (default priority)

Repository priorities are without effect. All enabled repositories share the same priority.
it@localhost:~> sudo zypper refresh
Repository 'Main Repository (NON-OSS)' is up to date.                                  
Repository 'Main Repository (OSS)' is up to date.                                      
Repository 'Main Update Repository' is up to date.                                     
Retrieving repository 'Bamboo - A Vietnamese Input method editor (openSUSE_Tumblewee[/]

New repository or package signing key received:

  Repository:       Bamboo - A Vietnamese Input method editor (openSUSE_Tumbleweed)
  Key Name:         home:lamlng OBS Project <home:lamlng@build.opensuse.org>
  Key Fingerprint:  D9749617 F9E82854 DB112110 360062B9 60D7EDDB
  Key Created:      Tue 30 Oct 2018 12:58:27 PM +07
  Key Expires:      Thu 07 Jan 2021 12:58:27 PM +07 (expires in 39 days)
  Rpm Name:         gpg-pubkey-60d7eddb-5bd7f303

Do you want to reject the key, trust temporarily, or trust always? [r/t/a/?] (r): a
Retrieving repository 'Bamboo - A Vietnamese Input method editor (openSUSE_Tumble[done]
Building repository 'Bamboo - A Vietnamese Input method editor (openSUSE_Tumblewe[done]
Repository 'openSUSE-20201117-0' is up to date.                                        
All repositories have been refreshed.
it@localhost:~> sudo zypper install ibus-bamboo
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libX11 needed by ibus-bamboo-0.6.7-1.8.x86_64
 Solution 1: do not install ibus-bamboo-0.6.7-1.8.x86_64
 Solution 2: break ibus-bamboo-0.6.7-1.8.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 
 
-------------------------------------------------------------------------------------------
Còn khi cài bằng Yast thì báo lỗi 

An error occurred while initializing the software repository.
Details:
https-download.opensuse.org-cb6e01ec: [https-download.opensuse.org-cb6e01ec|https://download.opensuse.org/repositories/openSUSE:/Tumbleweed/dod/] Valid metadata not found at specified URL
History:
 - [https-download.opensuse.org-cb6e01ec|https://download.opensuse.org/repositories/openSUSE:/Tumbleweed/dod/] Repository type can't be determined.

Try again?

Software installation
The installation has failed. For more information, see the log file at /var/log/YaST2/y2log. Failure stage was: Adding Repositories
Error Message
An error occurred while attempting to subscribe to the required repositories. Review the yast2 logs for more information.
The following repositories could not be added
https://download.opensuse.org/repositories/openSUSE:/Tumbleweed/dod/
https://download.opensuse.org/repositories/openSUSE:/Tumbleweed/dod_debug/

**Comment by luongthanhlam** [comment]
đã fix, bạn thử lại nhé:)
