### ISSUE TITLE
Trying to change óa into oá

### ISSUE THREAD

**Issue by zimhat** [BambooEngine/ibus-bamboo#192]
Hello, I am not a native speaker but I am learning the language. I learned that the new spelling rule is to put the accent on the "a" instead of the "o" as in : "Văn Hoá". Unfortunately, ibus-bamboo seems to follow the old spelling rule and automatically put the accent like this : "Văn Hóa". 

Is there a way to change that in the settings ? I am using version 0.6.8

**Comment by luongthanhlam** [comment]
> Hello, I am not a native speaker but I am learning the language. I learned that the new spelling rule is to put the accent on the "a" instead of the "o" as in : "Văn Hoá". Unfortunately, ibus-bamboo seems to follow the old spelling rule and automatically put the accent like this : "Văn Hóa".
> 
> Is there a way to change that in the settings ? I am using version 0.6.8

Yes, please uncheck option 'Dấu thanh chuẩn' in the settings to follow the new spelling rule.
