### ISSUE TITLE
Issue on Fedora 33?!

### ISSUE THREAD

**Issue by chaudoe** [BambooEngine/ibus-bamboo#193]
I build ibus-bamboo from source on Fedora 32 awhile ago and even until the latest Fedora 33(I upgraded from 32) roll out, everything was still good until yesterday I decide to make my yearly reinstall. Everything seem good, I still can build from source, ibus still recognize bamboo but now I can no longer type in Vietnamese despite every settings on ibus matched with previous version of my machine. 
Is this an error or did I miss something? I'm use Fedora 33 now and ibus-bamboo is not working on both Gnome and KDE.

**Comment by tnkhoi** [comment]
Bạn thử cài lại từ nguồn này xem:
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:lamlng/Fedora_33/home:lamlng.repo
dnf install ibus-bamboo
ibus restart
-Mình cũng đang dùng Fedora 33, thấy vẫn chạy ok. Nếu không được bạn thử khởi động lại máy và rồi vô phần: Setting->Region&Language->Input Sources->add->Vietnamese->Vietnamese (Bamboo).
Trên Gnome sẽ xuất hiện input (en) chuyển qua (vi) là ok.
Hi vọng giúp được bạn. Thân!

**Comment by chaudoe** [comment]
@tnkhoi Mình khắc phục được rồi nhưng không phải là bộ gõ có lỗi hay gì cả mà là do input method mặc định của Fedora không được chuyển hướng về ibus 😂so, obviously I did missed something, silly me😂.
Cách khắc phục cho những ai gặp vấn đề tương tự là sau khi cài đặt xong ibus thì nhớ chạy tiếp `im-chooser` > `Use-ibus` > `logout` cho chắc.
Case closed.
