### ISSUE TITLE
Gõ tắt không theo định nghĩa

### ISSUE THREAD

**Issue by shhlkien** [BambooEngine/ibus-bamboo#194]
**Mô tả lỗi**

Gõ tắt chỉ thay thế từ tắt bằng chữ thường

**Các bước tái hiện lỗi**

1. Định nghĩa 1 cụm từ cần gõ tắt bao gồm chữ hoa (ví dụ: `vn:Việt Nam`)
2. Mở bất kì phần mềm nào có thể soạn thảo
3. Gõ `vn` ra `việt nam`

**Kết quả mong muốn**

Hiển thị từ tắt đúng như định nghĩa

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![gõ tắt](https://user-images.githubusercontent.com/23404165/104673756-f2d5ea80-5714-11eb-8285-329afe4f0458.png)

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: v0.6.6

**Thông tin thêm**

**Comment by luongthanhlam** [comment]
Cảm ơn bạn, lỗi này mình sẽ fix trong bản tới :) Tạm thời bạn có thể khắc phục bằng cách bỏ chọn "Tự động viết hoa" trong mục Gõ tắt

**Comment by luongthanhlam** [comment]
Fixed
