### ISSUE TITLE
Không gõ được tiếng việt trên kitty terminal.

### ISSUE THREAD

**Issue by thuanpham2311** [BambooEngine/ibus-bamboo#196]
**Mô tả lỗi**

- Không gõ được tiếng việt trên kitty terminal.
- Copy một đoạn văn tiếng việt, copy paste vào neovim chạy trên kitty terminal thì vẫn thể hiện được. 

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở kitty terminal
2. Chuyển sang kiểu gõ tiếng việt (ibus bamboo)
3. Gõ trên terminal
4. Không thấy dấu gạch chân, không gõ gõ được ký tự tiếng việt

**Kết quả mong muốn**

Gõ "tôi đi code dạo" thì phải thấy "tôi đi code dạo" chứ không phải thấy "tooi ddi code dajo"

**Ảnh chụp màn hình, hoặc clip quay màn hình**

Clip quay tái hiện lỗi:

https://youtu.be/lkYVY-UzE4Q

**Môi trường**
 - OS và version: Ubuntu 20.10.1
 - Desktop: Gnome X11
 - Phiên bản ibus-bamboo: v.0.6.8

**Thông tin thêm**

- Cài đặt bằn apt get (add-apt-repository ppa:bamboo-engine/ibus-bamboo)
- Đã thử chuyển qua các bản mã khác của ibus bamboo nhưng vẫn không khác phục được lỗi.
- https://github.com/kovidgoyal/kitty

**Comment by luongthanhlam** [comment]
bạn thêm biến môi trường này nhé

`GLFW_IM_MODULE=ibus`

https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
