### ISSUE TITLE
Lỗi khi nhắn tin facebook trên Chrome lẫn Chromium + không gõ được tiếng việt trong VSC

### ISSUE THREAD

**Issue by Jayjaynoplays** [BambooEngine/ibus-bamboo#197]
**Mô tả lỗi**
Lỗi khi nhắn tin facebook trên Chrome lẫn Chromium + không gõ được tiếng việt trong VSC

**Các bước tái hiện lỗi**

1. Mở facebook bằng browser
2. chọn 1 người và nhắn tin
3. gõ tiếng việt + nhấn enter
4. khung chat với người đó biến mất + tin nhắn không được gửi
5. click vào lại người đó để mở khung chat để gõ lại tin nhắn
6. khi click vào thì khung tin nhắn vẫn ko hiện lên
7. reload lại page, lặp lại từ bước 2 thì hiện khung tin nhắn nhưng tình trạng vẫn xảy ra như từ bước 3
8. gõ được tiếng việt vào khung gõ tin nhắn, lỡ gõ nhầm, nhấn nút backspace để xóa thì backspace không hoạt động

Note: vẫn hoạt động bình thường với thanh tìm kiếm của browser, hộp gõ status của facebook lẫn LibreOffice Writter và các hộp soạn thảo khác, chỉ có nhắn tin facebook là bị lỗi. Còn trong VSC thì không gõ được tiếng Việt (ví dụ muốn gõ "â" thì sẽ ra là "aa"). Khi shift+~ để chuyển sang tiếng anh thì mọi lỗi trên không còn

**Kết quả mong muốn**
khi nhấn enter thì tin nhắn được gửi, khung tin nhắn vẫn còn trên màn hình, ko tắt, phím backspace vẫn hoatj động để xóa tin nhắn nếu gõ nhầm. VSC vẫn có thể gõ được tiếng Việt. 

**Ảnh chụp màn hình, hoặc clip quay màn hình**
https://drive.google.com/file/d/1GPRHhHMvy4oIPYGB-15tu_3ezhVO16Jq/view?usp=drivesdk

**Môi trường**
 - OS và version: Ubuntu 18.04
 - Desktop: gnome
 - Phiên bản ibus-bamboo: v0.6.8

**Thông tin thêm**
Lúc install thì khi "sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo" thì nhận được lỗi là "404  Not Found [IP: 91.189.88.149 80]"

**Comment by luongthanhlam** [comment]
Bạn nhấn shift+~, chọn chế độ gõ số 4 để gõ trong chrome nhé. Lỗi không gõ được trong VSC có thể fix ở đây https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60
