### ISSUE TITLE
Không gõ được trên Skype

### ISSUE THREAD

**Issue by pdutie94** [BambooEngine/ibus-bamboo#198]
Hiện tại mình thấy thì chưa gõ được trên skype

**Comment by luongthanhlam** [comment]
bạn cài skype từ snap/flatpak hay apt/.deb? https://github.com/BambooEngine/ibus-bamboo/wiki/T%E1%BA%A1i-sao-kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-Vi%E1%BB%87t-trong-%E1%BB%A9ng-d%E1%BB%A5ng-snap%3F
