### ISSUE TITLE
Danh sách loại trừ cho GNOME Wayland

### ISSUE THREAD

**Issue by long21wt** [BambooEngine/ibus-bamboo#199]
**Mô tả lỗi**

Hiện tại các ứng dụng native Wayland đang không thể hiên thị được bảng lựa chọn danh sách loại trừ (GNOME Terminal, Firefox, GNOME Files, ...), các ứng dụng chạy bằng XWayland như Discord, Microsoft Edge thì sử dụng bình thường.  

**Các bước tái hiện lỗi**

1. Mở các ứng dụng native Wayland (GNOME apps or Firefox)
2. Sử dụng default shortcut để bật pop up danh sách loại trừ

**Kết quả mong muốn**

Bảng danh sách loại trừ được hiện ra cho các ứng dụng native Wayland

**Môi trường**
 - OS và version: Fedora 33
 - Desktop: GNOME Wayland 
 - Phiên bản ibus-bamboo: built từ master

Có liên quan đến #44

**Comment by darktaiga01** [comment]
Mình cũng bị tương tự

**Comment by Slotheacientone** [comment]
Mình cũng bị lỗi vậy trên OpenSuse Tumbleweed Wayland

**Comment by luongthanhlam** [comment]
Fixed: https://github.com/BambooEngine/ibus-bamboo/commit/cc6a7589f4481827e62d9ab814b2c7a906d47645
