### ISSUE TITLE
Xử lí chuyển đổi kí tự khá chậm, nhiều khi bị mất chữ nếu gõ quá nhanh

### ISSUE THREAD

**Issue by HadesD** [BambooEngine/ibus-bamboo#200]
**Mô tả lỗi**
Khi gõ quá nhanh, hoặc sử dụng messenger, gõ phải delay tầm 0.5-1s, nếu không sẽ mất chữ

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở google chrome -> fb messenger
2. Nhắn tin gõ nhanh
3. Mất kí tự

ngày mai tôi muốn đi chơi đau đó thật vui
-> ng mai tôi muốn đi chơi đuâ đó thật vui 

**Kết quả mong muốn**

Mong muốn bamboo xử lí nhanh hơn

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Ubuntu 20.04 - Macbook Air 2012
 - Desktop: GNome
 - Phiên bản ibus-bamboo: v0.6.8

**Thông tin thêm**

**Comment by luongthanhlam** [comment]
hmm, không hiểu sao chế độ gõ số 5 xử lý cực chậm trên GNOME, bạn thử chế độ gõ số 4 hay 1 chưa?

**Comment by HadesD** [comment]
@luongthanhlam 
mình bật preddit thì gõ bình thường, nhưng muốn trải nghiệm ko gạch chân chút mà khó quá :(

**Comment by luongthanhlam** [comment]
> @luongthanhlam
> mình bật preddit thì gõ bình thường, nhưng muốn trải nghiệm ko gạch chân chút mà khó quá :(

bạn thử chế độ gõ không gạch chân số 4 chưa?

**Comment by crimethinking** [comment]
> > @luongthanhlam
> > mình bật preddit thì gõ bình thường, nhưng muốn trải nghiệm ko gạch chân chút mà khó quá :(
> 
> bạn đã thử chế độ gõ không gạch chân số 4 chưa?

mode 4 ko bị lỗi mất chữ khi gõ nhanh, đã test trên Arch/KDE 5.21.2/`ibus-bamboo 0.7.0`

**Comment by binhtran432k** [comment]
> **Mô tả lỗi**
> Khi gõ quá nhanh, hoặc sử dụng messenger, gõ phải delay tầm 0.5-1s, nếu không sẽ mất chữ
> 
> **Các bước tái hiện lỗi**
> 
> Ví dụ:
> 
>     1. Mở google chrome -> fb messenger
> 
>     2. Nhắn tin gõ nhanh
> 
>     3. Mất kí tự
> 
> 
> ngày mai tôi muốn đi chơi đau đó thật vui
> -> ng mai tôi muốn đi chơi đuâ đó thật vui
> 
> **Kết quả mong muốn**
> 
> Mong muốn bamboo xử lí nhanh hơn
> 
> **Ảnh chụp màn hình, hoặc clip quay màn hình**
> 
> **Môi trường**
> 
>     * OS và version: Ubuntu 20.04 - Macbook Air 2012
> 
>     * Desktop: GNome
> 
>     * Phiên bản ibus-bamboo: v0.6.8
> 
> 
> **Thông tin thêm**

Chắc do bạn dùng wayland rồi, qua xorg chơi tạm đi, chừng nào wayland support mạnh rồi chơi. Mình cũng đang dùng Manjaro Gnome ban đầu dùng gõ thấy có phần mêm chậm, có cái thì bình thường. Sau khi qua xorg chuyển sang mode 4 gõ tốt. Ngoài ra wayland còn có mấy cái ức chế lắm, không dùng được shortcut của goldendict trong phần mêm chạy = wayland, obs-studio đen thui,....

**Comment by ndgnuh** [comment]
Thực sự tôi sẽ blame facebook vì vấn đề này, vì nó chỉ xảy ra được trên facebook, trang khác thì không, kể cả trang messenger lẻ.

**Comment by tmn03** [comment]
mình xài chat zalo web cũng bị nhưng chuyển mode 4 thì không bị, bạn thử xem sao

**Comment by tynguyen2k1** [comment]
Mình cũng bị cái lỗi quần què này với facebook message. Mình sử dụng mode 4 và xài xorg

**Comment by goatastronaut0212** [comment]
Yep, lỗi này vẫn còn, mình cũng xài Xorg nhưng trong 1 số ứng dụng nhất định nếu gõ quá nhanh thì nó sẽ mất chữ hoặc đảo ngược chữ, xóa chữ. Đây là 1 điều khá tệ, đặc biệt là mình sử dụng Zed editor nhưng phải gõ chậm lại là 1 điều quá khọ chịu

**Comment by ndgnuh** [comment]
Mình vừa thử gõ trên messenger thì không reproduce được lỗi :( cả mode số 4 và số 5.

Cá nhân mình nghĩ cái này nó không phải vấn đề của Bamboo mà do cách một số phần mềm xử lý nhấn phím, nó cũng sửa cái textbox cùng lúc với Bamboo và gây ra lỗi. Hồi trước mình dùng Unikey trên Windows cũng bị lỗi tương tự khi các phần mềm lag. Bạn ở trên dùng Zed có thể thử các tắt tính năng tự điền xem có hết lỗi không.

**Comment by goatastronaut0212** [comment]
Có lẽ nên đóng báo cáo lỗi này là được rồi. Nếu còn nhiều lỗi khó chịu nữa chúng ta hãy mở 1 báo cáo mới thôi.
