### ISSUE TITLE
Không gõ tiếng Việt được trong Foxit Reader

### ISSUE THREAD

**Issue by zvtrung** [BambooEngine/ibus-bamboo#201]
**Mô tả lỗi**
Không gõ tiếng Việt được trong Foxit Reader

**Các bước tái hiện lỗi**

1. Mở Foxit Reader và nạp một tài liệu
2. Thử tạo một sticky notes trên tài liệu
3. Gõ tiếng Việt với ibus-bamboo --> Không có tác dụng.

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: mới nhất là v0.6.7

**Thông tin thêm**

**Comment by thuanpham2311** [comment]
**Bạn thử làm theo wiki coi có fix được lỗi hay không nha.**

Link: https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

**Comment by luongthanhlam** [comment]
Duplicate of https://github.com/BambooEngine/ibus-bamboo/issues/176
