### ISSUE TITLE
Cần Giúp Đở Cho UbPorts

### ISSUE THREAD

**Issue by dopaemon** [BambooEngine/ibus-bamboo#202]
Rất cần sự hỗ trợ cho cộng đồng ubports ( Ubuntu Touch ) 
Cảm Ơn

**Comment by luongthanhlam** [comment]
bạn gặp vấn đề gì trên ubports vậy??

**Comment by dopaemon** [comment]
> bạn gặp vấn đề gì trên ubports vậy??

Trên UbPorts Không có bộ gõ tiếng việt . cần giúp cài đặt trên UbPorts ạ 
https://t.me/UbPorts Nếu bác có telegram

**Comment by goatastronaut0212** [comment]
Đóng báo cáo lỗi này. Nếu muốn thêm đề xuất bạn có thể báo cáo thêm ở đây

https://github.com/BambooEngine/ibus-bamboo/issues/516
