### ISSUE TITLE
Failed to install in Manjaro

### ISSUE THREAD

**Issue by nguyenlekhtn** [BambooEngine/ibus-bamboo#204]
**Mô tả lỗi**
I can't install ibus-bamboo in my Manjaro after following the guide in https://software.opensuse.org//download.html?project=home:lamlng&package=ibus-bamboo. The terminal showed that file is "invalid or corrupted package (checksum)".

**Các bước tái hiện lỗi**

1. Add
```
[home_lamlng_Arch]
SigLevel = Never
Server = https://download.opensuse.org/repositories/home:/lamlng/Arch/$arch
```
into /etc/pacman.conf 
2. Open terminal with root permission and type 
```
pacman -Syu
pacman -S home_lamlng_Arch/ibus-bamboo
```

3. It showed
![Screenshot_20210222_122634](https://user-images.githubusercontent.com/25528200/108666259-4d7b1700-7509-11eb-8493-6dff271b43ad.png)
:
```
:: File /var/cache/pacman/pkg/ibus-bamboo-0.6.8-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package (checksum))
```

**Môi trường**
 - OS và version: Manjaro 20.2.1
 - Desktop: KDE
 - Phiên bản ibus-bamboo: not installed yet

**Comment by luongthanhlam** [comment]
Fixed, please try again:)
