### ISSUE TITLE
Không build được bản 0.6.8 trên Arch Linux

### ISSUE THREAD

**Issue by Narga** [BambooEngine/ibus-bamboo#205]
**Mô tả lỗi**
Không rõ là do Go hay do máy tính của mình sai về cấu hình, bản 6.5 thì build bình thường nhưng bản 6.8 thì không thể build được dù đã thử nhiều cách.

**Các bước tái hiện lỗi**
==> Starting build()...
GOPATH=/home/narga/external/AUR/sources/src/ibus-bamboo-git go build -ldflags="-s -w" -o ibus-engine-bamboo ibus-bamboo
package ibus-bamboo is not in GOROOT (/usr/lib/go/src/ibus-bamboo)
make: *** [Makefile:36: build] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Mình đang dùng bản Go go-2:1.16-1

**Comment by luongthanhlam** [comment]
Fixed, bạn build lại nhé:)

**Comment by Narga** [comment]
Đã ngon :+1: lên hẳn 0.6.9 luôn :smile:
