### ISSUE TITLE
Bamboo thinh thoang bi tu dong shutdown tren openSUSE

### ISSUE THREAD

**Issue by linh-ebisolvn** [BambooEngine/ibus-bamboo#206]
**Mô tả lỗi**
Khi sleep may, doi luc bamboo se tu dong thoat. Mac du da mo lai bang lenh run ibus nhung van khong the cho bamboo chay o background

**Các bước tái hiện lỗi**

Ví dụ:
1. Sleep may
2. Mo lai
3. Ibus bamboo bi shutdown

**Kết quả mong muốn**

Cli hoac feature de bamboo auto restart

**Môi trường**
 - OS và version: (ví dụ:openSUSE Leap 15.2)
 - Desktop: (KDE)
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.6.8)

**Comment by luongthanhlam** [comment]
bạn thêm lệnh `ibus-daemon -vrxd` vào cuối file ~/.bashrc và ~/.xprofile nhé
