### ISSUE TITLE
Reopen ibus bamboo trên một app đã tắt gõ tiếng Việt trước đó.

### ISSUE THREAD

**Issue by chientv90** [BambooEngine/ibus-bamboo#207]
**Mô tả lỗi:**
Xin cho hỏi làm cách nào để mở lại gõ tiếng Việt trên một app đã loại trừ trước đó (bằng phím Shift + ~)

**Các bước tái hiện:**
- Cài đặt ibus bamboo trên ubuntu 20.04
- Gõ tiếng Việt trên skype thành công
- Loại trừ gõ tiếng Việt trên Skype

**Kết quả mong muốn:**
- Mở lại gõ tiếng Việt trên skype.

**Môi trường:**
- Ubuntu 20.04.

**Comment by ndgnuh** [comment]
Bạn dùng lại tổ hợp `Shift + ~` và chọn chế độ 3 hoặc chế độ nào khác là được

**Comment by chientv90** [comment]
> Bạn dùng lại tổ hợp `Shift + ~` và chọn chế độ 3 hoặc chế độ nào khác là được

Ok cảm ơn bạn mình làm đc rồi!
