### ISSUE TITLE
Không gõ được tiếng việt trong visual studio code last version

### ISSUE THREAD

**Issue by Huytvc** [BambooEngine/ibus-bamboo#209]
**Mô tả lỗi**
Không gõ được tiếng việt trong visual studio code last version
Sau khi update version VScode thì không thể gõ tiếng việt có dấu

**Comment by luongthanhlam** [comment]
Bạn cài vscode từ trang chủ sẽ fix được lỗi này nhé.

**Comment by Huytvc** [comment]
Thank you!

Vào CN, 14 thg 3, 2021 vào lúc 20:48 Lâm ***@***.***> đã
viết:
