### ISSUE TITLE
Cách tắt bộ gõ trên một số ứng dụng

### ISSUE THREAD

**Issue by thienan99dt** [BambooEngine/ibus-bamboo#21]
Hiện tại mình đang sử dụng ibus-bamboo thấy rất ổn (Ubuntu 18.04 LTS).
Sau đây mình muốn hỏi là bộ gõ ibus-bamboo có chức năng tắt chế độ gõ tiếng việt trên một số ứng dụng do người dùng setting được không? ví dụ như Editor, Terminal, IDE, ... như vậy sẽ tiện lợi hơn.
Cho mình hỏi thêm hot key: `Shift` + `~` để làm gì vậy và sử dụng như thế nào? Mình sử dụng trên một số cửa sổ thấy không có bất kỳ sự thay đổi gì cả.

**Comment by luongthanhlam** [comment]
bạn nhấn Shift + ~ rồi nhấn tiếp phím 6 (v0.4.3) để tắt chế độ gõ tiếng việt nhé.

**Comment by luongthanhlam** [comment]
các chế độ gõ khác bạn tìm hiểu thêm ở đây http://lewtds.github.io/2014/07/31/uoc-mo-bo-go-kieu-unikey/
