### ISSUE TITLE
Ko thể chuyển nhanh để active bộ gõ

### ISSUE THREAD

**Issue by khachoale** [BambooEngine/ibus-bamboo#210]
Các bạn có thể có setting hay đặt default setting cho việc active/disable bộ gõ là Ctrl+Shift được ko? Tương tự các bộ gõ trên Windows để theo thói quen dễ chuyển đổi. Ngoài ra thì ko vì thói quen, mà do keyboard layout nào cũng hỗ trợ 2 phím này. ( mình ko dùng Keyboard English nên ko thể tắt bật nhanh bộ gõ như default setting hiện có được, mình luôn phải chuyển đổi bằng chuột nên thấy hơi bất tiện) 
Mình cám ơn

**Comment by ndgnuh** [comment]
Cái này bạn vào ibus-setup chỉnh lại phím nhé

**Comment by khachoale** [comment]
> Cái này bạn vào ibus-setup chỉnh lại phím nhé

Achso. Thanks bạn nhé. Mình nhầm giữa chế độ gõ trong setting của bamboo với input mode của Linux. 
Hóa ra chỉ cần bấm Windows+Space là chuyển nhanh đc
Cám ơn bạn rất nhiều
