### ISSUE TITLE
Terminal trong intellij

### ISSUE THREAD

**Issue by ndtai772** [BambooEngine/ibus-bamboo#211]
Có một số ứng dụng như Intellij (và họ nhà Jetbrain như PyCharm, Clion...) thì phần gõ trong vùng text và phần inner terminal sử dụng 2 cấu hình khác nhau mới gõ đúng được nên mỗi lần bật terminal lên gõ là lại phải đổi cấu hình hoặc chuyển hẳn sang tiếng anh, khá bất tiện.

Shortcut thay đổi cấu hình/chế độ gõ hiện tại là Shift+\~, khi muốn gõ ~ phải nhấn 2 lần và có prompt up khá khó chịu. Việc thay đổi cấu hình thì thường chỉ vào lần đầu dùng ứng dụng thôi, còn ký tự ~ thì dùng thường xuyên hơn nhiều, như muốn ~~gạch ngang đoạn này~~ phải nhấn tới 8 lần, có 4 cái prompt up. Mình kiến nghị đổi sang shortcut khác (như Ctrl+\~ hay Alt+~ hay Super+~ ...) hoặc thêm chức năng tùy chỉnh shortcut.

Và chức năng thay đổi cấu hình có thể tự động gợi ý thay vì phải test từng cái thì app sẽ mượt hơn rất nhiều.

**Môi trường**
 - OS và version: Manjaro (Kennel 5.9)
 - Desktop:  KDE (5.21.2) - X11
 - Phiên bản ibus-bamboo: 0.7.0-1

Cảm ơn team/bạn rất nhiều, không có project này chắc mình cũng chả dùng Linux <3

**Comment by ndgnuh** [comment]
Lạ nhỉ, cùng là một cửa sổ mà.

Bạn mở terminal, chạy `xprop`, sau đó click vào cái terminal trên IntelliJ, sau đó đăng output lên được không? Làm tương tự với cái editor của nó luôn nhé.

**Comment by ndtai772** [comment]
> Bạn mở terminal, chạy `xprop`, sau đó click vào cái terminal trên IntelliJ, sau đó đăng output lên được không? Làm tương tự với cái editor của nó luôn nhé.

https://www.diffchecker.com/r9CNcOTa đây nha

**Comment by ndgnuh** [comment]
Ca này khó nhỉ, nó nhìn hai cái như cùng 1 cửa sổ. Bạn thử chạy intellij với GTK_IM_MODULE=ibus xem (nếu bạn đang đặt là xim). Ứng dụng java hình như bị bug với GTK_IM_MODULE=xim.
