### ISSUE TITLE
Mất dấu khi sau khi dùng spacebar

### ISSUE THREAD

**Issue by huyhoang8398** [BambooEngine/ibus-bamboo#213]
**Mô tả lỗi**

Mất dấu của từ sau khi dùng spacebar

**Các bước tái hiện lỗi**

1. Mở chrome 
2. Gõ hịc r nhấn spacebar
...
4. Thấy hijc 

**Kết quả mong muốn**

Thấy hịc

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![image](https://user-images.githubusercontent.com/25379882/112782396-34580f80-904d-11eb-96cf-a097e4887325.png)

**Môi trường**
 - Archlinux kernel 5.11.10-arch1-1
 - Desktop: i3wm
 - Phiên bản ibus-bamboo: ibus-bamboo 0.7.0-1

**Thông tin thêm**

Chương trình được cài đặt từ: Arch Aur

**Comment by minhduc0711** [comment]
Hình như cái này là do spell check thôi, vì từ này không có trong từ điển tiếng Việt.
