### ISSUE TITLE
Lỗi "Can't connect to IBus" khi chạy lệnh "ibus restart"

### ISSUE THREAD

**Issue by nmhung1985** [BambooEngine/ibus-bamboo#214]
Mình thử cài trên Zorin OS Lite 32-bit cho 1 máy netbook (Asus T91MT). Đến bước cuối khi gõ lệnh "ibus restart" thì hệ thống báo 
`Can't connect to IBus`

Xin tác giả cho hỏi là có thể khắc phục bằng cách nào ạ?

**Comment by nmhung1985** [comment]
Đã tự giải quyết được:
+ Mở System Settings> Language Support (hệ thống có thể nhắc Install các công cụ cho ngôn ngữ thì cứ bỏ qua)
- Chỗ 'Keyboard input method system' chọn IBus
- Chọn 'Install / Remove Languages' > kéo xuống chọn 'Vietnamese' rồi ấn Apply (có thể bỏ chọn các ngôn ngữ khác đi kèm Zorin OS nếu thích).
+ Logout hoặc restart. Có thể phải chạy thêm lệnh ibus-setup. Nhưng mình restart thì đã hiện lên biểu tượng công cụ nhập liệu IBus bên góc phải > vào add thêm ngôn ngữ Vietnamese> chọn Bamboo nữa là xong.

**Comment by nguyenhai97** [comment]
Cái này đã đề cập trong phần wiki và tuy đây cũng là một cách mà thấy cách này cồng kềnh quá :)
