### ISSUE TITLE
Không mở được bảng gõ tắt

### ISSUE THREAD

**Issue by tmn03** [BambooEngine/ibus-bamboo#215]
Mình đang sử dụng manjaro kde + ibus -bamboo bảng mới nhất, chọn khung mở bảng gõ tắt nhưng nó có phản hồi gì. Ai fix được lỗi này giúp mình với

**Comment by luongthanhlam** [comment]
Tạm thời bạn mở trực tiếp file qua trình quản lý tập tin theo đường dẫn `.config/ibus-bamboo/ibus-bamboo.macro.text` nhé.
