### ISSUE TITLE
Thêm tùy chỉnh short cut

### ISSUE THREAD

**Issue by Ducvoccer** [BambooEngine/ibus-bamboo#217]
**Mô tả lỗi**
Thêm tùy chỉnh short cut cho mở emoij hay chuyển bộ gõ
**Kết quả mong muốn**
Mình thấy việc cố định các phím tắt cho mở emoij hay chuyển bộ gõ là khá tù túng. Phụ thuộc vào độ tiện dụng của mỗi người nên cho người dùng cài đặt short cut theo ý muốn

**Comment by Fubuchi** [comment]
+1

dân coder xài terminal nhiều, cd hay gõ gì có home path  thường dùng `Shift+~` thế là lại bị nhảy lên cái bảng chọn kiểu gõ :))

**Comment by luongthanhlam** [comment]
Bạn cập nhật lên bản v0.7.1 để tùy chỉnh shortcut Chuyển chế độ gõ trong menu `Phím tắt` nhé
