### ISSUE TITLE
Archlinux installation checksum error

### ISSUE THREAD

**Issue by JustMangoT** [BambooEngine/ibus-bamboo#218]
**Mô tả lỗi**
Install ibus-bamboo thong qua pacman bi loi checksum

**Các bước tái hiện lỗi**
1. Mở terminal
2. "sudo pamac build ibus-bamboo"
3. Thấy "Error: Failed to commit transaction: invalid or corrupted package (checksum)"

**Kết quả mong muốn**
Installation successfully

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://user-images.githubusercontent.com/38831897/115549463-e395a880-a2d2-11eb-9edb-423cad5b3ad8.png)

**Môi trường**
 - OS và version: Manjaro 21.0.2
 - Desktop: KDE
 - Phiên bản ibus-bamboo: 0.7.0-1

**Thông tin thêm**
Hien tai vi chua cai duoc ibus-bamboo nen minh khong the go dau

**Comment by luongthanhlam** [comment]
OBS thay đổi lại quy trình cài đặt, bạn làm theo ở đây nhé

> For Arch Linux, edit /etc/pacman.conf and add the following (note that the order of repositories in pacman.conf is important, since pacman always downloads the first found package):
[home_lamlng_Arch]
Server = https://download.opensuse.org/repositories/home:/lamlng/Arch/$arch
Then run the following as root
```
key=$(curl -fsSL https://download.opensuse.org/repositories/home:lamlng/Arch/$(uname -m)/home_lamlng_Arch.key)
fingerprint=$(gpg --quiet --with-colons --import-options show-only --import --fingerprint <<< "${key}" | awk -F: '$1 == "fpr" { print $10 }')

pacman-key --init
pacman-key --add - <<< "${key}"
pacman-key --lsign-key "${fingerprint}"

pacman -Sy home_lamlng_Arch/ibus-bamboo
```

https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo

**Comment by JustMangoT** [comment]
Ok chạy được rồi, mình cảm ơn
