### ISSUE TITLE
Không mở được chế độ thiết lập trong Ubuntu Budgie 20.04

### ISSUE THREAD

**Issue by lhhuong** [BambooEngine/ibus-bamboo#219]
**Mô tả lỗi**
Trong Ubuntu Budgie 20.04:
- Ko thể nhấn Shift +  để mở chế độ tắt gạch chân.
- Không mở được chế độ để thay đổi kiểu gõ.
**Kết quả mong muốn:**
Có thể thiết lập được như trên Ubuntu chuẩn.

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn ở đây nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60
