### ISSUE TITLE
Gợi ý emoji hiển thị góc dưới màn hình thay vì gần dòng đang gõ

### ISSUE THREAD

**Issue by manhnt9** [BambooEngine/ibus-bamboo#22]
**Mô tả lỗi**
Khi gõ emoji thì dòng gợi ý hiển thị ở góc dưới màn hình bên trái thay vì gần dòng đang gõ.

**Các bước tái hiện lỗi**
1. Kích hoạt gõ emoji
2. Mở Firefox, gõ trên Facebook hoặc GitHub Issue
3. Gõ dấu hai chấm `:`
4. Thấy gợi ý emoji ở góc dưới màn hình

**Kết quả mong muốn**
Nên hiển thị gợi ý gần dòng đang gõ, thường là ở dưới dòng đó.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot_2019-04-17_09-39-25](https://user-images.githubusercontent.com/11463928/56257003-1493df00-60f5-11e9-9e01-38e07c0debe7.png)

**Môi trường**
 - OS và version: Ubunty 18.04
 - Desktop: XFCE 4.12
 - Phiên bản ibus: IBus 1.5.17
 - Phiên bản ibus-bamboo: v0.4.5

**Comment by luongthanhlam** [comment]
đã fix ở bản mới nhất (v0.4.6).

**Comment by manhnt9** [comment]
Mình vẫn bị hiện ở góc trái dưới cùng của cửa sổ.

**Comment by manhnt9** [comment]
Màn hình của mình FullHD thôi, không HiDPI. Có thể do hạn chế của xfce đấy, nếu được thì bạn test thử trên desktop đó xem sao nhé.

**Comment by luongthanhlam** [comment]
Có vẻ là lỗi của ibus https://github.com/mike-fabian/ibus-typing-booster/issues/33

**Comment by manhnt9** [comment]
Của mình gặp trong tất cả các ứng dụng, không chỉ riêng Firefox. Cũng có thể là do ibus thật.
