### ISSUE TITLE
Lỗi sau khi update lên bản 0.7.1 trên KDE Neon

### ISSUE THREAD

**Issue by goingtosleep** [BambooEngine/ibus-bamboo#222]
**Mô tả lỗi**
Một số lỗi mình bị sau khi update:
- Không mở được hộp thoại chọn kiểu gõ (`Shift + ~`).
- Trừ kiểu gõ 1, các kiểu gõ khác đêu có vấn đề trên Firefox (mất chữ khi gõ, nhấn Ctrl vài lần rồi gõ thì bình thường với kiểu số 5).
Hiện tại mình buộc phải workaround bằng cách chuyển sang kiểu gõ 1 (chỉnh file json trong `.config`). 

**Các bước tái hiện lỗi**
Mở firefox và gõ hoặc mở app bất kì và `Shift + ~`.

**Môi trường**
 - OS và version: KDE Neon (Ubuntu 20.04)
 - Desktop: KDE Plasma 5.21.5
 - Phiên bản ibus-bamboo: 0.7.1, cài từ ppa

**Comment by luongthanhlam** [comment]
- Bạn không mở được hộp thoại chọn kiểu gõ trong firefox hay những ứng dụng nào?
- Kiểu gõ số 5 gặp vấn đề trên thanh địa chỉ hay một trang web nào đó vậy? bạn có thể mô tả chi tiết cách tái hiện lỗi này được không?

**Comment by PhamTuanSon99** [comment]
- Mình có cùng trường hợp với bạn trên, k mở được hộp thoại chọn kiểu gõ trong hầu hết ứng dụng ( vídụ: firefox, skype, terminal, visual studio code)
- trừ kiểu 1 thì các kiểu khác ngoài bị mất chữ thì mình còn không gõ được tiếng việt trên terminal
- ví dụ gõ history trên terminal:
![image](https://user-images.githubusercontent.com/78060651/117617711-2262a400-b197-11eb-8c7e-fe3a43938a8e.png)

**Comment by luongthanhlam** [comment]
@PhamTuanSon99 bạn làm theo hướng dẫn này https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng để thiết lập đúng các biến môi trường nhé

**Comment by goingtosleep** [comment]
@luongthanhlam Mình không mở dc hộp thoại với tất cả ứng dụng luôn (đã test: firefox, vivaldi, vscode, kwrite, konsole, lyx).

Với kiểu số 5, mình sẽ bị mất chữ đầu tiên khi gõ, ví dụ cụm "Với kiểu số 5", khi mình gõ xong chữ "Với" là nó mất. Hiện tại mình đang phải chuyển về kiểu số 1 để reply. Bị cả trên thanh address và các textarea của website. 
Kiểu 2, 3, 6 bị tinh trạng tương tự.
Kiểu 4 khi gõ cụm "gõ tiếng việt" trên address bar thì bị chuyển thành "goõ tiế/".

Mình nghĩ là biến môi trường (và các setup liên quan) đều ok, vì ver 0.7.0 trở về hoạt động bình thường.
```sh
~ ❯ env | grep "IM_MODULE\|XMODIFIERS"
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
QT4_IM_MODULE=ibus
XMODIFIERS=@im=ibus
```

**Comment by PhamTuanSon99** [comment]
> @PhamTuanSon99 bạn làm theo hướng dẫn này https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng để thiết lập đúng các biến môi trường nhé

mình đã thử mọi cách trong đó rồi trước khi đăng lên đây

**Comment by PhamTuanSon99** [comment]
> > @PhamTuanSon99 bạn làm theo hướng dẫn này https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng để thiết lập đúng các biến môi trường nhé
> 
> mình đã thử mọi cách trong đó rồi trước khi đăng lên đây
mình bị lỗi từ lúc update bản 0.7.1 ( tầm 12h tối qua)

**Comment by luongthanhlam** [comment]
hmm, mình thử trên máy ảo thì không gặp lỗi nào như 2 bạn mô tả cả

**Comment by PhamTuanSon99** [comment]
bạn có rảnh không, teamview qua máy mình xem thử

**Comment by luongthanhlam** [comment]
ok, bạn gửi vào email ltlam93@gmail.com nhé

**Comment by luongthanhlam** [comment]
thanks @PhamTuanSon99, lỗi hộp thoại chuyển chế độ gõ đã được fix :smile:

**Comment by goingtosleep** [comment]
Confirm sau khi up lên ver `0.7.2-0~202105101230~ubuntu20.04.1` đã mở dc hộp thoại 👍. 
Lỗi mất chữ vẫn còn, nhưng mình mới phát hiện là gõ từ đầu tiên xong ngưng 1 chút mới nhấn `space` thì không bị mất chữ, còn gõ `space` liền thì mới bị mất 🤔

**Comment by PhamTuanSon99** [comment]
> Confirm sau khi up lên ver `0.7.2-0~202105101230~ubuntu20.04.1` đã mở dc hộp thoại .
> Lỗi mất chữ vẫn còn, nhưng mình mới phát hiện là gõ từ đầu tiên xong ngưng 1 chút mới nhấn `space` thì không bị mất chữ, còn gõ `space` liền thì mới bị mất

mình nghĩ là do bộ đệm delay cao quá, lúc mất xóa 2 dấu cách liền thì nó hiện thị ra chữ bị mất nhập liền với từ phía trước đó và mất ký tự đầu (của chữ bị mất)

**Comment by luongthanhlam** [comment]
Đã fix ở bản v0.7.3, bạn kiểm tra lại giúp mình nhé :man_dancing:

**Comment by ndgnuh** [comment]
Tạo release đi bác 😄 Bên void chưa dám bump phiên bản chỉ vì 0.7.2 bị mất chữ. Mình test vài hôm rồi nếu ok bump lên 0.7.3 luôn.

**Comment by goingtosleep** [comment]
Confirm `0.7.3` đã ngon lành cành đào. Cảm ơn @luongthanhlam nhiều 🥳

**Comment by sontungx305** [comment]
Mình cũng bị lỗi không mở được hộp thoại chuyển chế độ gõ trên Ubuntu 18.04 vs 20.04 sau khi update từ 0.7.0 lên 0.7.3 
Chỉ khi sử dụng chức năng tạo phím tắt riêng để chuyển chế độ, ấn Shift+~ thì nó sẽ thành Shift+Mod2+~ sau đó ấn Shift+~ mới chuyển được.
![Image of Yaktocat](https://i.imgur.com/lIyUdtM.png)

**Comment by luongthanhlam** [comment]
@sontungx305 ok, bạn cập nhật lên bản 0.7.4 để fix lỗi này nhé
