### ISSUE TITLE
Lỗi mất chữ khi gõ nhanh ở mode 4

### ISSUE THREAD

**Issue by ndsdarkwalker** [BambooEngine/ibus-bamboo#223]
**Mô tả lỗi**
Mong muốn: "Vậy là hôm nay trời không mưa. Đi chơi được rồi"
Kết quả: "Vậy là hôm nay trời  mưa. Đi   rồi"
=> Mất chữ ngẫu nhiên (nhập nhanh)

**Các bước tái hiện lỗi**
Thực hiện trên Unicode + VNI + mode 4
Đã thử mở skype, gedit, facebook messenger,... khi gõ  kỳ kiểu gì đều bị mất chữ.

Có trường hợp đứng text ở messenger (nếu bị mất những chữ đầu tiên nhập)

**Kết quả mong muốn**
Mong muốn: gõ được đầy đủ chữ, không phải chờ delay 0.xx sec để không bị mất chữ ngẫu nhiên khi nhập nhanh

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Không có

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.7.2)

**Thông tin thêm**
- Tuần trước ngày 08/05/2021 thì mọi thứ đều ổn và trơn tru, ngày 10/05/2021 update lên thì bị
- Đã thử "ibus restart" switch qua lại en/vi
- Setting trước ngày ổn định không thay đổi
- Đã reset máy để kiểm tra lại

**Comment by luongthanhlam** [comment]
Đã fix ở bản v0.7.3, bạn kiểm tra lại giúp mình nhé :man_dancing:

**Comment by ndsdarkwalker** [comment]
@luongthanhlam cám ơn đội ngũ rất nhiều
