### ISSUE TITLE
Messed up tags

### ISSUE THREAD

**Issue by sgn** [BambooEngine/ibus-bamboo#224]
Chào Lâm,

Hình như tooling của Lâm có lỗi hay sao đó, mình thấy rất nhiều tag có vẻ được đánh không được tự nhiên lắm. Ví dụ như:

- v0.7.10
- v0.7.11
- v0.7.22

Những tag này làm lẫn lộn cơ chế phát hiện phiên bản mới của bên mình.

-- Danh

**Comment by ndgnuh** [comment]
Chào bạn, hình như bạn cũng dùng void thì phải. Mình nghĩ bạn nên bump thẳng lên 0.7.3, gỡ package ra rồi cài lại là được.

**Comment by sgn** [comment]
Mình là Developer của Void Linux ;), mình không dùng `ibus` và càng không dùng `ibus-bamboo`.

Chỉ có điều với cách tag này, thì cơ chế tự động nhận dạng update của bên mình bị lỗi, những bên khác, nếu có cơ chế nhận dạng tự động cũng sẽ gặp vấn đề này.

https://a-hel-fi.m.voidlinux.org/void-updates/void-updates/updates_ndgnuh%40protonmail.com.txt

**Comment by ndgnuh** [comment]
Wow, mình k biết đó, chỉ thấy mấy lần bạn comment trong commit 😄

**Comment by luongthanhlam** [comment]
ohh mình đánh tag bằng tay nên bị lỗi đó, đã fix : )
