### ISSUE TITLE
Cập nhật checksum cho ibus-bamboo-0.7.4-1-any.pkg.tar.zst trên pacman

### ISSUE THREAD

**Issue by Qynklee** [BambooEngine/ibus-bamboo#225]
Lỗi:
File /var/cache/pacman/pkg/ibus-bamboo-0.7.4-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Có vẻ phiên bản 0.7.4.1 trên pacman chưa được cập nhật checksum nên không thể cài được. Mong bạn sớm fix :D
Cảm ơn bạn! :+1: 
![image](https://user-images.githubusercontent.com/23394219/118753413-24132280-b88f-11eb-8257-1d0b6ddc8231.png)

**Comment by Qynklee** [comment]
Cách fix tạm thời: Xóa repo ibus-bamboo khỏi /etc/pacman.conf để update những gói khác ngoài ibus-bamboo trước.

**Comment by luongthanhlam** [comment]
OBS đang bị lỗi, mình vừa cập nhật thêm AUR package vào script cài đặt

**Comment by Qynklee** [comment]
Cảm ơn bạn :D
