### ISSUE TITLE
lỗi telegram trên manjaro

### ISSUE THREAD

**Issue by tmn03** [BambooEngine/ibus-bamboo#228]
Distro manjaro, kernel 5.10
telegram build từ kho AUR không gõ được tiếng việt trong khi mấy app khác hoàn toàn bình thường

**Comment by luongthanhlam** [comment]
mình thử thì vẫn gõ được bình thường, bạn kiểm tra lại các biến môi trường nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
