### ISSUE TITLE
Cài đặt bằng mã nguồn trên Kali, error glib-object.h: no suck file or directory

### ISSUE THREAD

**Issue by OrangeIsBlack** [BambooEngine/ibus-bamboo#229]
**Mô tả lỗi**
Cài đặt bamboo trên Kali linux thì vướng lỗi ở khâu "make install". Lỗi không tìm thấy thư viện glib-object.h

**Các bước tái hiện lỗi**
Thực hiện theo guideline https://github.com/BambooEngine/ibus-bamboo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-m%C3%A3-ngu%E1%BB%93n

sudo apt install make golang libx11-dev libxtst-dev
wget https://github.com/BambooEngine/ibus-bamboo/archive/master.zip -O ibus-bamboo.zip
unzip ibus-bamboo.zip
cd ibus-bamboo
sudo make install

(Đã thử clone mã nguồn và lỗi tương tự)

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2021-05-27 11-21-34](https://user-images.githubusercontent.com/84891301/119766641-96af7e00-bedf-11eb-814e-54ff1d8c042b.png)

**Môi trường**
 - OS và version: kali linux 2021.2
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.6.8)

**Comment by luongthanhlam** [comment]
bạn cài thêm gói libgtk-3-dev nhé

**Comment by luongthanhlam** [comment]
updated wiki
