### ISSUE TITLE
Bị gõ rất chậm trên Facebook

### ISSUE THREAD

**Issue by manhnt9** [BambooEngine/ibus-bamboo#23]
**Mô tả lỗi**
Hiện tại mình sử dụng mode fix gạch chân thứ 3, các mode khác không dùng được cho Firefox. Nhưng gặp vấn đề sau: trên Facebook gõ rất chậm mà GitHub thì không, có khi nào các app React sẽ gặp vấn đề này không nhỉ?

**Các bước tái hiện lỗi**
1. Mở Firefox
2. Vào Facebook.com
3. Để con trỏ vào ô cập nhật status
4. Chuyển sang chế độ gạch chân số 3
5. Bắt đầu gõ
6. Thấy chữ xuất hiện chậm

**Kết quả mong muốn**
Tốc độ hiển thị chữ bình thường

**Ảnh chụp màn hình, hoặc clip quay màn hình**
[Video](https://www.youtube.com/watch?v=2Nb_QNiHzUI)

**Môi trường**
 - OS và version: Ubunty 18.04
 - Desktop: XFCE 4.12
 - Phiên bản ibus: IBus 1.5.17
 - Phiên bản ibus-bamboo: v0.4.5

**Comment by luongthanhlam** [comment]
cho mình xin output của lệnh này nhé:
env | egrep 'IM_MODULE|XMODIFIERS'

**Comment by manhnt9** [comment]
CLUTTER_IM_MODULE=xim
QT4_IM_MODULE=xim
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
GTK_IM_MODULE=xim

**Comment by ndgnuh** [comment]
Vậy chắc là de của bạn chưa đc config để dùng ibus thôi. 
Cách 1 là thêm
```sh
ibus-daemon -rdx
```

vào trong phần auto start của xfce

Cách 2 là thêm những biến môi trường ở trên vào trong ~./profile, hoặc ~/.bashrc, nhưng thay `xim` bằng `ibus`.

Thông tin chi tiết bạn có thể tham khảo Archlinux wiki, nó của distro khác nhưng có phạm vi cover rất rộng và hữu ích.

**Comment by manhnt9** [comment]
Mình vừa thử luôn `ibus-daemon -rdx`, nhưng gõ trên fb vẫn chậm. Nếu thêm vào autostart thì vẫn tương tự.

Sẽ thử thêm việc sửa biến môi trường, tuy nhiên từ những lần trước thì theo mình nhớ là firefox sẽ hoàn toàn không chuyển chế độ gõ được. Hi vọng sẽ không bị lặp lại lỗi này.

**Comment by manhnt9** [comment]
À vừa tắt FF bật lại thì OK rồi. Thanks bạn!
