### ISSUE TITLE
Gõ được tiếng việt trên trình duyệt nhưng trong IDE, VIm, command line, gedit... thì không gõ được.

### ISSUE THREAD

**Issue by logbasex** [BambooEngine/ibus-bamboo#230]
Hiện tại mình đang dùng Ubuntu 20.04.
ibus-bamboo 0.7.4
Trước đó dùng GNOME thì không sao nhưng khi chuyển sang **i3** (v4.17.1) thì mới bị.

**Comment by luongthanhlam** [comment]
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
bạn xem ở đây nhé
