### ISSUE TITLE
Cài đặt với yay bị lỗi

### ISSUE THREAD

**Issue by thanhtoan1742** [BambooEngine/ibus-bamboo#231]
**Mô tả lỗi**
Khi chạy lệnh 
`yay -S ibus-bamboo`
bị lỗi 
```
File /var/cache/pacman/pkg/ibus-bamboo-0.7.4-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
```
![image](https://user-images.githubusercontent.com/30596211/120482538-6da95480-c3db-11eb-9e9b-726e31aded83.png)

**Môi trường**
 - OS và version: Arch Linux x86_64 
 - Kernel: 5.11.16-arch1-1 
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: bị lỗi khi cài ibus-bamboo-0.7.4-1

**Comment by luongthanhlam** [comment]
mình vẫn cài bằng yay bình thường, có vẻ trước đó bạn cài bằng pacman và bị lỗi?
