### ISSUE TITLE
Lôĩ không enter tag trên vscode khi mở ibus bamboo

### ISSUE THREAD

**Issue by duyanh4788** [BambooEngine/ibus-bamboo#232]
**Mô tả lỗi**
Không nhăc code trên vscode khi mở ibus bamboo

**Các bước tái hiện lỗi**
1. Mở ibus-bamboo
2. Mở vscode
3. Gõ tag div tên vscode hiên tag div nhưng enter thì bị xuông dòng không nhắc code 

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://user-images.githubusercontent.com/75610658/120735738-5a020900-c515-11eb-8384-c185730c4c28.mp4

**Môi trường**
Ubuntu 20.04

**Comment by luongthanhlam** [comment]
bạn nhất Shift+~ và chọn chế độ gõ số 4 nhé

**Comment by duyanh4788** [comment]
cảm ơn Anh
