### ISSUE TITLE
Lỗi k thể chọn Autocomplete Code vscode

### ISSUE THREAD

**Issue by ntvsp** [BambooEngine/ibus-bamboo#233]
**Mô tả lỗi**
khi vscode gợi ý code ấn -> k được

**Các bước tái hiện lỗi**
vscode all language
Ví dụ:
 video [https://youtu.be/X4cpv_RDySA](https://youtu.be/X4cpv_RDySA)
**Kết quả mong muốn**
sử dụng được tính năng autocomplete ấn mũi tên xuống, thì phải chọn vào cái menu đc gợi ý
**Môi trường**
 - OS và version: Ubuntu 20.04
 - Phiên bản ibus-bamboo: v0.6.8

**Comment by tmn03** [comment]
bác xài wayland hay là xorg, mình xài xorg chọn chế độ thứ 4 xài bình thường

**Comment by ntvsp** [comment]
> bác xài wayland hay là xorg, mình xài xorg chọn chế độ thứ 4 xài bình thường

là sao bác nhỉ... wayland là ibus khác à

**Comment by tmn03** [comment]
> > bác xài wayland hay là xorg, mình xài xorg chọn chế độ thứ 4 xài bình thường
> 
> là sao bác nhỉ... wayland là ibus khác à

bác vào terminal gõ lệnh 'echo $XDG_SESSION_TYPE' xem thử đang ở wayland hay là xorg

**Comment by ntvsp** [comment]
> > > bác xài wayland hay là xorg, mình xài xorg chọn chế độ thứ 4 xài bình thường
> > 
> > 
> > là sao bác nhỉ... wayland là ibus khác à
> 
> bác vào terminal gõ lệnh 'echo $XDG_SESSION_TYPE' xem thử đang ở wayland hay là xorg

x11 bác ơi

**Comment by luongthanhlam** [comment]
bạn nhấn Shift+~ chọn phím 4 nhé

**Comment by ntvsp** [comment]
> bạn nhấn Shift+~ chọn phím 4 nhé

done tks bác
