### ISSUE TITLE
Lôĩ gõ dâú

### ISSUE THREAD

**Issue by duyanh4788** [BambooEngine/ibus-bamboo#234]
**Mô tả lỗi**
Lôĩ gõ dâú nằm sai vị trí

**Các bước tái hiện lỗi**
Lôĩ , rảnh , nhưng4  , ....

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://user-images.githubusercontent.com/75610658/120927098-deb57880-c709-11eb-997b-23fcceec6c0f.mp4

**Môi trường**
 Ubuntu 20.04

**Comment by ntvsp** [comment]
cũng từng bị nhưng mình chọn dấu thanh chuân thì nó đánh dấ chuẩn

**Comment by luongthanhlam** [comment]
bạn đang dùng bảng mã gì? có thể chạy lệnh này và gửi output giúp mình đc không?
`
cat .config/ibus-bamboo/ibus-bamboo.config.json
`

**Comment by duyanh4788** [comment]
em đang dùng bảng mã unicode  , gưỉ anh output

{
  "InputMethod": "VNI",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex W": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode",
  "Flags": 6,
  "IBflags": 4416,
  "JupiterFlags": 0,
  "InputModeShortcut": "126,1",
  "DefaultInputMode": 4,
  "InputModeMapping": {}
}

**Comment by duyanh4788** [comment]
> cũng từng bị nhưng mình chọn dấu thanh chuân thì nó đánh dấ chuẩn

em chỉnh rôì , ko được ah

**Comment by luongthanhlam** [comment]
bạn bật tùy chọn `Bỏ dấu tự do` là được nhé
