### ISSUE TITLE
Facebook+ Firefox + Ubuntu problem

### ISSUE THREAD

**Issue by abysswalker84** [BambooEngine/ibus-bamboo#235]
Khi xài facebook + firefox 89.0+ Ubuntu 20.04.2
Gõ tiếng Việt cứ bị nhảy về đầu văn bản ( giống như nhấn phím Home )

**Comment by ntvsp** [comment]
mình k bị

**Comment by luongthanhlam** [comment]
bạn nhấn Shift+~, chọn phím 5 hoặc 4 và thử lại xem
