### ISSUE TITLE
Không gõ được tiếng việt trong spotify

### ISSUE THREAD

**Issue by NguyenTrongThinh** [BambooEngine/ibus-bamboo#236]
**Mô tả lỗi**
Không gõ được tiếng việt có dấu trong spotify hoặc bất kỳ app nào cài từ snapcraft

**Các bước tái hiện lỗi**
1. Cài spotify qua snapcraft
$ sudo snap install spotify
2. Chuyển chế độ gõ sáng tiếng việt
2. Chạy spotify
3. Tìm kiếm bài hát tiếng việt có dấu trong khung tìm kiếm
Không gõ được tiếng việt có dấu

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop:  Gnome
 - Phiên bản ibus-bamboo: v0.7.4

**Thông tin thêm**
Mình không chắc ibus-bamboo đã có interface để app trên snap connect vào chưa
https://snapcraft.io/docs/interface-management

**Comment by luongthanhlam** [comment]
hiện tại spotify (deb và snap) vẫn chưa hỗ trợ ibus bạn nhé https://community.spotify.com/t5/Desktop-Linux/Bug-fix-idea-Can-t-Input-CKJV-language-ibus-fcitx/m-p/4656202
