### ISSUE TITLE
Không gõ được dấu trong bình luận trên facebook

### ISSUE THREAD

**Issue by tynguyen2k1** [BambooEngine/ibus-bamboo#238]
**Mô tả lỗi**

Không gõ được dấu thứ 2 trên facebook
**Các bước tái hiện lỗi**

1. Mở facebook
2. Tìm 1 post bất kì
3. Thử gõ "ở" nhưng ra "ơr" và còn rất nhiều thứ khác nữa
**Kết quả mong muốn**
"ở"

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://user-images.githubusercontent.com/64082226/124062054-42f20080-da5a-11eb-8c2a-cc43bcd727e9.mp4

**Môi trường**
 - OS và version: Manjaro
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.6.8)

**Thông tin thêm**

**Comment by chessgenius** [comment]
Mình cũng bị lỗi tương tự, cả ibus-unikey và ibus-bamboo đều bị.

Có vẻ như lý do là nút backspace ảo bị làm sao đó.

Ví dụ nó sẽ thành thế này  "Test hoạtoạt động của faceacebook xem có hoạtoạt động khônông"

**Comment by tynguyen2k1** [comment]
> Mình cũng bị lỗi tương tự, cả ibus-unikey và ibus-bamboo đều bị.
> 
> Có vẻ như lý do là nút backspace ảo bị làm sao đó.
> 
> Ví dụ nó sẽ thành thế này  "Test hoạtoạt động của faceacebook xem có hoạtoạt động khônông"

Tui chuyển qua chế độ 4 lại viết được bình thường r 😂

**Comment by luongthanhlam** [comment]
có vẻ bạn chạm vào touchpad khi đang gõ nên bộ gõ mới commit từ đang gõ, bạn có gặp lỗi tương tự khi gõ trong ứng dụng khác không?

**Comment by tynguyen2k1** [comment]
https://user-images.githubusercontent.com/64082226/124127925-79556d00-daa6-11eb-8088-23d33a9ba4fa.mp4

Mình không có chạm vào touchpad, và có vẻ như nó chỉ lỗi với phần bình luận của facebook

**Comment by chessgenius** [comment]
video đây bạn nhé
https://youtu.be/OEWuF34HcKc

**Comment by fx500ms** [comment]
lỗi này còn xuất hiện ở bản 0.7.5 không bạn?

**Comment by Nghiauet** [comment]
Mình cũng bị bản 0.7.7 khi gõ bình luận facebook ở FireFox chrome không bị

**Comment by huynhthiensach** [comment]
cũng bị như vậy. Firefox

**Comment by superthin** [comment]
Một vấn đề các bạn cần lưu ý đó là nếu trình duyệt có cài extension hoặc addon chặn quảng cáo như Adblock Plus thì khả năng là gõ vào cửa sổ chat Facebook hoặc một số trang web sẽ khiến chữ nhảy lung tung. Cái này không phải là lỗi ibus-bamboo nhé.

**Comment by luongthanhlam** [comment]
các bạn vào Cài đặt của bộ gõ, bật tùy chọn "Sửa lỗi lặp chữ trong FB" để fix lỗi này nhé
