### ISSUE TITLE
Không thể bật setting trên Ubuntu 20

### ISSUE THREAD

**Issue by chessgenius** [BambooEngine/ibus-bamboo#239]
Môi trường mình sử dụng là Ubuntu 20.04.

Mình không thể nào bật setting lên được, click vào nút bật setting của ibus thì không hiện gì cả. Còn ấn shift + ~ thì cũng không hiện chỉ ra các dấu ~
~~~~~~
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by luongthanhlam** [comment]
bạn có thể chụp ảnh màn hình hoặc quay clip để mô tả lỗi rõ hơn không?
thử chạy 2 lệnh này xem
```
ibus restart
# Đặt ibus-bamboo làm bộ gõ mặc định
env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['xkb:us::eng', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"
```

**Comment by chessgenius** [comment]
video đây bạn 

https://youtu.be/OEWuF34HcKc

Đoạn đầu là mình ấn vào nút setting của Ibus-unikey thì ok nhưng Ibus-bamboo không được.

Đoạn sau mình ấn tổ hợp phím Shift+~ nhưng cũng không được.

1 đoạn mình quên k ghi là mình ấn vào thanh setting tắt trên system tray thì ibus-unikey có nhưng ibus-bamboo không được.

Mình đã thử cài ibus-bamboo trước không cài ibus-unikey cũng k được.

**Comment by luongthanhlam** [comment]
ibus bamboo chỉ có setting ở thanh thông báo thôi bạn

![](https://blogchiasekienthuc.com/wp-content/uploads/2019/06/cai-dat-bo-go-tieng-viet-tren-ubuntu-11.png)

**Comment by chessgenius** [comment]
Mình chọn trên thanh thông báo cũng không có setting gì cả, mình có nói ở trên mà :D

**Comment by luongthanhlam** [comment]
> Mình chọn trên thanh thông báo cũng không có setting gì cả, mình có nói ở trên mà :D

Bạn có thấy chữ V màu đỏ trên thanh thông báo không? Nếu không thấy bạn nhấn Control+Space rồi thử xem

**Comment by chessgenius** [comment]
![Screenshot from 2021-07-08 14-06-40](https://user-images.githubusercontent.com/12694540/124877965-cdf06f00-dff5-11eb-8ce2-0716fb59d41b.png)

Mình cài 2 máy thì 1 được, 1 không. Như hình.

**Comment by luongthanhlam** [comment]
bạn cài từ ppa hay từ mã nguồn? bạn chạy lệnh này và gửi output giúp mình nhé
```
/usr/lib/ibus-engine-bamboo
```

**Comment by vryy** [comment]
I also used ubuntu 20.04 and I can confirm that bamboo settings can't be accessed as described.

I run /usr/lib/ibus-engine-bamboo, this is the output:
2021/07/14 14:43:36.941792 Got Bus, Running Standalone
RECORD extension for local server is version 1.13
2021/07/14 14:43:36.948013 FocusIn.
Enable.WM_CLASS=(gnome-terminal-server:Gnome-terminal)

**Comment by chessgenius** [comment]
> bạn cài từ ppa hay từ mã nguồn? bạn chạy lệnh này và gửi output giúp mình nhé
> 
> ```
> /usr/lib/ibus-engine-bamboo
> ```

mình cài từ ppa, nhưng máy lúc đó không còn mới. Hiện mình bực quá cài lại Ubuntu rồi cài luôn ibus-bamboo thì lại không bị lỗi.

Có thể lúc đó máy mình bị lỗi pip nên mình đã gỡ hết các gói cài bằng pip khỏi hệ điều hành. Có gói Qt gì đó có thể ảnh hưởng.

**Comment by chessgenius** [comment]
> bạn cài từ ppa hay từ mã nguồn? bạn chạy lệnh này và gửi output giúp mình nhé
> 
> ```
> /usr/lib/ibus-engine-bamboo
> ```

May qua, ban cu van con. Chay thi ra nhu sau:

/usr/lib/ibus-engine-bamboo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/ibus-engine-bamboo)

**Comment by vryy** [comment]
> /usr/lib/ibus-engine-bamboo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/ibus-engine-bamboo)
> 
> Có vẻ như minh dự đoán, hệ điều hành không còn tốt nên chắc bị thiếu lib gì đó.

of ubuntu 18.04, the glibc version is 2.17. Therefore it won't run with library compiled against newer glibc. The only way to fix is to recompile bamboo for the old system.

**Comment by fx500ms** [comment]
bạn xóa ppa rồi thử lại nhé
