### ISSUE TITLE
Lỗi gõ tiếng Việt trên Telegram (portable)

### ISSUE THREAD

**Issue by huyndnse63331** [BambooEngine/ibus-bamboo#24]
Mình đang dùng Ubuntu 16.04.6 (amd64), Telegram là bản Telegram Desktop download trực tiếp từ trang chủ, không dùng snap.
Mình không gõ được chữ với dấu như bình thường, và đặt biệt là không thể dùng backspace xóa được.
![image](https://user-images.githubusercontent.com/25204246/56359293-557e1780-620b-11e9-9453-89355945e6e9.png)

**Comment by luongthanhlam** [comment]
Bạn nhấp tổ hợp phím Shift + ~, làm theo hướng dẫn để chọn chế độ gõ phù
hợp nhé

**Comment by huyndnse63331** [comment]
![final](https://user-images.githubusercontent.com/25204246/62637407-91c5b700-b965-11e9-93c4-5114d9f3a971.png)

Mình đã đổi sang chế độ gõ tiếng việt (ibus-bamboo), gõ được bình thường ở những field khác, nhưng mỗi Telegram lại không gõ được, mình vừa nâng cấp lên Ubutun 18.04.2 (amd64). Mình cũng bật chế độ shift - ~ nhưng ko hiện gì ở Telegram cũng như không gõ dấu được, mong bạn giúp mình. Mình cảm ơn

**Comment by luongthanhlam** [comment]
mình vừa test thử thì telegram 1.7.15 beta vẫn hoạt động bình thường, bạn gửi mình output lệnh này nhé `env | grep "IM_MODULE\|XMODIFIERS"`

**Comment by huyndnse63331** [comment]
@luongthanhlam đây nha bạn
```
% env | grep "IM_MODULE\|XMODIFIERS"
CLUTTER_IM_MODULE=xim
GTK_IM_MODULE=ibus
QT4_IM_MODULE=xim
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
```

**Comment by luongthanhlam** [comment]
Bạn cấu hình lại biến môi trường theo wiki https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60 rồi khởi động lại xem

**Comment by huyndnse63331** [comment]
thanks bạn nhiều nhé :3 được r
