### ISSUE TITLE
Không gõ được tiếng Việt bằng ibus trên Robo3T 1.4

### ISSUE THREAD

**Issue by liv1n9** [BambooEngine/ibus-bamboo#242]
**Mô tả lỗi**
Không gõ được tiếng việt trên Robo3T 1.4 trên Ubuntu 20.04

**Các bước tái hiện lỗi**

1. Tải Robo 3T 1.4 và giải nén
2. Tạo file `robo3t.desktop` trong `~/.local/share/applications`
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Robo3t
Icon=/home/liv1n9/Programs/Robo3t/bin/robomongo.png
Path=/home/liv1n9/Programs/Robo3t/bin/
Exec=env GTK_IM_MODULE=ibus QT_IM_MODULE=xim XMODIFIERS=@im=xim QT4_IM_MODULE=xim CLUTTER_IM_MODULE=xim /home/liv1n9/Programs/Robo3t/bin/robo3t
StartupNotify=false
StartupWMClass=Robo3t
OnlyShowIn=Unity;GNOME;
X-UnityGenerated=true
```
3. Khởi động Robo3t trong thanh favorites, mở mongo shell và gõ tiếng việt bằng ibus thì không được

**Kết quả mong muốn**
Gõ được tiếng Việt trong mongo shell

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: v0.6.7

**Comment by zenfas** [comment]
App liên quan đến QT mà QT_ và QT4_ bạn lại dùng xim mà không phải là ibus?

**Comment by luongthanhlam** [comment]
bạn xem ở đây nhé https://github.com/Studio3T/robomongo/issues/1260
