### ISSUE TITLE
Không gõ được tiếng Việt trên Telegram

### ISSUE THREAD

**Issue by lqa-gh** [BambooEngine/ibus-bamboo#243]
Mình đã thử sử dụng các phiên bản khác nhau của Telegram (cài bằng apt, snap, flatpak, ....) và đều không được. Mình đã sửa file /home/.bash.rc như wiki hướng dẫn, nhưng vẫn không thể gõ được tiếng Việt trong app này. 

Mình cũng đã thử cả 06 chế độ gõ, và vẫn không gõ được tiếng Việt trong Telegram. 

Nhưng rất lạ là mình gõ trên Chromium (snap app) thì lại được (chính là trình duyệt web mình đang dùng để viết post báo lỗi).

Mình đang chạy distro Kubuntu 20.04.02 LTS.

**Comment by zenfas** [comment]
Kiểm tra lại biến môi trường xem https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

**Comment by lqa-gh** [comment]
> Kiểm tra lại biến môi trường xem https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

mình thử chạy lệnh env | grep "IM_MODULE\|XMODIFIERS" thì thấy output không có gì cả, mặc dù đã sửa file .bash.rc như hướng dẫn. 

Vậy là bị làm sao nhỉ

**Comment by lqa-gh** [comment]
Mình đã thử sửa cả file .xprofile và giờ đã gõ được. Xin lỗi dev vì chưa đọc kỹ :sweat_smile:
