### ISSUE TITLE
Gõ bị nhảy chữ trên thanh chat Messenger trên trình duyệt Chrome

### ISSUE THREAD

**Issue by tienpv147** [BambooEngine/ibus-bamboo#245]
**Mô tả lỗi**

Gõ bị nhảy chữ trên thanh chat Messenger của trình duyệt Chrome

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở chat messenger
2. Gõ `được chưa nhỉ`
3. Nhấn enter thì thành `nhỉđược chưa`

**Môi trường**
 - OS và version: Ubuntu 20.04 LTS
 - Phiên bản ibus-bamboo: v0.7.4 (cài bằng apt)

**Comment by FA-tinhnd** [comment]
mình cũng bị 2,3 hôm này

**Comment by thaihoangminhtam** [comment]
Mình cũng đang bị, chính xác là khi đang gõ, từ cuối cùng của đoạn chat bị đẩy lên đầu tiên và viết dính với từ đầu tiên. Giải pháp tạm thời của mình là Chuyển chế độ gõ mắt định sang ForwardKeyEvent I và II dù mỗi lần gõ xong nó sẽ nháy một cái không đẹp bằng preedit. Cách thứ là là gõ thừa 1 dấu cách cuối câu dấu đó bị đem lên đầu không ảnh hưởng. Rồi ta đợi phản hồi từ dev team thui

**Comment by kidclone3** [comment]
Mình cũng bị, nhưng hôm nay mới thấy. Mình dùng chế độ Pre-edit. Mỗi lần gõ chữ mà bấm Ctrl như thói quen để ngắt là chữ bị nhảy lên đầu (có khi nhảy vào giữa dòng). Tạm thời chỉ có thể gõ chữ rồi bấm cách ra, xong mới dám bấm enter để gửi tin

**Comment by tqgminh** [comment]
Mình dùng ibus-unikey cũng bị, chuyển sang ibus-bamboo cũng bị luôn.

**Comment by nqhung291** [comment]
mình cũng bị, nhưng chỉ bị trên khung chat messenger của facebook

**Comment by tienpv147** [comment]
> Mình cũng bị, nhưng hôm nay mới thấy. Mình dùng chế độ Pre-edit. Mỗi lần gõ chữ mà bấm Ctrl như thói quen để ngắt là chữ bị nhảy lên đầu (có khi nhảy vào giữa dòng). Tạm thời chỉ có thể gõ chữ rồi bấm cách ra, xong mới dám bấm enter để gửi tin

y hệt mình luôn =)))

**Comment by vanthao03596** [comment]
vừa bị luôn

**Comment by ducpm151061** [comment]
space ở cuối là hết nhé

**Comment by LeVuMinhHuy** [comment]
confirm là mình cũng bị luôn, remove cài lại v0.7.4 hi vọng hết nhưng vẫn như vậy ...

**Comment by hongthaiphi** [comment]
Mình cũng đang bị hic hic

**Comment by buuduc1999** [comment]
em tưởng máy em bị gì lên đây coi thì cũng nhiều người bị :)))))

**Comment by nguyenduchuyvn** [comment]
Mình cũng bị lỗi này, mình dùng Ubuntu 18.04

**Comment by phamvanhanh6720** [comment]
> Mình cũng đang bị, chính xác là khi đang gõ, nhấn enter xong thì từ cuối cùng của đoạn chat bị đẩy lên đầu tiên và viết dính với từ đầu tiên. Giải pháp tạm thời của mình là Chuyển chế độ gõ mặt định sang ForwardKeyEvent I và II dù mỗi lần gõ xong nó sẽ nháy một cái không đẹp bằng preedit. Cách thứ 2 là là gõ thừa 1 dấu cách cuối câu dấu đó bị đem lên đầu không ảnh hưởng. Rồi ta đợi phản hồi từ dev team thui

Mình dùng vậy thì với messenger thì ổn. Nhưng gõ word online thì lại bị nhảy loạn cả lên :((
