### ISSUE TITLE
Lỗi khi bấm nút Back tại Messenger

### ISSUE THREAD

**Issue by NhatLam310399** [BambooEngine/ibus-bamboo#246]
**Mô tả lỗi**
Con trỏ chuột nhảy về ký tự đầu tiên 

Tại comment, messger khi dùng bộ gõ mặc định Pre-edit của Ibus-bamboo thì khi nhắn nhầm và bấm nút Back để xoá liên tực 2 3 lần là con trỏ chuột nhảy về vị trí đầu tiên.

**Kết quả mong muốn**
Xoá tới đâu thì con trỏ phải ở vị trí đó

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Trình duyệt chrome
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.7.4)

**Comment by fx500ms** [comment]
fixed https://github.com/BambooEngine/ibus-bamboo/commit/b40016884d26ffe4abba47b0b793ea8dfe73cf48
