### ISSUE TITLE
Lỗi đánh chữ hiện bên dưới dòng

### ISSUE THREAD

**Issue by viet-hung-it** [BambooEngine/ibus-bamboo#247]
![image](https://user-images.githubusercontent.com/33823245/126030959-b8ce3e4b-52f2-46e6-a682-b3043d826d02.png)
Mình làm  theo cac bước cài đặt trong readme, sau đó thử mọi cách mà không được, giờ cứ chọn viết dấu là bị như ảnh. Chữ viết hiện thị ở dưới và một lúc mới hiện ra, hoặc khi viết dấu cách.
Mong rằng đây là chức năng chứ không phải lỗi.
Ai giúp mình cách sửa với ạ! Cảm ơn mn

**Comment by viet-hung-it** [comment]
Mình xin bổ sung là mình đang dùng Elementary OS 5.1.7 Hera (vừa cài). Còn bị lỗi không hiện icon, vẫn dùng ctrl space để chuyển, shift ` không dùng được.

**Comment by fx500ms** [comment]
![2021-07-18_13-47](https://user-images.githubusercontent.com/26364140/126058377-1597c63e-46e7-4944-b4ec-970318063566.png)

trên Elementary OS, bạn cấu hình như hình trên để ẩn candidate box. Shift ~ không hoạt động thường do cấu hình biến môi trường sai, bạn làm theo hướng dẫn ở đây https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
