### ISSUE TITLE
Backspace trên facebook

### ISSUE THREAD

**Issue by ygoldendarkness** [BambooEngine/ibus-bamboo#248]
**Mô tả lỗi**
Vẫn còn lỗi về facebook về việc bị nhảy chữ về đầu tiên khi backspace sau nút space
Chế độ gõ: Preedit

**Các bước tái hiện lỗi**
Ví dụ:
1. Mở khung chat
2. Gõ 1 đoạn chat bất kì chứa dấu space, VD: "Xin chào"
3. Xoá từ "chào".
...
4. Thấy "<code>cursor</code>Xin<code>space</code>"

**Kết quả mong muốn**
Cursor xuất hiện ở cuối như bình thường là "Xin<code>space</code><code>cursor</code>"

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.7.5 (mới nhất)

**Thông tin thêm**
Phần mềm được cài đặt từ: apt-get

**Comment by ygoldendarkness** [comment]
Lỗi này hình như cùng lỗi với #246, có vẻ vẫn còn bug chưa được fix hết. Khi test trên cửa sổ chat của facebook thì vẫn bịbị.

**Comment by thaihoangminhtam** [comment]
Mình cũng bị tương tư, sáng nay anh dev mới fĩx cái lỗi chữ cuối cùng bị đem lên đầu. Bây giờ gặp lỗi là vẫn trên Facebook messenger là bấm backspace 2 lần là cursor chuyển lên đầu câu phải lấy chuột rê xuống cuối câu để gõ tiếp. Hiện tượng này khá khó chịu khi gõ sai một từ >2 chữ phải xóa hết cái nó chuyển cursor lên chữ cái đầu.

**Comment by fx500ms** [comment]
bạn cập nhật lên bản v0.7.6 và kiểm tra lại nhé!
