### ISSUE TITLE
Không mở được trình điều khiển trong Budgie DE

### ISSUE THREAD

**Issue by garconip** [BambooEngine/ibus-bamboo#249]
Bấm nút setting không hiện ra gì
![Screenshot from 2021-07-17 22-31-20](https://user-images.githubusercontent.com/75886203/126042000-dd24b5d9-2ea8-44a6-9a14-70af4665ea47.png)

**Comment by fx500ms** [comment]
cái này là lỗi của gnome, bạn muốn cài đặt gì thì click chuột vào icon bộ gõ trên thanh công cụ nhé.

**Comment by lhhuong** [comment]
> Bấm nút setting không hiện ra gì
> ![Screenshot from 2021-07-17 22-31-20](https://user-images.githubusercontent.com/75886203/126042000-dd24b5d9-2ea8-44a6-9a14-70af4665ea47.png)

Trên Budgie, bạn đã mở được setting chưa? mình vẫn chưa mở được. shift + ~ cũng ko có tác dụng luôn. Icon V trên top panel thì ko có setting.

**Comment by garconip** [comment]
> 
> 
> > Bấm nút setting không hiện ra gì
> > ![Screenshot from 2021-07-17 22-31-20](https://user-images.githubusercontent.com/75886203/126042000-dd24b5d9-2ea8-44a6-9a14-70af4665ea47.png)
> 
> Trên Budgie, bạn đã mở được setting chưa? mình vẫn chưa mở được. shift + ~ cũng ko có tác dụng luôn. Icon V trên top panel thì ko có setting.

Chưa bạn. Hiện mình mở DE khác chỉnh bên đó xong thoát ra rồi vô Budgie lại.

**Comment by fx500ms** [comment]
@garconip @lhhuong bạn chạy lệnh bên dưới rồi gửi output cho mình nhé
```
env | grep "IM_MODULE\|XMODIFIERS"
/usr/lib/ibus-engine-bamboo
```

**Comment by lhhuong** [comment]
Thế này ah bác.
lhhuong@HuongLuong-PC:~$ env | grep "IM_MODULE\|XMODIFIERS"
GLFW_IM_MODULE=ibus
GTK_IM_MODULE=ibus
QT4_IM_MODULE=ibus
XMODIFIERS=@im=ibus
CLUTTER_IM_MODULE=ibus
QT_IM_MODULE=ibus
lhhuong@HuongLuong-PC:~$ /usr/lib/ibus-engine-bamboo
2021/07/20 08:58:35.560227 Got Bus, Running Standalone
RECORD extension for local server is version 1.13
2021/07/20 08:58:35.574496 FocusIn.
Enable.WM_CLASS=(tilix:Tilix)

**Comment by fx500ms** [comment]
có vẻ Budgie vẫn chưa hỗ trợ cấu hình ibus trên thanh công cụ

**Comment by lhhuong** [comment]
> có vẻ Budgie vẫn chưa hỗ trợ cấu hình ibus trên thanh công cụ

vậy hiện nay có thể tinh chỉnh ở bản cập nhất tới một phương pháp chỉnh khác ko bác?

**Comment by fx500ms** [comment]
> > có vẻ Budgie vẫn chưa hỗ trợ cấu hình ibus trên thanh công cụ
> 
> vậy hiện nay có thể tinh chỉnh ở bản cập nhất tới một phương pháp chỉnh khác ko bác?

bạn chạy `ibus-setup` rồi chỉnh tùy chọn `Show property panel` thành `Always`
![](https://i.stack.imgur.com/gIaQs.jpg)

**Comment by garconip** [comment]
> > > có vẻ Budgie vẫn chưa hỗ trợ cấu hình ibus trên thanh công cụ
> > 
> > 
> > vậy hiện nay có thể tinh chỉnh ở bản cập nhất tới một phương pháp chỉnh khác ko bác?
> 
> bạn chạy `ibus-setup` rồi chỉnh tùy chọn `Show property panel` thành `Always`
> ![](https://camo.githubusercontent.com/ee8e19e8985732defd9103fd03e029ee93e3bf540079bad8ef03ca7f69bd19ad/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f67496151732e6a7067)

Được rồi bác. Trên Budgie-panel thêm vào applet "System tray" rồi sau đó chỉ cần chạy thêm lệnh:
`ibus-daemon --xim --replace &`
nếu cần thì thêm 
`budgie-wm  --replace &`
Còn như mở theo hình của OP thì không thực hiện được do ibus-bamboo mình không cung cấp cửa sổ riêng cho trình điều khiển.
