### ISSUE TITLE
Lỗi Enter trong messenger

### ISSUE THREAD

**Issue by BaeWaterLeo** [BambooEngine/ibus-bamboo#250]
**Mô tả lỗi**

Ubuntu 21.04 - đã thử ở 2 trình duyệt chrome và firefox thì CHỈ XẢY RA Ở CHROME
**Các bước tái hiện lỗi**

Ví dụ:
1. Mở facebook bằng chrome
2. Gõ "Hello Jack Rose" cho một người bạn trong mes
3. Nhấn Enter
4. Thấy tin nhắn gửi đi là "RoseHello Jack"

**Kết quả mong muốn**

Bấm Enter gửi tin nhắn "Hello Jack Rose"
**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Ubuntu 21.04
 - Desktop: mặc định
 - Phiên bản ibus-bamboo: 0.7.4
 - trình duyệt chrome 91.0.4472.114 (64 bit)
 - Đã thử tương tự ở trình duyệt firefox thì lỗi ko xảy ra. chỉ xảy ra ở trình duyệt chrome

**Thông tin thêm**

**Comment by zenfas** [comment]
Update lên 0.7.7 đi bạn

**Comment by BaeWaterLeo** [comment]
> Update lên 0.7.7 đi bạn

Mình lên 0.7.7 và ngon lành cành đào rùi. Cảm ơn cậu nhìu.
