### ISSUE TITLE
Lỗi không đánh được tiếng Việt trên phần mềm TeXstudio

### ISSUE THREAD

**Issue by vnphat96** [BambooEngine/ibus-bamboo#251]
**Mô tả lỗi**
!
Không sử dụng được bất kì cấu hình sửa lỗi nào ngoài cấu hình pre-edit.

**Các bước tái hiện lỗi**

1. Mở TeXstudio
2. Soạn bất kì, hiện lỗi như hình.

**Kết quả mong muốn**

Có thể sử dụng các cấu hình sửa lỗi khác ngoài pre-edit vì dùng pre-edit sẽ không dùng được tính năng suggestion khi soạn thảo.

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![Screenshot from 2021-07-18 23-37-53](https://user-images.githubusercontent.com/85694896/126075272-5d6984f6-5ecb-4517-8b1b-21935712ddd6.png)

**Môi trường**
 - OS và version: Linux Mint 20.2
 - Desktop: Cinnamon (mặc định)
 - Phiên bản ibus-bamboo: 0.7.7

**Thông tin thêm**

**Comment by fx500ms** [comment]
bạn làm theo hướng dẫn ở đây rồi thử lại nhé
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng

**Comment by vnphat96** [comment]
Cảm ơn ad rất nhiều.
