### ISSUE TITLE
Không thể chỉnh chế độ gõ trong Gnome với Bamboo 0.7.7

### ISSUE THREAD

**Issue by bg2908** [BambooEngine/ibus-bamboo#252]
**Mô tả lỗi**
Không thể chỉnh chế độ gõ của Bamboo trong gnome sau khi cài Bamboo 0.7.7. Chế độ mặc định của phiên bản này là gõ tiếng Anh, ko có cách nào chỉnh thành tiếng Việt được.
Các phiên bản trước vẫn có thể chỉnh được.

**Các bước tái hiện lỗi**
1. Cài đặt Bamboo phiên bản 0.7.7

**Kết quả mong muốn**
Bấm Shift+~ hoặc click vào icon trên panel để thay đổi chế độ gõ

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![Screenshot from 2021-07-19 04-18-17-bamboo](https://user-images.githubusercontent.com/51479893/126082994-a3626454-ff92-4b5a-ab20-456496a0ea41.png)
Phiên bản 0.7.7. Chế độ mặc định là tiếng Anh , không có menu để lựa chọn chế độ gõ

![Screenshot from 2021-07-19 04-28-54-bamboo](https://user-images.githubusercontent.com/51479893/126083009-1e8769ff-5457-443a-9145-3020dee1de54.png)
Phiên bản 0.7.6. Có menu để lựa chọn chế độ gõ

**Môi trường**
 - OS và version: ArchLabs Linux
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.7.7

**Thông tin thêm**
Phiên bản 0.7.7 cài đặt từ AUR.
Trước đỏ phiên bản 0.7.5 từ AUR vẫn bình thường.
Phiên bản 0.7.6 thì tự build từ Source

**Comment by fx500ms** [comment]
bạn chọn bộ gõ Bamboo trong phần Vietnamese nhé, hoặc chạy lệnh sau là được
```
env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['xkb:us::eng', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"
```

**Comment by bg2908** [comment]
Đã chỉnh trong settings được rồi nhé.
Phiên bản này thêm một đống lựa chọn nhìn mờ mắt.
Thay đổi lớn vậy cho mình xin cái patch notes / warning chỗ release với.

**Comment by fx500ms** [comment]
> Đã chỉnh trong settings được rồi nhé.
> Phiên bản này thêm một đống lựa chọn nhìn mờ mắt.
> Thay đổi lớn vậy cho mình xin cái patch notes / warning chỗ release với.

đây bạn https://github.com/BambooEngine/ibus-bamboo/releases/tag/v0.7.7
