### ISSUE TITLE
Không gõ được tiếng Việt trong Workplace

### ISSUE THREAD

**Issue by mcdoblivion** [BambooEngine/ibus-bamboo#254]
**Mô tả lỗi**
Không thể gõ tiếng Việt khi sử dụng [Workplace](https://www.workplace.com/)

**Các bước tái hiện lỗi**
Ở chế độ gõ tiếng Việt khi nhấn dấu cách (space) thì từ bị xóa dù từ được nhập là tiếng Anh hay tiếng Việt

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.7.7

**Comment by fx500ms** [comment]
bạn đã kiểm tra các biến môi trường và thử các chế độ gõ khác nhau chưa? 
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng

**Comment by mcdoblivion** [comment]
Cám ơn bạn. Mình đã gõ được tiếng Việt sau khi chuyển chế độ gõ.
Sorry vì chưa đọc kỹ hướng dẫn mà đã tạo issue.
