### ISSUE TITLE
Thoát ibus và bật lại gây đơ toàn bộ desktop shell 

### ISSUE THREAD

**Issue by lqa-gh** [BambooEngine/ibus-bamboo#255]
**Các bước tái hiện lỗi**
1. Nhấp chuột phải vào biểu tượng trong system tray 
2. Chọn Quit
3. Bật lại ibus từ Application Menu 
4. Chọn yes khi có hộp thoại ibus-daemon is not running
5. Nhấp ok với hộp thoại hướng dẫn tiếp theo 
6. Đợi vài giây và toàn bộ desktop shell đơ, phải dùng Alt + F2 để reboot máy bằng dòng lệnh 

**Môi trường**
 - OS và version: Ubuntu 20.04.2 LTS 
 - Desktop: LxQt 
 - Window Manager: Openbox
 - Phiên bản ibus-bamboo: 0.7.7 (cài bằng apt)
 - Kernel: 5.8.0-63 generic

**Comment by doankimhuy-it** [comment]
Mình cũng bị lỗi này trên Gnome 40 Arch linux, nếu set sẵn là bamboo, gõ ibus restart hoặc restart máy thì đôi lúc gnome shell tự reset.

**Comment by fx500ms** [comment]
Mình không tái hiện được lỗi này, có vẻ lỗi của ibus, bạn report cho team ibus nhé https://github.com/ibus/ibus/issues
