### ISSUE TITLE
Lỗi chữ cuối cùng nhảy lên đầu

### ISSUE THREAD

**Issue by eKevinHoang** [BambooEngine/ibus-bamboo#256]
Mới thấy nó update và kết quả là, chữ cuối cùng, enter xong nó nhảy lên đầu. Lúc gõ vẫn đúng, cứ enter là nó đưa chữ cuối cùng lên đầu.

![image](https://user-images.githubusercontent.com/40189997/126734644-bd0aaeba-1e6f-4184-ab34-d0d5ad4074e2.png)

**Comment by KevinHN** [comment]
Ngoài ra thỉnh thoảng con trỏ nó cũng bị nhảy, đang ở cuối nhảy lung tung chỗ khác.

**Comment by doankimhuy-it** [comment]
bác thử chuyển chế độ gõ từ preedit qua cái thứ 3 với thứ 4 xem

**Comment by Nghiauet** [comment]
Lỗi này mình bị ở tất cả các trình duyệt nhân Chomium khi nhắn tin bằng messenger. Firefox thì không bị. Bật tiếng Vi thì bị còn tiếng anh không bị.
Lỗi không thể comement bằng tiếng việt ở Firefox trên Facebook. 
Bản cập nhật mới chưa khắc phục được 2 lỗi trên.

**Comment by fx500ms** [comment]
@KevinHN bạn còn gặp lỗi này ở bản 0.7.7 không?

**Comment by nxh235** [comment]
> @KevinHN bạn còn gặp lỗi này ở bản 0.7.7 không?

Mình cũng bị vài tuần nay, chắc do Facebook update phiên bản mới. Mình vừa update lên phiên bản 0.7.7 sáng nay thì không còn tình trạng nhảy chữ cuối cùng lên đầu nữa (đối với Chrome, còn Firefox mình không rõ).

**Comment by KevinHN** [comment]
Mấy hôm bận quá nên không để ý, hiện thì lỗi nhảy chữ thấy ổn rồi nhưng đang bị lỗi như hình với 0.7.8, trên Google Chrome 64 bit và 1 số phần mềm hay bị.

Ngoài ra thỉnh thoảng gõ nó thòi 1 một mớ chữ linh tinh.

![image](https://user-images.githubusercontent.com/40189997/129876478-e217b6e6-5afd-4b35-8d83-a4275d5aac06.png)

**Comment by KevinHN** [comment]
Nếu chuyển sang chế độ gõ số 2 thì lại như dưới
![image](https://user-images.githubusercontent.com/40189997/129877176-94e5834d-5ce7-451e-b1c0-992eb72a580c.png)

**Comment by KevinHN** [comment]
Chế độ gõ số 3 thì khi nhiều chỗ bị lỗi như sau (ví dụ như gõ lên thanh address bar của chrome).
![image](https://user-images.githubusercontent.com/40189997/130348528-95768eff-0061-4bf8-b563-2bcf58ba573c.png)

**Comment by lioaslan** [comment]
Any update on this problem? MÌnh vẫn bị với version 0.7.9
- Mode 1 thì nhảy chữ
- Mode 3 không hiện dấu
- Mode 4 những kí tự vừa có dấu vùa có mũ bị lỗi : ử ẳ ở ổ,...

**Comment by peace195** [comment]
Mình cũng đang bị lỗi này khi chát trên facebook. Chắc phải downgrade xuống bản cũ.
