### ISSUE TITLE
Thêm dialog trong cài đặt GNOME, cải thiện ngôn ngữ trong menu.

### ISSUE THREAD

**Issue by doankimhuy-it** [BambooEngine/ibus-bamboo#257]
Mình thấy tác giả có thể làm thêm một dialog để cài đặt khi chọn Preferences, với lại dịch luôn cụm từ "Capture mouse events" trong menu qua tiếng Việt. Mình cám ơn.

**Môi trường**
 - OS và version: Arch Linux.
 - Desktop: Gnome 40.
 - Phiên bản ibus-bamboo: 0.7.7 cài đặt từ AUR.
![Screenshot from 2021-07-23 14-11-05](https://user-images.githubusercontent.com/31150748/126749086-7850bbfa-8ab3-43ea-85fc-a7339e7998e8.png)

**Comment by luongthanhlam** [comment]
fixed in v0.8.1
