### ISSUE TITLE
xung đột Ctrl+shift+u khi sử dụng trên burpsuite 

### ISSUE THREAD

**Issue by BinhMinhptit** [BambooEngine/ibus-bamboo#258]
**Mô tả lỗi**
xung đột Ctrl+shift+u khi sử dụng trên burpsuite 
**Các bước tái hiện lỗi**

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Linux 5.10.0-kali9-amd64 SMP Debian 5.10.46-1kali1 (2021-06-25) x86_64 GNU/Linux 
 - Desktop: XFCE
 - Phiên bản ibus-bamboo: 0.7.7

**Thông tin thêm**
issue đúng như llink: 
https://superuser.com/questions/358749/how-to-disable-ctrlshiftu 
- Mình đã fix như hướng dẫn là xóa unicode code point nhưng vẫn không được. nếu tắt bamboo thì tổ hợp phím ctrl+shift+u trên burpsuite lại hoạt động bình thường. Lạ là mình dùng ibus-unikey thì không bị lỗi này.

**Comment by zenfas** [comment]
Các phím tắt này liên quan đến sumit gần của tác giả @binhtran432k để gõ icon Unicode

**Comment by BinhMinhptit** [comment]
ý là giờ không thể tắt nó đi được hay sao ạ?

**Comment by binhtran432k** [comment]
Mình mới gửi Pull Request. Bây giờ chờ tác giả chính rep thôi. Cái này hôm bữa có bạn yêu cầu nên mình tạo cố định Ctrl + Shift + U giống với cái ibus tiếng anh. Nay mới biết nó xung đột nên mình thêm option để tắt nó trong phím tắt. Hi vọng sẽ đc cật nhập trong bản sau. Xin cảm ơn

**Comment by BinhMinhptit** [comment]
Chân thành cảm ơn bạn.
