### ISSUE TITLE
Khong the bat duoc Ibus tren Ubuntu

### ISSUE THREAD

**Issue by nghminh163** [BambooEngine/ibus-bamboo#26]
**Mô tả lỗi**
Một mô tả ngắn gọn về lỗi đang xảy ra
Minh dang su dung ibus tren ubuntu 18.04.2 nhung khong the chay duoc Ibus
Hien tai minh dang su dung Bamboo moi nhat 0.4.5 
Xin loi vi khong the bat duoc go tieng viet nen minh go khong dau :( mong cac ban thong cam
**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
Ví dụ:
1. Mở gedit
2. Gõ abc
...
4. Thấy xyz

**Kết quả mong muốn**
Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Ví dụ: Gõ abc thì phải thấy abc chứ không phải xyz

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Nếu cần thiết, hãy [đính kèm hình ảnh](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) hoặc gửi link youtube [quay lại màn hình](https://www.youtube.com/watch?v=N8M4zsqTkr4) tái hiện lỗi.

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 18.10)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus: (chạy command `ibus version` để xem phiên bản ibus)
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.4.5)

**Thông tin thêm**
Các nội dung khác có liên quan đến lỗi đang xảy ra.

**Comment by ndgnuh** [comment]
Bạn đã làm theo những hướng dẫn trong mục [các vấn đề thường gặp](https://github.com/BambooEngine/ibus-bamboo/wiki/C%C3%A1c-v%E1%BA%A5n-%C4%91%E1%BB%81-th%C6%B0%E1%BB%9Dng-g%E1%BA%B7p) chưa?

Nếu rồi thì bạn cung cấp thêm thông tin được không? (Ví dụ như bạn dùng desktop environment gì, nếu không biết có thể nói mặc định? Bạn dùng Ubuntu "gốc" hay một phiên bản nào đó của Ubuntu? Bạn không gõ được tiếng Việt ở những phần mềm nào, hay là chỗ nào cũng không gõ được?)
