### ISSUE TITLE
Không gõ được tiếng Việt có dấu trên Slack

### ISSUE THREAD

**Issue by tuong-olli** [BambooEngine/ibus-bamboo#260]
Mình đã cài đặt ibus-bamboo và sử dụng đc trên nhiều ứng dụng và browser nhưng chỉ có Slack là ko gõ được dấu. NHờ bạn kiểm tra lại giùm.

**Comment by fx500ms** [comment]
bạn cài bản slack trên trang chủ là gõ được nhé
