### ISSUE TITLE
Không xuất hiện menu Bamboo ở trong Ibus Input Method sau khi update bản mới nhất, 0.7.8

### ISSUE THREAD

**Issue by hukacode** [BambooEngine/ibus-bamboo#261]
**Mô tả lỗi**
Không xuất hiện menu Bamboo ở trong Ibus sau khi update bản mới nhất.
Mình chạy lệnh sau thì xuất hiện menu.
`env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['xkb:us::eng', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"`

**Các bước tái hiện lỗi**
Update version mới nhất ở Arch

**Kết quả mong muốn**
Hiển thị trong Input Method

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://user-images.githubusercontent.com/3462200/127791728-a74b371d-6f94-49f5-a0ee-4da5a1d04636.png)

**Môi trường**
 - OS và version: Arch
 - Desktop: Qtile
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.7.8)

**Thông tin thêm**
Được cài đặt từ AUR

**Comment by FurryOfficial** [comment]
Bạn thử vô phần iBus Preferences xem có trong đó không, chứ mình cũng như bạn, không thấy trong phần Settings > Input Method.

**Comment by hukacode** [comment]
@FurryOfficial 
Là ở đâu vậy nhỉ? Cho mình xin screenshot với

**Comment by FurryOfficial** [comment]
> @FurryOfficial
> Là ở đâu vậy nhỉ? Cho mình xin screenshot với


https://user-images.githubusercontent.com/70711319/128454414-662da513-0261-4679-b7c1-9bf49f66c6ed.mp4

**Comment by hukacode** [comment]
Cám ơn bạn nha.

Cơ mà Input Method là cái tab ở trong IBus Preferences mà mình nói ấy.
Sau khi click vào nút Add thì nó không có xuất hiện Bamboo để mình chọn.

**Comment by fx500ms** [comment]
bạn chạy lệnh `ibus restart` rồi thử lại xem

**Comment by hukacode** [comment]
Mình thử rồi mà vẫn không được.
Mình có uninstall xong cài lại vẫn không xuất hiện.

**Comment by fx500ms** [comment]
bạn chạy lệnh này rồi gửi output lên đây nhé
```
evn | grep "IM_MODULE\|XMODIFIERS"
ibus-daemon -xrv
```

**Comment by hukacode** [comment]
![image](https://user-images.githubusercontent.com/3462200/128523983-befccee3-c276-4740-8828-ad8e8c064d8b.png)
lệnh thứ 2 có cần mình nhấn hay gõ thêm gì không nhỉ?

**Comment by fx500ms** [comment]
hmm mọi thứ có vẻ vẫn ổn
bạn có thể chụp ảnh hoặc quay video mô tả từng bước đc không?

**Comment by hukacode** [comment]
Mình cũng chỉ nhớ là hôm bữa update yay, pacman gì đó xong khởi động lại thì không thấy bộ gõ Bamboo nữa, xong vào Input Method là không còn menu.
Bản trước mình update lên thì có thấy vài menu (candy, unikey,...) xong đến bản mới update thì nó mất hết.
Nếu chạy lệnh ở đầu bài thì có Input Method, nhưng menu thì không có gì.
![image](https://user-images.githubusercontent.com/3462200/128526039-c4e25a90-17cc-4978-aa60-80fc7affa9ec.png)

**Comment by fx500ms** [comment]
bạn thử cài lại xem có gặp lỗi gì không?

**Comment by hukacode** [comment]
Mình có thử uninstall xong cài lại mà vẫn không xuất hiện à.
Mình nhớ lần cuối mình chọn là cái Candy. Xong khởi động lại thì mất hết.

**Comment by fx500ms** [comment]
có thể là do package nào đó bị lỗi, mình thử thì không tái hiện được lỗi này trên các distro khác.

**Comment by binhtran432k** [comment]
@hukacode  Bạn nên search `bamboo` thay vì `viet` vì ibus trên arch nó search theo tên chứ không phải theo ngôn ngữ. Ở bản 0.7.8 mình đã bỏ `viet` ra khỏi tên của các icon mới để đồng bộ với bộ icon ban đầu nên khi search sẽ không thấy.

**Comment by hukacode** [comment]
Mình search theo `bamboo` thì đã thấy rồi. 🎆

**Comment by fx500ms** [comment]
@binhtran432k  có vẻ không ổn? tại sao Bamboo không còn nằm trong nhóm Vietnamese nữa? lỗi ibus hay engine?

**Comment by fx500ms** [comment]
ah hiểu rồi, do Bamboo không có \*Viet\* nên search không ra
