### ISSUE TITLE
[Solved] Không chạy trên libre, freeoffice. OS Manjaro 

### ISSUE THREAD

**Issue by TINeDITION** [BambooEngine/ibus-bamboo#262]

**Comment by thanhtai9606** [comment]
Chuẩn mình cũng bị tình trạng như bạn, không gõ được tiếng việt trên terminal luôn

**Comment by thanhtai9606** [comment]
Hi bạn mình mơi tìm được 1 giải pháp
bạn tạo file
vim ~/.xprofile
chép nội dung này vào
`export GTK_IM_MODULE=ibus
    export QT_IM_MODULE=ibus
    export XMODIFIERS=@im=ibus
    export QT4_IM_MODULE=ibus
    export CLUTTER_IM_MODULE=ibus
    export GLFW_IM_MODULE=ibus`

restart OS
chọn chế độ gõ mặc định
6. XTestKeyFakeEvent(không gạch chân)
là có thể gõ tiếng việt trong libre, freeoffice hoặc wps office nha bạn

**Comment by zenfas** [comment]
[Link hướng dẫn](https://forum.manjaro.org/t/cai-d-t-ibus-bamboo-d-go-ti-ng-vi-t-tren-manjaro/7586)

**Comment by TINeDITION** [comment]
Cám ơn bác nhe. Em xài Manjaro xfce 18.x thì gõ bình thường, chạy lên KDE Manjaro 20.x thì chịu. Để mình thử :)
