### ISSUE TITLE
Dù đang để ở tiếng anh vẫn gõ được tiếng việt

### ISSUE THREAD

**Issue by nhiennn** [BambooEngine/ibus-bamboo#264]
**Mô tả lỗi**
Mình mới gặp lỗi này, khi chuyển từ tiếng việt sang tiếng anh thì vẫn có thể gõ đươc tiếng việt

**Các bước tái hiện lỗi**
1. Mở terminal
2. Đổi ngôn ngữ sang tiếng việt
3. gõ tiếng việt OK
4. đổi ngôn ngữ sang tiếng anh
5. vẫn gõ được tiếng việt NG

**Kết quả mong muốn**
Tìm hiểu nguyên nhân và xử lý

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://user-images.githubusercontent.com/13449527/128848425-c830a205-3d8c-4ef0-876b-4d85d597adab.mp4

**Môi trường**
 - OS và version: Ubuntu 20.04.2 LTS
 - Desktop: **mặc định**
 - Phiên bản ibus-bamboo: bản mới nhất 0.7.8

**Comment by fx500ms** [comment]
bạn thử gỡ ra cài lại xem, nếu không được bạn chạy lệnh `ibus-daemon -vrx`, chuyển sang tiếng Anh, gõ một vài từ tiếng Việt rồi gửi mình output nhé
