### ISSUE TITLE
không gõ được tiếng việt trên hầu hết các app

### ISSUE THREAD

**Issue by minh-0** [BambooEngine/ibus-bamboo#265]
mình dùng Kali linux GNOME, chỉ gõ được tiếng việt trên thanh search của menu, các ứng dụng còn lại đều không gõ được. Đã thử gỡ đi cài lại

**Comment by ndgnuh** [comment]
Thử làm theo hướng dẫn trong https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60 chưa bạn?

**Comment by minh-0** [comment]
mình làm rồi mà vẫn không được

**Comment by minh-0** [comment]
mình cài thêm package `ibus-gtk3` thì đã fix được lỗi.
