### ISSUE TITLE
Minor bug + question.

### ISSUE THREAD

**Issue by ThomasDNguyen** [BambooEngine/ibus-bamboo#266]
**Mô tả lỗi**
Phần menu của ibus-bamboo tự hiện xuống mà không cần click chuột.

**Các bước tái hiện lỗi**
1. Tương tác với ibus-bamboo (thường là chỉnh settings).
2. Thỉnh thoảng phần thanh menu ("Preference, Emoji choice,..." - cái menu lúc bấm nút chuột phải vào biểu tượng ibus-bamboo ở system tray ý) sẽ tự bật xuống như đc click mặc dù người dùng không hề click.
3. Điều này chỉ xảy ra vài lần và thường là đương lúc và sau khi edit settings. Một lát sau vấn đề sẽ không xảy ra nữa.

**Kết quả mong muốn**
Phần menu không tùy tiện bật xuống như vậy.

**Môi trường**
 - OS và version: Kubuntu 21.04
 - Desktop: KDE (mặc định)
 - Phiên bản ibus-bamboo: 0.7.9 (mới nhất)

**Thông tin thêm**
1. Mình chỉ muốn report bug để đóng góp chứ thực ra lỗi này cứ kệ đi cũng được vì nó không có ảnh hưởng lớn tới user experience lắm.
2. Có 1 lứu ý là đồng thời cũng là 1 thắc mắc của mình: Theo như hướng dẫn trên github thì sau khi mình tải ibus-bamboo về cần chạy dòng lệnh sau `env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"`. Tuy nhiên mình không hề chạy dòng lệnh đó mà đã đánh vào terminal `ibus-setup` và setup từ đó luôn. Kết quả là mình đã chạy được ibus-bamboo thành công. Mình thắc mắc dòng lệnh trên có mục đích gì và nó có quan trọng không và bh mình có cần chạy dòng lệnh đó nữa không khi mà ibus-bamboo đã hoạt động ổn rồi?

**Comment by fx500ms** [comment]
Cám ơn bạn đã báo lỗi, mấy lỗi trên là lỗi của ibus/x11 nếu có thể bạn báo lỗi ở đây nhé https://github.com/ibus/ibus.

Lệnh `env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"` dùng để cấu hình ibus-bamboo từ dòng lệnh thay vì dùng GUI, nếu bạn đã setup từ `ibus-setup` thì không cần chạy lệnh đó nữa nhé.
