### ISSUE TITLE
Gõ JWWT thì ra JƯWT chứ không phải JWT hoặc JWWT

### ISSUE THREAD

**Issue by hukacode** [BambooEngine/ibus-bamboo#267]
Chào mọi người,

Mình đang dùng kiểu gõ Telex 2, muốn gõ kiểu như Unikey, JWWT thì nó sẽ ra JƯWT chứ không phải là JWT.
Có cách nào để setting cho nó ra như mong muốn không nhỉ?

Trường hợp mà gõ WW thì nó sẽ ra Ư rồi thành W, nhưng khi ghép với chữ khác thì ra ƯW.

Mình đã thử Telext W mà cũng không được.

**Comment by fx500ms** [comment]
mình thử với ibus-unikey thì JWWT -> JWWT mà bạn?

**Comment by hukacode** [comment]
À, ý mình là Unikey của Windows ấy.

Bạn thử gõ bằng Telex 2 của Bamboo thì nó sẽ ra như thế này nè:
HWW -> HW
JWW -> JƯW
IWW -> IƯW
OWW -> OW

Kiểu có một số kí tự thì gõ 2 lần WW thì nó không ra chữ W mà ra chữ ƯW ấy

**Comment by luongthanhlam** [comment]
lỗi đã được fix ở bạn v0.8.0 nhé bạn 👍
