### ISSUE TITLE
Gõ tiếng Việt bị lỗi trên Brave của Ubuntu 20.04

### ISSUE THREAD

**Issue by tab87vn** [BambooEngine/ibus-bamboo#268]
**Mô tả lỗi**
Gõ tiếng Việt bị lỗi trên trình duyệt Brave trên Ubuntu 20.04

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở Brave
2. Gõ bật kỳ câu tiếng việt nào trên thanh địa chỉ hoặc các ứng dụng web (Messenger, Zalo, ...)
3. Ví dụ `tiếng việt` sẽ trở thành `tieêngếng vieêtệt`
4. Lỗi này không bị trên các trình duyệt khác như Chromium hay Firefox (issue này đang đươc viết trên chromium)

**Kết quả mong muốn**

Khi gõ `tiếng việt` thì sẽ hiện ra `tiếng việt`

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![image](https://user-images.githubusercontent.com/2638833/130213834-6f234ac4-ae08-49a4-844a-70c5861f3d02.png)

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.7.9

**Thông tin thêm**

Phiên bản `0.7.9` được cài đặt và nâng cấp thông qua `apt-get upgrade`

**Comment by fx500ms** [comment]
bạn làm theo hướng dẫn ở đây nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#chuy%E1%BB%83n-sang-ch%E1%BA%BF-%C4%91%E1%BB%99-g%C3%B5-kh%C3%A1c
