### ISSUE TITLE
Onboard 

### ISSUE THREAD

**Issue by blaplafla13th** [BambooEngine/ibus-bamboo#269]
ở KDE Ubuntu X11, onboard bị lỗi không gõ được tiếng việt nhưng khi dùng snippet thì lại gõ ra tiếng việt kiểu here thành hể
mình cũng thử nhiều các bàn phím ảo khác và toàn ra vậy

**Comment by fx500ms** [comment]
bạn cập nhật bản mới rồi tắt tuỳ chọn `Bắt sự kiện chuột` sẽ gõ được trên bàn phím ảo nhé

**Comment by blaplafla13th** [comment]
thank you
