### ISSUE TITLE
Vẫn còn lỗi khi sử dụng trong Android Studio

### ISSUE THREAD

**Issue by xiabui** [BambooEngine/ibus-bamboo#27]
Mình sử dụng trong Android Studio bị lỗi mất space khi gõ và nếu thêm space giữ hai từ thì sẽ bị chèn tab ở giữa thay vì là space. Sau 1 thời gian sử dụng thì bộ gõ có 1 tí vấn đề là không gõ được tiếng việt nữa (mình bị trong site messenger.com) phải thay đổi bộ gõ sang US và chuyển lại mới khắc phục được.
- OS lúc bị lỗi: Ubuntu 18.10.
- OS đang sử dụng là: Ubuntu 19.04 và lâu lâu vẫn bị

Cảm ơn bạn!

**Comment by luongthanhlam** [comment]
bạn đang dùng phiên bản ibus bamboo nào nhỉ? có thể gửi mình clip quay màn hình lúc xảy ra lỗi được không?

**Comment by xiabui** [comment]
https://drive.google.com/file/d/1nhaQgl9_NeG8GVRRdYiP1dG5_GvWRS9_/view?usp=sharing
Phiên bản mới nhất nha bạn. Còn link ở trên là video nha. Cảm ơn nhiều

**Comment by thanhngch** [comment]
Có khi nào là do môi trường Gnome không, bạn thử chuyển sang xfce xem có bị lỗi không.
Mình dùng bộ gõ với xubuntu và thử trên Android Studio thấy thấy chạy rất tốt.

**Comment by ndgnuh** [comment]
Bạn thử tắt `android studio` đi sau đó chạy

```sh
killall ibus-daemon
IBUS_ENABLE_SYNC_MODE=1 ibus-daemon -xrd 
```

Sau đó khởi động lại `android studio` xem lỗi có được khắc phục không.

**Comment by xiabui** [comment]
Vẫn bị bạn ơi.

**Comment by luongthanhlam** [comment]
@xiabui lỗi này đã được fix trong bản build mới nhất (0.4.6ubuntu1-0~201904221408), bạn cập nhập lại ứng dụng từ ppa nhé
