### ISSUE TITLE
Không xài phím để swap eng vs vi được

### ISSUE THREAD

**Issue by dylandang18052** [BambooEngine/ibus-bamboo#270]
![image](https://user-images.githubusercontent.com/89272061/130571237-042616ee-784c-498b-8c33-667b16fd7bf0.png)
Hiện em đang cài tổ hợp phím này để có thể **chuyển đổi (Ctrl + Shift)** nhưng mà hình như em vẫn không thể chỉnh được ạ.
Em cảm hơn mọi người nhiều nhé

**Comment by fx500ms** [comment]
bạn theo dõi ở đây nhé https://gitlab.gnome.org/GNOME/gtk/-/issues/1128
