### ISSUE TITLE
Không tìm thấy ibus-bamboo trong Input Method

### ISSUE THREAD

**Issue by lnn2204** [BambooEngine/ibus-bamboo#272]
**Mô tả lỗi**
Mình không tìm thấy ibus-bamboo trong input method của ibus-setup

**Môi trường**
 - OS và version: Kali Linux 2021 
 - Desktop: KDE Plasma
 - Phiên bản ibus-bamboo: Từ git

**Comment by fx500ms** [comment]
bạn chạy thử 2 lệnh này xem
```
ibus restart && env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"
```

**Comment by danielphan2003** [comment]
mình thử restart rồi chạy lại ibus daemon và đã thấy ibus bamboo xuất hiện lại trong ibus-setup:
```
[ $(ibus restart && exit) ] || ibus-daemon -drxR
```

**Comment by lnn2204** [comment]
Mình sửa đc rồi, cảm ơn 2 bạn :dancing_men:
