### ISSUE TITLE
Không thể gõ tiếng việt trong Android Studio và Slack

### ISSUE THREAD

**Issue by hoanglocmdc** [BambooEngine/ibus-bamboo#273]
**Mô tả lỗi**

Không thể gõ tiếng việt trong Android Studio và Slack
**Các bước tái hiện lỗi**

Ví dụ:
1. Mở gedit
2. Gõ abc
...
4. Thấy xyz

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 20.04)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.7.9)

**Thông tin thêm**

**Comment by fx500ms** [comment]
bạn cài Android Studio và Slack từ snap hay apt, nếu cài từ snap, bạn gỡ ra và cài lại từ apt nhé

**Comment by hoanglocmdc** [comment]
ok. Mình thử cài bằng apt thì ok rồi. Thanks.
