### ISSUE TITLE
Bổ sung thêm ibus-gtk3 vào danh sách dependency trên ibus-bamboo repository

### ISSUE THREAD

**Issue by vdhan** [BambooEngine/ibus-bamboo#274]
**Mô tả lỗi**
Thiếu ibus-gtk3 để gõ Tiếng Việt trên Linux Mint, Debian

**Các bước tái hiện lỗi**
1. Mở chương trình có input chữ (terminal, trình duyệt, code editor, ...)
2. Chuyển ibus sang gõ Tiếng Việt
3. Gõ tiếng Việt không được
4. Cài ibus-gtk3
5. Vào lại chương trình, gõ Tiếng Việt được
6. Gỡ bỏ ibus-gtk3
7. Vào lại chương trình, không gõ được Tiếng Việt

**Kết quả mong muốn**
Bổ sung thêm ibus-gtk3 vào danh sách dependency trên ibus-bamboo repository

**Môi trường**
 - OS và version: Debian 11, Linux Mint 20.2, Linux Mint 19.3
 - Desktop: Xfce, Cinnamon, MATE (**mặc định**)
 - Phiên bản ibus-bamboo: 0.7.9

**Thông tin thêm**
Ở các linux distro như Ubuntu đã có sẵn ibus và ibus-gtk3 nên việc cài đặt ibus-bamboo và gõ Tiếng Việt dễ dàng. Tuy nhiên, ở các distro khác không cài sẵn ibus hoặc có cài đặt ibus nhưng không cài ibus-gtk3 thì nếu chỉ cài ibus-bamboo thôi thì không gõ Tiếng Việt được.
Vì ibus-gtk3 chỉ là recommend của ibus, không phải là dependency, nên dù cài lại ibus thì vẫn vậy.
ibus-bamboo cần dùng thư viện GTK+ 3 nên sẽ cần ibus-gtk3 để hoạt động ổn định cùng ibus. Vì vậy, nên bổ sung ibus-gtk3 vào danh sách dependency của ibus-bamboo repository.

**Comment by fx500ms** [comment]
thực ra ibus-bamboo chỉ phụ thuộc vào thư viện GTK+3 thôi bạn, ibus-gtk3 mới là phụ thuộc của ibus, tuy nhiên một số distro không đưa ibus-gtk3 vào dependency của ibus nên một số ứng dụng gtk3 không thể gõ được với ibus.

**Comment by fx500ms** [comment]
Ok, mình đã sửa lại hướng dẫn cài đặt để cài thêm các gói recommend của ibus.
