### ISSUE TITLE
Không thể Alt+Tab nhanh sau khi thực hiện một vài thao tác chuột

### ISSUE THREAD

**Issue by backy4rd** [BambooEngine/ibus-bamboo#275]
**Mô tả lỗi**
Không alt+tab nhanh được sau khi kéo thả chuột, nhấn tổ hợp phím alt+tab chậm(giữ alt khoảng 300ms và sau đó nhấn tab) hoặc alt+tab nhanh lần thứ 2 thì switch vẫn bình thường. Mình đã có thử trên Kubuntu nhưng vẫn xuất hiện lỗi này. Remap lại qua tổ hợp phím khác cũng không hiệu quả. Mình nghĩ đây là vấn đề của ibus-bamboo tại vì khi mình chuyển qua dùng ibus-unikey thì không xuất hiện lỗi này nữa.

**Các bước tái hiện lỗi**
1. Kéo thả chuột ở vị trí bất kỳ
2. Dùng tổ hợp phím Alt+Tab nhanh

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![vokoscreen-2021-09-19_16-34-00 (online-video-cutter com)](https://user-images.githubusercontent.com/56971973/133923318-e76e3bb8-0c46-4cf1-aa87-3dd5824e280b.gif)

**Môi trường**
 - OS và version: KDE Neon (Ubuntu 20.04)
 - Desktop: KDE Plasma 5.22.5
 - Phiên bản ibus-bamboo: 0.7.9

**Comment by ltlam2604** [comment]
mình vẫn chưa tái hiện được lỗi này, bạn thử tắt tuỳ chọn "Bắt sự kiện chuột" xem có khắc phục được không?

**Comment by backy4rd** [comment]
Tuy không rõ lý do nhưng sau khi mình thử gỡ và cài đặt lại thì không xuất hiện lỗi này nữa, mình có cấu hình xmodmap nên cũng có thể lỗi này không xuất phát từ ibus-bamboo mà từ cấu hình của mình.
