### ISSUE TITLE
Không gõ được tiếng Việt trên các ứng dụng

### ISSUE THREAD

**Issue by xxxtrglyn** [BambooEngine/ibus-bamboo#276]
**Mô tả lỗi**
Chỉ gõ được tiếng Việt trên thanh tìm kiếm

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở Chrome
2. Gõ tieengs Vieetj
...
4. Thấy tieengs Vieetj

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: mặc định
 - Phiên bản ibus-bamboo: 0.7.9

**Thông tin thêm**
Mình đã đọc phần các vấn đề thường gặp và làm theo những vẫn chưa sửa được lỗi này

**Comment by vinhjaxt** [comment]
Bạn đã đọc: https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60
Chưa.
Bạn có kết quả của các output các câu lệnh trên không?

**Comment by xxxtrglyn** [comment]
> Bạn đã đọc: https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60
> Chưa.
> Bạn có kết quả của các output các câu lệnh trên không?

Mình đã đổi mấy cái module qua lại bus vs xim rồi log out ra vào lại vẫn không được
