### ISSUE TITLE
Lỗi gõ Tiếng Việt trên Slack

### ISSUE THREAD

**Issue by v-diepttn147** [BambooEngine/ibus-bamboo#279]
**Mô tả lỗi**
Gõ Tiếng Việt trong Slack bị lỗi.

**Các bước tái hiện lỗi**
Gõ Tiếng Việt trong Slack, kiểu gõ TELEX, bảng mã UNICODE 

1. Mở Slack
2. Gõ `Gox treen Slack bij looix`
3. Thấy `Goõ treên Slack biị loôiỗi`

**Kết quả mong muốn**
`Gõ trên Slack bị lỗi `

**Môi trường**
 - OS và version: Ubuntu 21.04
 - Phiên bản ibus-bamboo: 0.7.9

**Thông tin thêm**
- Slack được download từ trang chủ. Không phải snap hay Ubuntu software.
- Lỗi xuất hiện từ sáng 05 Oct 2021, không có phần mềm nào thay đổi, update trước khi bị lỗi

Xin cảm ơn team ạ.

**Comment by luongthanhlam** [comment]
bạn nhấn `Shift`+`~`, chọn kiểu gõ số 1 hoặc 4 nhé.

**Comment by nghiadxvn** [comment]
@luongthanhlam lỗi này lại mới bị lại bạn ơi, Ubuntu 20.04 LTS + Ibus Bamboo 0.8.2

**Comment by luongthanhlam** [comment]
bạn bị lỗi gì nhỉ? bạn đã thử chuyển sang kiểu gõ số 1 chưa?

**Comment by nghiadxvn** [comment]
@luongthanhlam mình đã thử hết các kiểu gõ nhưng vẫn bị
Lỗi hiển thị: https://i.imgur.com/MkR0KEl.png

**Comment by luongthanhlam** [comment]
![image](https://github.com/BambooEngine/ibus-bamboo/assets/26364140/73dead14-5cbf-48da-9015-a3a050602df1)

mình vẫn gõ được mà? bạn đang dùng slack bản .deb hay snap? nhấn `Shift+~` có hiện gì không?

**Comment by luongthanhlam** [comment]
mình vẫn gõ được mà? bạn đang dùng slack bản .deb hay snap? nhấn `Shift+~` có hiện gì không?
![image](https://github.com/BambooEngine/ibus-bamboo/assets/26364140/53ff1d19-6332-4228-b826-bc1780ddd3fa)

**Comment by nghiadxvn** [comment]
@luongthanhlam vẫn bị bạn. Mình gỡ và cài lại thì chạy đc rồi
