### ISSUE TITLE
Vấn đề khi cài bộ gõ.

### ISSUE THREAD

**Issue by TranNgocTinh0810** [BambooEngine/ibus-bamboo#289]
- Mình đang gặp vấn đề khi cài đặt như trong hình, loay hoay nhưng vẫn không biết lỗi ở vấn đề gì, ai có thể cho mình hướng giải quyết về vấn đề này được không ạ. Mình cảm ơn rất nhiều.

![image](https://user-images.githubusercontent.com/55842203/138892498-3cf54eb2-3078-4e3a-bcac-8cbab5e51371.png)

**Comment by luongthanhlam** [comment]
@TranNgocTinh0810 sorry, bạn còn gặp lỗi này không nhỉ?
