### ISSUE TITLE
Tổng hợp các lỗi gặp phải

### ISSUE THREAD

**Issue by dieupxse** [BambooEngine/ibus-bamboo#29]
**Mô tả lỗi**
Hiện tại gặp lỗi như sau:
1. Trên ứng dụng Simplenote gõ gõ thường hay bị mất chữ
2. Không thể bỏ chọn cách fixed lỗi gạch chân trên các ứng dụng
3. Ứng dụng hay bị treo
4. Gõ trên thanh địa chỉ của chrome như sau: goo -> google sẽ suggest là google.com nhưng khi bấm Enter sẽ không đi đến google.com mà là goo

**Môi trường**
 - OS và version: Ubuntu 19.04
 - Desktop: Gnome 3.32
 - Phiên bản ibus: ibus 1.5.19
 - Phiên bản ibus-bamboo: v0.4.6

**Thông tin thêm**
Các nội dung khác có liên quan đến lỗi đang xảy ra.

**Comment by ndgnuh** [comment]
Lỗi 1: Test và confirm (tái hiện lỗi: `thịt`, `thì`, một số từ với dấu của các chữ cái `â`, `ă`, `ư`,..)
Lỗi 2: Bạn có thể [chuyển sang chế độ gõ khác để bỏ gạch chân](https://github.com/BambooEngine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng). Hình như tác giả để chế độ mặc định là pre-edit (có gạch chân).
Lỗi 3: Bạn có thể cung cấp thêm thông tin về ứng dụng nào treo được không?
Lỗi 4: Mình đã thử trên `chromium`, dùng chế độ thứ 3 (Fix gạch chân - Forward Key Event) và lỗi này không xảy ra?

**Comment by luongthanhlam** [comment]
@ndgnuh thực ra nếu người dùng không cấu hình gì cả thì chế độ mặc định là pre-edit, còn nếu người dùng chọn Fix lỗi gạch chân từ menu thì chế độ mặc định là chế độ số 3 @@

@dieupxse 
1. Trên simplenote bạn đang dùng chế độ gõ nào? bạn đã thử chuyển sang các chế độ gõ khác chưa?
2. Bạn có thể chọn chế độ mặc định (phím 1) để bỏ chọn các chế độ không gạch chân khác
3. Một số ứng dụng bật chế độ gõ không gạch chân có thể gõ chậm hơn bình thường (pre-edit), hiện giờ chưa có giải pháp khả dĩ nào để fix cả
4. Lỗi này đã được fix trong bản build mới nhất, bạn cập nhật lại từ ppa nhé

**Comment by TungQuan** [comment]
Mình dùng ubuntu 18.04
Telegram thì khi xoá ký tự thì nó bị lỗi là đã xoá ký tự nhưng vẫn còn ký tự đó và không thể thấy con trỏ

**Comment by luongthanhlam** [comment]
Bạn nhấp tổ hợp phím Shift + ~, làm theo hướng dẫn để chọn chế độ gõ phù
hợp nhé
