### ISSUE TITLE
Chèn thừa ký tự khi dùng chuột để chuyển focus sang text area khác

### ISSUE THREAD

**Issue by minhduc0711** [BambooEngine/ibus-bamboo#292]
**Mô tả lỗi**
Khi gõ tiếng Việt ở một text area 1, sau đó dùng chuột để chuyển sang text area 2 và gõ tiếp, các ký tự chưa được commit ở text area 1 sẽ được chèn vào text area 2.

**Các bước tái hiện lỗi**

1. Mở hai cái xfce4-terminal
2. Ở 1 cái terminal, gõ từ "lỗi" và không nhấn bất cứ phím commit nào (e.g. space, ctrl....)
3. Dùng chuột để chuyển focus sang terminal thứ 2
4. Gõ phím "a"
5. Xuất hiện chuỗi ký tự "ooix" bị chèn thêm trước ký tự "a"

**Kết quả mong muốn**
Cái "cache" này cần được xóa khi dùng chuột để chuyển focus

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://user-images.githubusercontent.com/34294427/140257655-db3f80fd-3b54-4727-8464-22ac6bf6689f.mp4

Lỗi tương tự trên Firefox

https://user-images.githubusercontent.com/34294427/140257977-0429eff4-ebbe-470b-a712-10b611c57c8a.mp4

**Môi trường**
 - OS và version: Arch
 - Desktop: Sway
 - Phiên bản ibus-bamboo: 0.7.9

**Comment by atheros98** [comment]
Mình cũng gặp phải tình trạng như thế này, phiên bản 0.8.0. 

Cách fix: Bật chức năng "Bắt sự kiện chuột" trong phần "Cấu hình khác"

![image](https://user-images.githubusercontent.com/19872680/140861723-1dbe81ae-4399-4c89-928b-cb515e60b92c.png)

**Comment by minhduc0711** [comment]
Hình như option đó chỉ có trên gnome thôi bác.

**Comment by luongthanhlam** [comment]
@minhduc0711 option đó có trên tất cả bản phân phối nhé.

**Comment by minhduc0711** [comment]
Hoạt động được trên cả wayland hả bác? Mình muốn chỉnh trong `ibus-bamboo.config.json` thì option này có tên là gì nhỉ?

**Comment by luongthanhlam** [comment]
à bạn dùng sway thì hiện sway chưa hỗ trợ bảng chọn trên thanh công cụ đâu, muốn sửa cấu hình bạn chọn `Show property panel`: `Always` nhé
![](https://i.stack.imgur.com/BFoxI.png)

**Comment by minhduc0711** [comment]
Mình thấy option "Capture mouse events" đã được tích sẵn rồi nhưng lỗi phía trên vẫn xảy ra. Liệu có phải do protocol trên wayland không hỗ trợ mouse capture không nhỉ?

**Comment by luongthanhlam** [comment]
yep, option "Capture mouse events" hiện chưa hoạt động trên wayland nhé bạn, bên wayland cũng chưa có protocol hỗ trợ chức năng này.
