### ISSUE TITLE
Lỗi trên thanh search firefox

### ISSUE THREAD

**Issue by Kritiqual** [BambooEngine/ibus-bamboo#293]
**Mô tả lỗi**

Gõ "aa" đáng lẽ thành "â" nhưng lại thành  "aâ" trên thanh search và một số liên quan đến thanh search của firefox

**Các bước tái hiện lỗi**

Tất cả các mode đều bị lỗi này và đều trên thanh search firefox:
1. Mở firefox
2. Bấm vào thanh search hoặc bất cứ đâu dùng để search
3. Gõ thử chữ tiếng việt, ví dụ: "â", "ơ", ...
4. Thấy "aâ" thay vì "a"

Lỗi 2:
Chuyển sang mode 1 thì không gõ được tiếng việt

Lỗi 3:
Chuyển sang mode 4 thì khi gõ bất cứ từ tiếng việt nào thì nó thêm "/" ở cuối
ví dụ: gõ "ă" : nhấn "a" -> nhấn "w" -> kết quả "aă/"

**Môi trường**
 - OS và version: Archlinux (5.14.16-arch1-1)
 - Desktop: Tùy chỉnh (awesome)
 - Phiên bản ibus-bamboo: 0.7.9 trên AUR

**Thông tin thêm**

Firefox bản 94.0-1 trên AUR

**Comment by luongthanhlam** [comment]
bạn kiểm tra các biến môi trường xem https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng

**Comment by Kritiqual** [comment]
Sau khi mình thử hết thì lỗi vẫn còn

**Comment by luongthanhlam** [comment]
mode 1 cũng lỗi nữa à? cụ thể lỗi như nào nhỉ?

**Comment by fxminhquan** [comment]
à mình cũng dùng Firefox, nhưng chế độ 1 với 3 gõ trên thanh search thì aa ra â, còn chế độ 4 thì aa mới ra aâ, thân gửi đến bạn Lâm nhé.
môi trường mình dùng: elementaryOS 6 (based on Ubuntu 20.04.03 LTS)

**Comment by Kritiqual** [comment]
Mình đã liệt kê hết rồi đấy, mode 1 thì còn không gõ đc tiếng việt mà

**Comment by fxminhquan** [comment]
Mình dùng elementary OS 6(based on Ubuntu 20.04.03LTS) thì chế độ 1 3 4 rất ổn, trên Firefox thì chế độ 3 ổn nhất. Chắc do bạn dùng Arch, chứ mode 1 là ổn nhất mà ko gõ đc tiếng việt thì hơi kì

**Comment by luongthanhlam** [comment]
@Kritiqual ở mode 1, khi gõ `aa` trên thanh địa chỉ bạn thấy gì? các biến môi trường bạn đang dùng là gì?
```
env | grep "IM_MODULE\|XMODIFIERS"
```

**Comment by Kritiqual** [comment]
Ở mode 1, mình gõ bất cứ từ tiếng việt nào nó cũng không nhận, ví dụ: "xin chào" -> "xin chaof", "â" -> "aa"

Đây là biến môi trường của mình:
```
$ env | grep "IM_MODULE\|XMODIFIERS"
GLFW_IM_MODULE=xim
GTK_IM_MODULE=ibus
QT4_IM_MODULE=ibus
XMODIFIERS=@im=ibus
CLUTTER_IM_MODULE=ibus
QT_IM_MODULE=ibus
```

**Comment by luongthanhlam** [comment]
bạn kiểm tra có cài thiếu gói nào trong này không `im-config ibus-qt ibus-gtk ibus-gtk3`? nếu ko được bạn thử cập nhật hệ thống hoặc cài lại HĐH xem.

**Comment by minhduc0711** [comment]
Mình nghĩ hiện tượng này xảy ra khi Firefox autocomplete URL thế này:
![20211123_22h36m53s_grim](https://user-images.githubusercontent.com/34294427/143055969-a7cf3fa1-2a53-4321-9a92-cfb82c6fdd92.png)
nếu gõ thêm chữ "e" nữa thì sẽ thành "teê".

Vậy nên workaround là vào `about:config` rồi đổi `browser.urlbar.autoFill` thành `false` nhé.

**Comment by Kritiqual** [comment]
Thank @minhduc0711, problem solved!
