### ISSUE TITLE
Build gói RPM cho Fedora 34, 35

### ISSUE THREAD

**Issue by tuwuna** [BambooEngine/ibus-bamboo#294]
Tương tự https://github.com/BambooEngine/ibus-bamboo/issues/172

Mình vừa chuyển từ arch qua fedora và lại bị https://github.com/BambooEngine/ibus-bamboo/issues/96

Chắc là bên fedora có version cũ nhỉ?

**Comment by luongthanhlam** [comment]
openbuild đang bị lỗi build package trên Fedora 34, 35, tạm thời bạn cài từ mã nguồn nhé https://github.com/BambooEngine/ibus-bamboo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-m%C3%A3-ngu%E1%BB%93n

**Comment by tmn03** [comment]
mình cũng fedora cũng bị trên gnome terminal bấm Shift + ~ không ra bảng để loại trừ

**Comment by luongthanhlam** [comment]
các gói cho fedora 34, 35 đã có trên OBS
