### ISSUE TITLE
Không gõ được tiếng việt ở Discord hoặc Google chat(unoffical),...trên Ubuntu 21.10 wayland

### ISSUE THREAD

**Issue by Smallbook20** [BambooEngine/ibus-bamboo#295]
Có vẻ như bản bamboo này chưa hỗ trợ các phần khác trên ubuntu 21.10 wayland. Ở Chrome mình có thể gõ tiếng việt nhưng ở các phần mềm như discord hoặc google chat (unoffical) thì không dùng được.
 Mình có thử chuyển qua ubuntu Xorg (x11) thì có thể dùng bình thường. 
 Mong team có thể fix lỗi này.

**Comment by luongthanhlam** [comment]
mình vẫn gõ được mà, bạn kiểm tra lại các biến môi trường nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
