### ISSUE TITLE
Không vào được setting trên ubuntu 20.04

### ISSUE THREAD

**Issue by vryy** [BambooEngine/ibus-bamboo#296]
**Mô tả lỗi**
Như tiêu đề

**Các bước tái hiện lỗi**
1. Mở Setttings/Region & Language
2. Trong Input Sources nhấn vào biểu tượng bánh răng bên cạnh Vietnamese (Bamboo)
3. Không thấy bất cứ gì hiện ra

**Kết quả mong muốn**
1. Đổi bộ gõ Vni/Telex

**Môi trường**
 - Ubuntu 20.04
 - Desktop:  Gnome
 - Phiên bản ibus-bamboo: 0.8.0

**Comment by luongthanhlam** [comment]
bạn nhấn `Ctrl-Space` để chuyển sang chế độ gõ tiếng Việt, click vào biểu tượng `vi` trên thanh công cụ, chọn `Kiểu gõ`, chọn `VNI` nhé

**Comment by vryy** [comment]
không chọn kiểu gõ đc @luongthanhlam . Khi nhấn vào biểu tượng vi thì hiện ra Character Map, Keyboard Layout Chart, Text Entry Settings. Không hiện ra Kiểu gõ như b nói.

**Comment by luongthanhlam** [comment]
bạn khởi động lại máy rồi thử lại xem?

**Comment by vryy** [comment]
Vẫn k đc b à

**Comment by luongthanhlam** [comment]
bạn có thể chụp ảnh hoặc quay màn hình để mô tả lỗi rõ hơn được không nhỉ?
