### ISSUE TITLE
Không gõ được trong Google Chrome

### ISSUE THREAD

**Issue by dangne** [BambooEngine/ibus-bamboo#297]
**Mô tả lỗi**
Không gõ được trong Google Chrome. Các ứng dụng khác gõ được bình thường.

**Các bước tái hiện lỗi**
1. Mở Google Chrome
2. Gõ bất kỳ (vd: "aaaaa")
3. Chỉ in ra ký tự đầu tiên ("a") và không gõ thêm được gì khác

**Kết quả mong muốn**
In ra đầy đủ những gì đã type ("aaaaa")

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: **mặc định**
 - Phiên bản ibus-bamboo: 0.8.0

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn trong wiki nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60
