### ISSUE TITLE
Lỗi chữ bị nhập trên ver 0.8.0 ubuntu

### ISSUE THREAD

**Issue by duy99uit** [BambooEngine/ibus-bamboo#299]
Mình gặp lỗi trên cả Talex và Vni
- Mong muốn "ế" sao khi gõ "e - 6 - 1" nhưng kết quả trên màn hình là "eêế"

**Comment by luongthanhlam** [comment]
bạn nhấn Shift+~, chọn 1 kiểu gõ phù hợp nhé https://github.com/BambooEngine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng
