### ISSUE TITLE
Lỗi đánh dấu với các chữ cái in hoa

### ISSUE THREAD

**Issue by quanpham0805** [BambooEngine/ibus-bamboo#3]
**Các bước tái hiện lỗi**
1. Mở bất kì chỗ nào có thể gõ và dùng được ibus-bamboo
2. Khi gõ bất kì cái gì mà dùng toàn bộ chữ in hoa (Caps lock || giữ shift), đánh thử những chữ cái sau:
 "ER", "EE", .....
3. Các cái kia phải đánh theo thứ tự: "E" + "E" + "E" hoặc "E" + "R" + "R"
4. Nhận được "EEe", "ERr",...

**Comment by luongthanhlam** [comment]
Cám ơn mọi người đã báo lỗi, mình sẽ fix lỗi này trong bản release tiếp theo. Tạm thời có thể khắc phục bằng cách click vào biểu tượng ibus-bamboo chọn Kiểm tra chính tả rồi bỏ chọn mục Sử dụng từ điển

**Comment by luongthanhlam** [comment]
Lỗi này đã được sửa trong https://github.com/BambooEngine/ibus-bamboo/commit/8a1ca6753d7c0545b2de026e2870e7d9fcffb9ea
