### ISSUE TITLE
Xin thêm tính năng cho phép nhấn Alt để gửi ký tự gốc khi dùng kiểu gõ TCVN (Microsoft Layout)

### ISSUE THREAD

**Issue by harn2412** [BambooEngine/ibus-bamboo#30]
Chào bạn,

Hiện nay, mình dùng kiểu gõ TCVN 6064 là chính và rất thích nó vì có thể nhập liệu lẫn lộn Anh - Việt tốt và dùng với VIM rất tốt vì có thể gửi lệnh trực tiếp mà không cần chuyển bộ gõ.

Nếu được mình xin thêm tính năng khi nhấn kèm phím Alt (được chỉ định phím Alt Right hoặc Alt Left thì càng tốt) thì sẽ gửi ký tự gốc. Ví dụ khi nhấn "1" thì sẽ ghi ra "ă" nhưng khi nhấn "alt" và "1" thì sẽ ghi ra "1". Như kiểu nhấn AltGr khi gõ bằng Vietnamese keyboard layout.

Vì mình nhập liệu không dùng từ điển và kiểm tra chính tả nên khi nhập số nó mất nhiều thời gian vì phải nhập 2 lần cho số đó.

Xin cảm ơn bạn rất nhiều.

**Comment by luongthanhlam** [comment]
tính năng xung đột với một số wm như i3 sử dụng Alt+phím số để switch workspace, mình nghĩ sử dụng phím tắt Shift+Space để hoàn tác chuỗi về dạng nguyên thể (raw) sẽ khả thi hơn
