### ISSUE TITLE
Lỗi hiện 2 bảng ibus cùng lúc (Arch)

### ISSUE THREAD

**Issue by kleqing** [BambooEngine/ibus-bamboo#301]
https://user-images.githubusercontent.com/78801337/144753476-fcc0693a-7d71-490f-adf1-af78af07ed70.mp4

 Mình cài ibus và ibus-bamboo từ AUR, mọi thứ hoạt động OK nhưng không hiểu sao lúc mình mở bảng ibus nó hiện cùng lúc 2 cái!
 Mong bạn có thể fix giùm!

**Comment by kleqing** [comment]
P/s: Chuột mình không bị nháy đúp nha bạn (Mình thử cả trackpad nhưng vẫn bị)

**Comment by luongthanhlam** [comment]
bạn vui lòng báo lỗi cho bên ibus nhé https://github.com/ibus/ibus/issues
