### ISSUE TITLE
Ẩn popup khi type

### ISSUE THREAD

**Issue by quocson95** [BambooEngine/ibus-bamboo#302]
**Mô tả lỗi**
Trợ giúp ẩn popup khi type

**Các bước tái hiện lỗi**

**Kết quả mong muốn**
Không có popup khi type

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://user-images.githubusercontent.com/8086898/145750371-99e4649d-578e-4345-95be-c98588ae9b7f.png)

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 18.04)
 - Desktop: (cinnamon)
 - Phiên bản ibus-bamboo: (0.7.9)

**Comment by luongthanhlam** [comment]
bạn chọn `Hide automatically` như trong hình nhé 

![](https://i.stack.imgur.com/bOIRQ.png)
