### ISSUE TITLE
Không cài được linux mint 

### ISSUE THREAD

**Issue by phamhai93** [BambooEngine/ibus-bamboo#303]
![image](https://user-images.githubusercontent.com/15818325/145969793-93c05279-59a2-430b-a0cc-45df6b2bbbe0.png)g)

Em cài trên linux mint thì bị lỗi này, không thể cài đặt được bước tiếp

**Comment by luongthanhlam** [comment]
bạn chạy lại lệnh này nhé, gần đây kết nối mạng ra quốc tế không được ổn định lắm
```
sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo
sudo apt-get update
```
