### ISSUE TITLE
Lỗi nhảy chử trên Goolge Chrome 

### ISSUE THREAD

**Issue by duyanh4788** [BambooEngine/ibus-bamboo#304]
**Mô tả lỗi**
Gõ chữ có dấu trên goolge chrome double chữ , VS Code gõ tiếng việt bình thường
Bảng mã : Unicode 
kiểu gõ : VNI

**Các bước tái hiện lỗi**
Ví dụ:
1. Mở goolge chrome
2. Gõ : tiếng việt
...
4. Thấy : tiengêngếng vietêtệt

**Kết quả mong muốn**
tiếng việt

**Clip quay màn hình**
https://user-images.githubusercontent.com/75610658/147741911-252f1b92-0ec3-416c-9595-6fd0e0552628.mp4

**Môi trường**
 Ubuntu 20.04

**Comment by luongthanhlam** [comment]
bạn nhấn Shift+~ và chọn kiểu gõ phù hợp theo hướng dẫn ở đây nhé https://github.com/BambooEngine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng
