### ISSUE TITLE
Khong tim thay Ibus Bamboo

### ISSUE THREAD

**Issue by datlechin** [BambooEngine/ibus-bamboo#305]
**Mô tả lỗi**
Da chay xong cac cau lenh de cai dat Ibus bamboo nhung vao settings khong tim thay vietnamese (bamboo)

![Screenshot from 2021-12-31 00-44-05](https://user-images.githubusercontent.com/56961917/147775754-f1717206-2ec3-4925-a57d-e7eb7f914dba.png)

![Screenshot from 2021-12-31 00-45-31](https://user-images.githubusercontent.com/56961917/147775875-ac0dd08c-eaa5-4872-99bc-d4d0c1d83d1c.png)

**Môi trường**
 - OS và version: Ubuntu 20.04.3 LTS
 - Desktop: Mac dinh

 - Phiên bản ibus-bamboo: latest

**Comment by luongthanhlam** [comment]
bạn logout, login rồi thử lại xem, hoặc dùng lệnh này
```
env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"
```

**Comment by datlechin** [comment]
Dạ tìm thấy rồi anh
Có cách nào bỏ dấu gạch chân dưới chữ khi gõ tiếng Việt ko anh

**Comment by luongthanhlam** [comment]
bạn làm theo ở đây nhé https://github.com/BambooEngine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng
