### ISSUE TITLE
Lỗi khi bật gõ tắt lên thì chức năng tự động sửa lỗi với phím từ sai bị vô hiệu hóa

### ISSUE THREAD

**Issue by pnkill3327** [BambooEngine/ibus-bamboo#306]
**Mô tả lỗi**

*như tiêu đề:<
**Các bước tái hiện lỗi**

Ví dụ:
1. Bật kiểm tra chính tả(là cái em muốn bật), bật gõ tắt(em cũng muốn bật cái này:< ko tắt đc)
2. Gõ gõ "khánh", ko gõ dấu cách gõ thêm mấy chữ chữ "h" xong gõ dấu cách
...
4. Thấy nó ra khánhhhh thay vì ra khanhshhh (khi tắt gõ tắt)

**Kết quả mong muốn**

gõ khánhhhh thì phải thấy khanhshhh thay vì vẫn là khánhhhh 
hoặc
gõ config thì phải thấy config chứ không phải là cònig (khi bật gõ tắt)

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://www.awesomescreenshot.com/video/6667337?key=9d507382ab3c3ed307997d7cb1172d69

https://user-images.githubusercontent.com/56959175/147878487-7598319a-6f1a-45c4-a09f-3b40ac50e6c3.mp4

**Môi trường**
 - OS và version: Ubuntu 16.04 LST 64bit 
 - Desktop: mặc định của hệ điều hành :< 
 - Phiên bản ibus-bamboo: 0.8.0
![image](https://user-images.githubusercontent.com/56959175/147878559-83e73574-4b1c-4824-908a-1c407f84e441.png)

**Thông tin thêm**

được cài đặt theo hướng dẫn của trang: https://truongtc.com/cai-dat-bo-go-tieng-viet-ibus-bamboo-tren-ubuntu/

**Comment by luongthanhlam** [comment]
đã fix, bạn cập nhật lên bản mới nhé
