### ISSUE TITLE
Ibus-Bamboo không hoạt động trên Sublime Text 4

### ISSUE THREAD

**Issue by ducdat02** [BambooEngine/ibus-bamboo#307]
**Mô tả lỗi**
Ibus-Bamboo không hoạt động trên Sublime Text 4 bản Ubuntu 21.04

**Comment by ducdat02** [comment]
**Mô tả lỗi**

Nhập Tiếng Việt ở Sublime Text 4, không hiện chữ, phải nhấn space thì chữ mới xuất hiện. 

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở sublime text 4 
2. Gõ "abc"
3. Không thấy "abc"
4. Nhấn space mới thấy "abc"

**Kết quả mong muốn**

Mong muốn gõ thì chữ hiện lên luôn, không cần phải đợi đến khi nhấn space mới hiện. 
**Ảnh chụp màn hình, hoặc clip quay màn hình**

Không có. 

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 20.04)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.7.9)
- Ubuntu 21.04
- Desktop: Gnome 
- Phiên bản: mới nhất. 
**Thông tin thêm**

Không có.

**Comment by K4zoku** [comment]
Bro thử đổi `Chế độ gõ` xem (mặc định là phím `Shift` + <code>`</code>)
Tôi đang dùng trong Sublime text 4 (build 4126) với `Chế độ gõ` số 6 khá ổn

**Comment by zenfas** [comment]
Cái lỗi không hiện chữ đến khi nhấn space hao hao thằng WPS Office

**Comment by luongthanhlam** [comment]
sublime text 4 chưa hỗ trợ tính năng pre-edit nên bạn chịu khó chờ bên đó bổ sung tính năng này hoặc chuyển sang chế độ gõ khác (nhấn Shift+` để chuyển)
