### ISSUE TITLE
[Enchanment] Để cài đặt vào trong Preferences của Ibus

### ISSUE THREAD

**Issue by K4zoku** [BambooEngine/ibus-bamboo#308]
Mình thấy ibus-mozc có hiện dc cái nút Preferences 
![image](https://user-images.githubusercontent.com/34259386/148552691-f050cef3-b342-434a-97b6-182a3257b5de.png)

Còn ibus-bamboo thì không có cái nút này
![image](https://user-images.githubusercontent.com/34259386/148552819-75a2cecb-7a76-4090-84fa-517cb09e474f.png)

Nếu dc thì mong các tác giả chuyển các cài đặt vào trong đấy thay vì để ở system tray menu (hoặc vẫn giữ system tray menu nhưng thêm chỗ cài đặt ở trong ibus preferences)

**Comment by luongthanhlam** [comment]
fixed in v0.8.1
