### ISSUE TITLE
Không gõ được tiếng Việt

### ISSUE THREAD

**Issue by truong1978** [BambooEngine/ibus-bamboo#309]
**Mô tả lỗi**
đã cài đủ các bước, thấy ibus-bamboo, add trong phần ngôn ngữ nhưng không gõ được tiếng Việt bằng telex hay vni.

**Các bước tái hiện lỗi**
1. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo
…..
Tìm thấy:1 http://vn.archive.ubuntu.com/ubuntu focal InRelease
Tìm thấy:2 http://vn.archive.ubuntu.com/ubuntu focal-updates InRelease         
Lấy:3 http://vn.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]   
Tìm thấy:4 https://dl.google.com/linux/chrome/deb stable InRelease             
Tìm thấy:5 http://ppa.launchpad.net/bamboo-engine/ibus-bamboo/ubuntu focal InRelease
Lấy:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]      
Tìm thấy:7 http://ppa.launchpad.net/teni-ime/ibus-teni/ubuntu focal InRelease  
Bỏq:8 http://ppa.launchpad.net/ubuntu-vn/ppa/ubuntu focal InRelease            
Lỗi:9 http://ppa.launchpad.net/ubuntu-vn/ppa/ubuntu focal Release
  404  Not Found [Địa chỉ IP: 91.189.95.85 80]
Đang đọc các danh sách gói... Xong            
E: The repository 'http://ppa.launchpad.net/ubuntu-vn/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

2. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ sudo apt-get update

Tìm thấy:1 http://vn.archive.ubuntu.com/ubuntu focal InRelease
Tìm thấy:2 http://vn.archive.ubuntu.com/ubuntu focal-updates InRelease         
Lấy:3 http://vn.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]   
Tìm thấy:4 https://dl.google.com/linux/chrome/deb stable InRelease             
Tìm thấy:5 http://ppa.launchpad.net/bamboo-engine/ibus-bamboo/ubuntu focal InRelease
Lấy:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]      
Tìm thấy:7 http://ppa.launchpad.net/teni-ime/ibus-teni/ubuntu focal InRelease  
Bỏq:8 http://ppa.launchpad.net/ubuntu-vn/ppa/ubuntu focal InRelease            
Lỗi:9 http://ppa.launchpad.net/ubuntu-vn/ppa/ubuntu focal Release              
  404  Not Found [Địa chỉ IP: 91.189.95.85 80]
Đang đọc các danh sách gói... Xong            
E: The repository 'http://ppa.launchpad.net/ubuntu-vn/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

2. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ sudo apt-get install ibus-bamboo --install-recommends

Đang đọc các danh sách gói... Xong
Đang xây dựng cây quan hệ phụ thuộc       
Đang đọc thông tin về tình trạng... Xong
ibus-bamboo is already the newest version (0.8.0-0~202110090928~ubuntu20.04.1).
(Các) gói sau đây đã được tự động cài đặt nên không còn cần yêu cầu lại:
  linux-headers-5.11.0-27-generic linux-hwe-5.11-headers-5.11.0-27
  linux-image-5.11.0-27-generic linux-modules-5.11.0-27-generic
  linux-modules-extra-5.11.0-27-generic
Hãy dùng lệnh “sudo apt autoremove” để gỡ bỏ chúng.
0 nâng cấp, 0 được cài đặt mới, 0 cần gỡ bỏ, và 1 chưa được nâng cấp.

3. buntu@ubuntu-To-be-filled-by-O-E-M:~$ echo $XDG_SESSION_TYPE
x11

4. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ ibus-daemon -xrv
FocusIn.
Enable.XGrabPointer: successfully grabbed mouse pointer
RECORD extension for local server is version 1.13
WM_CLASS=("Gnome-terminal")

XGrabPointer: successfully grabbed mouse pointer
MotionNotify: delta_x=65 delta_y=21

FocusOut.
Disable.FocusIn.
Enable.WM_CLASS=("libreoffice-writer")

^C

5. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ ibus engine Bamboo

(process:2753): IBUS-CRITICAL **: 12:25:47.738: ibus_bus_set_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
Set global engine failed.

6. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ echo $IBUS_ADDRESS

7. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ echo $IBUS_ADDRESS_FILE

8. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ cat /var/lib/dbus/machine-id
26bc0855b3a940db99a0481023830cd6

9. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ cat /etc/achine-id
cat: /etc/achine-id: Không có tập tin hoặc thư mục như vậy

10. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ ls ~/.config/ibus/bus/
26bc0855b3a940db99a0481023830cd6-unix-0

11. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ ls ~/.config/ibus/bus/
26bc0855b3a940db99a0481023830cd6-unix-0

12. ubuntu@ubuntu-To-be-filled-by-O-E-M:~$ cat $(ls ~/.config/ibus/bus/)
cat: 26bc0855b3a940db99a0481023830cd6-unix-0: Không có tập tin hoặc thư mục như vậy

...

**Comment by luongthanhlam** [comment]
bạn chạy giúp mình lệnh này nhé
```
ls -la ~/.config/ibus/bus/
```

**Comment by truong1978** [comment]
ubuntu@ubuntu:~$ ls -la ~/.config/ibus/bus
tổng 12
drwx------ 2 ubuntu ubuntu 4096 Thg 1  10 07:32 .
drwx------ 3 ubuntu ubuntu 4096 Thg 1   8 15:43 ..
-rw-rw-r-- 1 ubuntu ubuntu  380 Thg 1  10 07:32 26bc0855b3a940db99a0481023830cd6-unix-0

**Comment by luongthanhlam** [comment]
oh, bạn chưa khởi động ibus-daemon lên thì phải. Bạn thêm dòng `ibus-daemon -rdx` vào file `~/.profile` (hoặc `~/.bashrc`) và đăng nhập lại nhé.

**Comment by truong1978** [comment]
mình đã thử đúng như vậy, log out nhưng kết quả vẫn không đổi. sau
đó restart máy, vẫn không thể gõ tiếng Việt.
vẫn chưa thể viết Tiếng Việt. bamboo, Teni đều không có tác dụng.

**Comment by luongthanhlam** [comment]
bạn không gõ được trên tất cả ứng dụng à? bạn chạy `/usr/lib/ibus-bamboo/ibus-engine-bamboo` trong terminal, gõ 1 vài từ tiếng Việt rồi gửi mình output nhé

**Comment by truong1978** [comment]
no such file or directory

**Comment by luongthanhlam** [comment]
bạn cài lại ibus-bamboo theo hướng dẫn này nhé https://github.com/BambooEngine/ibus-bamboo#ubuntu-v%C3%A0-c%C3%A1c-distro-t%C6%B0%C6%A1ng-t%E1%BB%B1
Cài xong thì kiểm tra các biến môi trường `env | grep "IM_MODULE\|XMODIFIERS"`

**Comment by truong1978** [comment]
khi chaỵ lệnh này, kết quả như sau:
***@***.***:~$ env | grep "IM_MODULE\|XMODIFIERS" GTK_IM_MODULE=xim
***@***.***=unikey QT_IM_MODULE=ibus ***@***.***:~$

hy vọng lần này có thể giúp mình fix được, đúng là lúc đầu cài
Unikey nhưng mãi không chạy, mới gở và cài lại bamboo.
nhưng ở đây vẫn còn dính dáng tới Unikey :)

**Comment by truong1978** [comment]
khi chạy lệnh dưới, kết quả:
***@***.***:~$ /usr/lib/ibus-bamboo/ibus-engine-bamboo 2022/02/14
13:04:45.831171 Got Bus, Running Standalone XGrabPointer: successfully
grabbed mouse pointer Enable.2022/02/14 13:04:45.855926 FocusIn. RECORD
extension for local server is version 1.13 WM_CLASS=("Gnome-terminal") tuw
tieeng vieetj khoong gox dduwowcj XGrabPointer: successfully grabbed mouse
pointer XGrabPointer: successfully grabbed mouse pointer MotionNotify:
delta_x=66 delta_y=24

**Comment by luongthanhlam** [comment]
bạn cấu hình biến môi trường sai rồi, thử lại theo hd này nhé
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
