### ISSUE TITLE
Lỗi khi chuyển sang chế độ Tiếng Việt

### ISSUE THREAD

**Issue by kildo162** [BambooEngine/ibus-bamboo#31]
**Mô tả lỗi**
Khi chuyển sang chế độ Tiếng Việt từ tiếng Anh thì lập tức bị khóa scroll. scroll lên xuống đều bị rescroll lại chỗ con trỏ đang đặt. teni ko bị lỗi này. Tắt đi okokokokok

**Môi trường**
 - OS và version: buntu 18.04
 - Desktop: Gnome
 - Phiên bản ibus: 1.5.17
 - Phiên bản ibus-bamboo: mới nhất

**Comment by luongthanhlam** [comment]
đã fix trong v0.4.7
