### ISSUE TITLE
L

### ISSUE THREAD

**Issue by nahpld** [BambooEngine/ibus-bamboo#310]
**Mô tả lỗi**

**Các bước tái hiện lỗi**
Lỗi nặng trên VIQR, không đánh được chữ ngã

Không gõ được dấu ngã trong VIQR (vì  ký tự ~ được dùng để làm danh sách loại trừ)
1. Lựa cách gõ VIQR
2. Đánh chữ: Nga~
Thấy Nga và danh sách loại trừ hiển thị (Shift ̃ )
Nga~ (Khi đánh đúp (Shift ̃  ) thêm lần nữa 

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - version: (ví dụ: Ubuntu 20.04)
 - Desktop: (Gnome,... hoặc **mặc định**)
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.7.9)

**Thông tin thêm**

**Comment by luongthanhlam** [comment]
Bạn mở bảng chọn ibus-bamboo, chọn `Phím tắt` rồi xóa hoặc thay đổi phím tắt `Chuyển chế độ gõ` nhé
<img width="666" alt="Screen Shot 2022-01-09 at 15 02 02" src="https://user-images.githubusercontent.com/26364140/148674529-0a0da3b2-5079-4646-8218-0a3ca1e96bef.png">

**Comment by nahpld** [comment]
Cám ơn bạn hướng dẫn và đã khắc phục được cách đánh dấu ngã, nhưng còn
một lỗi khác rất năng ngoài lỗi đã report:

khi gõ (\.)  phải ra (.)     // Đây là dấu nặng
khi gõ  (\?) phải ra (?)   // Đây là dấu hỏi
khi gõ  (\\) phải  ra (\)    // Đây là dấu chéo ngược
khi gõ (dd) phải ra chữ (đ)  // Không gõ được chữ  (đ)

Nói tóm lại, là Escape Character \ không hoạt động và không đánh được
chữ đ, Đ khi xử dụng VIQR.
Nếu có cách khắc phục, xin bạn hướng dẫn dùm.  Cám ơn bạn.

Dũng.

**Comment by luongthanhlam** [comment]
Hiện tại, ibus-bamboo không hỗ trợ kí tự thoát `\` để đánh dấu chấm câu, bạn có thể gõ các kí tự `.?~` 2 lần để gõ các dấu chấm câu này. Ví dụ, `nga~~` -> `ngã`, `nang)..` -> `nặng`.

Lỗi đánh chữ `đ` đã được fix ở bản mới nhất, bạn cài và thử lại nhé.

**Comment by nahpld** [comment]
Cám ơn sự giải thích của bạn.  Mong ibus-bamboo sớm hỗ trợ ký tự
thoát để hoàn thành hoàn hảo
cách đánh VIQR trên Linux.

Tôi và nhiều bạn khác đã dùng VIQR mấy chục năm nay và xem ký tự
thoát \ là một phần integrated, không
thể thiếu khi xử dụng VIQR.  Cả Microsoft, Google và Keyman đều xử
dụng ký tự thoát \ trong tất cả các phiên
bản gõ của họ từ trước đến nay.  Gần đây nhất trong các phiên
bản IMEs trên mạng trong Google Input Tools.

Ibus-bamboo là software uyển chuyển và có rất nhiều tiềm năng.  Tôi
và các bạn xử dụng VIQR mong sẽ có ngày
có thể xử dụng ibus-bamboo để thay thế Google IMEs và Keyman, có
cách đánh đồng nhất cho tất cả các applications
trên Linux.

Chúc bạn thành công.

Dũng.
