### ISSUE TITLE
Lỗi nặng trên VIQR, không dùng \ để đánh được dấu nặng (.), dấu hỏi (?) và các ký tự dùng dấu gạch chéo ngược (\) đi trước để báo dấu theo sau.

### ISSUE THREAD

**Issue by nahpld** [BambooEngine/ibus-bamboo#311]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

Ví dụ:
1) Lựa cách gõ VIQR
2) Đánh chữ \., \?, \-
3) Thấy chữ \., \?, \-

**Kết quả mong muốn**

**Môi trường**
 - OS và version: (Ubuntu 20.04)
 - Desktop: (Gnome)
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.7.9)

**Comment by luongthanhlam** [comment]
Hiện tại, ibus-bamboo không hỗ trợ kí tự thoát `\` để đánh dấu chấm câu `.?~`, bạn cần gõ các kí tự `.?~` 2 lần để thoát chế độ bỏ dấu thanh nhé.
