### ISSUE TITLE
Minh cai tren Kali Linux thi bi loi nay

### ISSUE THREAD

**Issue by levuphucnguyen** [BambooEngine/ibus-bamboo#313]
GOPATH=/home/kali/ibus-bamboo GO111MODULE=off go build -ldflags "-w -s -X main.Version=0.8.0" -o ibus-engine-bamboo ibus-bamboo
gcc -o keyboard-shortcut-editor setup-ui/keyboard-shortcut-editor.c `pkg-config --libs --cflags gtk+-3.0`
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
setup-ui/keyboard-shortcut-editor.c:2:10: fatal error: gtk/gtk.h: No such file or directory
    2 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:46: build] Error 1
                                                                           
Tren terminal nos bao loi nay thi phai lam sao a?
![image](https://user-images.githubusercontent.com/96976083/149607102-4b591e29-c35e-4510-b924-ae7a54807b66.png)

**Comment by luongthanhlam** [comment]
bạn cài thêm các gói phụ thuộc nhé 
https://github.com/BambooEngine/ibus-bamboo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-m%C3%A3-ngu%E1%BB%93n
