### ISSUE TITLE
Ibus không khởi động được với OS

### ISSUE THREAD

**Issue by sngkhiem** [BambooEngine/ibus-bamboo#314]
**Mô tả lỗi**
Ibus không tự startup với OS

**Các bước tái hiện lỗi**
Đã thử add ibus-daemon vào startup applications 
Đã thêm các dòng sau:
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus
ibus-daemon -drx
Vào .bashrc nhưng vẫn không được

**Kết quả mong muốn**
Ibus khởi động chung với OS

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome (BSPWM)
 - Phiên bản ibus-bamboo: mới nhất

**Comment by luongthanhlam** [comment]
bạn chạy lệnh này nhé `im-config -n ibus`, nếu không được bạn copy những dòng này vào cuối file `/etc/profile` và khởi động lại máy
```
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus
```
