### ISSUE TITLE
Change instruction on README so that making ibus-bamboo does not remove other layouts

### ISSUE THREAD

**Issue by coughingmouse** [BambooEngine/ibus-bamboo#315]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

Ví dụ:
1. Scrap instructions and run in terminal
2. Your keyboard layout settings get messed up unless your setting was "us" only

**Kết quả mong muốn**

Installing a layout should not remove other existing layouts?? I use [('xkb', 'us+altgr-intl'), ('ibus', 'hangul'), ('xkb', 'vn'), ('ibus', 'libpinyin'), ('ibus', 'mozc-jp')], and you can't just erase my existing layouts without warning, can you? Like goes for preloaded-engines; append, not overwrite.

env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 20.04) Pop!_OS 21.10 (equivalent to Ubuntu 21.10, I believe)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**) Gnome
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.7.9)

**Thông tin thêm**

**Comment by luongthanhlam** [comment]
Thank you, it is fixed in https://github.com/BambooEngine/ibus-bamboo/commit/a09b2468ea345ae0be6ad191d016bc9b26f57a7c
