### ISSUE TITLE
Không mở được popup danh sách loại trừ

### ISSUE THREAD

**Issue by long21wt** [BambooEngine/ibus-bamboo#317]
**Mô tả lỗi**
Hiện tại thì không hiểu sao với ibus bamboo master mình không thể mở được pop up danh sách loại trừ với `Shift` + `~`.
Trước đó mình đã không dùng Linux trong 6 tháng nên không nhớ trước đó như thế nào.
Trước đó mình nhớ là ibus bamboo có đọc 1 file config bên trong đó chứa id của input windows.
Mình gợi ý tác giả có thể cho 1 file mẫu danh sách loại trừ như thanh search của GNOME, Terminal, etc. ,

**Môi trường**
 - OS và version: Fedora 35
 - Desktop: GNOME 41
 - Phiên bản ibus-bamboo: master

**Comment by leanhtai01** [comment]
Mình bị lỗi tương tự nhưng trong Firefox.
Trong Firefox `Shift` + `~` khi sử dụng ibus-bamboo cho ra dấu ~ không mở được bảng chuyển chế độ gõ.

**Thông tin thêm**
- OS: Arch Linux
- Firefox đã được cấu hình lại như hướng dẫn tại đây: https://wiki.archlinux.org/title/firefox#Hardware_video_acceleration
- ibus-bamboo: master

**Comment by luongthanhlam** [comment]
@long21wt @leanhtai01 các bạn đang dùng firefox bản bao nhiêu vậy? gửi mình output lệnh này nhé
```
cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
```

> Mình gợi ý tác giả có thể cho 1 file mẫu danh sách loại trừ như thanh search của GNOME, Terminal, etc. ,

Mỗi window manager có cách đặt tên WM_CLASS khác nhau nên không dùng chung được bạn ạ

**Comment by leanhtai01** [comment]
@luongthanhlam 
Mình bổ sung là lỗi này chỉ xảy ra trên Wayland và bị trên nhiều ứng dụng như Firefox, GNOME Terminal,...
**Khi sử dụng Xorg không bị lỗi này.**

Output lệnh `cat ~/.config/ibus-bamboo/ibus-bamboo.config.json`
[output.txt](https://github.com/BambooEngine/ibus-bamboo/files/8053411/output.txt)

**Thông tin thêm**
- OS Name: Arch Linux
- OS Type: 64-bit
- GNOME Version: 41.3
- Windowing System: Wayland
- Firefox version: 98.0b3 (64-bit)
- ibus-bamboo: master

**Comment by luongthanhlam** [comment]
@leanhtai01 mình thử trên ubuntu thì vẫn mở được popup, bạn thử thay `Shift+~` sang phím tắt khác xem?
