### ISSUE TITLE
[gnome, manjaro] không hiển thị được menu/ cài đặt, không gõ được tiếng việt

### ISSUE THREAD

**Issue by thuanpham2311** [BambooEngine/ibus-bamboo#318]
**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://user-images.githubusercontent.com/40050527/154798850-73ff4b43-7685-43d3-9d13-56c5e7c8da2e.mp4

**Môi trường**
 - OS: manjaro
 - Desktop: gnome 41.3 (wayland), đã test trên x11 vẫn không được
 - Phiên bản ibus-bamboo: home_lamlng_Arch/ibus-bamboo 0.8.1-1

**Comment by thuanpham2311** [comment]
update:
- do không xài được ibus-bamboo, nên tui cài ibus-unikey xài tạm, hiện tại vẫn okay
- cài ibus bamboo bằng yay sử dụng build từ source bị lỗi thiếu thư viện `gtk/gtk.h`, tui có thử seach trên mạng rồi cài mấy cái gtk lib trên arch rồi mà vẫn không ăn thua (hổm nay xài cái ibus-bamboo không build từ source thì vẫn bình thường, mấy ngày trước gõ trên chrome chuyển qua lại kiểu gõ thì trên thanh top bar, cái icon nó lag lag đơ đơ gì đố mà cũng gõ được, nhưng hôm nay bay màu luôn 😆)

<details>
<summary>báo lỗi khi build từ source</summary>

```bash
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
glib-compile-resources --generate-source setup-ui/keyboard.gresource.xml
GOPATH=/home/master/.cache/yay/ibus-bamboo/src/ibus-bamboo-0.8.1-RC3 GO111MODULE=off go build -ldflags "-w -s -X main.Version=0.8.1" -o ibus-engine-bamboo ibus-bamboo
gcc -o keyboard-shortcut-editor setup-ui/keyboard-shortcut-editor.c `pkg-config --libs --cflags gtk+-3.0`
/bin/sh: line 1: pkg-config: command not found
setup-ui/keyboard-shortcut-editor.c:2:10: fatal error: gtk/gtk.h: No such file or directory
    2 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:47: build] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: ibus-bamboo
```

</details>

**Comment by luongthanhlam** [comment]
bạn chạy lệnh `ibus-daemon -vxr` rồi thử lại xem có lỗi gì không?

**Comment by thuanpham2311** [comment]
> bạn chạy lệnh `ibus-daemon -vxr` rồi thử lại xem có lỗi gì không?

- nó vẫn vậy, mình thấy nó log hình như thiếu glibc mà mình đã installed glibc rồi nên không biết sao. 

![image](https://user-images.githubusercontent.com/40050527/154805580-ac42cfdb-e0f7-4e3e-b48d-078bc5ac4213.png)
```bash
❯ ibus-daemon -vxr
/usr/lib/ibus-bamboo/ibus-engine-bamboo: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/ibus-bamboo/ibus-engine-bamboo)
```

**Comment by DickyDicky7** [comment]
Trên manjaro glibc chỉ mới version 2.33-5 thôi, ibus-bamboo yêu cầu 2.34 🥲

**Comment by thuanpham2311** [comment]
sau khi manajro upgrade một đống package gì đó và thêm chút magic hiện tại ibus bamboo mội thứ xài điều okay
