### ISSUE TITLE
Không thể gõ tiếng Việt trên Ubuntu 20.04 (xorg)

### ISSUE THREAD

**Issue by hoatd1993** [BambooEngine/ibus-bamboo#319]
**Mô tả lỗi**
Hiện tại mình đang dùng GNOME/Unity trên Ubuntu 20.04. 
* Khi sử dụng Wayland thì gõ tiếng Việt bình thường.
* Nhưng khi chuyển qua xorg thì ngoại trừ khung search khi bấm phím Super ra là gõ được tiếng Việt, còn lại không thể nào gõ được.

**Các bước tái hiện lỗi**
* Chuyển qua chế độ xorg khi dùng GNOME hay Unity trên Ubuntu 20.04
* Mở Chrome browser, terminal và gõ tiếng Việt thử
* **Actual:** Không thể gõ tiếng Việt
* **Expected:** Tiếng Việt gõ bình thường.

**Comment by luongthanhlam** [comment]
bạn kiểm tra các biến môi trường theo wiki nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng

**Comment by hoatd1993** [comment]
> bạn kiểm tra các biến môi trường theo wiki nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng

Sau khi check lại thì phát hiện ra những app mở bằng cái dock của `gnome-shell` process khi chạy trên `xorg` nó tự động set env variable `GTK_IM_MODULE=xim` khiến cho không thể nào gõ tiếng Việt được. Hiện tại đã thử tất cả các cách chỉnh lại trong `.bashrc` hay `.profile` hay `/etc/environment`... đều không khả thi, terminal thì có tác dụng nhưng riêng process `gnome-shell` thì không được.

**Comment by goatastronaut0212** [comment]
Mình vẫn chưa hiểu lắm. Các version mới của GNOME có vẻ không còn vấn đề n nữaày. Mình sẽ đóng lại vậy. Nếu như lỗi vẫn còn hãy cung cấp thêm thông tin nữa và mình sẽ mở nó lại để tiếp tục tìm hiểu thêm.
