### ISSUE TITLE
Maintain AUR package for Archlinux

### ISSUE THREAD

**Issue by huyhoang8398** [BambooEngine/ibus-bamboo#32]
Mình rất thích package này của bạn, liệu mình và bạn có thể port nó lên AUR trên Arch để việc cài đặt dễ dàng hơn được không?

**Comment by luongthanhlam** [comment]
welcome :)) 
@ndgnuh có thể support được không?

**Comment by ndgnuh** [comment]
Trước khi đưa lên AUR thì mình nghĩ bạn nên nhờ review trên forum đã (mình chưa bảo trì pkg nào cho Arch nên mình cũng không biết review sao). Cả 2 file `PKGBUILD` cho bản git và release đều nằm trong trang github này rồi.

Hiện tại mình dùng `namcap` check file `PKGBUILD` và file `.tar.xz` thì file `PKGBUILD` không có vấn đề gì, nhưng mà file `tar.xz` (file sau khi build) thì nó có 1 cái lỗi với warning, mình chưa tìm hiểu mấy cái đó. 

```sh
$ namcap ibus-bamboo-0.4.6-1-any.pkg.tar.xz 
ibus-bamboo E: ELF file ('usr/lib/ibus-engine-bamboo') found in an 'any' package.
ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') lacks FULL RELRO, check LDFLAGS.
ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') is unstripped.
ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') lacks PIE.
ibus-bamboo W: Dependency included and not needed ('ibus')
```

Nghe nói đôi lúc `namcap` cũng không chính xác lắm, mình không biết với warning như trên thì nó ảnh hưởng gì, nhưng nếu để cài đặt và dùng được thì ok rồi.

Với bản git thì cũng không cần update gì nhiều đâu, chỉnh số phiên bản là được. Bản release thì cũng chỉnh số phiên bản nhưng mà chỉ chỉnh khi mà tác giả thêm một tag release mới thôi.

**Comment by vsim3** [comment]
> ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') lacks FULL RELRO, check LDFLAGS.
> ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') lacks PIE.
> ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') is unstripped.
> ibus-bamboo W: Dependency included and not needed ('ibus')

**Comment by vsim3** [comment]
Mình không dùng Arch, nhưng mấy cái ở đây có thể chỉnh lại lúc build
> ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') lacks FULL RELRO, check LDFLAGS.
> ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') lacks PIE.

Build với PIE sẽ tắt thông báo 2 cái này <code> go build -buildmode=pie</code>
> ibus-bamboo W: ELF file ('usr/lib/ibus-engine-bamboo') is unstripped.

Không build với thông tin debug sẽ bỏ được cái này <code>go build -ldflags="-s -w"</code>
> ibus-bamboo W: Dependency included and not needed ('ibus')

Còn cái này chắc là do nó phụ thuộc vào gói ibus nhưng không có link tới thư viện.

**Comment by nopain2110** [comment]
Mình đã check thử bằng namcap và không có warning hay error rồi up lên aur: [ibus-bamboo](https://aur.archlinux.org/packages/ibus-bamboo/)

**Comment by luongthanhlam** [comment]
@nopain2110 :+1:  Bạn có thể tạo pull request hướng dẫn cài đặt trên README không?

**Comment by nopain2110** [comment]
Mình tạo pull request rồi bạn.
Bạn có thể close issue này được rồi.

**Comment by nopain2110** [comment]
Mình cũng vừa bổ sung ibus-bamboo vào list vietnamese input method ở trang [ArchWiki#IBus](https://wiki.archlinux.org/index.php/IBus)

**Comment by luongthanhlam** [comment]
Nice, thanks you!
