### ISSUE TITLE
Lỗi bị lag và mất dấu trên phần mềm WPS office 

### ISSUE THREAD

**Issue by xuandich** [BambooEngine/ibus-bamboo#321]
**Mô tả lỗi**

Chỉ có chế độ số 6 là gõ được, còn các chế độ khác thì không gõ ra chữ.
Khi gõ dấu thì dấu hiển thị chậm và đa số là không hiển thị dấu.

**Môi trường**
 - OS và version: Linux LXLE 18.04
 - Desktop: mặc định
 - Phiên bản ibus-bamboo: bản 0.8.1

**Thông tin thêm**

Phần mềm WPS Office được cài đặt từ Snap Store
$ sudo snap install wps-2019-snap

**Comment by luongthanhlam** [comment]
bạn cập nhật lên bản mới và chọn kiểu gõ số 1 nhé
