### ISSUE TITLE
Cài ibus-bamboo mà không cần sudo?

### ISSUE THREAD

**Issue by minhduc0711** [BambooEngine/ibus-bamboo#322]
Như tiêu đề, mình đang dùng máy tính của cơ quan nên không có quyền root. Liệu có cách nào để cài bamboo mà không cần root không nhỉ?

**Comment by luongthanhlam** [comment]
bạn vào đây https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo tải file cài đặt tương ứng với hệ điều hành đang sử dụng (hoặc build từ source), giải nén rồi chạy file `./usr/lib/ibus-bamboo/ibus-engine-bamboo` là được nhé

**Comment by minhduc0711** [comment]
Cảm ơn bạn nhé, bamboo chạy ngon luôn!
Vậy cứ lúc nào mình muốn dùng ibus lại phải bật engine thủ công, không biết có workaround nào để chèn entry bamboo vào menu ibus mà không cần root không nhỉ?

**Comment by minhduc0711** [comment]
À ý mình là menu này. Nếu mình muốn chuyển sang tiếng Anh thì phải kill process bamboo do không có bamboo trong menu layout.
![image](https://user-images.githubusercontent.com/34294427/159449990-5a543a9e-fd83-48a2-967c-bae3b0cdfc89.png)
