### ISSUE TITLE
Không gõ được tiếng Việt trong Visual Studio Code trên Ubuntu 22.04

### ISSUE THREAD

**Issue by datlechin** [BambooEngine/ibus-bamboo#323]
**Mô tả lỗi**
Mình cài Ibus Bamboo trên Pre-release Ubuntu 22.04
Nhưng gõ tiếng Việt không được trong Visual Studio Code, còn các phần mềm, tools khác đều gõ được tiếng Việt

**Môi trường**
 - OS và version: Ubuntu 22.04 (pre-release)
 - Desktop: Gnome 42
 - Phiên bản ibus-bamboo: latest

**Comment by luongthanhlam** [comment]
bạn cài vscode từ trang chủ hay từ snap? đã kiểm tra các biến môi trường chưa
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng

**Comment by datlechin** [comment]
VSCode cài bằng file deb hay từ snap vẫn gõ không được
Mìn chạy lệnh `env | grep "IM_MODULE\|XMODIFIERS"`
, nó hiện như này
```
IM_MODULE\|XMODIFIERS"
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
```

**Comment by ntvsp** [comment]
> VSCode cài bằng file deb hay từ snap vẫn gõ không được Mìn chạy lệnh `env | grep "IM_MODULE\|XMODIFIERS"` , nó hiện như này
> 
> ```
> IM_MODULE\|XMODIFIERS"
> XMODIFIERS=@im=ibus
> QT_IM_MODULE=ibus
> ```


lỗi tương tự ạ

**Comment by luongthanhlam** [comment]
@datlechin @ntvsp mn làm theo hướng dẫn ở đây nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
