### ISSUE TITLE
Làm cách nào để disable bộ gõ trong Launcher của Pop!_OS

### ISSUE THREAD

**Issue by dattran1232003** [BambooEngine/ibus-bamboo#324]
**Chào team phát triển, trước tiên em xin cảm ơn team vì team đã làm ra một bộ gõ tuyệt vời cho người Việt Nam sử dụng.**

Hệ điều hành Pop!_OS em đang dùng có 1 ô để tìm kiếm ứng dụng, tìm kiếm cửa sổ đang mở, thực hiện tính toán,.. gọi là Launcher (như Spotlight của MacOS).  Vấn đề em đang gặp là không thể nào thêm cái Launcher này vào danh sách loai trừ của bộ gõ được (dùng Shift + ~), mà nó chỉ hỏi em có muốn thêm ứng dụng đang mở bên dưới Launcher vào hay không =((.

[Link Video](https://drive.google.com/file/d/1RX8Tj3v8kw_tG0XYJF6QcF-Qg6HfP_As/view?usp=sharing)
![image](https://user-images.githubusercontent.com/57513789/162350629-1d32f6a0-59da-4220-accb-cea8e1716288.png)

**Comment by hieutkt** [comment]
Mình vừa xử lý vấn đề này xong. Cách mình đã làm là chỉnh sửa phần `InputModeMapping` trong file `~/.config/ibus-bamboo/ibus-bamboo.config.json`. Đây là cài đặt của mình khi mình muốn đưa Emacs và Pop Launcher vào danh sách loại trừ:

```
...
"InputModeMapping": {
    "\"Emacs\"": 7,
    "\"Show Launcher\"": 7
  }
...
```

**Comment by dattran1232003** [comment]
Tuyệt vời! Mình làm được rồi. Cảm ơn bạn ạ! @hieutkt

**Comment by hieutkt** [comment]
Mình test quanh một lúc nữa thì cái launcher lại crash lung tung. Cái danh sách loại trừ nó hoạt động một lúc xong rồi lại không. 

Chưa hiểu lý do là gì nhưng mình đoán là do phía cái pop-launcher, vì cái này còn mới nên hay lỗi vặt. Hiện tại thì đành sống với nó vậy. Mình dùng Pop OS nửa năm nay nhìn chung sử dụng không vấn đề gì.

**Comment by dattran1232003** [comment]
@hieutkt Mình dùng lệnh `dpkg -l` thì thấy được 3 cái package có tên là launcher (gõ "/" + từ khóa để tìm kiếm trong vim). Mình thử từng cái thì thấy bỏ cái `launcher` vào file config là ổn nhất. (Mình dùng Pop!_OS 21.10).

![image](https://user-images.githubusercontent.com/57513789/162395307-5499f7c8-3753-46fa-8b79-ccf83b4f7de3.png)

**Comment by dattran1232003** [comment]
Đúng vậy bạn ạ, mình thử đủ tên luôn mà vẫn chưa được, lúc nãy được là do mình chuyển qua `en` trước khi gõ :((

**Comment by hieutkt** [comment]
Mình đoán cái Pop Launcher nó không phải là một cái X-window như bình thường mà là một lớp overlay nên không dùng cái `InputModeMapping` kia với nó được. 

Nó sẽ thừa hưởng thuộc tính của cái cửa sổ nào đang được focus. Ví dụ nếu mình thêm `Emacs` vào danh sách loại trừ, thì nếu mình bật launcher khi đang dùng Emacs, ibus sẽ bỏ qua cái launcher, như thể đang bỏ qua Emacs.

**Comment by luongthanhlam** [comment]
> Mình đoán cái Pop Launcher nó không phải là một cái X-window như bình thường mà là một lớp overlay nên không dùng cái InputModeMapping kia với nó được.
> 
> Nó sẽ thừa hưởng thuộc tính của cái cửa sổ nào đang được focus. Ví dụ nếu mình thêm Emacs vào danh sách loại trừ, thì nếu mình bật launcher khi đang dùng Emacs, ibus sẽ bỏ qua cái launcher, như thể đang bỏ qua Emacs.

đúng rồi bạn, lỗi này tương tự lỗi khung Overview của gnome. Có điều pop OS chưa có API để kiểm tra trạng thái cửa sổ launcher nên ko làm tương tự được
