### ISSUE TITLE
Hỗ trợ bỏ dấu kiểu mới

### ISSUE THREAD

**Issue by Huy-Ngo** [BambooEngine/ibus-bamboo#325]
Hiện tại bộ gõ bamboo đang bỏ dấu theo kiểu cũ (òa, òe, ùy) thay vì kiểu mới (oà, oè, uỳ). Nên có thêm tùy chọn để có thể bỏ dấu theo kiểu mới

Xem thêm: [Quy tắc đặt dấu thanh trong chữ quốc ngữ](https://vi.wikipedia.org/wiki/Quy_t%E1%BA%AFc_%C4%91%E1%BA%B7t_d%E1%BA%A5u_thanh_trong_ch%E1%BB%AF_qu%E1%BB%91c_ng%E1%BB%AF)

**Comment by luongthanhlam** [comment]
bạn vào cài đặt của bộ gõ, bỏ chọn "Dấu thanh chuẩn" là gõ được nhé

**Comment by Huy-Ngo** [comment]
cho mình hỏi phiên bản bao nhiêu có tính năng này nhỉ? Hiện tại mình đang dùng bản 0.7.0 không mở được cài đặt
![ibus setup](https://user-images.githubusercontent.com/19296926/162465478-d6bc476d-8750-4b75-acbb-b862ffafb593.png)

**Comment by luongthanhlam** [comment]
<img width="424" alt="Screen Shot 2022-04-08 at 21 58 11" src="https://user-images.githubusercontent.com/26364140/162467526-35d5d154-5337-4713-b947-18b83d3cd47f.png">

bạn xem trong hình nhé

**Comment by Huy-Ngo** [comment]
cám ơn nhé, mình sẽ báo bên distro để update
