### ISSUE TITLE
[Arch] Shift +  ~ không hoạt động trên Alacritty Terminal + không gõ được tiếng việt

### ISSUE THREAD

**Issue by mngnt** [BambooEngine/ibus-bamboo#326]
**Distro:** Arch
**DE**: KDE (X11)
**Terminal**: Alacritty
- không dùng được gõ tiếng việt trên Alacritty dù đã bấm Shift + ~
- Đã add
> export GTK_IM_MODULE=ibus
> export QT_IM_MODULE=ibus
> export XMODIFIERS=@im=ibus
> export QT4_IM_MODULE=ibus
> export CLUTTER_IM_MODULE=ibus
> ibus-daemon -drx

vào /etc/profile

**Comment by luongthanhlam** [comment]
bạn có cài Alacritty từ snap không? nếu có bạn gỡ ra và cài lại qua ppa nhé. Hiện tại Alacritty vẫn còn 1 số lỗi với ibus chưa fix https://github.com/alacritty/alacritty/issues/1613
