### ISSUE TITLE
ko go tieng viet dc

### ISSUE THREAD

**Issue by MizuharaKazuto** [BambooEngine/ibus-bamboo#327]
minh khong go dc tieng viet ai giup minh voi @@

**Comment by nguyenhai97** [comment]
Thử cái này chưa bạn https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

**Comment by MizuharaKazuto** [comment]
> Thử cái này chưa bạn https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

thu roi bn @@

**Comment by luongthanhlam** [comment]
bạn còn bị lỗi này chứ?
