### ISSUE TITLE
Lỗi font khi gõ tiếng việt trên trinh duyệt Edge

### ISSUE THREAD

**Issue by tab87vn** [BambooEngine/ibus-bamboo#328]
**Mô tả lỗi**
Lỗi font khi gõ tiếng việt trên trinh duyệt Edge

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở trình duyệt edge, vào các ứng dụng web (messenger, zalo, web form, etc.) hoặc trên thanh địa chỉ
2. Gõ 1 dòng tiếng việt bất kỳ, ví dụ "tiếng việt"
3. Chữ hiện ra là "tieêngếng vieêtệt"

**Kết quả mong muốn**
Đúng ra phải hiện ra "tiếng việt"

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: bản mới nhất là 0.8.1

**Comment by quocthinhle** [comment]
minhình cuũng biị tuoương tuưự =))) nhinìn minhình goõ laà hieêuểu hehehe

**Comment by quocthinhle** [comment]
tieếng vieêệt

**Comment by luongthanhlam** [comment]
bạn nhấn `Shift ~` và chọn kiểu gõ phù hợp nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#chuy%E1%BB%83n-sang-ch%E1%BA%BF-%C4%91%E1%BB%99-g%C3%B5-kh%C3%A1c
