### ISSUE TITLE
Lặp 3 lần giao diện trên Lubuntu 20.04 LTS

### ISSUE THREAD

**Issue by TianHuijun** [BambooEngine/ibus-bamboo#329]
**Mô tả lỗi**

Bị lặp 3 lần giao diện trên Lubuntu 20.04.4 LTS (bản Lubuntu 22.04 LTS cũng vậy)

**Các bước tái hiện lỗi**

Ví dụ:
1. Cài Lubuntu 20.04.4 LTS (tải trên https://lubuntu.me/downloads/)
2. Cài ibus-bamboo theo: https://github.com/BambooEngine/ibus-bamboo#ubuntu-v%C3%A0-c%C3%A1c-distro-t%C6%B0%C6%A1ng-t%E1%BB%B1
3. Dùng lệnh `ibus-daemon -drx` trên terminal (vì không ibus restart được)
4. Bấm vào biểu tượng (như hình bên dưới) ở thanh task bar
 ![img](https://i.imgur.com/btAejRd.png)
5. Thấy xuất hiện 3 lần giao diện như này (Tức là phải bấm 3 lần vào `Vietnamese - Bamboo` thì nó mới đóng giao diện)
![img](https://i.imgur.com/llfa9NI.png)

**Kết quả mong muốn**

Không muốn bị lặp 3 lần giao diện 

**Môi trường**
 - OS và version: Lubuntu 20.04.4 LTS
 - Desktop: LXQt
 - Phiên bản ibus-bamboo: bản mới nhất 0.8.1

**Comment by Someone8859** [comment]
Mình cũng bị như vậy nha, nhưng nó không có gì là quá khó chịu cả. Trước hết bỏ qua và đợi đội ngũ khắc phục.

**Comment by luongthanhlam** [comment]
lỗi ibus hoặc Lxqt rồi, bạn report cho upstream nhé https://github.com/ibus/ibus/issues

**Comment by Someone8859** [comment]
Chắc là ibus thì dùng gtk mà bạn dùng qt thì đôi chỗ nó không tương thích rồi. LXQt (trên Lubuntu) dùng nhiều cái có thể không tương thích với gtk lắm.
