### ISSUE TITLE
Vị trí Emoji không thay đổi sau lần đầu tiên sử dụng

### ISSUE THREAD

**Issue by ngcngmnh** [BambooEngine/ibus-bamboo#33]
**Mô tả lỗi**
Vị trí Emoji không thay đổi sau lần đầu tiên sử dụng

**Các bước tái hiện lỗi**
1. Mở Firefox
2. Gõ trên Github, Facebook
3. Gõ :
4. Thấy emoji ở vị trí gõ
5. Thay đổi vị trí gõ : 
6. Thấy emoji vẫn ở vị trí cũ

**Kết quả mong muốn**
Emoji xuất hiện ở vị trí gõ mới

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Vị trí ban đầu
![lần1](https://user-images.githubusercontent.com/43900679/57296327-f10df400-70f6-11e9-8b79-fae2eb5c2088.png)

Sau khi đổi vị trí gõ
![lần2](https://user-images.githubusercontent.com/43900679/57296328-f408e480-70f6-11e9-9227-59d62ad4e979.png)

**Môi trường**
 - OS: Manjaro Linux 18.0.4 Illyria
 - Kernel: x86_64 Linux 5.1.0-1-MANJARO
 - DE: KDE 5.57.0 / Plasma 5.15.4
 - Phiên bản ibus: 1.5.20
 - Phiên bản ibus-bamboo: v0.4.7

**Comment by luongthanhlam** [comment]
đã fix, bạn cập nhật lên 0.4.8 nhé
