### ISSUE TITLE
Tạo gói .deb (cho debian), .rpm (cho fedora) và PKGBUILD (cho arch) 

### ISSUE THREAD

**Issue by hahahahacker2009** [BambooEngine/ibus-bamboo#330]
Các hệ điều hành khác nhau sẽ có thể dùng repo khác nhau. Bạn nên cung cấp dưới dạng .deb, .rpm và PKGBUILD để tạo ra sự tiện lợi cho người dùng vì họ có thể không muốn cài repo ở nơi khác vào máy.

**Comment by nguyenhai97** [comment]
Ibus-bamboo có dùng Open Build Service để build cho các distro khác rồi mà. PKGBUILD tự viết khá đơn giản ai cũng làm được, rpm thì có thể dùng copr của fedora để build (mình có tạo ở đây https://copr.fedorainfracloud.org/coprs/ndhai/ibus-bamboo/) ubuntu thì không dùng nên không có ý kiến gì thêm
