### ISSUE TITLE
không viết được Tiếng Việt trong Discord

### ISSUE THREAD

**Issue by yuukiAme** [BambooEngine/ibus-bamboo#333]
**Mô tả lỗi**

không viết được Tiếng Việt với ibus-bamboo trong Discord
mình cài đặt theo hướng dẫn của trang gitbut của dev.

**Các bước tái hiện lỗi**

1. Mở Discord
2. chỉnh viết Tiếng = ibus-bamboo
3. viết tiếng Việt. 
...
5. toàn chữ không dấu

**Kết quả mong muốn**
viết tiếng việt ra dấu như mình đang viết trên Firefox và Github

**Môi trường**
 - OS và version: Fedora 36
 - Desktop: Gnome 42
 - Phiên bản ibus-bamboo: 0.8.1)

**Thông tin thêm**
Discord download từ Flatpak
cài đặt ibus-bamboo từ OpenBuildService

trước khi cài đặt ibus-bamboo, mình có dùng keyboard trong setting của gnome thêm vào

> Vietnamese (telex(m17n)

để viết trong Discord. Nhưng bây giờ mình không có cách nào viết tiếng Việt vào trong Discord ngoài Copy and Paste.

**Comment by quocthinhle** [comment]
minình thiị biị loôỗi oơở Chrome

**Comment by yuukiAme** [comment]
@quocthinhle bạn cũng dùng Fedora hả?

**Comment by luongthanhlam** [comment]
@yuukiAme bạn thử gỡ bản flatpak và cài lại từ repository nhé https://itsfoss.com/install-discord-fedora/

@quocthinhle bạn có thể nhấn Shift+~ và chọn chế độ gõ khác thử xem

**Comment by yuukiAme** [comment]
@luongthanhlam cài lại Discord từ RPM dùng được tiếng Việt như thường. Vậy là [Solved] rồi. Cám ơn bạn nhiều.

**Comment by quocthinhle** [comment]
> @yuukiAme bạn thử gỡ bản flatpak và cài lại từ repository nhé https://itsfoss.com/install-discord-fedora/
> 
> @quocthinhle bạn có thể nhấn Shift+~ và chọn chế độ gõ khác thử xem

Không dc bạn ơi, mình mới xài ubuntu chưa rành lắm hic, hình như user hiện tại chưa có quyền thì phải, mình chạy thử cat ~/config/ibus/bus thì không có gì cả.

**Comment by luongthanhlam** [comment]
> > @quocthinhle bạn đã thử những chế độ gõ nào rồi? bạn có thể gửi video để mô tả lỗi rõ hơn không
> 
> ![image](https://user-images.githubusercontent.com/55595623/167453454-a21388d0-c35c-416c-9483-058d0118aa98.png) minh thu ca 6 roi a, van bi loi

bạn thử chế độ gõ số 1 nhé

**Comment by quocthinhle** [comment]
vaâẫn biị nhuư naày aạ

**Comment by quocthinhle** [comment]
co moi google Chrome la bi loi thoi a, nhan chronium nhu Microsoft Edge cung khong bi

**Comment by luongthanhlam** [comment]
bạn tạo giúp mình issue mới nhé, lỗi này xảy ra ở tất cả trang hay chỉ ở thanh tiêu đề?
