### ISSUE TITLE
Phím tắt khôi phục phím dùng để làm gì ?

### ISSUE THREAD

**Issue by haoadoreorange** [BambooEngine/ibus-bamboo#334]
Mình thấy trong phần phím tắt có cho chọn phím tắt cho "Khôi phục phím" nhưng ko rõ dùng để làm gì ?
EDIT: nhân tiện cho mình hỏi luôn là kiểu gõ Telex W thì khác gì với Telex 2 ?

**Comment by luongthanhlam** [comment]
> Mình thấy trong phần phím tắt có cho chọn phím tắt cho "Khôi phục phím" nhưng ko rõ dùng để làm gì ?

phím tắt này khôi phục từ tiếng việt về tiếng anh (nguyên dạng), vd `hơ` -> `how`

> nhân tiện cho mình hỏi luôn là kiểu gõ Telex W thì khác gì với Telex 2 ?

Telex W là kiểu gõ telex bổ sung tính năng tự động chuyển w thành ư
Telex 2 là kiểu gõ telex bổ sung tính năng tự động chuyển w thành ư, `{` -> ơ, `}` -> ư

**Comment by haoadoreorange** [comment]
> phím tắt này khôi phục từ tiếng việt về tiếng anh (nguyên dạng), vd `hơ` -> `how`
Cảm ơn bạn. Nếu vậy phím này thì dùng cho trường hợp nào vậy bạn ? Vì khi mình dùng chế độ pre-edit (có gạch chân), bấm bất kì tổ hợp phím nào có ctrl hoặc alt hoặc super đều sẽ commit chữ đang gõ (mất gạch chân) chứ ko khôi phục phím.

Thêm nữa là cho mình hỏi có chỗ nào mình có thể đọc về các chế độ gõ khác nhau ko (khi nào thì dùng chế độ nào, khác nhau những gì ? Mình đang dùng pre-edit nhưng chế độ gõ này ko hoạt động tốt khi dùng để search trên gnome chẳng hạn (kí tự không được nhận cho đến khi commit nên kết quả không hiện lên lúc type), nên mình muốn tìm hiểu những chế độ khác.

**Comment by luongthanhlam** [comment]
> Cảm ơn bạn. Nếu vậy phím này thì dùng cho trường hợp nào vậy bạn ? Vì khi mình dùng chế độ pre-edit (có gạch chân), bấm bất kì tổ hợp phím nào có ctrl hoặc alt hoặc super đều sẽ commit chữ đang gõ (mất gạch chân) chứ ko khôi phục phím.

bạn thử đặt phím tắt là `Shift`+`Space` xem

> Thêm nữa là cho mình hỏi có chỗ nào mình có thể đọc về các chế độ gõ khác nhau ko (khi nào thì dùng chế độ nào, khác nhau những gì ? Mình đang dùng pre-edit nhưng chế độ gõ này ko hoạt động tốt khi dùng để search trên gnome chẳng hạn (kí tự không được nhận cho đến khi commit nên kết quả không hiện lên lúc type), nên mình muốn tìm hiểu những chế độ khác.

cái này không có công thức chung đâu bạn, mỗi ứng dụng hoặc version sẽ phù hợp với từng chế độ gõ khác nhau
