### ISSUE TITLE
Con trỏ chuột bị dính (như kiểu ấn insert) ở terminal 

### ISSUE THREAD

**Issue by minhnb11** [BambooEngine/ibus-bamboo#336]
**Mô tả lỗi**
con trỏ chuột bị dính, chữ đầu tiên bị mất 

**Các bước tái hiện lỗi**

1. cài ibus-bamboo
2. mở terminal 
3. nếu tương tác với terminal thường xuyên thì sẽ không có lỗi. 

**Kết quả mong muốn**

không bị mất chữ đầu tiên. 

**Ảnh chụp màn hình, hoặc clip quay màn hình**

[![issue.png](https://i.postimg.cc/5yrL82T7/issue.png)](https://postimg.cc/y3FDHsVc)

**Môi trường**
 - OS và version: S: Kali GNU/Linux Rolling x86_64 (5.16.0-kali7-amd64) 
 - Desktop: DE: Xfce 4.16 
 - Phiên bản ibus-bamboo:  0.8.1

**Thông tin thêm**
đã thử cài tất cả các cách đều bị lỗi, cài ibus-unikey thì không bị.

**Comment by minhnb11** [comment]
mình đã thử thay đổi định dạng cursor, nhưng vẫn không thay đổi gì cả. 
[![cursor.png](https://i.postimg.cc/qRwMPDG2/cursor.png)](https://postimg.cc/HcJg52RL)

**Comment by luongthanhlam** [comment]
bạn có thể mô tả lỗi rõ hơn không? như hình trên kia thì terminal đang gợi ý command chứ đâu phải dính chữ nhỉ?

**Comment by minhnb11** [comment]
mình cho terminal vào danh sách loại trừ. sau đõ gõ lệnh bình thường. ví dụ id-> nó sẽ nhận id, nhưng khi alt+tab đi tương tác với các ứng dụng khác, như chrome web... back về lại  terminal, lúc này nếu gõ chữ id -> nó sẽ tự động đẩy chữ i về phía sau con trỏ chuột, và nhận chữ d vào terminal, --> phải xóa gõ lại, hoặc click chuột phải -> chuột trái rồi gõ lại bth.

**Comment by minhnb11** [comment]
có lẽ tiêu đề hơi nhầm lẫn, thành thật xin lỗi bạn. Lỗi ở trên sẽ hết nếu mình gỡ cài đặt ibus-bamboo, dùng ibus-unikey.

**Comment by minhnb11** [comment]
https://drive.google.com/file/d/1ug_GczDrHN-kxiqoKPPaby-pWWTUMpU_/view?usp=sharing  đoạn nó lỗi là đoạn 3:20s ạ, lỗi này chỉ gây khó chịu khi phải gõ lại câu lệnh thôi. mình vẫn dùng bình thường, nhưng dùng terminal nhiều gặp nhiều lần nên hơi phiền chút

**Comment by luongthanhlam** [comment]
bạn bật tùy chọn `Bắt sự kiện chuột` xem có hết không?

**Comment by minhnb11** [comment]
Mình thử rồi nhưng không hết ạ

**Comment by minhnb11** [comment]
:D mình thử cài lại kali xfce, cài lại ibus-unikey 0.8.0 cho debian testing rồi mà vẫn bị lỗi này. :(

**Comment by luongthanhlam** [comment]
mình cài kali từ máy ảo vẫn không tái hiện được lỗi này :&

**Comment by minhnb11** [comment]
mình vừa test ở máy ảo, cũng chưa tái hiện được lỗi, để cuối tuần mình thêm thời gian test kĩ phần máy ảo thử. phần máy thật mình đã buil từ source, thử mọi cách cài. chọn các setting khác nhau *(bamboo/bamboo US layout) thì vẫn bị. dùng ibus-unikey thì hết.

**Comment by minhnb11** [comment]
có thể nó xung đột với các tool mình đang xài ở máy thật. cái này để mình test kĩ lại phần máy ảo. cài thêm từng tool để xem thử xung đột với cái nào, rồi có gì mình báo lại.

**Comment by kien-manabie** [comment]
Mình cũng bị lỗi này, mặc dù thêm vào danh sách loại trừ rồi nhưng vẫn bị.
Mình dùng **konsole** trên ubuntu 22.04, GNOME 42, xorg

**Comment by minhnb11** [comment]
> Mình cũng bị lỗi này, mặc dù thêm vào danh sách loại trừ rồi nhưng vẫn bị. Mình dùng **konsole** trên ubuntu 22.04, GNOME 42, xorg

=)) đó đến giờ mình sống chung với lũ thôi bạn ạ.

**Comment by googlesky** [comment]
Mình đang trên Manjaro KDE dùng bản lastest và mình xác nhận có lỗi này. Chuyển sang dùng Chế độ gõ mặc định số 3 là hết.

**Comment by phamtruc-work** [comment]
Hiện mình đang sử dụng arch linux cùng konsole ver 23.08.1 và ibus-bamboo ver 0.8.3 và hiện đang cùng bị lỗi như này khi con trỏ chuột bị dính ở đầu dòng trong terminal của konsole. Khi dùng các layout khác của ibus thì không bị nhưng gặp vấn đề này với ibus-bamboo

**Comment by luongthanhlam** [comment]
mình có bị 1 lần nhưng thử lại thì không tái hiện được nữa, có bạn nào biết cách tái hiện lỗi này không nhỉ?

**Comment by goatastronaut0212** [comment]
Mình có xem video và thấy nó khá là kỳ quặc. Nhưng mình không dám chắc đây có phải là 1 lỗi hợp lệ của ibus-bamboo lắm, mình sẽ dành thời gian để tìm hiểu nó sau.

Không biết là có môi trường nào có thể tái hiện lại lỗi này 100% nhỉ.

**Comment by minhnb11** [comment]
mình đang xài bamboo 0.8.2 nhưng lâu rồi mình để ý không còn gặp tình trạng trên nữa, hoặc do xfce update, hoặc do tool update. nếu còn gặp lại bug thì mình sẽ reopen và note lại thông tin chi tiết sau. xin cảm ơn mọi người.

**Comment by YoungHug** [comment]
cho mình hỏi , của mình nó ko hiện chuột thì làm sao để hết vậy ạ
