### ISSUE TITLE
Không hiển thị hộp thoại Chọn chế độ gõ/Ds loại trừ trong một số ứng dụng.

### ISSUE THREAD

**Issue by MeowIce** [BambooEngine/ibus-bamboo#337]
**Mô tả lỗi**

`ibus-bamboo` không hiển thị hộp thoại để chọn cđ gõ/ds loại trừ trên một số ứng dụng.
**Các bước tái hiện lỗi**

1. Mở chương trình có chứa khu vực nhập liệu (ví dụ `gnome-terminal` hoặc `libreoffce`).
2. Bấm tổ hợp `Shift` + `~`.
3. Hộp thoại chọn Chế độ gõ không hiển thị.

**Kết quả mong muốn**
`ibus-bamboo` hiển thị hộp thoại chọn chế độ gõ khi bấm tổ hợp `Shift` + `~`.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Không có.

**Môi trường**
 - OS và version: Fedora 36 Workstation Edition
 - Desktop: GNOME 42.0
 - Phiên bản ibus-bamboo: 0.8.1

**Thông tin thêm**
Lỗi này xuất hiện nhiều hơn trong môi trường Wayland. X11 có hiển thị ở hầu hết các ứng dụng/chương trình.

**Comment by lnn2204** [comment]
Mình cũng đang dính lỗi này, Gnome-Terminal của Ubuntu 22.04 LTS.
