### ISSUE TITLE
Cập nhật bamboo-core để bắt kịp source của ibus-bamboo

### ISSUE THREAD

**Issue by hmtheboy154** [BambooEngine/ibus-bamboo#338]
Xin chào, hôm nay mình vừa mới chat với  @wengxt, tác giả của fcitx5 và có nhắc đến chuyện đưa bamboo lên fcitx5. Vấn đề mà Weng bảo mình là repo [bamboo-core](https://github.com/BambooEngine/bamboo-core/commits/master) hiện tại bị chậm hơn so với [bamboo-core trong ibus-bamboo](https://github.com/BambooEngine/ibus-bamboo/commits/master/src/github.com/BambooEngine/bamboo-core). Weng đã chuẩn bị một bản port bamboo lên fcitx5 rồi nhưng chưa ra mắt vì lí do trên.

Vậy nên mong tác giả có thể kéo repo bamboo-core cho bằng với ibus-bamboo, và để có thể dễ dàng quản lí hơn thì có thể sử dụng `git submodule`. 

Anh ấy cũng tạo Issue ở bamboo-core năm ngoái https://github.com/BambooEngine/bamboo-core/issues/2

**Comment by luongthanhlam** [comment]
Cám ơn bạn, mình không để ý có issue bên đó 😵‍💫

**Comment by luongthanhlam** [comment]
đã update code
