### ISSUE TITLE
Góp ý về kiểu gõ Microsoft

### ISSUE THREAD

**Issue by lehboi** [BambooEngine/ibus-bamboo#339]
Cảm ơn tác giả đã tạo ra sản phẩm hữu ích này!
Xin góp ý với tác giả: tên chính thức của kiểu gõ Microsoft nên đặt là TCVN 5712. Đó là tài liệu do Tổng cục Tiêu chuẩn Đo lường Chất lượng ban hành năm 1993 về bố trí bàn phím Việt Nam, và Microsoft đã áp dụng tiêu chuẩn đó vào Windows. Gọi đúng tên để tôn trọng TCTCĐLCL. Trong tiêu chuẩn đó còn quy định dấu tiền đồng '₫'  ở vị trí phím '=' trong bàn phím US, nhờ tác giả thêm dấu này vào Bamboo.
Cảm ơn tác giả!

**Comment by luongthanhlam** [comment]
Ý bạn là TCVN 6064:1995, kiểu gõ này hơi khác kiểu gõ Microsoft một chút https://vi.wikipedia.org/wiki/TCVN_6064:1995

**Comment by lehboi** [comment]
À, tôi định nói đến TCVN 6064.
Gõ dấu tiền đồng trong kiểu gõ Microsoft của iBus Bamboo như thế nào vậy tác giả?

**Comment by luongthanhlam** [comment]
dấu tiền đồng là kí tự đặc biệt chứ không phải kí tự nằm trong bảng chữ cái nên mình không cho vào kiểu gõ này. Nếu muốn bạn có thể bật chức năng gõ tắt và thêm dòng này vào cuối file gõ tắt
```
=:₫
```
