### ISSUE TITLE
Xorg client được tạo ra khi bật/tắt bộ gõ.

### ISSUE THREAD

**Issue by ndgnuh** [BambooEngine/ibus-bamboo#34]
**Mô tả lỗi**
Như tiêu đề mô tả.

**Các bước tái hiện lỗi**
Bật tắt bộ gõ rất nhiều lần (khoảng 700 lần?), có thể dùng `vim` hoặc một bash script để thực hiện.
```sh
# Cách này chưa test đâu
for i in {1..700}; do
  ibus engine Bamboo
  ibus engine xkb:us::eng
done
```

**[Ảnh chụp màn hình, hoặc clip quay màn hình](https://youtu.be/4ni1TEfeuqY)**

**Môi trường**
 - OS và version: Void Linux
 - Desktop: `awesome`
 - Phiên bản ibus: 1.5.20
 - Phiên bản ibus-bamboo: 0.4.7

**Thông tin thêm**
*Workaround khi bị "kẹt":*
Nhần `Ctrl + Alt + F2` để vào tty2, đăng nhập và chạy (nếu đang có terminal mở sẵn thì có thể chạy luôn, hoặc bạn có thể tắt bớt một cửa sổ đi và mở terminal):
```sh
killall ibus-daemon
```
Edit: cách toggle nguyên cái daemon không tốt, nó spawn một đống process của `ibus-engine-bamboo`.

**Comment by luongthanhlam** [comment]
đã fix cho bản 0.4.8 :dancer:

**Comment by ndgnuh** [comment]
Đã test với 999 lần toggle, không xảy ra lỗi. :clap:
