### ISSUE TITLE
Lỗi gõ tiếp sau chữ cái 'u'

### ISSUE THREAD

**Issue by ducthaidev** [BambooEngine/ibus-bamboo#340]
**Mô tả lỗi**
Không gõ đuoc tiếp 'o' sau chu 'u'. VD chu 'uong' thành 'u' không thể gõ tiếp. 

**Các bước tái hiện lỗi**
Bật chrome, gõ trên thanh địa chỉ chu 'uống'.

**Môi trường**
 - OS và version: Pop OS 22.04 lts
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: bản mới nhất là 0.8.1

**Comment by MeowIce** [comment]
Bạn thử chuyển sang chế độ gõ số 4 thử đi

**Comment by ducthaidev** [comment]
> Bạn thử chuyển sang chế độ gõ số 4 thử đi

Không đuoc bạn à mình vẫn bị lỗi đó

**Comment by ducthaidev** [comment]
https://github.com/BambooEngine/ibus-bamboo/issues/316
