### ISSUE TITLE
bỏ qua một số app VD: terminal 

### ISSUE THREAD

**Issue by longtth** [BambooEngine/ibus-bamboo#344]
hi các bạn, 
cám ơn đã tạo ra và duy trì 1 bộ gõ tiếng Việt cho linux 

cho mình hỏi có cách gì config để ignore một số app không nhỉ? ví dụ: terminal 
thường khi gõ trong terminal mình sẽ hiếm khi cần gõ tiếng Việt, nhưng lúc này phải thêm 1 thao tác tắt bộ gõ, 
có cách gì để ibus bamboo tự nhận diện đang focus vào terminal và chuyển sang chế độ tắt bộ gõ không ?

**Comment by huyxdong** [comment]
Mình đang dùng Debian 12, trong cái Terminal của Debian 12 thì không tài nào gọi cái phần chọn số 7 để ignore ibus bamboo đấy lên được, ở app khác ví dụ như VSCode thì được. 
Nhờ bạn kiểm tra giúp nhé.
