### ISSUE TITLE
Không thể tùy chỉnh phím tắt chuyển chế độ gõ giống Unikey

### ISSUE THREAD

**Issue by huynp1999** [BambooEngine/ibus-bamboo#345]
**Mô tả lỗi**
Mình muốn đổi từ `Super+Space` thành `Ctrl+Shift` để cho đồng bộ với Unikey của Windows thì tổ hợp phím không hoạt động.

**Các bước tái hiện lỗi**

![image](https://user-images.githubusercontent.com/83684068/177138897-96c3a934-fe9d-4b69-aa4b-0b23595dcce3.png)

Tùy chỉnh theo trên hình và ấn lưu. Thực hiện tổ hợp phím `Ctrl+Shift` nhưng chế độ gõ không tự động chuyển từ `vi` sang `en`, hoặc ngược lại.

**Kết quả mong muốn**
Tùy chỉnh được phím tắt chuyển chế độ gõ thành `Ctrl+Shift`

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.8.0

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn trang này nhé https://topthuthuat.com/cach-cai-dat-bo-go-tieng-viet-ubuntu/

![ibus](https://topthuthuat.com/images/Ubuntu/go_tieng_viet_unikey_ibus_5.png)

**Comment by huynp1999** [comment]
Trong bài viết là Ubuntu 14. Ubuntu 20 ko còn ứng dụng nào tên `Text entry` nữa, và mình không tìm thấy cách nào khác ngoài vào mục này để sửa hotkey.
![image](https://user-images.githubusercontent.com/83684068/177232378-fc088255-ecc3-4ec6-baaf-69688dc53b9c.png)

Mình đã tìm được giải pháp khác, tuy nhiên đổi thành `ctrl+shift` sẽ bị conflict với `ctrl+shift+T` mà mình hay dùng, nên thôi lại dùng mặc định vậy =(( hơi buồn linux
