### ISSUE TITLE
Không gõ được tiếng Việt khi chỉnh ozone platform về auto/wayland

### ISSUE THREAD

**Issue by lamndl** [BambooEngine/ibus-bamboo#346]
**Mô tả lỗi**
Không gõ được tiếng Việt khi chỉnh ozone platform về auto/wayland trên các trình duyệt lõi chromium

**Các bước tái hiện lỗi**:
1. Vào chrome://flags/ trên chrome hoặc brave://flags/ trên brave
2. Tìm và chỉnh "Preferred Ozone platform" về Auto
3. Không gõ được tiếng Việt nữa

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2022-07-04 23-23-26](https://user-images.githubusercontent.com/29592868/177192870-f3bdf109-90f2-4545-9cf3-a3f01847259f.png)

**Môi trường**
 - OS và version: Fedora 36
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.8.1

**Thông tin thêm**

**Comment by luongthanhlam** [comment]
bạn thử chạy chrome với `--gtk-version=4` xem, https://bugs.chromium.org/p/chromium/issues/detail?id=1183262

**Comment by lamndl** [comment]
Mình chạy thử và bị lỗi như sau
```
ClumsyOnce@fedora ~]$ google-chrome --gtk-version=4
[28055:28055:0705/115219.356884:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is egl, ANGLE is
```
Có lẽ đây là lỗi của chrome, do có nhiều lỗi nên mình đành phải chỉnh "Preferred Ozone platform" về default . Mọi thứ lại chạy bình thường

**Comment by luongthanhlam** [comment]
bạn theo dõi ở đây https://bugs.chromium.org/p/chromium/issues/detail?id=1183262
