### ISSUE TITLE
Hướng dẫn build Ibus-Bamboo trên FreeBSD

### ISSUE THREAD

**Issue by zenfas** [BambooEngine/ibus-bamboo#347]
Hiện trên FreeBSD chỉ có thể gõ tiếng Việt thông qua ibus-m17n hoặc fcitx-m17n, nhờ tác giả hỗ trợ hướng dẫn để build và dùng được trên FreeBSD

**Comment by hopingstar1806** [comment]
@luongthanhlam Cũng không liên quan lắm nhưng mà mình cũng dùng OpenBSD và đang cố để làm nó hoạt động trên đây.
Mình cần được giúp đỡ khi làm cho nó hoạt động trên OpenBSD. Về cơ bản là mình đã build nó thành công nhưng mà mình loay hoay mãi vẫn không làm nó hoạt động được.  Mình không hiểu sao mỗi lần mình chuyển sang bộ gõ tiếng Việt thì nó chỉ xuất hiện 1 giây và sau đó ibus bị freeze và buộc mình phải restart ibus lại

Mã nguồn ở đây: https://github.com/hopingstar1806/ibus-bamboo

**Comment by tuanth66** [comment]
Tình hình sao rồi các bác. Em vẫn đang dùng cái có sẵn.

**Comment by s0m3sushi** [comment]
https://github.com/BambooEngine/ibus-bamboo/assets/30410170/9852edc9-bbb4-4b8c-9b25-2e6af5d8c811

Phiên bản của @goatastronaut0212 hoạt động tốt nhé, ngoại trừ khi sử dụng phần mềm thông qua Linuxulator. Mình đã thử set biến trong ``/compat/linux/etc/environment`` rồi nhưng không có gì thay đổi cả. Video trên cho thấy Chrome chạy qua Linuxulator và HandBrake chạy qua native.
Chuyển sang vt mình thấy ibus báo lỗi rằng chrome không hỗ trợ tính năng surrounding-text.

**Comment by goatastronaut0212** [comment]
> 2023-12-13.23-06-26.mp4
> 
> Phiên bản của @goatastronaut0212 hoạt động tốt nhé, ngoại trừ khi sử dụng phần mềm thông qua Linuxulator. Mình đã thử set biến trong `/compat/linux/etc/environment` rồi nhưng không có gì thay đổi cả. Video trên cho thấy Chrome chạy qua Linuxulator và HandBrake chạy qua native. Chuyển sang vt mình thấy ibus báo lỗi rằng chrome không hỗ trợ tính năng surrounding-text.

Cái đó mình sẽ cố gắng sửa sau. Lần cuối mình thử thì cũng còn 1 lỗi khá là ngớ ngẩn khi nó cứ lấy vị trí của chuột iên tục nếu như bạn gõ tiếng việt quá nhanh. Mình không rõ là bạn có gặp vấn đề đó không nhưng tình hình hiện tại là có thể 1 PR hoàn chỉnh sẽ còn khá là dài. Dù sao thì mình cũng sẽ quay lại làm tiếp.

**Comment by goatastronaut0212** [comment]
mình có update code bên repo mình rồi. Bạn có thể test giúp mình được không? Không biết bạn có gặp lỗi chuột không thể dùng được giống như mình không nên mình cần chắc chắn lại @s0m3sushi

**Comment by s0m3sushi** [comment]
![2023-12-15_1337x132](https://github.com/BambooEngine/ibus-bamboo/assets/30410170/d980bf07-737f-4253-aaa6-c70f9e877b4a)
Mình đang gặp lỗi này bạn nhé @goatastronaut0212

**Comment by goatastronaut0212** [comment]
Nó không nên xảy ra lỗi này. Nó bị gì đó khi cố lấy thư viện về trong thư mục `~/go`. bạn thử không đăng nhập vào người dùng root và thay vào bạn hãy đó thử dùng các phần cấp quyền khác `sudo` hoặc `doas` để chạy lại lệnh thử xem. @s0m3sushi

**Comment by s0m3sushi** [comment]
Mình đã thử ``doas`` rồi nhưng vẫn xảy ra lỗi này. Để mình thử rollback trở về snapshot hồi mình mới cài ``ibus`` xem sao.

**Comment by goatastronaut0212** [comment]
có lẽ hình như mình test lại có vẻ như dùng mỗi lệnh `sudo` là được còn `doas `với quyền root thì không. Có lẽ mình sẽ cần phải xem lại tại sao go module lại bị như vậy @s0m3sushi

**Comment by s0m3sushi** [comment]
Mình đã thử lại sau khi rollback và mình vẫn gặp lỗi đấy nhé, nếu mình chạy ``gmake install`` thông qua user thông thường thì code sẽ đc compile như bình thường, nhưng sẽ fail khi nó cài các file như icon và json vì thiếu quyền của root. @goatastronaut0212

**Comment by goatastronaut0212** [comment]
@s0m3sushi  Nó có vẻ không phải là lỗi của mình để mình sửa, đó có vẻ là tính năng của Go module rồi. Về cơ bản bạn có thể cung cấp cho git với option [safe] cho directory chứa đường dẫn source code để build trong `.gitignore` ở thư mục `/home/root` để build thành công cho `doas` và root user. Có lẽ sudo tuy được cấp quyền nhưng việc nó quản lý vẫn ở thư mục home của bạn còn doas sẽ giống như root mọi thứ sẽ nằm trong thư mục `/home/root` của nó. Nếu không muốn phải động tay vô cái thư mục `/home/root` thì việc còn lại chỉ là tách Makefile ra 2 quá trình khác nhau thôi

`gmake build` sẽ build mà không cần quyền.

còn `gmake install` sẽ không còn build nữa mà chỉ là install thôi với quyền root là xong rồi.

**Comment by s0m3sushi** [comment]
https://github.com/BambooEngine/ibus-bamboo/assets/30410170/a4e900f2-db2d-427a-9975-f7e0660aed9b

Mình ``su`` sang root rồi cài từ đấy, có vẻ cách này đã khắc phục vấn đề build. Mình đang thấy vấn đề liên quan đến chuột mà bạn nhắc đến. Chuột bấm không hề register một tí gì luôn.

**Comment by s0m3sushi** [comment]
https://github.com/BambooEngine/ibus-bamboo/assets/30410170/dac244b4-3403-42dc-a293-21520b8b7e4b

Mình test thử trong Minecraft chạy native cho FreeBSD qua ``openjdk17`` và có vẻ nó cũng không hoạt động trong đấy. Mình nghĩ có thể cái này cần set thêm biến cho Java hoặc là cùng một vấn đề với Chrome.

**Comment by goatastronaut0212** [comment]
> @goatastronaut0212 bạn đã có tiến triển gì với cái này chưa nhỉ, không biết cái nhánh `go-module` của bạn đã dùng đc cho FreeBSD chưa?

Lần cuối mình thử nhánh `bsd-dev` có lẽ vẫn build ổn mà. Nhưng có lẽ bạn sẽ phải đợi cho đến khi PR `go-module` được merge vào (có thể là vào tháng 4 khi Ubuntu release 1 bản). Hiện tại mình cũng chưa có nhiều kiến thức về C và lập trình Unix nên mình cũng chưa thể tiếp tục công việc được. Chỉ có FreeBSD là build được nhưng chạy còn chưa ổn còn các BSD khác thì phải vọc khá là nhiều.

**Comment by goatastronaut0212** [comment]
> 2023-12-16.16-11-14.mp4 
> Mình `su` sang root, `git clone` từ đầu, rồi cài từ đấy, có vẻ cách này đã khắc phục vấn đề build. Mình đang thấy vấn đề liên quan đến chuột mà bạn nhắc đến. Chuột bấm không hề register một tí gì luôn. Mình vẫn chưa dùng đc `ibus` trên Chrome nhé. Chrome vẫn chưa nhận đc `ibus` và vẫn còn cái lỗi surrounding text.

À, mình quên note về cái vấn đề chuột này mình nghĩ chắc tạm thời tắt tính năng bắt sự kiện chuột của ibus-bamboo thì có vẻ sẽ trải nghiệm sẽ tốt hơn.

**Comment by superchick** [comment]
> Hiện trên FreeBSD chỉ có thể gõ tiếng Việt thông qua ibus-m17n hoặc fcitx-m17n, nhờ tác giả hỗ trợ hướng dẫn để build và dùng được trên FreeBSD

Tôi nghĩ là bạn nên tìm cách để build `fcitx-unikey` thì sẽ dễ hơn.

**Comment by goatastronaut0212** [comment]
Mình đã quay lại issue này. Mong là PR này https://github.com/BambooEngine/ibus-bamboo/pull/504 sẽ sớm được merge, chúng ta có thể sẽ hiện thực hóa việc gõ tiếng việt trên FreeBSD và issue này có thể đóng hoàn toàn. Có thể sẽ mất thêm 1 chút thời gian nữa để khiến lỗi sự kiện chuột không bị lỗi nữa.

**Comment by goatastronaut0212** [comment]
FreeBSD đã được hỗ trợ trên nhánh master nếu cón thêm báo cáo lỗi nào nữa các bạn có thể báo cáo thêm lại sau
