### ISSUE TITLE
Icon EN, VN không thay đổi

### ISSUE THREAD

**Issue by tea0112** [BambooEngine/ibus-bamboo#348]
**Mô tả lỗi**
Không thay đổi Icon từ EN sang VN và ngược lại sau khi đã thay đổi chế độ gõ

**Các bước tái hiện lỗi**
1. Meta+Space(thay đổi bộ gõ).
2. Bộ gõ đã thay đổi.
3. Icon chỉ thay đổi cho đến khi click vào một vùng để nhập input nào đó.

**Kết quả mong muốn**
Icon chuyển từ EN sang VN

**Môi trường**
 - OS và version: Manjaro
 - Desktop: Xfce
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Comment by luongthanhlam** [comment]
lỗi Xfce/ibus nhé bạn

**Comment by tea0112** [comment]
> lỗi Xfce/ibus nhé bạn

Bạn ơi tôi đang dùng manjaro KDE đây, vẫn vậy mà bạn. Nói chung họ nhà Arch luôn.

**Comment by luongthanhlam** [comment]
@tea0112  bạn có gặp lỗi này với ibus-unikey không? nếu không thì bạn vào cài đặt bộ gõ và tắt phím tắt "Chuyển chế độ gõ" xem

**Comment by tea0112** [comment]
> @tea0112 bạn có gặp lỗi này với ibus-unikey không? nếu không thì bạn vào cài đặt bộ gõ và tắt phím tắt "Chuyển chế độ gõ" xem

Không được bạn ạ với cả mình chỉ dùng ibus-bamboo thôi. Nó cũng chả anh hưởng gì đến khả năng gõ tiếng việt đâu nhưng mà nó cứ gây khó chịu khi phải ấn vào ô text nào đó mới thay đổi icon.

**Comment by luongthanhlam** [comment]
theo mình biết thì trên X11, ibus không được cấp quyền lắng nghe sự kiện từ bàn phím nếu người dùng không gõ trên 1 input text nào đó. Tuy nhiên, bạn có thể gán hotkeys của DE với lệnh chuyển bộ gõ của ibus
```
ibus engine xkb:us::eng # chuyển sang TA
ibus engine Bamboo # chuyển sang TV
```

**Comment by ngfuong** [comment]
> theo mình biết thì trên X11, ibus không được cấp quyền lắng nghe sự kiện từ bàn phím nếu người dùng không gõ trên 1 input text nào đó. Tuy nhiên, bạn có thể gán hotkeys của DE với lệnh chuyển bộ gõ của ibus
> 
> ```
> ibus engine xkb:us::eng # chuyển sang TA
> ibus engine Bamboo # chuyển sang TV
> ```
hi bac @luongthanhlam , cam on vi da support!
Co cach nao de bind 1 to hop key de toggle qua lai giua TA va TV khong nhi?
Nghia la chi dung 1 command, neu dang la TA thi chuyen sang TV, neu dang la TV thi chuyen sang TA ay a?
