### ISSUE TITLE
Menu lưu tùy chọn xổ ra thay vì ký tự '~' được chèn vào

### ISSUE THREAD

**Issue by hieuns** [BambooEngine/ibus-bamboo#35]
**Mô tả lỗi**
Menu lưu tùy chọn được xổ ra thay vì ký tự `~` được chèn vào khi cần gõ ký tự `~` bằng cách nhấn tổ hợp phím `Shift` + `` ` ``

**Các bước tái hiện lỗi**
1. Mở trình duyệt web
2. Nhấn vào text field/text area
3. Nhấn tổ hợp phím `Shift` + `` ` ``
4. Menu thông báo lưu tùy chọn xuất hiện thay vì ký tự `~` được chèn vào text field/text area

**Kết quả mong muốn**
Ký tự `~` được chèn vào text field/text area thay vì hiển thị menu lưu tùy chọn

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![tilde](https://user-images.githubusercontent.com/6816517/57899683-29949700-7888-11e9-9f01-fffa6210a020.gif)

**Môi trường**
 - OS và version: Ubuntu 16.04
 - Desktop: **mặc định**
 - Phiên bản ibus: IBus 1.5.11
 - Phiên bản ibus-bamboo: v0.4.7

**Thông tin thêm**
Cấu hình của ibus-bamboo khi gõ
- Bảng mã: Unicode
- Kiểu gõ: Telex
- Gõ tắt: không chọn
- Kiểm tra chính tả: Bật
- Cấu hình được chọn khác:
  - Bỏ dấu tự do
  - Dấu thanh chuẩn
  - Theo dõi chuột
  - Ẩn gạch chân
  - Sửa lỗi gạch chân

**Comment by ndgnuh** [comment]
[Bạn nhấn tổ hợp phím đó hai lần để chèn kí tự `~` nhé.](https://github.com/BambooEngine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng)

**Comment by hieuns** [comment]
Mình xin lỗi vì không đọc kỹ hướng dẫn :bow:. Cơ mà bạn có thể gắn chức năng này vào tổ hợp phím khác không liên quan đến việc chèn ký tự vào ô nhập liệu, chẳng hạn như `ctrl` + `` ` `` không, vì mình nghĩ khi cần gõ ký tự mà lại xuất hiện menu như vậy thì hơi khó hiểu và bất tiện một chút.

**Comment by ndgnuh** [comment]
Hiện tại tác giả bộ gõ chưa đưa ra tính năng này, tuy nhiên nếu muốn bạn có thể vá một ít mã nguồn để map lại cái menu theo ý mình muốn. 

Bạn tìm trong file `src/ibus-bamboo/ibus-const.go` dòng:
```go
IBUS_OpenLookupTable = IBUS_TILDE
```

và thay cái `IBUS_TILDE` bằng mã kí tự mình muốn. Kí tự ở đây có dạng `0x<mã unicode của kí tự>`. Ví dụ như ở một dòng khác trong file đó, tác giả định nghĩa `IBUS_TILDE` (dấu `~`) là `0x007e`. Mã unicode thì bạn có thể lấy ở [đây](https://unicode-table.com).

**Comment by hieuns** [comment]
Vâng, cảm ơn bạn nhé.

**Comment by luongthanhlam** [comment]
bản 0.5.1 mặc định sẽ tắt tổ hợp phím này.
