### ISSUE TITLE
Lỗi gõ tiếng việt trên chrome 

### ISSUE THREAD

**Issue by DinhSonpro12** [BambooEngine/ibus-bamboo#351]
**Mô tả lỗi**
khi gõ tiếng việt có dấu trên chrome thì chữ hiện thị như sau:

Xin chao ào minhình teên laà DĐinh Sonơn vaà minhình gaăpặp phaiải vvaânấn dđeêề khi goõ tieêngếng vieêtếtệt treên chrome.

**Các bước tái hiện lỗi**

1. Mở chrome.
2. Gõ tiếng việt.
3. Chữ hiển thị như trên mô tả lỗi.

**Kết quả mong muốn**
Khi gõ: xin chào bạn.
Đáng lẽ phải hiện thị: xin chào bạn
Thay vì: xin chao ào banạn.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
link youtube: https://youtu.be/lcen2BMAyC8

**Môi trường**
 - OS và version:Ubuntu 22.04.1 LTS
 - Desktop: mặc định
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Thông tin thêm**
- Lỗi chỉ xảy ra khi mình gõ tiếng Việt trên chrome, còn vs các trình duyệt firefox hay là app notepad thì hoàn toàn bình thường.

**Comment by TuanHAnhVN** [comment]
minh cung bi tuong tu, minh thi ko hien thi ky tu

**Comment by luongthanhlam** [comment]
bạn nhấn `Shift+~` để chuyển sang chế độ gõ khác nhé https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#chuy%E1%BB%83n-sang-ch%E1%BA%BF-%C4%91%E1%BB%99-g%C3%B5-kh%C3%A1c
