### ISSUE TITLE
Bị lỗi duplicate chữ trên facebook/messenger (Chrome)

### ISSUE THREAD

**Issue by kienmatu** [BambooEngine/ibus-bamboo#352]
**Mô tả lỗi**

Bị nhân đôi chữ trên messenger và facebook
**Các bước tái hiện lỗi**

Ví dụ:
1. Mở facebook.com
2. Gõ vào thanh tin nhắn "xin chào bạn"
3. Thấy "xin chào bạnbạn"

**Kết quả mong muốn**

Đáng lẽ phải thấy  "xin chào bạn"
**Ảnh chụp màn hình, hoặc clip quay màn hình**

![test loi ibus bamboo](https://user-images.githubusercontent.com/38078992/185027979-da0730b9-74c4-4bbd-bc40-a3b5fd7b14fa.gif)

**Môi trường**
 - OS và version: Ubuntu 22.04
 - Desktop: GNOME 42.2
 - Phiên bản ibus-bamboo: 0.8.1-0~202203200330~ubuntu22.04.1 amd64
**Thông tin thêm**

**Comment by luongthanhlam** [comment]
sống chung với lũ thôi bạn 😢 
facebook mỗi lần cập nhật là lại phát sinh lỗi mới, nếu không bạn thử đổi sang chế độ gõ khác xem https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#chuy%E1%BB%83n-sang-ch%E1%BA%BF-%C4%91%E1%BB%99-g%C3%B5-kh%C3%A1c

**Comment by nammon72** [comment]
đúngđúng là trên trình duyệt cũng bị. hiện tại mình đang còm mà còn dính double chữ lên nè bạn :(

**Comment by kien-manabie** [comment]
Lỗi này thì mình đã có thể fix được rồi.
Cách fix:
- Gõ Ctrl + ~
- Chọn chế độ gõ số 3:
![image](https://user-images.githubusercontent.com/106640702/187136983-7f441b33-361d-48d6-86d5-a75c9c1bf2dc.png)

Đánh đổi là tốc độ gõ sẽ chậm hơn, nhảy chữ chậm hơn xíu.

**Comment by binhbo12456** [comment]
bị cái này mà chưa có cách fix, nhắn tin cứ phải xóa chữ thừa khó chịu thật

**Comment by MeowIce** [comment]
> bị cái này mà chưa có cách fix, nhắn tin cứ phải xóa chữ thừa khó chịu thật 
> 

Mình không gặp hiện tượng này...

**Comment by huydangg** [comment]
mình cũng bị tương tự trên telegram

**Comment by MeowIce** [comment]
> mình cũng bị tương tự trên telegram

Bạn thử để chế độ số 4 xem sao ?

**Comment by haihn168** [comment]
mình cũng dính chưởng trên single box 

![image](https://user-images.githubusercontent.com/45808282/198930041-3757e87d-9699-4715-bd21-c604a0d643da.png)

**Comment by binhbo12456** [comment]
vẫn chưa có gì mới, pump lên cái

**Comment by kienmatu** [comment]
Lỗi này hình như không phải chỉ mỗi Linux bị thôi đâu, Windows mà là bộ gõ mặc định Telex theo OS cũng dính chưởng luôn, dùng Unikey hay EVKey thì hết.

**Comment by kienmatu** [comment]
Mình phát hiện bộ gõ này khá xịn, tuy nhiên phiên bản Linux lại chỉ có mỗi command line mà chưa có UI:
https://github.com/tuyenvm/OpenKey

**Comment by binhbo12456** [comment]
ảo thật nhỉ, lâu lắm rồi mình ko dùng windows nên cũng ko rõ, từ đợt nó lỗi tới giờ, nhắn tin trên chrome nó bị duplicate khó chịu quá nên mình chỉ nhắn telegram thôi chứ chrome thì chịu thua

**Comment by quantranhong1999** [comment]
Hi, lỗi này quay lại với bản 0.8.3 rồi ah.

**Comment by datleviet** [comment]
e mới dùng bamboo đc 1 tuần, lúc đầu rất ổn nhưng mấy hôm nay thì bị duplicate khi gõ trên trình duyệt (Brave).
dưới đây là một ví dụ:
---
goõ tuưừ naào cuũng biị heêết huhu

**Comment by tristankhiem** [comment]
minhình biị nhuư vayâyậy neè :(( coó dođoiỏi mode thuử roôiồi nhunưng vaâẫn biị

**Comment by linh-eureka** [comment]
Minhình dđang gaăpặp loôiỗi tuoương tuưự voơiới trinình duyeêệt Edge Latest Version 121.0.2277.128 (Official build) (64-bit), goõ thuưử treên chrome thiì vaâẫn binhình thuongươngờng.

**Comment by luongthanhlam** [comment]
@tristankhiem @linh-eureka các bạn nhấn `Shift+~` và chọn lại chế độ gõ nhé

**Comment by hdong69** [comment]
minhf cungx danđang biị vaà chuưa suưaả dđc

**Comment by luongthanhlam** [comment]
các bạn vào setting của bộ gõ, bật tùy chọn "Sửa lỗi lặp chữ trong Facebook" nhé.
@hdong69 bạn kiểm tra có đang tắt tùy chọn "Bỏ dấu tự do" không, nếu có thì bật lại sẽ hết lỗi này.

**Comment by quantranhong1999** [comment]
> các bạn vào setting của bộ gõ, bật tùy chọn "Sửa lỗi lặp chữ trong Facebook" nhé.

Mình 0.8.3 không thấy option này, version 0.8.4 rc mới có à b?

**Comment by luongthanhlam** [comment]
đúng rồ, bạn up lên v0.8.4 nhé

**Comment by quantranhong1999** [comment]
> đúng rồ, bạn up lên v0.8.4 nhé

Tks b nhe' :-)

**Comment by VietDucNg** [comment]
mình dùng chế độ gõ 6 thì ổn
