### ISSUE TITLE
keyring deprecation warning 

### ISSUE THREAD

**Issue by vuongkienthanh** [BambooEngine/ibus-bamboo#353]
Mình mới up lên linux mint 21. Mỗi lần apt update thì báo thế này:

W: http://ppa.launchpad.net/bamboo-engine/ibus-bamboo/ubuntu/dists/jammy/InRelease: 
Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn ở đây nhé https://tecadmin.net/resolved-key-is-stored-in-legacy-trusted-gpg-keyring/, nếu không được thì xóa ppa đi rồi add lại.
