### ISSUE TITLE
Muốn thay đổi phím setting. Hiện tại đang là (shift + ~)

### ISSUE THREAD

**Issue by willriver-dev** [BambooEngine/ibus-bamboo#355]
**Mô tả lỗi**

Hiện tại gõ ký tự ~ thì hiện ra bảng setting. Có cách nào để thay shortcut này không ạ.
**Các bước tái hiện lỗi**

Ví dụ:
1. Mở gedit
2. Gõ abc
...
4. Thấy xyz

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 20.04)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Thông tin thêm**

**Comment by MeowIce** [comment]
Chuột phải vô icon của bamboo rồi chọn phần `Phím tắt` nhen.

> **Mô tả lỗi**
> 
> Hiện tại gõ ký tự ~ thì hiện ra bảng setting. Có cách nào để thay shortcut này không ạ. **Các bước tái hiện lỗi**
> 
> Ví dụ:
> 
> 1. Mở gedit
> 2. Gõ abc
>    ...
> 3. Thấy xyz
> 
> **Kết quả mong muốn**
> 
> **Ảnh chụp màn hình, hoặc clip quay màn hình**
> 
> **Môi trường**
> 
> * OS và version: (ví dụ: Ubuntu 20.04)
> * Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
> * Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)
> 
> **Thông tin thêm**

**Comment by willriver-dev** [comment]
Tksssss @MeowIce <3
