### ISSUE TITLE
Lỗi Không gõ được trên Google docs

### ISSUE THREAD

**Issue by congluanbui** [BambooEngine/ibus-bamboo#356]
**Mô tả lỗi**
Lỗi gõ Telex trên Google Docs, gõ xong bị mất chữ, mình đã chọn thử tất cả các kiểu gõ rôi mà vẫn không bộ nào hoạt động được cả

**Các bước tái hiện lỗi**

Ví dụ:
1. Tuyến --> sẽ trở thành "tu". Giáp--> "Gia"
2. bào --> b
...
**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - Ubuntu 22.04
 - Desktop: mặc định
 - Phiên bản ibus-bamboo: 0.8.1

**Comment by luongthanhlam** [comment]
bạn nhấn `Shift+~` và chuyển sang chế độ gõ khác nhé (nên thử 1 trước)

**Comment by congluanbui** [comment]
> bạn nhấn `Shift+~` và chuyển sang chế độ gõ khác nhé (nên thử 1 trước)

MÌnh đã thử tất cả các kiểu gõ rồi nhé (6 kiểu gõ) mà vẫn không được

**Comment by luongthanhlam** [comment]
> > bạn nhấn `Shift+~` và chuyển sang chế độ gõ khác nhé (nên thử 1 trước)
> 
> MÌnh đã thử tất cả các kiểu gõ rồi nhé (6 kiểu gõ) mà vẫn không được

ý bạn là vẫn bị mất chữ? bạn gửi mình ouput lệnh này nhé
```
cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
```

**Comment by congluanbui** [comment]
{
  "InputMethod": "Telex W",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex W": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "d": "D_Đ",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode",
  "Flags": 7,
  "IBflags": 295360,
  "Shortcuts": [
    5,
    96,
    0,
    0,
    0,
    0,
    0,
    0,
    12,
    117
  ],
  "DefaultInputMode": 6,
  "InputModeMapping": {
    "google-chrome:Google-chrome": 6
  }

**Comment by luongthanhlam** [comment]
bạn đang dùng chế độ gõ số 6 kìa, nhấn `Shift+~` trong Google docs để chuyển sang 1 và thử lại nhé
