### ISSUE TITLE
Không mở được chuyển đổi bộ gõ trong Terminal Ubuntu 22.04

### ISSUE THREAD

**Issue by vuLongLtPt** [BambooEngine/ibus-bamboo#358]
**Mô tả lỗi**
Mặc dù đã đổi phím tắt chuyển ngôn ngữ sang các phím khác nhưng mình không thể bật được cửa sổ chuyển bộ gõ để chọn chức năng Loại trừ ứng dụng.

**Comment by luongthanhlam** [comment]
bạn đã thiết lập đúng môi trường chưa (gõ `env | grep "IM_MODULE\|XMODIFIERS"` trong terminal để kiểm tra). Có thể gửi mình cấu hình bộ gõ không
```
cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
```

**Comment by vuLongLtPt** [comment]
Lệnh môi trường đây bạn:
![image](https://user-images.githubusercontent.com/82805156/188457913-9c420789-1b71-43a8-9e15-0cd27a902b32.png)
Còn đây là file cấu hình:
{
  "InputMethod": "Telex",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex W": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "d": "D_Đ",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode",
  "Flags": 7,
  "IBflags": 262592,
  "Shortcuts": [
    12,
    61,
    0,
    0,
    8,
    122,
    0,
    0,
    5,
    117
  ],
  "DefaultInputMode": 1,
  "InputModeMapping": {
    "code:Code": 7,
    "gnome-terminal-server:Gnome-terminal": 1,
    "google-chrome:Google-chrome": 1
  }
}
Mình thử trên chrome hay mọi chỗ khác đều có thể bật cửa sổ chuyển bộ gõ lên chỉ riêng Terminal là ko

**Comment by zenfas** [comment]
Hình như thiếu biến môi trường GTK rồi bạn
GTK_IM_MODULE=ibus

**Comment by vuLongLtPt** [comment]
Mình thêm đầy đủ như này rồi mà vẫn ko bật được bạn à
![image](https://user-images.githubusercontent.com/82805156/188883300-240afb56-76fb-47d0-af89-45d4cb5cb944.png)

**Comment by vuLongLtPt** [comment]
Mình dùng gnome terminal luôn mà bạn. Có khi nào do mình cài zsh shell ko nhỉ

**Comment by zenfas** [comment]
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

**Comment by luongthanhlam** [comment]
@namnguyen6595 bạn thay phím tắt `Shift+~` trong cài đặt hoặc thử đổi sang bộ gõ `Bamboo (US layout)` nhé

**Comment by namnguyen6595** [comment]
@luongthanhlam mình thay đổi rồi thì có cần phải restart lại ibus hay reboot lại k nhỉ

**Comment by prd-huynh-le** [comment]
> @namnguyen6595 bạn thay phím tắt `Shift+~` trong cài đặt hoặc thử đổi sang bộ gõ `Bamboo (US layout)` nhé

Hi @luongthanhlam, mình cũng bị lỗi tương tự trên Ubuntu 22.04, Bamboo tự chuyển tab qua Terminal khi switch input source.

**Comment by zenfas** [comment]
Thấy issue này nhắc đến hỗ trợ has_focus_id trên ibus phiên bản mới mike-fabian/ibus-typing-booster#328, @luongthanhlam xem có ứng dụng gì cho Bamboo được không

**Comment by luongthanhlam** [comment]
@namnguyen6595 có nhé
@prd-huynh-le bạn mô tả lỗi rõ hơn được không?
@zenfas mấy cái đó mình đã implement trong gói *_introspector.go rồi

**Comment by namnguyen6595** [comment]
@luongthanhlam mình có thử r nhưng vẫn k được bạn ạ

**Comment by luongthanhlam** [comment]
Gnome bản mới trên wayland không cho phép gọi trực tiếp API nhận diện ứng dụng đang chạy qua dbus https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/7298ee23e91b756c7009b4d7687dfd8673856f8b, để bật lại API này mọi người cần cài thêm extension https://github.com/linushdot/unsafe-mode-menu và bật `Unsafe mode`
