### ISSUE TITLE
<Request> Sửa từ sau khi back lại 

### ISSUE THREAD

**Issue by zenfas** [BambooEngine/ibus-bamboo#359]
Sau khi gõ 1 từ và nhấn phím space bar, mình muốn nhấn phím back quay lại ở vị trí cuối từ để sửa dấu từ (bàn Gboard trên Android xử lý việc này rất hay)

**Comment by luongthanhlam** [comment]
hiện tại bộ gõ chỉ hỗ trợ tính năng này trên chế độ gõ số 2,3,4,5 nhé bạn
