### ISSUE TITLE
Không gõ được tiếng việt trong WPS office version 11.1.0.8392

### ISSUE THREAD

**Issue by Mattstacey321** [BambooEngine/ibus-bamboo#36]
Hiện tại mình đang sử dụng Manjaro Deepin 18.10. Ba công cụ của bộ WPS office đều không gõ được tiếng việt.
Cảm ơn bạn.

**Comment by luongthanhlam** [comment]
bạn bị hiện tượng thế nào? ví dụ gõ chữ "và" ra "vaf" hay "vaà"? bạn đã thử đổi sang chế độ gõ khác chưa https://github.com/BambooEngine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng?

**Comment by Mattstacey321** [comment]
Hiện tại mình đang sử dụng phiên bản mới nhất, dù mình có chuyển kiểu gõ nhưng điều không thành công. 
Google Chrome build 75.0.3770.100, mình không thể gõ tiếng việt được ( trên thanh address,  chat mess)  - Còn firefõx thì mình gõ bình thường . Mong bạn sẽ fĩx trong thời gian sớm nhất . 
Cảm ơn bạn.

**Comment by luongthanhlam** [comment]
bạn cập nhật lên phiên bản mới nhất v0.5.4 và chọn chế độ Sửa lỗi gạch chân số 4 để khắc phục lỗi nhảy chữ trên chrome nhé.
