### ISSUE TITLE
Em moi hoc dung linux va khong biet lam the nao de cai ibus bamboo cho fedora

### ISSUE THREAD

**Issue by thecursehunter** [BambooEngine/ibus-bamboo#360]
**Mô tả lỗi**
Em khong su dung duoc ibus-bamboo tren fedora

**Các bước tái hiện lỗi**
- Cai dat Ibus-bambo bang 2 lenh nay: 

1. dnf config-manager --add-repo https://download.opensuse.org/repositories/home:lamlng/Fedora_36/home:lamlng.repo
2. dnf install ibus-bamboo

- vao ibus-setup trong terminal nhung khong kiem ra duoc cai gi duoc ghi la ibus bamboo trong phan input method

4. Thấy xyz

**Kết quả mong muốn**
em ko biet minh lam sai o dau, ai giup em di

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://user-images.githubusercontent.com/73272262/190880964-04be379e-2bef-45a4-8880-22fae2cff132.png)

**Môi trường**
 - OS và version: Nobara 36
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.8.1-4.1

**Comment by MeowIce** [comment]
> **Mô tả lỗi**
> Em khong su dung duoc ibus-bamboo tren fedora
> 
> **Các bước tái hiện lỗi**
> - Cai dat Ibus-bambo bang 2 lenh nay: 
> 
> 1. dnf config-manager --add-repo https://download.opensuse.org/repositories/home:lamlng/Fedora_36/home:lamlng.repo
> 2. dnf install ibus-bamboo
> 
> - vao ibus-setup trong terminal nhung khong kiem ra duoc cai gi duoc ghi la ibus bamboo trong phan input method
> 
> 4. Thấy xyz
> 
> **Kết quả mong muốn**
> em ko biet minh lam sai o dau, ai giup em di
> 
> **Ảnh chụp màn hình, hoặc clip quay màn hình**
> ![image](https://user-images.githubusercontent.com/73272262/190880964-04be379e-2bef-45a4-8880-22fae2cff132.png)
> 
> **Môi trường**
>  - OS và version: Nobara 36
>  - Desktop: Gnome
>  - Phiên bản ibus-bamboo: 0.8.1-4.1
> 

Bạn tải package về cài nha.

**Comment by thecursehunter** [comment]
> 

Tải cái rpm á? Em cũng thử cài cái rpm x86_64 rồi mà cũng ko đc

**Comment by luongthanhlam** [comment]
bạn khởi động lại máy xem? nếu không được thì chạy lệnh này xem có lỗi gì không
```
/usr/lib/ibus-bamboo/ibus-engine-bamboo
```

**Comment by thecursehunter** [comment]
> bạn khởi động lại máy xem? nếu không được thì chạy lệnh này xem có lỗi gì không
> 
> ```
> /usr/lib/ibus-bamboo/ibus-engine-bamboo
> ```

Thank you, em restart lai dc roi, nhung bay gio em ko biet chinh phim tat lam sao de doi 
![image](https://user-images.githubusercontent.com/73272262/190952401-1d864de6-07f1-48fd-a3fe-aec1a2da5c08.png)
em bam control shift ma ko dc

**Comment by thecursehunter** [comment]
> bạn khởi động lại máy xem? nếu không được thì chạy lệnh này xem có lỗi gì không
> 
> ```
> /usr/lib/ibus-bamboo/ibus-engine-bamboo
> ```

cám ơn, em làm được rồi
