### ISSUE TITLE
Không gõ được tiếng Việt trên Ubuntu 22.04

### ISSUE THREAD

**Issue by anhvandev** [BambooEngine/ibus-bamboo#362]
Mô tả:
Cài đặt ibus-bamboo theo các bước hướng dẫn nhưng không gõ được tiếng việt, cũng không thể mở bảng điều khiển.
Các bạn hỗ trợ mình setup với ạ, mình chỉ là normal user :(((
Khi sử dụng lệnh `ibus-setup` để cài đặt cho ibus-bamboo thì nhận được lỗi này
```
panic: dial unix @/home/myuser@mydomain/.cache/ibus/dbus-5bAdaB6c: connect: connection refused

goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/github.com/BambooEngine/goibus/ibus/bus.go:16
github.com/BambooEngine/goibus/ibus.NewBus()
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/github.com/BambooEngine/goibus/ibus/bus.go:21 +0x1dd
main.main()
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/ibus-bamboo/main.go:74 +0x1ea
```
Môi trường:
Ubuntu 22.04.1 LTS
Gnome
Biến môi trường:
GLFW_IM_MODULE=ibus
GTK_IM_MODULE=ibus
QT4_IM_MODULE=ibus
XMODIFIERS=@im=ibus
CLUTTER_IM_MODULE=ibus
QT_IM_MODULE=ibus

**Comment by luongthanhlam** [comment]
bạn chạy 2 lệnh này và gửi output cho mình nhé
```
find ~/.config/ibus/bus/
cat $(find ~/.config/ibus/bus/)
```

**Comment by anhvandev** [comment]
@luongthanhlam output khi minh chay lenh:
```
/home/myuser@mydomain/.config/ibus/bus/
/home/myuser@mydomain/.config/ibus/bus/282a5f4e185648b19a57db5b6f98c1e0-unix-0
/home/myuser@mydomain/.config/ibus/bus/282a5f4e185648b19a57db5b6f98c1e0-unix-2
/home/myuser@mydomain/.config/ibus/bus/282a5f4e185648b19a57db5b6f98c1e0-unix-wayland-0
cat: /home/myuser@mydomain/.config/ibus/bus/: Is a directory
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-Jx5KeVa1,guid=dd69e4500ef456205b370c7f632aafc3
IBUS_DAEMON_PID=42694
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-LYj2UV1M,guid=92add43b19bbc32e03c5c1cd631e8cd0
IBUS_DAEMON_PID=3829
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-Jx5KeVa1,guid=dd69e4500ef456205b370c7f632aafc3
IBUS_DAEMON_PID=42694

```

**Comment by pmkhue** [comment]
@luongthanhlam minh cung bi y chang luon 18 thi ko bi nay ngua ngua up len 20 thi dinh. Nho ban coi dum voi

~$ find ~/.config/ibus/bus/
/home/me/.config/ibus/bus/
/home/me/.config/ibus/bus/e8b8962eb2bb459db9bfbec3889881c9-unix-wayland-0
/home/me/.config/ibus/bus/e8b8962eb2bb459db9bfbec3889881c9-unix-0
$ cat $(find ~/.config/ibus/bus/)
cat: /home/me/.config/ibus/bus/: Is a directory
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/me/.cache/ibus/dbus-Q1GiKqaO,guid=76cdd40e6efac6353d1d2a87632f04f5
IBUS_DAEMON_PID=1692
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/me/.cache/ibus/dbus-Q1GiKqaO,guid=76cdd40e6efac6353d1d2a87632f04f5
IBUS_DAEMON_PID=1692

**Comment by pmkhue** [comment]
`@luongthanhlam minh cung bi y chang luon 18 thi ko bi nay ngua ngua up len 20 thi dinh. Nho ban coi dum voi

~$ find ~/.config/ibus/bus/
/home/me/.config/ibus/bus/
/home/me/.config/ibus/bus/e8b8962eb2bb459db9bfbec3889881c9-unix-wayland-0
/home/me/.config/ibus/bus/e8b8962eb2bb459db9bfbec3889881c9-unix-0
$ cat $(find ~/.config/ibus/bus/)
cat: /home/me/.config/ibus/bus/: Is a directory
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/me/.cache/ibus/dbus-Q1GiKqaO,guid=76cdd40e6efac6353d1d2a87632f04f5
IBUS_DAEMON_PID=1692
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/me/.cache/ibus/dbus-Q1GiKqaO,guid=76cdd40e6efac6353d1d2a87632f04f5
IBUS_DAEMON_PID=1692
`

**Comment by luongthanhlam** [comment]
@anhvandev @pmkhue  bạn có thể gửi teamviewer cho mình (ltlam93 at gmail.com) debug lỗi này trên máy được không nhỉ?

**Comment by pmkhue** [comment]
ok ban minh dang online ne de minh gui ban id

**Comment by anhvandev** [comment]
@luongthanhlam hiện tại máy của mình ko thể dùng teamviewer mong bạn thông cảm, @pmkhue nhờ bạn hỗ trợ @luongthanhlam nha

**Comment by pmkhue** [comment]
@anhvandev @luongthanhlam minh co thu go firefox ra cai bang apt nhung co ve van khong go dc tieng viet :D

**Comment by luongthanhlam** [comment]
@pmkhue lỗi của bạn là do cài app từ snap
@anhvandev bạn gửi giúp mình ouput các lệnh này nhé
```
echo $XDG_CONFIG_HOME
echo $IBUS_ADDRESS
echo $IBUS_ADDRESS_FILE
echo $DISPLAY
echo $WAYLAND_DISPLAY

IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-Jx5KeVa1,guid=dd69e4500ef456205b370c7f632aafc3 IBUS_DAEMON_PID=42694 /usr/lib/ibus-bamboo/ibus-engine-bamboo

IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-LYj2UV1M,guid=92add43b19bbc32e03c5c1cd631e8cd0 IBUS_DAEMON_PID=3829 /usr/lib/ibus-bamboo/ibus-engine-bamboo
```

**Comment by anhvandev** [comment]
@luongthanhlam chỉ có lệnh:
echo $DISPLAY có kết quả là :0
echo $WAYLAND_DISPLAY kêt quả là wayland-0
còn các lệnh khác ko có gì xảy ra

**Comment by luongthanhlam** [comment]
bạn chạy lệnh này `ibus restart && cat $(find ~/.config/ibus/bus/ -name '*-wayland-0)` rồi thay IBUS_ADDRESS và IBUS_DAEMON_PID trong đó vào lệnh trên và thử lại nhé

**Comment by anhvandev** [comment]
@luongthanhlam 
minh chay dc ket qua ntn khui chay `ibus restart && cat $(find ~/.config/ibus/bus/ -name '*-wayland-0')`
```
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-Ryik8VgH,guid=1a839219724300aa1c341a5b633c32be
IBUS_DAEMON_PID=380853
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-jd3UvOor,guid=24a72bf291e45fe380e87e3563358de7
IBUS_DAEMON_PID=2690```

**Comment by luongthanhlam** [comment]
OK, thêm 2 lệnh này nhé
```
/usr/lib/ibus-bamboo/ibus-engine-bamboo
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-jd3UvOor,guid=24a72bf291e45fe380e87e3563358de7 IBUS_DAEMON_PID=2690 /usr/lib/ibus-bamboo/ibus-engine-bamboo
```

**Comment by luongthanhlam** [comment]
cả 2 lệnh đều bị lỗi như vậy hay chỉ lệnh đầu tiên hả bạn? gửi thêm mình output lệnh này nhé
```
find ~/.config/ibus/bus/ && cat $(find ~/.config/ibus/bus/)
```

**Comment by anhvandev** [comment]
@luongthanhlam ca 2 lenh deu loi ban a
ket qua cua lenh `find ~/.config/ibus/bus/ && cat $(find ~/.config/ibus/bus/)`
```
/home/myuser@mydomain/.config/ibus/bus/
/home/myuser@mydomain/.config/ibus/bus/282a5f4e185648b19a57db5b6f98c1e0-unix-0
/home/myuser@mydomain/.config/ibus/bus/faea0d22860f48f78bfddfbfefa16e8f-unix-0
/home/myuser@mydomain/.config/ibus/bus/faea0d22860f48f78bfddfbfefa16e8f-unix-wayland-0
/home/myuser@mydomain/.config/ibus/bus/282a5f4e185648b19a57db5b6f98c1e0-unix-2
/home/myuser@mydomain/.config/ibus/bus/282a5f4e185648b19a57db5b6f98c1e0-unix-wayland-0
cat: /home/myuser@mydomain/.config/ibus/bus/: Is a directory
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-jd3UvOor,guid=24a72bf291e45fe380e87e3563358de7
IBUS_DAEMON_PID=2690
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-E0r7hSg8,guid=350dbe5e1b02400c2e2556b2633c335c
IBUS_DAEMON_PID=385179
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-E0r7hSg8,guid=350dbe5e1b02400c2e2556b2633c335c
IBUS_DAEMON_PID=385179
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-LYj2UV1M,guid=92add43b19bbc32e03c5c1cd631e8cd0
IBUS_DAEMON_PID=3829
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-jd3UvOor,guid=24a72bf291e45fe380e87e3563358de7
IBUS_DAEMON_PID=2690
```

**Comment by luongthanhlam** [comment]
nếu thay bằng lệnh này thì sao?
```
cat /var/lib/dbus/machine-id

IBUS_ADDRESS=unix:abstract=/home/myuser%40mydomain/.cache/ibus/dbus-E0r7hSg8,guid=350dbe5e1b02400c2e2556b2633c335c IBUS_DAEMON_PID=385179 /usr/lib/ibus-bamboo/ibus-engine-bamboo
```

**Comment by anhvandev** [comment]
@luongthanhlam ok

**Comment by anhvandev** [comment]
@luongthanhlam 
`cat /var/lib/dbus/machine-id` co ket qua la:
`faea0d22860f48f78bfddfbfefa16e8f`
con lenh dat VAR thi van loi nhu vay
```
panic: dial unix @/home/myuser%40mydomain/.cache/ibus/dbus-E0r7hSg8: connect: connection refused

goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/github.com/BambooEngine/goibus/ibus/bus.go:16
github.com/BambooEngine/goibus/ibus.NewBus()
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/github.com/BambooEngine/goibus/ibus/bus.go:21 +0x1dd
main.main()
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/ibus-bamboo/main.go:74 +0x1ea
```

**Comment by luongthanhlam** [comment]
@anhvandev mình vẫn chưa thể tái hiện lỗi này, bạn có thể tái hiện lỗi này trên máy ảo không?

**Comment by namdv-1375** [comment]
@luongthanhlam mình cũng đang bị lõi ko gõ đc tiếng việt trên 22.04 này, đọc đoạn này `/usr/lib/ibus-bamboo/ibus-engine-bamboo
`, mình cd vào ko đc vì ibus-engine-bamboo là 1 file

**Comment by namdv-1375** [comment]
chạy `IBUS_ADDRESS=unix:abstract=/h` cũng lỗi tương tự nuôn :((

**Comment by luongthanhlam** [comment]
> @luongthanhlam mình cũng đang bị lõi ko gõ đc tiếng việt trên 22.04 này, đọc đoạn này `/usr/lib/ibus-bamboo/ibus-engine-bamboo `, mình cd vào ko đc vì ibus-engine-bamboo là 1 file

bạn chạy thử file này trong terminal chưa? có lỗi gì vậy?

**Comment by namdv-1375** [comment]
@luongthanhlam 
```ruby
➜  ~ /usr/lib/ibus-bamboo/ibus-engine-bamboo
panic: dial unix @/home/dang.van.nam%40sun-asterisk.com/.cache/ibus/dbus-tTKiAwHQ: connect: connection refused

goroutine 1 [running]:
github.com/BambooEngine/goibus/ibus.NewBus.func1(...)
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/github.com/BambooEngine/goibus/ibus/bus.go:16
github.com/BambooEngine/goibus/ibus.NewBus()
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/github.com/BambooEngine/goibus/ibus/bus.go:21 +0x1dd
main.main()
	/build/ibus-bamboo-1bnAWK/ibus-bamboo-0.8.1/src/ibus-bamboo/main.go:74 +0x1ea
```
nó bị lỗi này @@

**Comment by luongthanhlam** [comment]
có vẻ là do lỗi phân quyền đọc ghi file cho user, có điều mỗi máy lại cấu hình khác nhau nên mình cũng không biết tái hiện lỗi kiểu gì. Nếu bạn có thể tái hiện lỗi trên máy ảo thì mình sẽ dễ debug hơn

**Comment by namdv-1375** [comment]
@luongthanhlam cái này mình nghĩ ko phải do quyền, vì mình cấp full quyền cho user r, mà lỗi quyền thường bắn lỗi kiểu `Permission...` :D
mình check thì giao diện nó cũng chỉ hiện như này 
![image](https://user-images.githubusercontent.com/49262063/197466872-65b22e43-e2b0-4237-833a-5cf5c5c319e6.png)
còn đúng ra thì nó phải hiện thế này 
![image](https://user-images.githubusercontent.com/49262063/197466982-0dba8a66-7a1d-422a-b054-8dc9128be2e3.png)

**Comment by luongthanhlam** [comment]
mình cũng thử tạo user mới và cấp quyền nhưng không tái hiện được lỗi này:((

**Comment by namdv-1375** [comment]
@luongthanhlam hay do mình dùng zsh mình install nhỉ?

**Comment by luongthanhlam** [comment]
mình không nghĩ là do zsh đâu

**Comment by huyfam** [comment]
> Mình bị lỗi này từ 20.04 rồi. Upgrade lên 22.04, 22.10 vẫn bị tiếp. Dùng ibus-unikey thì lại được. Nếu cài lại từ đầu thì chắc k bị đâu.

**Comment by anhvandev** [comment]
@huyfam đúng đúng, mình xài unikey nó ko lỗi, cơ mà gõ lỗi vch. @luongthanhlam hic, cty có rule ko cài máy ảo khi chưa xin phép và các phần mềm remote cũng cấm nên mình ko thể support đc á, máy cá nhân cũng cài OS cty rùi.

**Comment by canh912009** [comment]
mình fix đc r , 

Logout --> vào lại , có cài unkley hay bản bamboo trước đó thì gỡ sạch sẽ cả các gói liên quan --> Logout --> cài lại từ đầu theo trang chủ  [bamboo](https://github.com/BambooEngine/ibus-bamboo) --> Logout là mình lại OK r

**Comment by huyfam** [comment]
> mình fix đc r ,
> 
> Logout --> vào lại , có cài unkley hay bản bamboo trước đó thì gỡ sạch sẽ cả các gói liên quan --> Logout --> cài lại từ đầu theo trang chủ [bamboo](https://github.com/BambooEngine/ibus-bamboo) --> Logout là mình lại OK r

Mình dùng lệnh sudo apt purge ibus-bamboo để xoá gói và cài đặt lại thì k được bạn ạ. Bạn làm rõ hơn các bước bạn thực hiện được không ?

**Comment by haipnh** [comment]
> mình fix đc r ,
> 
> Logout --> vào lại , có cài unkley hay bản bamboo trước đó thì gỡ sạch sẽ cả các gói liên quan --> Logout --> cài lại từ đầu theo trang chủ [bamboo](https://github.com/BambooEngine/ibus-bamboo) --> Logout là mình lại OK r

Mình cũng fix được theo cách này, ko cần logout trước khi gỡ đâu.
```shell
# Step 1:
sudo apt purge --remove ibus-bamboo
# Step 2: Logout -> Login
# Step 3:
sudo apt install ibus-bamboo
# Step 4: Logout -> Login.
```
Tới đây thì sẽ xài được oke.

**Comment by anminhha** [comment]
find ~/.config/ibus/bus/
cat $(find ~/.config/ibus/bus/)
/home/anha/.config/ibus/bus/
/home/anha/.config/ibus/bus/c31fb2d3f8134ee8b1dccd113fd4ba41-unix-0
/home/anha/.config/ibus/bus/c31fb2d3f8134ee8b1dccd113fd4ba41-unix-wayland-0
cat: /home/anha/.config/ibus/bus/: Is a directory
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/anha/.cache/ibus/dbus-5xeXt6RA,guid=30e3cca4113507ab7d8dc4d365a4e20c
IBUS_DAEMON_PID=16500
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/anha/.cache/ibus/dbus-5xeXt6RA,guid=30e3cca4113507ab7d8dc4d365a4e20c
IBUS_DAEMON_PID=16500
Mình cũng dùng Ubuntu 22.04. Gõ trên chrome thì được nhưng có vẻ như trên ÓS thì lại tịt. Mình đã thử tên Text editor và LibreOffice writer hay thậm chí cả terminal thấy k được.

**Comment by goatastronaut0212** [comment]
Mình nghĩ chắc không còn cần thiết để lỗi này ở đây nữa vì cũng có người tìm ra được giải pháp rồi. Nếu các bạn còn lỗi hãy mở 1 báo cáo lỗi mới.

**Comment by anhvandev** [comment]
> Mình nghĩ chắc không còn cần thiết để lỗi này ở đây nữa vì cũng có người tìm ra được giải pháp rồi. Nếu các bạn còn lỗi hãy mở 1 báo cáo lỗi mới.

ko fix đc đâu bro, lỗi trong core luôn r

**Comment by goatastronaut0212** [comment]
Bạn vẫn còn lỗi sao @anhvandev. Mình vẫn thắc mắc bạn làm thế nào để ra được lỗi?

**Comment by anhvandev** [comment]
> Bạn vẫn còn lỗi sao @anhvandev. Mình vẫn thắc mắc bạn làm thế nào để ra được lỗi? Các phiên bản mới của ibus-bamboo thì sao và bạn có thử cài ibus-bamboo hay ibus lại chưa? như cách bạn @haipnh thực hiện
> 
> ```
> # Step1
> sudo apt purge --remove ibus-bamboo
> # Step 2: Logout -> Login
> # Step 3:
> sudo apt install ibus-bamboo
> # Step 4: Logout -> Login.
> ```

ko có tác dụng gì đâu mình thử đi thử lại nhiều lần rồi. chỉ cần máy tồn tại unikey 1 lần thì ko bao giờ cài đc bamboo nữa

**Comment by goatastronaut0212** [comment]
Rõ ràng không phải là lỗi của ibus-bamboo nhưng chắc chắn các file config trong unikey có thể chưa được gỡ

**Comment by TranSangQST** [comment]
Mình remove ibus rồi cài lại thì hết lỗi
