### ISSUE TITLE
Click chuột tự chèn chữ 

### ISSUE THREAD

**Issue by dtk9289** [BambooEngine/ibus-bamboo#364]
**Mô tả lỗi**

khi gõ chữ mà lấy chuột click vào bất kì chỗ nào trong đoạn văn thì nó chèn từ đang nhập vào chỗ vị trí chuột click
**Các bước tái hiện lỗi**

Wayland Firefox
1. gõ đoạn văn
2. gõ đoạn văn<lấy chuột>
3. gõ <click chỗ này>vănđoạn văn

**Kết quả mong muốn**
tự kết thúc chữ đang gõ, không chèn thêm vào chỗ click chuột

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: arch
 - Desktop: sway
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Thông tin thêm**

**Comment by luongthanhlam** [comment]
bạn vào `Cấu hình khác`, bật tùy chọn `Bắt sự kiện chuột` để khắc phục lỗi này nhé
