### ISSUE TITLE
Bỏ pop-up lựa chọn tính năng?

### ISSUE THREAD

**Issue by tmpm697** [BambooEngine/ibus-bamboo#365]
**Mô tả lỗi**
Có cách nào remove/disbale cái pop-up như hình dưới không? mỗi lần chuyển tiếng việt hay anh của Bamboo đều có 1 cái pop-up chứa "shortcuts, về trang chủ, ..etc"

![test](https://i.imgur.com/AUjWNuq.png)

WM hiện tại đang dùng i3wm/swaywm ko hỗ trợ đầy đủ nên pop-up hiện ra rất khó chịu, có cách nào set config trong ~/.config/<..> thay vì pop-up ko? và cách disable/remove cái pop-up đi.

Sau khi start `ibus-daemon -drxR` và chọn engine `ibus engine Bamboo - Bamboo`, pop-up sẽ chặn luôn input của các app khác.
Ví du, mih đang có firefox đang mở, sau đó chạy 1 script để start/chọn engine như trên, cả workspace sẽ bị block và ko thể type gì trên firefox (ví dụ bạn đang viết gì đó vào thanh địa chỉ trước khi gọi script)
Bắt buộc phải switch workspace để lấy lại input (keyboard), việc click trái bằng chuột để lựa chọn firefox ko có hiệu quả.
(Ngay cả nếu bạn chạy script = 1 terminal nào đó cũng có issue như vậy)

Như vậy nên có 1 tùy chọn để ẩn toàn bộ cái pop-up gtk này trong ibus-setup?

**Comment by luongthanhlam** [comment]
<img width="310" alt="Screen Shot 2022-10-04 at 20 53 12" src="https://user-images.githubusercontent.com/26364140/193838108-e8149b69-10e6-4084-a282-e394124abcbe.png">

bạn mở ibus-setup và cấu hình như này nhé
