### ISSUE TITLE
Khi nào thì ibus daemon sẵn sàng cho set engine sau khi start nó?

### ISSUE THREAD

**Issue by tmpm697** [BambooEngine/ibus-bamboo#366]
**Mô tả lỗi**
vi script.sh  
```
ibus-daemon -drxR
ibus engine Bamboo - Bamboo
```
nếu cho chạy script trên, ibus engine sẽ fail khi set engine, kết quả, engine ko đc thay đổi qua Bamboo.

Nhưng nếu:
vi script.sh
```
ibus-daemon -drxR
sleep 3
ibus engine Bamboo - Bamboo
```
nếu chạy script trên, ibus engine set thành công engine thành Bamboo.
** NOTE: sleep 3 phụ thuộc vào từng hệ thống -- sleep 10 hoặc 20 để thấy rõ lỗi.

Kết quả mong muốn: ko cần dùng sleep vẫn set đc ibus engine ngay sau khi start ibus-daemon, nếu ko thì cần phải check đc status của ibus-daemon để start engine cho đúng ("đúng" nghĩa là sau khi ibus-daemon start thành công và sẵn sàng để update engine)

**Comment by luongthanhlam** [comment]
bạn dùng lệnh này nhé
```
ibus-daemon -drxR && while ! ibus engine; do ibus engine Bamboo; done
```
