### ISSUE TITLE
Lỗi gõ tiếng Việt trên WPS (version 11.1.0.11664)

### ISSUE THREAD

**Issue by pndhuy150902** [BambooEngine/ibus-bamboo#367]
**Mô tả lỗi**
Gõ tiếng Việt nhưng lúc nào cũng sẽ hiển thị ra một cái ô nhỏ màu đen. Đổi hêt tất cả các chế độ gõ của ibus bamboo thì có cái sẽ mất cái ô đen đó nhưng sẽ gõ bị lỗi.

Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Ví dụ: Khi gõ chữ 'chào' thì nó sẽ hiển thị một ô màu đen nhỏ ở phía dưới hiển thị như cái mình nhập. Và khi chuyển sang chế độ khác có chế độ gõ không được có chế độ thì khi gõ chữ 'nó' thì sẽ hiển thị ra 'noó'.

**Môi trường**
 - OS và version: Linux Mint 21 "Vanessa"
 - Desktop: xfce
 - Phiên bản ibus-bamboo: 0.8.1

**Comment by luongthanhlam** [comment]
Rất tiếc là WPS bản mới đã bỏ tính năng inline predit nên hiện tại không có cách nào fix bạn nhé
