### ISSUE TITLE
Không thể dùng phím tắt để chuyển đổi nhanh giữa 2 chế độ gõ

### ISSUE THREAD

**Issue by hanslanzd1** [BambooEngine/ibus-bamboo#369]
Mình đã configure phím tắt về **Super + Space** nhưng chức năng này không hoạt động. Mình dùng **Mint cinnamon**. 

Khá là bất tiện khi phải di chuột liên tục. Mong tính năng này sẽ được sửa nhanh nhất có thể.

_Xin cảm ơn!_

**Comment by zenfas** [comment]
Phím này trên Linux Mint bị trùng nhé [Win+Space](https://forums.linuxmint.com/viewtopic.php?t=291898)

**Comment by hanslanzd1** [comment]
> Phím này trên Linux Mint bị trùng nhé [Win+Space](https://forums.linuxmint.com/viewtopic.php?t=291898)

Mình thử chuyển qua các tổ hợp như Ctrl + Shift cũng không được =[[[

**Comment by luongthanhlam** [comment]
bạn cấu hình ở đâu? có thể gửi ảnh để mô tả rõ hơn không?

**Comment by kytosai** [comment]
> > Phím này trên Linux Mint bị trùng nhé [Win+Space](https://forums.linuxmint.com/viewtopic.php?t=291898)
> 
> Mình thử chuyển qua các tổ hợp như Ctrl + Shift cũng không được =[[[

Mình đang dùng ubuntu 22.04, mặc định khi thay đổi phím ngôn ngữ, nó sẽ luôn luôn bắt phải kèm phím `SHIFT + phím tắt` đã đổi để giúp đảo ngược ngôn ngữ đã đổi trước đó, nên bác đổi dính cái phím `SHIFT` thì không được đâu.

Hiện tại mình đang dùng tổ hợp ALT + Z để đổi, khi mình gán phím ALT + Z để đổi ngôn ngữ thì mặc định Ubuntu cũng sẽ kèm thêm 1 phím tắt nữa là SHIFT + ALT + Z để revert lại ngôn ngữ đã đổi trước đó

**Comment by ThieuMinh26** [comment]
![image](https://user-images.githubusercontent.com/92904701/208833561-98f6d6df-05f5-4d90-b785-0a865b791689.png)
Mình set như vậy sao ko chuyển đc nhỉ

**Comment by thanhhocse96** [comment]
Cái lỗi trên Linux Mint chắc đợi linux mint cập nhật xem. Tui thì đang dùng theo cách này ([copy ở đây ra](https://zefro.wordpress.com/2022/12/29/kinh-nghiem-su-dung-debian-linux-ubuntu-linux-mint/#super-space-error-linux-mint)) để dùng tạm:
+ `ibus list-engine` để lấy danh sách engine
+ Vào trong thư mục Keyboard > Shortcut
+ Thêm các lệnh vào phần shortcut, ví dụ: `ibus engine Bamboo::Candy` rồi gán cho tổ hợp ctrl+alt+v chẳng hạn
