### ISSUE TITLE
Cross build lỗi

### ISSUE THREAD

**Issue by ndgnuh** [BambooEngine/ibus-bamboo#37]
**Mô tả lỗi**
Build chỉ hoạt động với `GOARCH=amd64` (mặc định).

**Các bước tái hiện lỗi**
```sh
env GOARCH=386 make
env GOARCH=arm make
env GOARCH=arm64 make
```

**Môi trường**
 - OS và version: Void Linux
 - Phiên bản ibus-bamboo: 0.4.8

**Thông tin thêm**

Log khi build (tất cả các arch khác `amd64` đều có lỗi giống nhau, mình cho vào một log):
```sh
GOPATH=/home/hung/ibus-bamboo-0.4.8 go test ./src/ibus-bamboo
# ibus-bamboo [ibus-bamboo.test]
src/ibus-bamboo/engine.go:106:16: undefined: x11GetFocusWindowClass
src/ibus-bamboo/engine.go:114:3: undefined: x11ClipboardReset
src/ibus-bamboo/engine.go:135:3: undefined: startMouseTracking
src/ibus-bamboo/engine.go:145:2: undefined: x11ClipboardExit
src/ibus-bamboo/engine.go:146:2: undefined: stopMouseTracking
src/ibus-bamboo/engine.go:318:4: undefined: startMouseTracking
src/ibus-bamboo/engine.go:321:4: undefined: stopMouseTracking
src/ibus-bamboo/engine_backspace.go:199:4: undefined: x11SendBackspace
src/ibus-bamboo/engine_backspace.go:202:4: undefined: x11SendBackspace
src/ibus-bamboo/engine_preedit.go:104:2: undefined: mouseCaptureUnlock
src/ibus-bamboo/engine_preedit.go:104:2: too many errors
FAIL	ibus-bamboo [build failed]
make: *** [Makefile:34: test] Error 2
```

**Comment by luongthanhlam** [comment]
Bạn làm theo hướng dẫn này xem https://gist.github.com/steeve/6905542

**Comment by ndgnuh** [comment]
Mình thấy trong mã nguồn có file `c` nên mình thử đặt bộ cài C khi cross build.
```sh
`CC=armv7l-linux-gnueabihf-gcc GOARCH=arm go build -v -o ibus-bamboo-engine -ldflags="-s -w -extld=$CC" ./src/ibus-bamboo
```

Trên máy mình có vẻ `armv7l-linux-gnueabihf-gcc` không nhận `libX11` với `libXtst` nên mấy file `c` ở trong build lỗi? Trong môi trường build của Void Linux thì không hiểu tại sao lại có flag `-m64` ở đâu ra.

Các bước ở trên có cần không bạn, theo như link gist trên thì bản `go` hiện tại đã hỗ trợ cross build rồi? Mình dùng `go-1.12`.

**Comment by luongthanhlam** [comment]
bạn phải set CGO_ENABLED=1 nữa vì khi cross build go sẽ tự động set về 0

**Comment by ndgnuh** [comment]
issue mở quá 3 tháng rồi, cộng với việc bên Void linux họ chấp nhận không cross build nên mình close issue.
