### ISSUE TITLE
Không gõ được tiếng Việt trên Ubuntu 22.04

### ISSUE THREAD

**Issue by namdv-1375** [BambooEngine/ibus-bamboo#370]
- Mình đang bị lỗi giống vs issue này https://github.com/BambooEngine/ibus-bamboo/issues/362
k thể gõ đc tiếng việt dù đã setting đủ, ai chỉ mình các fix vs

**Comment by haipnh** [comment]
Check lại issue [#362](https://github.com/BambooEngine/ibus-bamboo/issues/362#issuecomment-1492259295) nha.

**Comment by luongthanhlam** [comment]
bạn tham khảo các lỗi thường gặp ở wiki https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60
