### ISSUE TITLE
Không gõ được tiếng việt trên onlyoffice

### ISSUE THREAD

**Issue by thecursehunter** [BambooEngine/ibus-bamboo#371]
**Mô tả lỗi**
Không gõ được tiếng việt trên onlyoffice

**Các bước tái hiện lỗi**
1. cài Ibus-Bamboo cho Fedora 36
2. Tải onlyoffice bản flatpak hoặc rpm package
3. gõ thử trong đó với input method là bamboo candy 

**Kết quả mong muốn**
Gõ được tiếng việt trên Onlyoffice

**Môi trường**
 - OS và version: Fedora 37
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Comment by luongthanhlam** [comment]
bạn cập nhật lên bản v0.8.2 để fix lỗi này nhé
