### ISSUE TITLE
Làm sao để vẫn dùng được tính năng suggestion trên firefox khi dùng Bamboo engine?

### ISSUE THREAD

**Issue by tmpm697** [BambooEngine/ibus-bamboo#375]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

1. Đang dùng ibus engine: Bamboo
2. Mở firefox-beta trên archlinux
3. Chọn vào thanh địa chỉ/address và bắt đầu nhập chữ `go`
4. Quan sát thấy rằng sau khi nhập chữ `go`, firefox-beta đã không tự suggest ra `google` hay các trang tượng liên quan tới chữ `go` (đã bật tính năng suggestion trên firefox-beta)
Ở đây chỉ thấy chứ `go` trên thanh địa chỉ, ko suggestions ko tự nhập `google.com` trên thanh địa chỉ --> tính năng suggestion trên firefox-beta hoàn toàn bị loại bỏ.

Nếu dùng engine `BambooUs` thì tính năng suggestion vẫn hoạt động bình thường.

**Kết quả mong muốn**
Làm thế nào để vẫn sử dụng tính năng suggestions trên firefox-beta khi đang dùng ibus engine `Bamboo`?

Việc chuyển qua lại `BambooUs` để dùng tính năng suggestion rất bất tiện.

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![suggestions bị disable khi đang dùng engine Bamboo](https://i.imgur.com/L3XbnVg.png)

**Môi trường**
 - OS và version: Archlinux latest
 - Desktop: Swaywm
 - Phiên bản ibus-bamboo: Latest

**Comment by luongthanhlam** [comment]
bạn đang dùng chế độ gõ số mấy nhỉ (nhấn Shift+~ để kiểm tra)? một số chế độ gõ không làm việc tốt với tính năng suggestion trên firefox

**Comment by tmpm697** [comment]
làm sao để kiểm tra đang ở chế độ ngõ nào? mih nhấn vào thanh địa chỉ firefox khi đang ở `Bamboo` thì nó chỉ ra ký tự `~` thôi.

**Comment by zenfas** [comment]
Nó có giống bug đang mở của Firefox không https://bugzilla.mozilla.org/show_bug.cgi?id=1796491
https://bugzilla.mozilla.org/show_bug.cgi?id=1693726

**Comment by luongthanhlam** [comment]
Bamboo sử dụng keyboard mặc định của hệ thống, còn BambooUS sử dụng keyboard theo layout US nên tính năng suggestion có thể không hoạt động nếu bạn đang dùng Bamboo và keyboard layout không phải US.

**Comment by tmpm697** [comment]
qua dùng chrome thì thấy ok :)
