### ISSUE TITLE
Không thể gõ được trên Telegram phiên bản flatpak

### ISSUE THREAD

**Issue by lethinhrider** [BambooEngine/ibus-bamboo#378]
**Mô tả lỗi**
Ibus bamboo không có phản hồi khi gõ trên Telegram, kể cả ấn nút Shift + ~ để đổi kiểu fix gạch chân thì cũng không có phản hồi. Gõ giống như chưa có bật bộ gõ và không thể sử dụng được bất cứ tính năng nào khác của ibus-bamboo.

**Các bước tái hiện lỗi**
1. Cài app Telegram qua flatpak: flatpak install flathub org.telegram.desktop
2. Mở Telegram lên đăng nhập rồi gõ thử sẽ thấy không gõ được tiếng Việt và không sử dụng bất cứ tính năng nào của ibus-bamboo.

**Kết quả mong muốn**
Phải gõ được tiếng Việt và sử dụng được tính năng Shift + ~

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://user-images.githubusercontent.com/43519453/202894095-82972b4b-9196-45a4-bd42-d244b7f5e131.png)

**Môi trường**
 - OS: Ubuntu 20.04, Debian 11 và các distro dựa trên Ubuntu 20.04 và Debian 11
 - Desktop: Gnome, KDE, Cinnamon
 - Phiên bản ibus-bamboo: 0.8.2

**Thông tin thêm**
Các phiên bản mới hơn của các distro thì không gặp lỗi này, ví dụ Ubuntu 22.04, Debian phiên bản dev thì không bị lỗi khi gõ trên Telegram phiên bản flatpak, chỉ phiên bản cũ mới bị lỗi. Mình đã test trên nhiều distro base Ubuntu 20.04 và Debian 11 thì đều bị lỗi này, còn mới hơn thì không bị nên mình khẳng định chỉ có bản cũ là gặp lỗi.
Mình chưa muốn update distro lên phiên bản cao hơn chỉ vì một app, các phiên bản distro mới hơn thật sự chưa ổn định và thiếu app mình cần.

**Comment by lethinhrider** [comment]
Update: Mình cũng đã thử build từ source nhưng vẫn gặp lỗi trên với các distro Ubuntu 20.04, Debian 11 và base. Cả phiên bản build từ source và cài từ apt đều ghi là 0.8.2
![image](https://user-images.githubusercontent.com/43519453/202896735-2d4275e2-f0a3-4882-bdda-7fa6e3163b22.png)

**Comment by luongthanhlam** [comment]
bạn làm thử theo hướng dẫn ở đây nhé https://github.com/flathub/io.atom.electron.BaseApp/issues/4 https://dev.to/ajeebkp23/ibus-not-working-with-flatpak-apps-4omf

**Comment by lethinhrider** [comment]
> bạn làm thử theo hướng dẫn ở đây nhé [flathub/io.atom.electron.BaseApp#4](https://github.com/flathub/io.atom.electron.BaseApp/issues/4) https://dev.to/ajeebkp23/ibus-not-working-with-flatpak-apps-4omf

Mình đã đọc và làm theo chỉ dẫn ---> khởi động lại nhưng vẫn không fix được. Quái lạ là lỗi này chỉ ở Telegram thôi còn tất cả các app khác cài từ flatpak đều gõ được

**Comment by lethinhrider** [comment]
> > > bạn làm thử theo hướng dẫn ở đây nhé [flathub/io.atom.electron.BaseApp#4](https://github.com/flathub/io.atom.electron.BaseApp/issues/4) https://dev.to/ajeebkp23/ibus-not-working-with-flatpak-apps-4omf
> > 
> > 
> > Mình đã đọc và làm theo chỉ dẫn ---> khởi động lại nhưng vẫn không fix được. Quái lạ là lỗi này chỉ ở Telegram thôi còn tất cả các app khác cài từ flatpak đều gõ được
> 
> ở cái hướng dẫn dev.to ông thay `GTK_IM_MODULE` thành `QT_IM_MODULE` chưa ?

Đã thử như ông chỉ rồi khởi động lại máy, vẫn không fix được :(
Kiểu này là phải xài Telegram web đỡ rồi.
