### ISSUE TITLE
Mình muốn bỏ tùy chọn kiểu gì vậy,  mình nhấn shift + ` nhưng lỡ chọn sai tùy chọn, mình ko biết bỏ kiểu gì ?

### ISSUE THREAD

**Issue by TC-Fat** [BambooEngine/ibus-bamboo#38]
**Mô tả lỗi**
Một mô tả ngắn gọn về lỗi đang xảy ra

**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
Ví dụ:
1. Mở gedit
2. Gõ abc
...
4. Thấy xyz

**Kết quả mong muốn**
Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Ví dụ: Gõ abc thì phải thấy abc chứ không phải xyz

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Nếu cần thiết, hãy [đính kèm hình ảnh](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) hoặc gửi link youtube [quay lại màn hình](https://www.youtube.com/watch?v=N8M4zsqTkr4) tái hiện lỗi.

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 18.10)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus: (chạy command `ibus version` để xem phiên bản ibus)
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.4.8)

**Thông tin thêm**
Các nội dung khác có liên quan đến lỗi đang xảy ra.

**Comment by ndgnuh** [comment]
Nếu bạn chọn "sửa lỗi gạch chân trong menu" thì mặc định là 3, nếu không thì là 1.
