### ISSUE TITLE
Không gõ được tiếng việt trên trình duyệt sử dụng Wayland

### ISSUE THREAD

**Issue by phannhat17** [BambooEngine/ibus-bamboo#380]
**Mô tả lỗi**

Không gõ được tiếng việt trên trình duyệt sử dụng `Preferred Ozone platform` là `Wayland` (đã test trên Chrome và Brave) các ứng dụng khác vẫn bình thường

**Các bước tái hiện lỗi**

1. Mở Brave
2. Truy cập `brave://flags/`
3. Search `Preferred Ozone platform`
4. Chọn `Wayland`

**Kết quả mong muốn**

Gõ "aa" thì sẽ ra "â" 

**Môi trường**
 - OS và version: `Ubuntu 22.04.1 LTS x86_64`
 - Desktop: `GNOME 42.5`
 - Phiên bản ibus-bamboo: `0.8.2`

**Thông tin thêm**

Biến môi trường
```
╰─$ env | grep "IM_MODULE\|XMODIFIERS"

QT_IM_MODULE=ibus
QT4_IM_MODULE=ibus
GTK_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
XMODIFIERS=@im=ibus
GLFW_IM_MODULE=ibus
```

**Comment by luongthanhlam** [comment]
Duplicated of https://github.com/BambooEngine/ibus-bamboo/issues/346
