### ISSUE TITLE
Lỗi không sử dụng được ibus-bamboo trên firefox

### ISSUE THREAD

**Issue by cobeo2004** [BambooEngine/ibus-bamboo#382]
**Mô tả lỗi**
Sau khi đã tải và build ibus-bamboo bằng make + tải ibus trên apt về, em nhận thấy rằng e không thể sử dụng được nó trên firefox, mặc dù trong máy thì dùng hoàn toàn ok

**Các bước tái hiện lỗi**
1. Tải bamboo về từ release và build (do không thể dùng add-apt-repo được)
2. Tải ibus từ apt
3. Run ibus và set chế độ gõ về chế độ 2
**Kết quả mong muốn**
Nó nhẽ ra phải gõ được trên firefox những không, nó không sử dụng đc 

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Kali Linux 6.0.3 dành cho arm64
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.8.1

**Thông tin thêm**
Đã thử từ các issues trước và đã làm theo hưỡng dẫn từ https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng nhưng vẫn k ăn thua.

**Comment by zenfas** [comment]
Bạn kiểm tra xem mấy gói ibus-gtk, ibus-gtk3 đã cài đặt chưa?

**Comment by cobeo2004** [comment]
Em cám ơn ad nhiều, sau một hồi check packages thì đúng là nó thiếy ba packs này, em cài vào rồi reset lại máy là chạy ngon lành rồi.
