### ISSUE TITLE
Không gõ được tiếng việt trong Google Chrome khi bật Wayland trong Chrome

### ISSUE THREAD

**Issue by ghost** [BambooEngine/ibus-bamboo#383]
**Mô tả lỗi**

Google Chrome mình bị mờ và tìm thấy cách giải quyết là bật "Preferred Ozone platform" ở "chrome://flags/#ozone-platform-hint" từ "Default" sang chế "Auto" hoặc chính hơn là "Wayland". Sau Logout thì mọi thứ nét bình thuờng nhưng gõ tiếng việt thì không được. Bật lại "Default" thì gõ bình thuờng. Còn về hệ thống thì vẫn gõ bình thuờng. 

**Môi trường**
 - OS và version: openSUSE Tumbleweed
 - Windowing System: Wayland
 - Desktop: (Gnome)
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.2)

**Comment by luongthanhlam** [comment]
Duplicated of https://github.com/BambooEngine/ibus-bamboo/issues/346
