### ISSUE TITLE
Click chuột mang theo từ cuối câu đi nơi khác

### ISSUE THREAD

**Issue by superthin** [BambooEngine/ibus-bamboo#385]
**Mô tả lỗi**
Từ chuỗi cùng của cụm từ/ câu được mang sang cửa sổ ứng dụng khác hoặc text box khác của ứng dụng hiện đang.

**Các bước tái hiện lỗi**
Mở một ứng dụng bất kỳ, cụ thể như Text (gEdit) trên Ubuntu hoặc ngay cả trình duyệt web hiện tại có ô nhập liệu.

Gõ một dòng như là: _cộng hoà xã hội chủ nghĩa._ Click chuột bất kỳ chỗ nào trong dòng chữ vừa đánh thì chữ "_nghĩa_" bỗng nhiên nhảy đến "ngồi" vào đó.

**Kết quả mong muốn**
Không mang theo cái chữ cuối cùng của dòng chữ đang gõ đi đâu khác khi bất chợt click chuột đi chỗ khác mà chỗ khác là ô có thể nhập liệu.

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.8.1

**Comment by luongthanhlam** [comment]
bạn đang sử dụng môi trường X11 hay wayland nhỉ? nếu là X11 thì chỉ cần bật tính năng `Bắt sự kiện chuột` là được nhé

**Comment by superthin** [comment]
@luongthanhlam tuyệt quá bạn, cám ơn bạn rất nhiều vì hoá ra là bắt sự kiện chuột giải quyết được vấn đề. Trước đây mình không hiểu "bắt sự kiện chuột" là gì, cũng có thử bật nhưng lúc đó không cảm nhận được tác dụng nên lại tắt đi, ngốc thật.
