### ISSUE TITLE
Làm thế nào để chuyển nhanh tiếng việt sang tiếng anh

### ISSUE THREAD

**Issue by ThieuMinh26** [BambooEngine/ibus-bamboo#386]
**Mô tả lỗi**

Mình muốn chuyển nhanh giữa tiếng anh và tiếng việt bằng phím ctrl + shift thì làm thế nào vậy

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![image](https://user-images.githubusercontent.com/92904701/208834357-d662c9b2-d3a9-4f00-9829-58f97db69dea.png)

**Môi trường**
 - OS và version: Mint 21
 - Desktop: xfce
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Comment by thanhhocse96** [comment]
Same issue with Mint 21: Cinnamon

**Comment by luongthanhlam** [comment]
để cấu hình phím tắt chuyển anh-việt bạn cấu hình trong Setting của hệ thống (Ubuntu, Fedora, Gnome)
![](https://topthuthuat.com/images/Ubuntu/go_tieng_viet_unikey_ibus_5.png)

hoặc `ibus-setup` (với KDE, xfce,...)
![](http://3.bp.blogspot.com/-aQXetl_A45c/VTIqIt76uEI/AAAAAAAAFFU/KCaXhNmx5fs/s1600/keyboard-shortcuts.png)

**Comment by thanhhocse96** [comment]
It's not working, but maybe the problem is Linux mint xorg
