### ISSUE TITLE
bug on  ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by canh912009** [BambooEngine/ibus-bamboo#387]
Cai dat xong tren ubuntu 22.04.1 LTS
KHong chon duoc ngon ngu ngo la tieng viet unikey . ko dung dc

**Comment by canh912009** [comment]
![image](https://user-images.githubusercontent.com/12532267/209288731-c5eab219-ae1d-4841-906b-4b9c1e271520.png)

**Comment by canh912009** [comment]
mình fix đc r , 

Logout --> vào lại , có cài unkley hay bản bamboo trước đó thì gỡ sạch sẽ cả các gói liên quan --> Logout --> cài lại từ đầu theo trang chủ  [bamboo](https://github.com/BambooEngine/ibus-bamboo) --> Logout là mình lại OK r

**Comment by thanhhocse96** [comment]
After install bamboo, you run command: 
```ibus restart```
No need for logout

**Comment by nguythequang200** [comment]
> mình fix đc r ,
> 
> Logout --> vào lại , có cài unkley hay bản bamboo trước đó thì gỡ sạch sẽ cả các gói liên quan --> Logout --> cài lại từ đầu theo trang chủ [bamboo](https://github.com/BambooEngine/ibus-bamboo) --> Logout là mình lại OK r

Go cai dat the nao v b. Minh moi dung Linux nen chua thuoc

**Comment by nguythequang200** [comment]
> > mình fix đc r ,
> > Logout --> vào lại , có cài unkley hay bản bamboo trước đó thì gỡ sạch sẽ cả các gói liên quan --> Logout --> cài lại từ đầu theo trang chủ [bamboo](https://github.com/BambooEngine/ibus-bamboo) --> Logout là mình lại OK r
> 
> Go cai dat the nao v b. Minh moi dung Linux nen chua thuoc

mình log out ra xong vào lại thì lại được rồi. :D

**Comment by haipnh** [comment]
Duplicated voi issue [#362](https://github.com/BambooEngine/ibus-bamboo/issues/362#issuecomment-1492259295) nha.
