### ISSUE TITLE
Tại sao gõ tiếng việt trên Wayland mang lại cảm giác tốt hơn là gõ trên X11?

### ISSUE THREAD

**Issue by tea0112** [BambooEngine/ibus-bamboo#388]
Như title, mọi người có thể cho mình thêm ý kiến và dẫn chứng với.

**Comment by nguyendangkin** [comment]
Wow. Nhưng sao tôi không gõ được trên wayland nhỉ? Tôi đang dùng gnome x11

**Comment by hieu-van** [comment]
Đây ko phải là issue, nên chuyển sang phần discussion

xin @luongthanhlam close thớt
