### ISSUE TITLE
Không gõ được tiếng việt trên libreoffice

### ISSUE THREAD

**Issue by LuThaiHoc** [BambooEngine/ibus-bamboo#391]
Mình đã build thành công Ibus && Ibus Bamboo trên kit nhúng. Sau khi set các biến môi trường và chọn engine Bamboo nhưng không gõ được tiếng Việt trên libreoffice. 
_Command:_
**ibus-daemon -ds**
**ibus engine Bamboo** 
**ls /home/root/.config/ibus/**
`ed07907757e34e758e8bee88435a2816-unix-0  ed07907757e34e758e8bee88435a2816-unix-wayland-0`
_Environment varibles:_
**env | grep ibus**
`GLFW_IM_MODULE=ibus`
`GTK_IM_MODULE=ibus`
`QT4_IM_MODULE=ibus`
`XMODIFIERS=@im=ibus`
`CLUTTER_IM_MODULE=ibus`
`QT_IM_MODULE=ibus`
`OLDPWD=/home/root/build-ibus`
Mình thử sử dụng một engine mặc định từ ibus: `ibus engine xkb:vn::vie` thì thấy vẫn gõ được tiếng Việt trên libreoffice. Cho mình hỏi mình nên kiểm tra thêm các cấu hình cần thiết ở đâu để có thể gõ được tiếng việt trên ứng dụng cụ thể ạ?

**Comment by luongthanhlam** [comment]
khi chạy `/usr/lib/ibus-bamboo/ibus-engine-bamboo` bạn có gặp lỗi nào không? nếu được bạn có thể dựng máy ảo để tái hiện lỗi này được không?

**Comment by LuThaiHoc** [comment]
Hi anh Lâm, mình đã thử chạy ibus-engine-bamboo và ra kết quả như sau
```
/usr/lib/ibus-bamboo/ibus-engine-bamboo 
2023/02/07 01:24:00.592781 Got Bus, Running Standalone
2023/02/07 01:24:00.613571 FocusIn.
Enable.XGrabPointer: successfully grabbed mouse pointer
MotionNotify: click
Xlib:  extension "RECORD" missing on display ":0".
RECORD extension is not supported on this X server!
WM_CLASS=()
```
Mình đang làm trên kit nhúng nên khả năng không tạo được máy ảo để tái tạo lỗi như thế. Mình đã thử trên máy host và mọi thứ chạy bình thường. Mình nghĩ trong quá trình build có thể có một số lib không đúng dẫn đến chương trình bị sai vì mình build ngoài và add khá nhiều thư viện bằng tay vào OS. Anh có đề xuất cách nào để build Ibus-Bamboo gọn nhẹ nhất không ạ, có thể bỏ phần giao diện đi chỉ cần build và sử dụng Bamboo core-engine không?

**Comment by LuThaiHoc** [comment]
Hi, mình phát hiện ra là có vẻ như ibus-daemon không connect được tới ibus bus:
**ibus-daemon -rsv**
`portal is not running: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.IBus exited with status 1`

**Comment by luongthanhlam** [comment]
@LuThaiHoc bạn fix được lỗi này chưa?
