### ISSUE TITLE
Không gõ được tiếng việt trên Firefox

### ISSUE THREAD

**Issue by namnh198** [BambooEngine/ibus-bamboo#395]
**Mô tả lỗi**
Không gõ được tiếng việt trên Firefox version > 100

**Các bước tái hiện lỗi**
Trên Firefox không nhận bộ gõ tiếng việt. Ấn `shift + ~` cũng không hiển thị bảng thay đổi tùy chọn. Mặc dù trên google-chrome và các ứng dụng khác vẫn gõ bình thường

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Desktop: Gnome 3.36.8
 - Phiên bản ibus-bamboo: 0.8.2

**Thông tin thêm**
Đã gỡ và cài đặt lại firefox qua apt nhưng vẫn không nhận

**Comment by luongthanhlam** [comment]
bạn lên trang chủ download file deb về cài nhé, cài qua apt thực chất vẫn bản snap https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04
