### ISSUE TITLE
Lỗi nhân đôi phím đ khi gõ trên thanh tìm kiếm Firefox

### ISSUE THREAD

**Issue by revoluzionario** [BambooEngine/ibus-bamboo#396]
Mình gõ ở chế độ 3 trên thanh tìm kiếm Firefox, bảng gõ Vietnamese (Bamboo). Lỗi này thi thoảng hơi bất tiện nên mình muốn hỏi cách sửa nếu có.
**Môi trường**
 - OS và version: Fedora 37
 - Desktop: Gnome Wayland
 - Phiên bản ibus-bamboo: bản mới nhất

**Comment by revoluzionario** [comment]
P/s 2: Hóa ra là có người từng lên issue về vấn đề này rồi, nhưng có điểm khác là mình dùng Wayland. Vậy thì làm sao để sửa trên Wayland ạ? Mình cảm ơn!

**Comment by revoluzionario** [comment]
Mình gõ ở chế độ 3 trên thanh tìm kiếm Firefox, bảng gõ Vietnamese (Bamboo). Lỗi này thi thoảng hơi bất tiện nên mình muốn hỏi cách sửa nếu có.
**Môi trường**
 - OS và version: Fedora 37
 - Desktop: Gnome Wayland
 - Phiên bản ibus-bamboo: bản mới nhất

**Comment by luongthanhlam** [comment]
các chế độ gõ sử dụng phím backspace giả đều bị lỗi này do xung đột với khung gợi ý của trình duyệt, cách sửa tạm thời là chuyển sang chế độ gõ 1 (preedit) nhé bạn.
