### ISSUE TITLE
Ứng dụng bị lost focus khi chuyển ngôn ngữ bằng Super + Space

### ISSUE THREAD

**Issue by ppvan** [BambooEngine/ibus-bamboo#397]
**Mô tả lỗi**

 (đã test trên firefox (native), terminal (flatpak), và vscode(native))
Ở tất cả ứng dụng khi đổi ngôn ngữ bằng phím tắt Super Space sẽ mất focus và buộc phải click chuột để focus cửa sổ đang gõ
**Các bước tái hiện lỗi**

1. Mở một ứng dụng bất kỳ
2. Gõ tiếng Anh hoặc việt
3. Đổi ngôn ngữ bằng Supper+Space
4. Focus vào ứng dụng đang gõ bị mất

**Kết quả mong muốn**

- Vẫn focus vào ứng dụng đang gõ

**Môi trường**
 - OS và version: Arch Linux 
 - Desktop: Gnome 43 (gnome-shell 1:43.3-2)
 - Phiên bản ibus-bamboo: 0.8.2_RC3-1 (AUR)

**Thông tin thêm**
- Tất cả setting của ibus-bamboo ở chế độ mặc định
- Lỗi xảy ra trên Xorg (không chắc về Wayland)
- Đã tắt tất cả gnome extension và tất cả yếu tố có thể ảnh hưởng.

**Comment by TruongTrongThanh** [comment]
@ppvan lỗi này theo mình biết là của bên compositor Gnome Mutter, không liên quan tới bamboo.
https://gitlab.gnome.org/GNOME/mutter/-/issues/2626
Bạn có thể downgrade xuống 43.2 để tránh bug hoặc chờ tụi GNOME release bản 44.

**Comment by ppvan** [comment]
Cảm ơn bác. Tụi dev GNOME ngày càng chán, này phải qua VM thôi
