### ISSUE TITLE
không thể gõ tiếng việt trên google docs

### ISSUE THREAD

**Issue by ThanhPhu-Dev** [BambooEngine/ibus-bamboo#398]
**Mô tả lỗi**

1. mở trình duyệt chrome
2. vào https://docs.google.com/document/u/0/
3.  gõ cụm từ "công cụ kiểm thử"

**Kết quả thực tế**
không thể gõ được tiếng việt với 6 loại tùy chọn của bamboo
**Kết quả mong muốn**
có thể gõ được tiếng việt

**Môi trường**
 - google chrome Version 109.0.5414.119 (Official Build) (64-bit)
 - IBus 1.5.27
 - ibus-bamboo 0.8.2

**Thông tin thêm**
gõ trên công cụ tìm kiểm của trình duyệt bình thường, lổi chỉ xảy ra khi dùng google docs

config env:
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT4_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
GLFW_IM_MODULE=ibus

**Comment by ThanhPhu-Dev** [comment]
add comment

**Comment by DangDinhThi** [comment]
Chào bác, @googlesky 
Bác có thể confirm lại với Version 113.0.5672.126 (Official Build) (64-bit) không ạ.
thật sự thì không gõ được trong google docs như !1 đã nói ạ.

**Comment by googlesky** [comment]
Chào bạn @DangDinhThi ,
Mình confirm đang trên Version 115.0.5790.13 (Official Build) beta (64-bit) và vẫn đang gõ trên google docs bình thường 
![image](https://github.com/BambooEngine/ibus-bamboo/assets/4094347/063b4109-46af-4cc3-93c1-7d3384f3f5a3)

Maybe vấn đề của bạn chỉ cần add  vào /etc/environment
```
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT4_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
```
Là ok
