### ISSUE TITLE
Tắt thông báo lỗi "{tên ứng dụng} has no capability of surrounding-text feature"

### ISSUE THREAD

**Issue by Lephat902** [BambooEngine/ibus-bamboo#399]
**Mô tả lỗi**
Đây không phải lỗi nhưng là một sự báo warnings không cần thiết gây ảnh hưởng tới hard disk

**Các bước tái hiện lỗi**
Ví dụ:
1. Mở một chương trình có khả năng nhận text ngoài gedit như gnome-terminal-server, google chrome, vscode,...
2. Gõ bất kỳ ký tự chữ nào
3. Logs sẽ hiện ra rất nhiều warnings có dạng "{tên ứng dụng} has no capability of surrounding-text feature", với khoảng 2-3 ký tự tiếng Việt mình gõ sẽ có khoảng 8-9 warnings.

**Kết quả mong muốn**
Mình xin nhờ bạn dev giúp mình tắt đi warnings này, warnings được log liên tục khi gõ sẽ gây ảnh hưởng tới hard disk.
Một chương trình cũ khác là ibus-unikey mình sử dụng không có log warnings này, tuy nhiên ibus-unikey lại có nhiều lỗi khó chịu và đã không còn được bảo trì nên mình cũng không muốn sử dụng làm công cụ gõ chính thức.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2023-03-23 21-23-22](https://user-images.githubusercontent.com/80326548/227233985-3f29ae07-c348-413a-a6d3-b4e34b52343d.png)

**Môi trường**
 - OS và version: Ubuntu 22.04.02
 - Desktop: Gnome 42.5
 - Phiên bản ibus-bamboo: 0.8.2

**Comment by thanhminhmr** [comment]
Mình không nghĩ đây là lỗi in ra bởi `ibus-bamboo` đâu. Mình không tìm thấy cụm "has no capability of surrounding-text feature" chỗ nào trong mã nguồn `ibus-bamboo` cả.

**Comment by luongthanhlam** [comment]
bạn xóa dòng này đi https://github.com/BambooEngine/ibus-bamboo/blob/d14fd96d860866f8a813d2203829eb10c8a880c0/src/ibus-bamboo/engine.go#L97 rồi build lại là được nhé
