### ISSUE TITLE
không thể sự dụng tổ hợp phím Shift + ~ để đổi chế độ gõ

### ISSUE THREAD

**Issue by Fozzyishere** [BambooEngine/ibus-bamboo#402]
**Mô tả lỗi**
không thể sự dụng tổ hợp phím Shift + ~ để đổi chế độ gõ dựa theo README.md

**Các bước tái hiện lỗi**
1. nhấp chuột vào khung nhập dữ liệu (đã thử trên firefox, libreoffice và GNOME search bar)
2. nhấn tổ hợp phím Shift + ~

**Kết quả mong muốn**
bản hiển thị chế độ gõ hiện lên

**Ảnh chụp màn hình, hoặc clip quay màn hình**
nil

**Môi trường**
 - OS và version: Fedora Workstation 38
 - Desktop: Gnome 44 wayland
 - Phiên bản ibus-bamboo: 0.8.2-25.26

**Thông tin thêm**
`env | grep ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus`

**Comment by luongthanhlam** [comment]
Duplicate https://github.com/BambooEngine/ibus-bamboo/issues/374
