### ISSUE TITLE
không thể tìm thấy config file nếu build from source

### ISSUE THREAD

**Issue by Fozzyishere** [BambooEngine/ibus-bamboo#403]
**Mô tả lỗi**
Không thể tìm thấy config file tại `~/.config/ibus-bamboo/ibus-bamboo.config.json` (dựa theo [#188](https://github.com/BambooEngine/ibus-bamboo/issues/188))

**Các bước tái hiện lỗi**
- Build from source theo [hướng dẫn](https://github.com/BambooEngine/ibus-bamboo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-m%C3%A3-ngu%E1%BB%93n)
- Mở thư mục ~/.config/ibus-bamboo/

**Kết quả mong muốn**

- File config xuất hiện và có thể edit được

**Kết quả đạt được**
- Thư mục trống (show hidden files đã bật. Sử dụng cd+ls trong terminal (lẫn sudo và không) cho kết quả tương tự)

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![image](https://user-images.githubusercontent.com/101717395/235602384-389d0297-4ad3-4095-a669-f0e54f4561c4.png)

**Môi trường**
    OS và version: Fedora Workstation 38
    Desktop: Gnome 44 wayland
    Phiên bản ibus-bamboo: 0.8.2-25.26

**Comment by luongthanhlam** [comment]
bạn gõ được tiếng Việt chưa? file Config chỉ xuất hiện sau khi ibus-bamboo được kích hoạt sử dụng
