### ISSUE TITLE
Lỗi gõ tiếng Việt trên Chrome - Ký tự trùng và hiển thị không đúng

### ISSUE THREAD

**Issue by manhit96** [BambooEngine/ibus-bamboo#404]
**Mô tả lỗi**
Khi gõ tiếng Việt bằng bộ gõ IBus Bamboo trên Chrome, ký tự bị trùng và không hiển thị đúng. Lỗi này xảy ra bất kể trang web hay tính năng nào trên Chrome. Cụ thể, các lỗi như sau:
- Các nguyên âm có dấu bị thêm một dấu sắc nữa ở sau, và một số trường hợp có thêm ký tự không mong muốn. Ví dụ: "ô" trở thành "ôô", "ố" trở thành "ôôố", "ẩm" trở thành "âầm", "uời" trở thành "uơời".
- Các phụ âm cuối trong từ bị lặp lại. Ví dụ: "năm" trở thành "naăm", "sáu" trở thành "sauáu", "bảy" trở thành "baâyẩy".
- Dấu hỏi và dấu ngã không được hiển thị đúng. Ví dụ: "tám" trở thành "tamám", "chín" trở thành "chinín".

**Các bước tái hiện lỗi**
1. Mở Chrome Version 113.0.5672.63 (Official Build) (64-bit)
2. Chuyển sang bộ gõ IBus Bamboo
3. Gõ "một" (sử dụng kiểu gõ Telex và chế độ Pre-edit)
4. Kết quả hiển thị là "mo ôtột"

**Kết quả mong muốn**
Khi gõ "một" bằng bộ gõ IBus Bamboo trên Chrome, kết quả hiển thị phải là "một" chứ không phải "mo ôtột"

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2023-05-07 13-11-06](https://user-images.githubusercontent.com/13987005/236660917-b8d8bacd-c646-4a09-a033-f586290b500f.png)
![Screenshot from 2023-05-07 13-10-13](https://user-images.githubusercontent.com/13987005/236660919-e7f84176-ec89-4d98-a0bd-12312f0f82f5.png)

**Môi trường**
- OS và version: Ubuntu 22.04
- Desktop: Gnome (mặc định)
- Phiên bản ibus-bamboo: (bản mới nhất là 0.8.2)
- Trình duyệt: Chrome Version 113.0.5672.63 (Official Build) (64-bit)
- Kiểu gõ: Telex
- Chế độ gõ: Pre-edit (đổi kiểu gõ và chế độ gõ khác vẫn lỗi tương tự)

**Thông tin thêm**
Biến môi trường và config:
```
QT_IM_MODULE=ibus
QT4_IM_MODULE=ibus
GTK_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
XMODIFIERS=@im=ibus
GLFW_IM_MODULE=ibus

➜  ~ find ~/.config/ibus/bus/          
cat $(find ~/.config/ibus/bus/)               

/home/manhdv51/.config/ibus/bus/
/home/manhdv51/.config/ibus/bus/47553ecb621a479c9572c856a0a588a9-unix-wayland-0
/home/manhdv51/.config/ibus/bus/47553ecb621a479c9572c856a0a588a9-unix-0
cat: /home/manhdv51/.config/ibus/bus/: Is a directory
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/manhdv51/.cache/ibus/dbus-iSs9QU3G,guid=05d2ad871fa9951a279a180964573bc0
IBUS_DAEMON_PID=21254
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/manhdv51/.cache/ibus/dbus-iSs9QU3G,guid=05d2ad871fa9951a279a180964573bc0
IBUS_DAEMON_PID=21254
```

**Comment by shinomax** [comment]
Yeah currently i goin trouble with that. Let try using extensions on chrome.

**Comment by luongthanhlam** [comment]
trong ô nhập liệu trên Chrome bạn nhấn `Shift+~` và chọn chế độ gõ Pre-edit nhé
