### ISSUE TITLE
không gõ được tiếng việt ở opera và vivaldi

### ISSUE THREAD

**Issue by jjigoku** [BambooEngine/ibus-bamboo#405]
trước đây khi mới cài tầm vài tháng mình gõ được tiếng việt trên Endeavour, nhưng xài được tầm 1 tháng thì không gõ được nữa, sau khi cập nhật vài gói phần mềm, mình gõ được tiếng việt ở mọi nơi, kể cả Firefox, nhưng riêng các trình duyệt nhân Chromiun như Opera, Vivaldi thì k gõ được, nó bị lỗi như này khi gõ 

tại sao lại như vậy

khi gõ trên opera, vivaldi

ti sao li nh y

**Môi trường**
 - OS và version: (Endeavour ban moi nhat)
 - Desktop: (Xfce)
 - Phiên bản ibus-bamboo:  0.8.2

**Comment by luongthanhlam** [comment]
bạn nhấn `Shift+~`, chọn kiểu gõ số 1 và thử lại nhé
