### ISSUE TITLE
[GNOME] Bị đúp ký tự đầu tiên lúc gõ trên thanh tìm kiếm

### ISSUE THREAD

**Issue by kienmatu** [BambooEngine/ibus-bamboo#406]
**Mô tả lỗi**

Khi bấm Super và bắt đầu gõ để tìm kiếm app trên GNOME, thì chữ cái đầu tiên sẽ bị đúp.

**Các bước tái hiện lỗi**

Ví dụ:
1. Nhấn Super (Windows) để mở overview của GNOME
2. Gõ `tw` (mục đích để tìm `tweak`)
3. Ô tìm kiếm hiện chữ `ttư`

**Kết quả mong muốn**
Ô tìm kiếm phải hiện chữ `tư`

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2023-05-19 14-08-10](https://github.com/BambooEngine/ibus-bamboo/assets/38078992/58e56f00-4624-4d21-b44a-f8e0b6d59cd2)

**Môi trường**
 - OS và version: Ubuntu 22.04
 - Desktop: GNOME 42.5-0ubuntu1 amd64
 - Phiên bản ibus-bamboo: 0.8.2

**Thông tin thêm**

Đề xuất: Hỗ trợ disable khỏi gnome shell, ngoài lỗi này ra thì đôi lúc save file từ chrome, thì cũng không thể gõ được file name mà phải tắt vi mode, bật lại (Super + Space) mới gõ được tiếp...

**Comment by kienmatu** [comment]
@luongthanhlam , hi mình dùng x11

**Comment by luongthanhlam** [comment]
Bạn có thể đổi sang mode 7 để disable, không stable là sao nhỉ ❓

**Comment by kienmatu** [comment]
Kiểu lúc được lúc không ấy bạn

**Comment by kienmatu** [comment]
Mà mình phát hiện xài mode 1 ngon nhất, đỡ lag lỗi nên lâu giờ chuyển qua preedit xài rồi
