### ISSUE TITLE
Ubuntu 23.04 không cài đặt được phím tắt để chuyển chế độ gõ vi - en

### ISSUE THREAD

**Issue by donhuvy** [BambooEngine/ibus-bamboo#407]
Ubuntu 23.04 không cài đặt được phím tắt để chuyển chế độ gõ vi - en .

![image](https://github.com/BambooEngine/ibus-bamboo/assets/1328316/4a97fa55-884d-477a-b49d-0513a4ff7725)

![image](https://github.com/BambooEngine/ibus-bamboo/assets/1328316/e5ad222d-2ef9-4a26-97e0-85a3d8c45f61)

```
firerose@firerose-desktop:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
firerose@firerose-desktop:~$ 
```
việc này rất bất tiện, vì phải dùng Click chuột để chuyển ngôn ngữ, tốn nhiều thời gian.

**Comment by donhuvy** [comment]
Hi, em học cùng lớp cao học với anh. Phím Super (chắc em dùng macOS à) có phải phím Shift không em?

**Comment by thanhminhmr** [comment]
Hình như bên MacOS nó là phím ⌘ (Command) anh ạ. Em không dùng Mac nên cũng không rõ lắm.

**Comment by donhuvy** [comment]
Là phím Windows, anh sẽ thử phím Windows với Ubuntu 23.04 để đổi ngôn ngữ của bộ gõ.

![image](https://github.com/BambooEngine/ibus-bamboo/assets/1328316/c08a983b-2b96-48dc-b5b4-86b1edb8d1fd)

**Comment by donhuvy** [comment]
Treen GitHub issue khoong go duoc Tieng Vieet.

Trên Ubuntu 23.04 , bàn phím chuẩn 101-104 phím, anh dùng Windows + Space có thể chuyển được chế độ vi - en. Thông tin thêm, comment trên GitHub issue, không thể gõ được Tiếng Việt, dù đã ở chế độ vi (phát hiên ra trong chính comment này).

**Comment by donhuvy** [comment]
![image](https://github.com/BambooEngine/ibus-bamboo/assets/1328316/53ea346a-5ee1-438d-b596-763aa46cdcac)

**Comment by luongthanhlam** [comment]
setting trong hình dùng để cấu hình chế độ gõ (không gạch chân/có gạch chân), bạn muốn chuyển vi-en cần vào setting của Gnome để chuyển.
