### ISSUE TITLE
Không gõ được tiếng việt trên firefox (endeavour)

### ISSUE THREAD

**Issue by classborke09** [BambooEngine/ibus-bamboo#408]
**Mô tả lỗi**
Mình gõ được tiếng việt trên tất cả ứng dụng, trừ mỗi firefox ra dù mình đã chuyển đổi tất cả các chế độ gõ

**Các bước tái hiện lỗi**

      1.mở firefox
      2.gõ trên thanh tìm kiếm
      3.gõ 'xin chào'

**Kết quả mong muốn**
xin chào
**Kết quả thực tế**
xin chaof

OS: Endeavour 
DE: KDE Plasma 5.27.5 ( X11 )
Ibus-bamboo 0.8.2

**Comment by quangcaol** [comment]
Mình cũng bị lỗi như bạn, không biết bạn fix như thế nào ?
