### ISSUE TITLE
Đề xuất: Phân biệt chữ thường/Hoa trong từ khoá "gõ tắt"

### ISSUE THREAD

**Issue by bixycler** [BambooEngine/ibus-bamboo#411]
Mình nghĩ từ khoá trong gõ tắt cần phải súc tích nhất có thể, nên việc không phân biệt thường/Hoa làm giảm sự súc tích đi rất nhiều.

VD có phân biệt thường/Hoa:
```
VN:Việt Nam
Vn:Vietnam
\phi:φ
\Phi:Φ
```

Còn nếu không phân biệt thì phải chế thêm ký tự vô từ khoá để phân biệt làm cho từ khoá rắc rối hơn, VD:
```
v-n:Việt Nam
vn:Vietnam
\phi:φ
\^phi:Φ
```

Tham khảo: Ngay như HTML có truyền thống viết không phân biệt thường/Hoa (`<html>` == `<HTML>`) hay viết thường hết như `onclick` (thay vì camelCase `onClick`), nhưng họ vẫn đặt tên ký hiệu có phân biệt thường/Hoa như
- &phi; = `&phi;` = Greek small letter phi
- &Phi; = `&Phi;` = Greek capital letter phi

**Comment by luongthanhlam** [comment]
bạn update lên bản mới sẽ có phân biệt hoa/thường nếu tắt tùy chọn "Tự động viết hoa" nhé

**Comment by bixycler** [comment]
Cảm ơn Lâm, mình đã gõ tắt phân biệt thường/Hoa được rồi.
