### ISSUE TITLE
Lỗi ở Ubuntu 22.04 "đôi khi kí tự bị đảo lộn vị trí khi nhấn"

### ISSUE THREAD

**Issue by fundokukiri** [BambooEngine/ibus-bamboo#413]
**Mô tả lỗi**

Khi chuyển sang chế độ gõ tiếng việt đôi khi gõ nhiều kí tự nhanh liên tiếp xảy ra lỗi kí tự được gõ thứ 2 sẽ nhảy lên đầu

**Comment by luongthanhlam** [comment]
bạn nhấn Shift+~ ở form nhập liệu rồi chọn chế độ gõ số 1 nhé
