### ISSUE TITLE
Package cho debian 12

### ISSUE THREAD

**Issue by ppvan** [BambooEngine/ibus-bamboo#414]
Package cho debian 12 (bookworms) được k ạ?

**Comment by luongthanhlam** [comment]
bạn thử lại nhé https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo

**Comment by ppvan** [comment]
Em cài được rồi ạ.

**Comment by abcd1222** [comment]
Mới cài cho Debian Testing thì bị lỗi File has unexpected size (1510872 != 1510536). Mirror sync in progress?.
![a_2023-07-24_20-51-34](https://github.com/BambooEngine/ibus-bamboo/assets/39787218/dc8f3406-ba41-43e2-ae6d-58795c861ee4)

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn xem (apt-get update hoặc apt install ibus-bamboo --fix-mising)
