### ISSUE TITLE
can you make ibus to appimage format , appimage can run every

### ISSUE THREAD

**Issue by newyorkthink** [BambooEngine/ibus-bamboo#415]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở gedit
2. Gõ abc
...
4. Thấy xyz

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 20.04)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Thông tin thêm**

**Comment by luongthanhlam** [comment]
it's impossible as ibus engines can't interact with host ibus from a sandboxed environment
