### ISSUE TITLE
Đổi keyboard shortcut để chuyển đổi ngôn ngữ không hoạt động

### ISSUE THREAD

**Issue by mnguyen081002** [BambooEngine/ibus-bamboo#418]
**Mô tả lỗi**
Đổi keyboard shortcut để chuyển đổi ngôn ngữ không hoạt động

**Các bước tái hiện lỗi**
Chạy ibus-setup -> Đổi next input method thành "<Control><Shift>" -> restart -> ấn Ctrl + Shift -> Không hoạt động

**Kết quả mong muốn**
Chạy ibus-setup -> Đổi next input method thành "<Control><Shift>" -> restart -> ấn Ctrl + Shift -> Đổi ngôn ngữ

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://github.com/BambooEngine/ibus-bamboo/assets/76799726/bf402b3f-81e2-47d6-b637-81f9cf3e2275)

**Môi trường**
 - OS và version: Ubuntu 23.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: 0.8.2

**Comment by luongthanhlam** [comment]
trên ubuntu bản mới, bạn cần đổi trong Setting của hệ thống trong mục Keyboard Shortcuts ▸ Customize Shortcuts ▸ Typing.

**Comment by mnguyen081002** [comment]
Đổi trong Keyboard Shortcuts ▸ Customize Shortcuts ▸ Typing sử dụng thành công Ctrl + Shift, nhưng không thể ấn Ctrl + Shift + [Keyboard] được nữa. Cảm ơn bạn đã hỗ trợ, bây giờ tôi sẽ tìm kiếm câu trả lời ở Ubuntu
