### ISSUE TITLE
không mở được bảng chọn trên Firefox nhưng chrome lại được

### ISSUE THREAD

**Issue by nghia4mt** [BambooEngine/ibus-bamboo#419]
- OS: Fedora Kde 38 Wayland
- Đã thêm các biến môi trường vào /etc/profile
- chỉ mở được bảng chọn ( Shift + ~ ) trong chrome nhưng Firefox và các app khác không được, đã thử xoá Firefox và cài lại firefox-wayland

**Comment by luongthanhlam** [comment]
bạn xóa firefox từ snap và cài từ ppa xem https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04

**Comment by nghia4mt** [comment]
> bạn xóa firefox từ snap và cài từ ppa xem https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04

Mình xài fedora ý, mình xoá flatpak và cài từ repo rồi

**Comment by luongthanhlam** [comment]
có vẻ bạn đang chạy firefox trong chế độ wayland, mà wayland thì không support tính năng tùy chọn chế độ gõ của ibus-bamboo. Bạn thử chạy `unset MOZ_ENABLE_WAYLAND && firefox` xem

**Comment by nghia4mt** [comment]
Để mình test thử, không được nữa thì về máng cũ xorg thôi
