### ISSUE TITLE
Không gõ được tiếng việt trên telegram, goldendict(Qt)

### ISSUE THREAD

**Issue by tea0112** [BambooEngine/ibus-bamboo#422]
env | grep "IM_MODULE\|XMODIFIERS"
Kết quả:
![image](https://github.com/BambooEngine/ibus-bamboo/assets/35191308/43b21c58-8e51-44fa-954f-b2d60358b415)
Chrome mình vẫn gõ tốt tiếng việt. Mình đang dùng xubuntu 22.04.
Mình thấy do 2 ứng dụng trên đều là Qt nên vậy.

**Comment by luongthanhlam** [comment]
mình vẫn gõ bình thường trên xubuntu 22.04, bạn thử tham khảo thêm các lỗi thường gặp ở wiki https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60
