### ISSUE TITLE
Ngõ tắt không hoạt động khi nhấn enter hoặc các dấu câu

### ISSUE THREAD

**Issue by HM-Huong** [BambooEngine/ibus-bamboo#423]
**Mô tả lỗi**
Ngõ tắt không hoạt động khi nhấn enter hoặc các dấu câu

**Các bước tái hiện lỗi**
1. cài gõ tắt "ko" thành "không"
2. ngõ "ko" rồi ấn enter hoặc các dấu câu như: . , ? !
3. thấy ko

**Kết quả mong muốn**
"ko" chuyển thành "không"

**Comment by luongthanhlam** [comment]
bạn cài bản mới (v0.8.3) và thử lại nhé
