### ISSUE TITLE
[Feature Request] RPMs for Fedora 39

### ISSUE THREAD

**Issue by runlevel5** [BambooEngine/ibus-bamboo#425]
Firstly I would like to extend my gratitude for your hard work on maintaining one of the best Vietnamese Input software for Linux.

As you might have known, Fedora 39 will be released in October 2023 and the beta testing is on-going. I would like to ask if you could enable Fedora 39 build for https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo

Many thanks in advance

**Comment by luongthanhlam** [comment]
Thank you for the information, but currently Fedora 39 is not available in OBS
<img width="1422" alt="Screenshot 2023-09-21 at 20 13 40" src="https://github.com/BambooEngine/ibus-bamboo/assets/26364140/7e70f5d8-ce54-48a7-9148-933daeaf5312">

**Comment by runlevel5** [comment]
Oh I see. It's a bit too early I guess. I will re-open this issue once the time is right.
