### ISSUE TITLE
Không gõ được tiếng việt Wayland app

### ISSUE THREAD

**Issue by datthanhdoan** [BambooEngine/ibus-bamboo#427]
Mình set Preferred Ozone platform của brave là Wayland thì không thể gõ tiếng việt ,ấn shift + ~ cũng không hiện menu ( set Wayland với edge , chrome cũng bị tương tự ) , khi mình chuyển lại x11 hoặc default thì lại sử dụng bình thường . Mọi ngừoi có cách nào giải quyết không ? 

Mình cài bamboo qua apt (0.8.3)
Ubuntu 22.04
Gnome 42.9

**Comment by luongthanhlam** [comment]
bạn theo dõi ở đây nhé https://bugs.chromium.org/p/chromium/issues/detail?id=1183262
