### ISSUE TITLE
Lỗi lặp ký tự trên đường link của trình duyệt brave

### ISSUE THREAD

**Issue by vuonglv1602** [BambooEngine/ibus-bamboo#43]
**Mô tả lỗi**
Mình muốn tìm kiếm ngay trên đường link của trình duyệt brave, nhưng khi nhập các ký tự tiếng việt thì có hiện tượng lặp ký tự, vd: "Điều khiển" thì ra "dđiêều khiêển" hay "dđiều khiển"
**Các bước tái hiện lỗi**
1. Bật chế độ gõ 3
2. Mở brave gõ vào thanh đường dẫn cụm từ "điều khiển"

**Ảnh chụp màn hình, hoặc clip quay màn hình**
[Ảnh mô tả lỗi](https://photos.app.goo.gl/5g8dunXDSfrrMu366)

**Môi trường**
 - OS và version: Ubuntu 19.04
 - Desktop: Gnome
 - Phiên bản ibus: 1.5.19
 - Phiên bản ibus-bamboo: v0.4.8

**Comment by vuminhcongvmc** [comment]
Vì Brave browser sử dụng nhân chromium như google chrome nên ibus-bamboo sẽ bị lỗi khi gõ trên trình duyệt này, banj nên sử dụng trình duyệt firefox để tránh lỗi.
Nếu bạn muốn tiếp tục sử dụng brave thì bạn có thể sử dụng chế độ 1 cho tác vụ bình thường còn khi code bạn có thể sử dụng chế độ 4 để code cho ổn định.
