### ISSUE TITLE
Lỗi hiện popup Remote desktop trên Gnome 45

### ISSUE THREAD

**Issue by berlinx2104** [BambooEngine/ibus-bamboo#430]
**Mô tả lỗi**
Nhảy popup Remote desktop khi sử dụng bộ gõ ibus-bamboo, tắt đi và click vào bất kỳ của sổ nào cũng hiện lại popup trên.
Update: Lỗi chỉ xảy ra trên Gnome Wayland, Gnome Xorg vẫn hoạt động tốt.

**Các bước tái hiện lỗi**
1. Mở google-chrome
2. Chuyển đổi sang bộ gõ ibus-bamboo
3. Gõ
4. Click vào cửa sổ bất kỳ -> Hiện popup Remote desktop
5. Tắt popup đi, click vào cửa sổ bất kì -> Hiện popup lại

**Kết quả mong muốn**
Không hiện của sổ popup trên

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2023-09-28 14-48-24](https://github.com/BambooEngine/ibus-bamboo/assets/146148325/18b5d63d-e452-4029-bdd0-0e9875fb520d)

**Môi trường**
 - OS và version: openSUSE Tumbleweed
 - Desktop: Gnome  45
 - Phiên bản ibus-bamboo: 0.8.3-2.3 from OBS

**Comment by luongthanhlam** [comment]
bạn tắt tính năng "Bắt sự kiện chuột" trong cài đặt của ibus-bamboo là hết nhé

**Comment by maisonhai3** [comment]
Mong các contributor đưa cái fix lỗi này vào bản build mới nhất, chưa đừng dừng lại ở mức trả lời bug như này.

Hôm nay, 9/1/2023,
mình update Bamboo trên Fedora 39, lỗi này vẫn tồn tại.

**Comment by ppvan** [comment]
Lỗi này có vẻ cũng xuất hiện trên vscode, người bạn cũ election
vscode 1.89.1 aur 
GNOME 46.2
Arch
