### ISSUE TITLE
Gõ tắt: Không còn gõ tắt được với những từ gõ tắt có chứa số

### ISSUE THREAD

**Issue by DuongQuy123** [BambooEngine/ibus-bamboo#432]
Trong phiên bản 0.8.3 mới nhất mình tải về sử dụng thì mình không còn có thể gõ tắt cho những từ có chứa số trong đó nữa.
Ví dụ: Đây là 1 danh sách nhỏ những từ mà trước giờ mình vẫn dùng để tạo ra các ký tự Unicode thay thế để tạo đánh dấu văn bản và thư mục, mình cần số thứ tự để sắp xếp theo thứ tự ưu tiên giảm dần và nó tự xếp theo thứ tự bảng chữ cái.
csao:✪
csao2:✬
csao3:✶
csao4:(⭐)

Bây giờ tất cả trở thành:
csao:✪
csao2:✪2
csao3:✪3
csao4:✪4

Ở phiên bản mới nhất đã không còn có thể ghi nhận số cũng là một phần trong chuỗi ký tự đang gõ nữa, nó khiến cho việc gõ tắt gặp phải lỗi ngắt ra như trên, các bạn có thể khôi phục lại giúp mình như trước được hay không vì việc đánh số 1,2,3... để lấy các ký tự unicode để đánh dấu với mình rất quan trọng để sắp xếp văn bản và thư mục, cám ơn các bạn

Đây là ví dụ nhỏ về việc mình cần các ký tự này để sắp xếp thư mục
![ảnh](https://github.com/BambooEngine/ibus-bamboo/assets/68831019/d04ef981-d04a-490d-ae94-ced19291e506)

**Môi trường**
 - OS và version: KDE Neon 5.27
 - Desktop: KDE
 - Phiên bản ibus-bamboo: 0.8.3
- Cách cài repo: add-apt-repository -y ppa:bamboo-engine/ibus-bamboo

**Comment by luongthanhlam** [comment]
bạn cập nhật lên bản mới nhất để fix lỗi này nhé!
