### ISSUE TITLE
Các phím tắt của LyX ngừng hoạt động khi update lên 0.8.3

### ISSUE THREAD

**Issue by ndgnuh** [BambooEngine/ibus-bamboo#433]
**Mô tả lỗi**
Phím tắt `Alt + m <phím bất kỳ>` không hoạt động khi đang bật Bamboo.

**Các bước tái hiện lỗi**
Ví dụ:

1. Cài Bamboo, phiên bản 0.8.3.
1. Mở LyX
2. Nhấn phím tắt `Alt + m` rồi nhấn `d`
3. Phím tắt không hoạt động

**Kết quả mong muốn**
Hộp thoại nhập công thức toán hiện ra (và các phím tắt khác cũng hoạt động).

**Ảnh chụp màn hình, hoặc clip quay màn hình**

[Video cài các bản khác nhau của Bamboo và thử phím tắt trên LyX](https://www.youtube.com/watch?v=4mGnqWADb2w)

**Môi trường**
 - OS và version: Debian 12
 - Desktop: AwesomeWM
 - Phiên bản ibus-bamboo: 0.8.3

**Thông tin thêm**
Phiên bản cuối cùng không mắc lỗi này là `v0.8.2-RC18`

**Comment by luongthanhlam** [comment]
bạn cập nhật lên bản v0.8.3-RC5 và chọn chế độ gõ số 5 nhé
