### ISSUE TITLE
Lỗi đánh chữ trên Teams (Ubuntu) sau khi update từ bản v0.8.3-RC3, v0.8.3-RC4

### ISSUE THREAD

**Issue by tuyennn** [BambooEngine/ibus-bamboo#434]
**Mô tả lỗi**
- Sử dụng bảng mã Telex gõ tiếng việt trên phần mềm Teams

**Các bước tái hiện lỗi**
1. Mở Teams trên Ubuntu
2. Gõ "Nói chung là kinh vậy sao"
3. Thấy "Noiói chung laà kinh vaâyậy sao"

**Kết quả mong muốn**
Thấy "Nói chung là kinh vậy sao"

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://github.com/BambooEngine/ibus-bamboo/assets/4010395/e69c02e0-045b-4a3e-a104-f7fce870379c)

**Môi trường**
 - OS và version: Ubuntu 23.04
 - Desktop: **mặc định**
 - Phiên bản ibus-bamboo: v0.8.3-RC3, v0.8.4-RC3

**Thông tin thêm**
Lỗi trên phầm mềm Teams, từ sau phiên bản ibus-bamboo: v0.8.3-RC3, v0.8.4-RC3

**Comment by luongthanhlam** [comment]
bạn nhấn `Shift+~` và chọn 1 hoặc 3 để chuyển sang chế độ gõ phù hợp nhé
