### ISSUE TITLE
Gõ tiếng việt trên terminal của Cent os 7

### ISSUE THREAD

**Issue by hungn17** [BambooEngine/ibus-bamboo#437]
Hi , cho mình hỏi , mình muốn gõ tiếng việt trên terminal của cent os 7 thì cài theo hướng dẫn nào nhỉ ?

**Comment by luongthanhlam** [comment]
bạn đã cài GUI/DE cho centos chưa? nếu rồi thì làm theo hướng dẫn ở đây nhé https://github.com/BambooEngine/ibus-bamboo#c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-openbuildservice
