### ISSUE TITLE
<Feature request> Ibus-bamboo không hoạt động trên Deepin OS V23

### ISSUE THREAD

**Issue by ngocdd** [BambooEngine/ibus-bamboo#438]
Hiện tại mình không sử dụng được Ibus-bamboo trên Deepin OS V23, Team phát triển có plan support Ibus-bamboo trên Deepin OS không nhỉ?

**Comment by luongthanhlam** [comment]
bạn gặp lỗi gì vậy?

**Comment by goatastronaut0212** [comment]
> Hiện tại mình không sử dụng được Ibus-bamboo trên Deepin OS V23, Team phát triển có plan support Ibus-bamboo trên Deepin OS không nhỉ?

Mình tưởng là Deepin OS cũng dựa trên Debian chứ nhỉ, chắc là cũng xài mấy cái câu lệnh tương tự như Debian? Nếu bạn có vấn đề gì thì có thể cung cấp thêm thông tin nữa có được không?

**Comment by goatastronaut0212** [comment]
Đóng issue này lại có vẻ là được rồi. Dù gì đi nữa theo cá nhân mình cảm nhận về Deepin, nó là 1 OS của Trung Quốc và đối tượng hướng đến của nó chủ yếu chỉ dành cho người Trung Quốc đúng là 1 số người khác cũng có thể dùng nó nhưng 

1. Mình sẽ nghi ngờ khả năng chúng ta tương tác thế nào với họ?
2. Liệu họ có chấp nhận 1 gói ibus-bamboo vào repo của họ không?
3. Deepin dù có nói thế nào cũng chỉ là dựa trên Ubuntu/Debian, vì ngoài cái DE ra không có gì quá khác biệt cả. Chúng ta chỉ cần lấy package của ad Lâm về cài và nó hoạt động vẫn tốt.
4. Cho rằng 1, 2 đã thực hiện được và bỏ qua 3 thì câu hỏi mình đặt ra là ai sẽ làm nó? Có chắc rằng gói sẽ được hỗ trợ và giám sát đó tới cùng với 1 bộ tiêu chuẩn mà bên Deepin đưa ra không? Không thì sẽ chẳng có gói nào ở đó cả.

Nhưng mình thấy 1 và 2 là trường hợp khó mà thành hiện thực được nên việc cài đặt từ third party không phải là quá tệ.

**Comment by goatastronaut0212** [comment]
Đóng lại vì giờ chúng ta có 1 báo cáo lỗi chung ở đây. Nếu bạn vẫn cần hãy comment thêm ở đây nhé

https://github.com/BambooEngine/ibus-bamboo/issues/516
