### ISSUE TITLE
KHÔNG thêm được các kí tự đặc biệt như: ā, Ṃ, ś...

### ISSUE THREAD

**Issue by mimosahouse** [BambooEngine/ibus-bamboo#439]
**Mô tả lỗi**
 Tôi cần thêm các kí tự  đặc biệt như:  ā, Ṃ, ś...

**Các bước tái hiện lỗi**
Chọn chương trình Vietnamese(Bamboo)

1. Mở Kiểu gõ > tự định nghĩa kiểu gõ
 "Telex W": {
      "-": "A_Ā",
...
2. Sau đó khởi động lại ibus (ibus restart)
3. Chọn kiểu gõ Telex W - Nhưng vẫn không gỗ được ký tự đặc biệt đó

**Kết quả mong muốn**
gõ "a" + "-" = "ā"

**Môi trường**
 - OS và version: fedora 38 
 - Desktop:  Gnome,... 
 - Phiên bản ibus-bamboo: 0.8.3

**Thông tin thêm**

**Comment by luongthanhlam** [comment]
để gõ các kí tự đặc biệt này bạn cần dùng chức năng "Gõ tắt" hoặc làm theo hướng dẫn ở đây https://help.ubuntu.com/stable/ubuntu-help/tips-specialchars.html.en
