### ISSUE TITLE
Không gõ được dấu trên MX Linux

### ISSUE THREAD

**Issue by pth-1641** [BambooEngine/ibus-bamboo#440]
**Mô tả lỗi**
Không gõ được dấu trên Chome, Firefox,.. ngoại trừ FeatherPad mặc định của OS

**Môi trường**
- OS và version: MX Linux 23.1
- Desktop: Xfce
- Phiên bản ibus-bamboo: v0.8.3

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn ở đây https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60 và đảm bảo đã cài các gói phụ thuộc như ibus-gtk, ibus-gtk3 ibus-gtk4 
```
sudo apt install ibus-gtk ibus-gtk3 ibus-gtk4
```

**Comment by Hth4nh** [comment]
Tôi đang tốn 2 tiếng chỉ để nhận ra mình chưa cài mấy gói này :))
Cảm ơn bạn nhiều
