### ISSUE TITLE
Lộ mật khẩu trong terminal khi gõ lệnh liên quan tới sudo trong ubuntu 23.10

### ISSUE THREAD

**Issue by LeoPkm2-1** [BambooEngine/ibus-bamboo#441]
**Mô tả lỗi**

Khi nhập mật khẩu của các câu lệnh liên quan tới **sudo**  trong bật chế độ gõ tiếng việt thì bị hiện mật khẩu lên
**Các bước tái hiện lỗi**

Ví dụ: khi sử dụng cậu lệnh `sudo apt update`
1. Mở bộ gõ tiếng việt ở chế độ **VNI**
2. mở terminal `Ctrl Alt T`
3. nhập lệnh `sudo apt update`
4. nhập mật khẩu

**Kết quả mong muốn**

Khi nhập mật khẩu ở bước 4 thì mật khẩu lộ ra, điều này chỉ xảy ra khi bật chế độ gõ là tiếng việt (VNI,TELEX)

**Ảnh chụp màn hình, hoặc clip quay màn hình**

[image_bug](https://ibb.co/R96tcy5)
**Môi trường**
 - OS và version:  **Ubuntu 23.10**
 - Phiên bản ibus-bamboo:  0.8.3

**Comment by luongthanhlam** [comment]
bạn nhấn `Shift+~` và chọn 1 kiểu gõ không gạch chân để khắc phục lỗi này nhé
