### ISSUE TITLE
Không gõ được tiếng Việt trên Chrome Ubuntu 23.10

### ISSUE THREAD

**Issue by minhnq22** [BambooEngine/ibus-bamboo#442]
Mình vừa cập nhật lên Ubuntu 23.10, các ứng dụng khác vẫn sử dụng bình thường, riêng Google Chrome thì không thể gõ được.
Mình đã thử trên những trình duyệt khác cùng nhân Chromium như Edge hay Opera thì vẫn gõ được.

OS: Ubuntu 23.10
Desktop: Gnome 45.0 Wayland
Google Chrome: Version 118.0.5993.88 (Official Build) (64-bit)

**Comment by minhnq22** [comment]
Sau một ngày tìm hiểu vấn đề thì mình nhận ra không phải do Ubuntu 23.10 thay đổi gì, vấn đề vẫn là vì Wayland. Mình buộc phải kích hoạt Wayland trên Chrome thay vì để X11 là vì đã quen với Touchpad Gestures.
[https://www.reddit.com/r/gnome/comments/td8irt/touchpad_gestures_in_chromechromium](url)
Khi để Preferred Ozone platform > Wayland, ibus lập tức không hoạt động với Chrome.
Lúc này cần thêm đoạn này vào bashrc:
```
GTK_IM_MODULE=ibus
```
Câu lệnh khởi động Chrome đầy đủ:
```
google-chrome --enable-features=TouchpadOverscrollHistoryNavigation --gtk-version=4
```

Hướng dẫn khắc phục của ibus-bamboo cũng đã trình bày vấn đề này tại đây.
[https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60](url)
[https://www.reddit.com/r/archlinux/comments/sc0oxo/ibus_japanese_input_not_working_in_google_chrome/](url)

**Comment by mrninhvn** [comment]
Mình không gõ được trên google-chrome-stable bật wayland, firefox wayland chạy bình thường, đã thử các cách trong wiki :(

**Comment by minhnq22** [comment]
Ngay cả khi bạn sử dụng câu lệnh này cũng không được?
```
google-chrome --enable-features=TouchpadOverscrollHistoryNavigation --gtk-version=4
```

**Comment by mrninhvn** [comment]
> Ngay cả khi bạn sử dụng câu lệnh này cũng không được?
> 
> ```
> google-chrome --enable-features=TouchpadOverscrollHistoryNavigation --gtk-version=4
> ```

Đúng rồi bạn, vẫn không được, mình dùng trên Arch

**Comment by minhnq22** [comment]
Bạn kiểm tra biến môi trường xem có ```GTK_IM_MODULE=ibus``` chưa. Biến môi trường này cần được defind ngay sau khi khởi động hệ điều hành.
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng

**Comment by mrninhvn** [comment]
> Bạn kiểm tra biến môi trường xem có `GTK_IM_MODULE=ibus` chưa. Biến môi trường này cần được defind ngay sau khi khởi động hệ điều hành. https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng

Có rồi bạn, mình thử cả chuyển sang `xim`, đều không được.

**Comment by minhnq22** [comment]
> > Bạn kiểm tra biến môi trường xem có `GTK_IM_MODULE=ibus` chưa. Biến môi trường này cần được defind ngay sau khi khởi động hệ điều hành. https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
> 
> Có rồi bạn, mình thử cả chuyển sang `xim`, đều không được.

Bạn thêm vào đâu? .profile hay .bashrc? Tôi không rõ Arch sẽ khác như thế nào nhưng hiện tại Ubuntu 23.10 của tôi vẫn chạy ổn. Tôi đã thêm duy nhất dòng ```GTK_IM_MODULE=ibus``` vào .profile và khởi động Chrome bằng lệnh như trên.

**Comment by mrninhvn** [comment]
> > > Bạn kiểm tra biến môi trường xem có `GTK_IM_MODULE=ibus` chưa. Biến môi trường này cần được defind ngay sau khi khởi động hệ điều hành. https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng
> > 
> > 
> > Có rồi bạn, mình thử cả chuyển sang `xim`, đều không được.
> 
> Bạn thêm vào đâu? .profile hay .bashrc? Tôi không rõ Arch sẽ khác như thế nào nhưng hiện tại Ubuntu 23.10 của tôi vẫn chạy ổn. Tôi đã thêm duy nhất dòng `GTK_IM_MODULE=ibus` vào .profile và khởi động Chrome bằng lệnh như trên.

Mình thêm vào `/etv/enviroment`, chromium đã nhận nhưng chrome và edge thì không.

```
env | grep "IM_MODULE\|XMODIFIERS"
GLFW_IM_MODULE=ibus
GTK_IM_MODULE=ibus
QT4_IM_MODULE=ibus
XMODIFIERS=@im=ibus
CLUTTER_IM_MODULE=ibus
QT_IM_MODULE=ibus
```
