### ISSUE TITLE
Duplicate nội khi chat trên fb khi dùng chrome (ubuntu20.04, ibus từ v0.8.3-RC2 -> v0.8.3-RC5)

### ISSUE THREAD

**Issue by longtqtqn** [BambooEngine/ibus-bamboo#443]
OS: ubuntu 20.04LTS, 
Google Chrome: Version 118.0.5993.70 (Official Build) (64-bit)

Từ version v0.8.3-RC2 -> v0.8.3-RC5 sẽ có lỗi như ở dưới (v0.8.3-RC1 không bị):

Các bước reproduce bug:
1. truy cập domain của facebook
2. chọn 1 người bất kỳ để hiên cửa số chat
3. gõ: "kaka" rồi nhấn enter
4. bên kìa sẽ bị duplicate thành "kakakaka"

**Comment by quangnguyen310** [comment]
mình cũng bị giống v

**Comment by luongthanhlam** [comment]
duplicate https://github.com/BambooEngine/ibus-bamboo/issues/447
> Lỗi này tạm thời mình sẽ không fix do nó xung đột với tính năng gợi ý tìm kiếm trên thanh địa chỉ của Chrome. Bạn có thể workaround bằng cách thêm 1 dấu cách hoặc control rồi mới ấn enter
