### ISSUE TITLE
Tự động đóng Telegram

### ISSUE THREAD

**Issue by khanh1808** [BambooEngine/ibus-bamboo#446]
Mô tả lỗi
Lỗi: Khi sử dụng Telegram, nếu ấn Ctrl A, Ctrl V, ... sẽ bị tự động đóng Telegram dù đã reset hết shortcut của Ibus
Đã thử trên 3 máy khác nhau, cài chung OS và đều bị lỗi này.

Môi trường

    Ubuntu 22.04.3 LTS
    Ubuntu desktop
    Phiên bản ibus-bamboo: IBus 1.5.26
![image](https://github.com/BambooEngine/ibus-bamboo/assets/56547324/ae1084dc-2980-4c6d-81fa-0c5d3589f238)

**Comment by namdt5** [comment]
Mình bị lỗi tương tự trên bản 0.8.3 
Tạm thời tắt chức năng gõ tắt đi thì sẽ ko bị. 
Bật tính năng gõ tắt lên là sẽ bị 

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

![Screenshot from 2023-11-30 10-17-03](https://github.com/BambooEngine/ibus-bamboo/assets/11503877/47862016-d94f-4071-9a0f-be9ebce98d1e)

**Comment by luongthanhlam** [comment]
bạn còn gặp lỗi này chứ? mình test thử thì lỗi này không còn xuất hiện trên bản v0.8.4 nữa

**Comment by goatastronaut0212** [comment]
Có lẽ nên tạm thời đóng lỗi này nếu các bạn vẫn còn lỗi thì hãy tạo 1 báo cáo lỗi mới
