### ISSUE TITLE
Bị duplicate từ khi chỉ gõ một từ duy nhất và nhấn enter

### ISSUE THREAD

**Issue by sontungexpt** [BambooEngine/ibus-bamboo#447]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở messenger
2. Gõ `vậy`
3. Thấy `vậyvậy`

**Kết quả mong muốn**

Gõ `vậy` thì chỉ hiện `vậy` sau khi enter chứ ko hiện `vậyvậy`  

**Ảnh chụp màn hình, hoặc clip quay màn hình** 

Lỗi khi gõ `tung` và nhấn enter

![image](https://github.com/BambooEngine/ibus-bamboo/assets/92097639/2ff61cad-e624-4a50-a416-14a48af11536)

**Môi trường**
 - OS và version: Arach (6.5.9-arch2-1)
 - Desktop: i3
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Comment by luongthanhlam** [comment]
Lỗi này tạm thời mình sẽ không fix do nó xung đột với tính năng gợi ý tìm kiếm trên thanh địa chỉ của Chrome. Bạn có thể workaround bằng cách thêm 1 dấu cách hoặc control rồi mới ấn enter
