### ISSUE TITLE
Suggestion trên thanh search của firefox không hiển thị tự động

### ISSUE THREAD

**Issue by PhucNVH** [BambooEngine/ibus-bamboo#45]
**Mô tả lỗi**
Khi gõ trên thanh search không xuất hiện suggestion

**Các bước tái hiện lỗi**
1. Mở Firefox
2. Gõ facebook.com
3. không hiển thị các suggestion

**Kết quả mong muốn**
Vừa gõ vừa có suggestion hiện lên

**Ảnh chụp màn hình, hoặc clip quay màn hình**
 https://youtu.be/hERPjFQKUx8

**Môi trường**
 - OS và version: Ubuntu 18.04
 - Desktop: Gnome
 - Phiên bản ibus: 1.5.17
 - Phiên bản ibus-bamboo: 0.4.8

**Thông tin thêm**
Tắt theo dõi chuột : Khi nhấn chuột vào thanh search (di chuyển con trỏ) thì mới xuất hiện suggestion
Bật theo dõi chuột: Suggestion chỉ xuất hiện tức thì, chớp 1 phát rồi ko hiện nữa.
Trên trình duyệt brave: Không có lỗi

**Comment by luongthanhlam** [comment]
Hiện tại bạn có thể khắc phục bằng cách nhấn Shift+~ rồi nhấn tiếp phím 2/3/4/5, khuyên dùng chế độ gõ số 5 cho firefox
