### ISSUE TITLE
Debian 12, ứng dụng Terminal mặc định trên Gnome không thể đưa được vào danh sách ignored. 

### ISSUE THREAD

**Issue by huyxdong** [BambooEngine/ibus-bamboo#450]
**Mô tả lỗi**
Mình đang sử dụng Debian 12, mình muốn 1 số ứng dụng được ignored ibus-bamboo để đỡ phải chuyển qua lại giữa tiếng anh và tiếng việt khi gõ.
Tuy nhiên, ứng dụng Terminal mặc định khi bấm Shift + ~ thì nó chỉ xuất hiện kí tự ~ mà thôi, không xuất hiện popup có 7 tùy chọn kiểu gõ để chọn. 
Các ứng dụng khác như VSCode, Chrome... thì đều đưa được vào danh sách ignored. 
Mình có thử đổi phím tắt cho phần chuyển chế độ gõ thành bộ phím khác nhưng khi gọi popup tùy chọn trong Terminal lên dùng theo bộ phím tắt nào cũng không được.

Nhờ các bạn kiểm tra giúp ạ. Mình cảm ơn. Mình đang xài bản Ibus Bamboo 0.8.3 trên Debian 12 Bookworm

**Comment by luongthanhlam** [comment]
bạn có đang chạy trên gnome wayland không? nếu có thì bạn có thể chuyển sang X11 để khắc phục lỗi này

**Comment by huyxdong** [comment]
Cảm ơn bạn, mình đã thử X11 và thành công.
