### ISSUE TITLE
Không gõ được trên Google doc 

### ISSUE THREAD

**Issue by namdt5** [BambooEngine/ibus-bamboo#451]
**Mô tả lỗi**
Không gõ được trên Google doc, Google excel vẫn gõ được bình thường 

**Các bước tái hiện lỗi**
1. Tạo mới tài liệu google doc trên trình duyệt chrome 
2. Gõ thử "Chào các bạn tôi là nam đây" 
3. Kết quả: tuỳ theo tốc độ gõ, sẽ ra các chuỗi không đúng khác nhau như ảnh chụp màn hình 

**Kết quả mong muốn**
Ra đúng từ tôi gõ "Chào các bạn tôi là nam đây" 

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2023-11-30 10-22-40](https://github.com/BambooEngine/ibus-bamboo/assets/11503877/26bc1505-22dd-4710-8965-9bb51d2b08a5)

**Môi trường**
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

**Thông tin thêm**
N/A

**Comment by gnoluv9x** [comment]
Mình cũng đang gặp lỗi giống bạn trên Popos 22.04 và chrome version 119

**Comment by namtao** [comment]
Mình cũng bị tình trạng này trên Fedora 39

**Comment by luongthanhlam** [comment]
bạn nhấn Shift+~ và chọn chế độ gõ số 1 nhé
