### ISSUE TITLE
khong cai dat duoc ibus-bamboo

### ISSUE THREAD

**Issue by Hai-TN** [BambooEngine/ibus-bamboo#453]
ad oi, giup minh voi, minh ko cai duoc ibus-bamboo, bi loi nhu trong hinh, da lam theo tung buoc nhu trong huong dan nhung ko duoc, minh cai tren he dieu hanh debian 11.8, cam on ad

![Screenshot_2023-12-05_10-29-46](https://github.com/BambooEngine/ibus-bamboo/assets/106439850/e94b2b1a-b93f-49f6-baf0-b2d2a711ca4f)

**Comment by luongthanhlam** [comment]
bạn chạy thử lệnh `apt-get update` hoặc `apt-get install --fix-missing` như hướng dẫn trong hình chưa?

**Comment by Hai-TN** [comment]
> bạn chạy thử lệnh `apt-get update` hoặc `apt-get install --fix-missing` như hướng dẫn trong hình chưa?

ui, đợi ad rep lâu quá cứ tưởng ad lơ luôn rồi, mình đã làm đủ cách rồi vẫn ko được ad ơi, hiện đang dùng tạm ibus-unikey

**Comment by luongthanhlam** [comment]
bạn thử lại xem, thỉnh thoảng OBS bị lỗi:(
