### ISSUE TITLE
<Feature request> Thay đổi Icon khi chuyển qua lại giữa english, tiếng việt

### ISSUE THREAD

**Issue by michael-nhat** [BambooEngine/ibus-bamboo#454]
**Nhiều lúc không biết mình đang ở chế độ nào, đang gõ tiếng anh hay tiếng việt**

**Các bước tái hiện lỗi**

Ví dụ:
1. Đang ở bộ gõ bamboo
2. Gõ Alt space để tạm tắt bộ gõ, có 1 thông báo ngắn hiện ra khi chuyển qua tiếng anh
3. Nhìn vào icon ở system tray, không rõ có đang tạm tắt tiếng Việt hay không (đôi khi là có)

...
4. Thấy xyz

**Kết quả mong muốn**

Cần thay đổi Icon màu sắc hoặc kí tự ở icon system tray để biết đang gõ tiếng việt hay đã tạm tắt
hoặc cung cấp dòng lệnh linux để truy vấn trạng thái bộ gõ hiện tại

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://github.com/BambooEngine/ibus-bamboo/assets/66666570/f701a967-5601-42e3-922a-50a7437180d8)

**Comment by luongthanhlam** [comment]
Bạn nên dùng phím tắt của hệ thống (Super + Space) để chuyển qua lại giữa tiếng Anh và tiếng Việt, icon của bộ gõ cũng sẽ được thay đổi theo. Tính năng tạm tắt bộ gõ chỉ nên dùng khi thực sự cần thiết (ví dụ như cần chuyển qua lại tiếng Việt và tiếng Anh nhiều lần khi gõ văn bản), sau khi tạm tắt thì bộ gõ sẽ gửi thông báo cho bạn.

**Comment by michael-nhat** [comment]
ok bạn, thanks
