### ISSUE TITLE
nhấp nháy trên arch linux

### ISSUE THREAD

**Issue by nhktmdzhg** [BambooEngine/ibus-bamboo#455]
**Mô tả lỗi**
nhấp nháy khi tùy chọn ibus từ systray như kiểu gõ, chế độ mặc định trên arch linux, không có cách nào đổi qua vni đc, phải mổ cò bằng telex 

**Các bước tái hiện lỗi**
bấm vào ibus trên systray và không chọn được bất cứ thứ gì do nhấp nháy không cho chọn

**Kết quả mong muốn**

-->

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - EndeavourOS
 - KDE Plasma
 - ibus-bamboo mới nhất

**Thông tin thêm**

**Comment by nhktmdzhg** [comment]
à có lẽ lỗi này là lỗi của kde, mình dùng ibus-unikey vẫn bị lỗi tương tự. Ai biết cách fix có thể chỉ mình đc 0 ạ. Mình cảm ơn

**Comment by nghia4mt** [comment]
mình dùng kde cũng bị, đã đổi sang fcitx5 ngon lành

**Comment by nghia4mt** [comment]
![image](https://github.com/BambooEngine/ibus-bamboo/assets/58174632/4a9fc0a1-5bd0-4d89-8d1e-8ca2db5df6bc)
nếu bạn vẫn muốn dùng ibus thì sửa file ~/.config/ibus-bamboo/ibus-bamboo.config.json ở đoạn này thành VNI là xong

**Comment by nhktmdzhg** [comment]
tks bạn
