### ISSUE TITLE
Không gõ được tiếng việt trên VSCode và Chrome

### ISSUE THREAD

**Issue by dhcvn** [BambooEngine/ibus-bamboo#456]
Bộ gõ đã cài đặt thành công nhưng không phải sử dụng cho toàn bộ phần mềm trong máy. 
Hiện có Chrome và VSCode không sử dụng bình thường được như các ứng dụng khác. 
Ví dụ trong VSCode khi gõ "Nữ" sẽ ra là "Nuưữ".
Bạn nào gặp tình trạng như này rồi cho xin giải pháp với!

**Comment by luongthanhlam** [comment]
bạn có đang sử dụng chức năng sửa lỗi gạch chân không? nếu có bạn nhấn `Shift+~` và chọn lại mode 1 nhé
