### ISSUE TITLE
Bị lặp khi gõ và gửi 1 từ ở các trang mxh FB Ig 

### ISSUE THREAD

**Issue by daachild** [BambooEngine/ibus-bamboo#460]
**Mô tả lỗi**
khi nhắn 1 từ ở các trang mxh như facebook instargram thì từ đó sẽ bị lặp lại

**Các bước tái hiện lỗi**
1. Mở phần chat của trang web facebook hoặc instargram
2. Gõ bruh gửi đi
3. Thấy bruhbruh trong đoạn chat

**Kết quả mong muốn**
--> Không xảy ra tình trạng này nữa

**Ảnh chụp màn hình, hoặc clip quay màn hình**
-->
![image](https://github.com/BambooEngine/ibus-bamboo/assets/135897360/6843f43b-2876-4e20-a808-2c41edd811dc)
![image](https://github.com/BambooEngine/ibus-bamboo/assets/135897360/e211fead-9805-42ea-8798-759bd29867bb)

**Môi trường**
 - OS và version: Nobara 38
 - Desktop: Gnome,
 - Phiên bản ibus-bamboo: 0.8.3

**Comment by luongthanhlam** [comment]
Lỗi này tạm thời không thể sửa do nó xung đột với tính năng gợi ý tìm kiếm trên thanh địa chỉ của Chrome. Bạn có thể workaround bằng cách thêm 1 dấu cách hoặc control rồi mới ấn enter
Ref: https://github.com/BambooEngine/ibus-bamboo/issues/443
