### ISSUE TITLE
Các cài đặt trên thanh task manager không truy cập được

### ISSUE THREAD

**Issue by tranmanhducslt** [BambooEngine/ibus-bamboo#461]
**Mô tả lỗi**
Khi mở task manager (KDE Plasma) để truy cập cài đặt của bộ gõ thì không thể mở các menu cấp hai được  -> ví dụ, không thể thay Telex thành VNI

**Các bước tái hiện lỗi**
1. Chuột phải vào thanh task manager
2. Chọn một cài đặt
3. Danh sách hiện ra rồi lại tắt đi, đôi khi điều này còn khởi động lại giao diện KDE 
**Kết quả mong muốn**
Đáng ra phải mở được danh sách để chọn kiểu gõ và những thứ khác

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot_20240102_180919](https://github.com/BambooEngine/ibus-bamboo/assets/79132392/106ddd26-bb26-4d53-9750-9d7286925ca0)

**Môi trường**
 - Endeavour OS Galileo 
 - Desktop: KDE Plasma 
 - Phiên bản ibus-bamboo: 0.8.3-RC6   

**Thông tin thêm**
Lỗi cũng xảy ra khi dùng ibus-unikey

**Comment by luongthanhlam** [comment]
Có vẻ là lỗi của DE/OS, bạn có thể thử tạm khắc phục bằng cách chạy `ibus-setup` rồi chọn Always Show property panel
