### ISSUE TITLE
Unable to locate package ibus-bamboo on Debian 12 Bookworm

### ISSUE THREAD

**Issue by hungpham2411** [BambooEngine/ibus-bamboo#462]
**Mô tả lỗi**
On Raspberry Pi OS based on Debian 12 Bookworm.  
Follow this: `https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo`.  
After adding repository and update successful, I try install ibus-bamboo then the error shows up:  
```
Unable to locate package ibus-bamboo
```

**Các bước tái hiện lỗi**
1. Open Terminal.
2. Run: `echo 'deb http://download.opensuse.org/repositories/home:/lamlng/Debian_12/ /' | sudo tee /etc/apt/sources.list.d/home:lamlng.list`
Output:
```
deb http://download.opensuse.org/repositories/home:/lamlng/Debian_12/ /
```
3. Run: `curl -fsSL https://download.opensuse.org/repositories/home:lamlng/Debian_12/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_lamlng.gpg > /dev/null`
4. Run: `sudo apt update`
Output:
```
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease
Get:5 http://download.opensuse.org/repositories/home:/lamlng/Debian_12  InRelease [1,534 B]      
Get:6 http://download.opensuse.org/repositories/home:/lamlng/Debian_12  Packages [1,246 B]
Fetched 2,780 B in 2s (1,198 B/s)   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
83 packages can be upgraded. Run 'apt list --upgradable' to see them.
```
5. Run `sudo apt install ibus-bamboo`
Output:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ibus-bamboo
```

**Kết quả mong muốn**
Package ibus-bamboo is available to install on Debian 12 Bookworm.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
NA

**Môi trường**
 - OS và version: Raspberry Pi OS based on Debian 12 Bookworm 64bit
 - Desktop: LXDE
 - Phiên bản ibus-bamboo: Default on repository.

**Thông tin thêm**
Display protocol: Wayland.  
Sorry, no Vietnamese because I couldn't install ibus-bamboo.

**Comment by ngocdd** [comment]
I also got problem when try to install Ibus bamboo on Debian 12
![image](https://github.com/BambooEngine/ibus-bamboo/assets/107824423/042ca374-b0ad-4806-aad6-f0f37ba98782)

**Comment by hungpham2411** [comment]
> I also got problem when try to install Ibus bamboo on Debian 12 ![image](https://private-user-images.githubusercontent.com/107824423/296529736-042ca374-b0ad-4806-aad6-f0f37ba98782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDcxMDYsIm5iZiI6MTcwNTIwNjgwNiwicGF0aCI6Ii8xMDc4MjQ0MjMvMjk2NTI5NzM2LTA0MmNhMzc0LWIwYWQtNDgwNi1hYWQ2LWYwZjM3YmE5ODc4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwNDMzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmFkODBhYTk1MmFhZTc5MjM0YmVlMGRkNGZjZjMyMDE0MGEwZTMzODNiYzMxMzM2ZWU0OWU3OTQzYmQzM2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xr-b3ivslllFPzAHL1UVGdlqX3etM3Rg3TpM8RyRDpM)

This caused by missing dependency lib `python3-launchpadlib`. Install it, you should be able to use add-apt-repository after.

**Comment by luongthanhlam** [comment]
I'm not sure why, but OBS sometimes fails to locate the package. I'll try triggering the build again, hoping that will help.
