### ISSUE TITLE
Không thao tác được trong UI

### ISSUE THREAD

**Issue by Watadp** [BambooEngine/ibus-bamboo#463]
**Mô tả lỗi**
Không thao tác được trong UI

**Các bước tái hiện lỗi**
Ví dụ:
1. Mở IBus Panel
2. Di chuột lên kiểu gõ
3. Meny mở nhưng tắt ngay lập tức

**Kết quả mong muốn**

https://github.com/BambooEngine/ibus-bamboo/assets/110218050/607d3c90-4b12-4158-b0fe-b8365617ee4b

**Môi trường**
 - OS và version: Manjaro 5.27.10
 - Desktop: KDE
 - Phiên bản ibus-bamboo: 0.8.3
**Thông tin thêm**

**Comment by luongthanhlam** [comment]
Có vẻ lỗi từ DE hoặc có ứng dụng nào đó xung đột với ibus. Bạn thử chạy `ibus-setup` và chọn "Always show propery panel" để mở ibus panel thay vì mở từ thanh trạng thái xem
![image](https://github.com/BambooEngine/ibus-bamboo/assets/26364140/d8171462-42b4-4c86-a981-1d4e408d3fb2)
