### ISSUE TITLE
Gõ bị duplicate trên mess/fb

### ISSUE THREAD

**Issue by hiensumi** [BambooEngine/ibus-bamboo#464]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

Dùng chế độ gõ pre-edit

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

[Screencast from 2024-01-28 17-24-17.webm](https://github.com/BambooEngine/ibus-bamboo/assets/47080203/5d15ab8e-16d3-4f92-96ac-46f48cfd277a)

**Môi trường**
-OS: Debian 12 Bookworm

**Thông tin thêm**

**Comment by hiensumi** [comment]
Em phải ấn thêm space thì nó mới k bị dup ạ :D nhưng mà khi gõ nhanh thì không để ý lắm nên đôi lúc hơi phiền.

**Comment by luongthanhlam** [comment]
duplicate https://github.com/BambooEngine/ibus-bamboo/issues/352. Lỗi này tạm thời mình sẽ không fix do nó xung đột với thanh địa chỉ của chrome.

**Comment by luongthanhlam** [comment]
Có thể bản mới mình sẽ thêm tùy chọn bật tắt cái lỗi này
