### ISSUE TITLE
Không thể thay đổi kiểu gõ dùng phím tắt `shift+~`

### ISSUE THREAD

**Issue by HalmondD** [BambooEngine/ibus-bamboo#469]
### Mô tả lỗi
Như tiêu đề, cho dù mình có thay đổi phím tắt bao nhiêu lần đi nữa thì vẫn không có một cửa sổ hiện ra để mình thay đổi kiểu gõ,.

### Các bước tái hiện lỗi
Cái này thì mình không biết phải tái hiện như thế nào nữa, mình tải theo cái ReadMe, sau đó reset lại máy là có, mọi thứ vẫn ok, kể cả đổi ngôn ngữ bàn phím bằng `super+space`, duy chỉ có chức năng đổi kiểu gõ là đến bây giờ vẫn không làm gì được.

### Môi trường
 - OS và version: Ubuntu 22.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Comment by luongthanhlam** [comment]
bạn gửi mình output lệnh này nhé `cat ~/.config/ibus-bamboo/*.json`

**Comment by HalmondD** [comment]
### ibus-bamboo.config.json
```
{
  "InputMethod": "Telex",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex W": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "d": "D_Đ",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode",
  "Flags": 7,
  "IBflags": 262642,
  "Shortcuts": [
    1,
    126,
    0,
    0,
    0,
    0,
    0,
    0,
    5,
    117
  ],
  "DefaultInputMode": 3,
  "InputModeMapping": {}
}
```
###  ibus-bamboostandalone.config.json
```
{
  "InputMethod": "Telex",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex W": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "d": "D_Đ",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode",
  "Flags": 7,
  "IBflags": 295408,
  "Shortcuts": [
    1,
    96,
    0,
    0,
    0,
    0,
    0,
    0,
    5,
    117
  ],
  "DefaultInputMode": 1,
  "InputModeMapping": {}
}
```

**Comment by Jarock07** [comment]
Mình cũng bị lỗi tương tự như vậy khi sử dụng một số application

Môi trường
OS và version: Debian 12
Desktop: KDE
Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Comment by dinhphu28** [comment]
Mình cũng bị lỗi tương tự, khi chọn Tiếng Việt và show menu, hover để chọn sub-menu (chẳng hạn chọn chế độ gõ mặc định) thì không được, nó chỉ hiện menu đó nháy 1 cái rồi tắt, nếu tiếp tục hover thì crash luôn thanh menu.

Minh đang xài openSUSE Tumbleweed
Desktop Envirionment: KDE 6
Ibus-Bamboo: 0.8.3

**Comment by goatastronaut0212** [comment]
> Mình cũng bị lỗi tương tự như vậy khi sử dụng một số application
> 
> Môi trường OS và version: Debian 12 Desktop: KDE Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

Mình thắc mắc không biết bạn sử dụng ứng dụng nào vậy? Cho mình biết thêm thông tin nữa có được không?

**Comment by FuLygon** [comment]
mình cũng đang bị tương tự giống @dinhphu28, khi hover vào sub-menu sẽ bị crash plasmashell, và không mở được pop-up thay đổi chế độ gõ `shift+~` đã thử thay đổi keybind nhưng cũng không được.

môi trường:
- de: kde plasma 6
- distro: arch linux
- ibus: 1.5.29-3
- ibus-bamboo: 0.8.3_RC6-1

**Comment by goatastronaut0212** [comment]
> và không mở được pop-up thay đổi chế độ gõ `shift+~` đã thử thay đổi keybind nhưng cũng không được.

ý bạn là khi xài konsole nó bị lỗi hả?

**Comment by FuLygon** [comment]
> > và không mở được pop-up thay đổi chế độ gõ `shift+~` đã thử thay đổi keybind nhưng cũng không được.
> 
> ý bạn là khi xài konsole nó bị lỗi hả?

mình bị lỗi ở firefox và kate, mình chưa test thêm ở app khác, hiện tại mình đang dùng tạm `fcitx5`

**Comment by goatastronaut0212** [comment]
> > > và không mở được pop-up thay đổi chế độ gõ `shift+~` đã thử thay đổi keybind nhưng cũng không được.
> > 
> > 
> > ý bạn là khi xài konsole nó bị lỗi hả?
> 
> mình bị lỗi ở firefox, kate và vscode, mình chưa test thêm ở app khác, hiện tại mình đang dùng tạm `fcitx5`

phiền bạn có thể test và đưa giúp mình thêm video hay gì đó có được không. Mình vẫn chưa hình dung ra bạn làm thế nào được

**Comment by goatastronaut0212** [comment]
Có vẻ như mình hiểu ra vấn đề rồi. Để có gì mình tìm hiểu tại sao lại như vậy

**Comment by goatastronaut0212** [comment]
Mình nghĩ cái lỗi menu này vì các bạn đều sử dụng trên KDE hết và mình test KDE 6 trên Arch Linux và nhận thấy cái khi hover vô các sub menu này có thể là lỗi liên quan đến Qt hoặc Ibus. Mình không nghĩ đây là lỗi của Ibus-bamboo đâu mình cũng không biết tại sao nó lại như vậy nhưng nếu hover sub menu trên các DE khác như GNOME hay Cinnamon thì không có lỗi giật giật như vậy đâu. Có lẽ nếu muốn sửa thì sẽ phải báo cáo lại cho upstream.

Còn về Shift + ~ thì mình thấy vẫn chạy bình thường mà ta :D . Các bạn có chắc là đã bỏ hết các biến ibus vô shell hay gì đó chưa. Nếu chưa hãy thử lại xem nếu còn vấn đề hãy báo lại cho mình biết nhé. Link mình để ở dưới để bạn tham khảo.

https://wiki.archlinux.org/title/IBus
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

**Comment by FuLygon** [comment]
> Mình nghĩ cái lỗi menu này vì các bạn đều sử dụng trên KDE hết và mình test KDE 6 trên Arch Linux và nhận thấy khi hover vô các sub menu này sẽ bị giật và không chọn được có thể là lỗi liên quan đến Qt hoặc Ibus. Mình không nghĩ đây là lỗi của Ibus-bamboo đâu mình cũng không biết tại sao nó lại như vậy nhưng nếu hover sub menu trên các DE/WM khác như Awesomewm hay Cinnamon thì không có lỗi giật giật như vậy đâu. Có lẽ nếu muốn sửa thì sẽ phải tìm ra lỗi và làm báo cáo hoàn chỉnh lại cho upstream để họ sửa.
> 
> Còn về `Shift` + `~` thì mình thấy vẫn chạy bình thường mà ta. Các bạn có chắc là đã bỏ hết các biến ibus vô shell config hay gì đó chưa. Nếu chưa hãy thử lại xem nếu còn vấn đề hãy báo lại cho mình biết nhé. Link mình để ở dưới để bạn tham khảo.
> 
> https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

Không biết bạn đang dùng `xorg` hay `wayland`, bên mình thì đang dùng wayland, theo mình thấy khi setup `ibus` hay cả `fcitx5` trên wayland thì kde đều notify là start `ibus`/`fcitx5` thông qua virtual keyboard setting của kde (system setting > keyboard > virtual keyboard > ibus/fcitx5), khi start thông qua kiểu này thì cũng sẽ có notify là disable 2 env `GTK_IM_MODULE` và `QT_IM_MODULE`, chỉ để lại `XMODIFIERS`, hiện tại mình đang setup ibus theo kiểu này thì có vẻ như không dùng đc `shift+~`, mình có thử start ibus kiểu cũ bằng `ibus-daemon -rdx` kèm theo 3 env `GTK_IM_MODULE QT_IM_MODULE XMODIFIERS` và không start ibus thông qua virtual keyboard, mình chưa test thử xem `shift+~` có work nếu start theo kiểu này không nhưng nếu start theo kiểu này thì có mình có issue chung trên cả `ibus/fcitx5` là không thể gõ đc tiếng việt trong 1 số app electron ngay cả khi dùng flag `--enable-wayland-ime` (mình bị trên spotify và obsidian), hoặc 1 số app phải start với flag `--enable-features=UseOzonePlatform --ozone-platform=wayland` cũng sẽ không gõ được tiếng việt nếu không dùng qua virtual keyboard của kde

**Comment by goatastronaut0212** [comment]
> Không biết bạn đang dùng `xorg` hay `wayland`, bên mình thì đang dùng wayland, theo mình thấy khi setup `ibus` hay cả `fcitx5` trên wayland thì kde đều notify là start `ibus`/`fcitx5` thông qua virtual keyboard setting của kde (system setting > keyboard > virtual keyboard > ibus/fcitx5), khi start thông qua kiểu này thì cũng sẽ có notify là disable 2 env `GTK_IM_MODULE` và `QT_IM_MODULE`, chỉ để lại `XMODIFIERS`, hiện tại mình đang setup ibus theo kiểu này thì có vẻ như không dùng đc `shift+~`, mình có thử start ibus kiểu cũ bằng `ibus-daemon -rdx` kèm theo 3 env `GTK_IM_MODULE QT_IM_MODULE XMODIFIERS` và không chọn ibus trong virtual keyboard, mình chưa test thử xem `shift+~` có work nếu start theo kiểu này không nhưng nếu start theo kiểu này thì có mình có issue chung trên cả `ibus/fcitx5` là không thể gõ đc tiếng việt trong 1 số app electron ngay cả khi dùng flag `--enable-wayland-ime` (mình bị trên spotify và obsidian), hoặc 1 số app phải start với flag `--enable-features=UseOzonePlatform --ozone-platform=wayland` cũng sẽ không gõ được tiếng việt nếu không dùng qua virtual keyboard của kde

Mình chẳng tin vào việc set biến của các Desktop Environment như KDE hay GNOME, chúng đôi lúc hoạt động không đúng ý mình lắm. Thường thì mình sẽ bỏ các biến sau vào `/etc/environment`, bỏ vào shell config hay là tạo 1 shell script auto start cùng như vậy sẽ chắc ăn hơn. Logout hoặc reboot lại thì sẽ thành công thôi.

```
export GTK_IM_MODULE=xim # đổi thành xim
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
# Dành cho những phần mềm dựa trên qt4
export QT4_IM_MODULE=ibus
# Dành cho những phần mềm dùng thư viện đồ họa clutter/OpenGL
export CLUTTER_IM_MODULE=ibus
export GLFW_IM_MODULE=ibus
```

Còn về Wayland mình nghĩ là mình cũng làm rõ quan điểm ở đây rồi. Giải thích thì khá là dài dòng nhưng về cơ bản thì Wayland vẫn chưa có 1 định hình cụ thể nào cho các input-method như fcitx5 hay là ibus và chúng ta thì phụ thuộc nhiều vào họ nên nếu họ chưa có sửa hay implement wayland protocol thì mọi việc không đi tới đâu cả, vì vậy nếu bạn xài wayland thì hãy chắc chắn rằng ứng dụng của bạn có thể chạy backend là X11/Xorg.

https://github.com/BambooEngine/ibus-bamboo/issues/44

**Comment by goatastronaut0212** [comment]
@FuLygon 

Mình khi setup export các biến trên thì có thể gõ tiếng việt và sử dụng `Shift` + `~` như bình thường thôi không có vấn đề gì hết. Không biết là bạn còn có vấn đề hay thắc mắc gì nữa không vì mình cố gắng cũng giải đáp hết rồi. Nếu bạn thấy trải nghiệm Wayland tệ bạn có thể quay trở lại Xorg và mọi thứ sẽ không có vấn đề gì cả. Wayland chỉ dành cho bọn cool kids, developers, testers hoặc những contributors có đủ bản lĩnh thì mới xài ở thời điểm hiện tại thôi.

**Comment by FuLygon** [comment]
> @FuLygon 
> 
> Mình khi setup export các biến trên thì có thể gõ tiếng việt và sử dụng `Shift` + `~` như bình thường thôi không có vấn đề gì hết. Không biết là bạn còn có vấn đề hay thắc mắc gì nữa không vì mình cố gắng cũng giải đáp hết rồi. Nếu bạn thấy trải nghiệm Wayland tệ bạn có thể quay trở lại Xorg và mọi thứ sẽ không có vấn đề gì cả. Wayland chỉ dành cho bọn cool kids, developers, testers hoặc những contributors có đủ bản lĩnh thì mới xài ở thời điểm hiện tại thôi.

Issue mình gặp trước giờ trên xorg ngay cả gnome và xfce là mình không thể đẩy đc refresh rate external monitor chạy max ở 144hz mặc dùng đã dùng `envycontrol` force sang mode nvidia only, mình dùng wayland trên hyprland hoặc kde thì mình không gặp issue này, thật sự thì mình cũng không muốn dùng wayland vì nó cũng unstable hơn, một số app cũng flickering nhiều buộc mình phải launch kèm flag, nhưng external monitor 144z chỉ render đc ở 40hz 50hz nên mới phải dùng wayland, v chắc tạm thời mình sử dụng fcitx5-bamboo đến khi ibus hoặc ibus-bamboo có update

**Comment by Phunguy65** [comment]
Xác nhận vấn đề khi dùng ibus trên kde plasma 6 gây lag, crash plasmashell

**Comment by goatastronaut0212** [comment]
> Xác nhận vấn đề khi dùng ibus trên kde plasma 6 gây lag, crash plasmashell

Mình nghĩ đó là vấn đề của upstream không phải của Ibus-bamboo. Mình nhớ mình có note ở đây rồi mà

> Mình nghĩ cái lỗi menu này vì các bạn đều sử dụng trên KDE hết và mình test KDE 6 trên Arch Linux và nhận thấy khi hover vô các sub menu này sẽ bị giật và không chọn được có thể là lỗi liên quan đến Qt hoặc Ibus. Mình không nghĩ đây là lỗi của Ibus-bamboo đâu mình cũng không biết tại sao nó lại như vậy nhưng nếu hover sub menu trên các DE/WM khác như Awesomewm hay Cinnamon thì không có lỗi giật giật như vậy đâu. Có lẽ nếu muốn sửa thì sẽ phải tìm ra lỗi và làm báo cáo hoàn chỉnh lại cho upstream để họ sửa.

**Comment by goatastronaut0212** [comment]
Mình sẽ thử tìm cách để giải quyết vấn đề này trên Wayland. Lỗi này trên Wayland không thể gõ `Shift` + `~` nhưng trên Xorg thì lại gõ được. Có gì mình sẽ thông báo lại sau. Giờ thì mọi người tạm thời sống chung với lũ vậy.

**Comment by dunneeee** [comment]
Em su dung ubuntu wayland thi setup nhu nao vay cac bac!

**Comment by goatastronaut0212** [comment]
> Em su dung ubuntu wayland thi setup nhu nao vay cac bac!

Bạn không nên sử dụng wayland vì ibus chưa implement được v2 protocol nên nó chưa thực sự ổn định.

Mà bạn bảo cần setup là sao vậy?

**Comment by vuboi** [comment]
Mình sử dụng kubuntu cũng bị crash, sau mình chuyển sang kde neon thì sài ổn hẳn ko còn bị lỗi nhấp nháy menu nữa

**Comment by Phunguy65** [comment]
> Mình sử dụng kubuntu cũng bị crash, sau mình chuyển sang kde neon thì sài ổn hẳn ko còn bị lỗi nhấp nháy menu nữa

Bạn đang trên session nào x11 hay wayland, x11 mình nghĩ chắc chắn không vấn đề, wayland chưa ổn định phần tùy chọn menu ở task bar.

**Comment by vuboi** [comment]
> > Mình sử dụng kubuntu cũng bị crash, sau mình chuyển sang kde neon thì sài ổn hẳn ko còn bị lỗi nhấp nháy menu nữa
> 
> Bạn đang trên session nào x11 hay wayland, x11 mình nghĩ chắc chắn không vấn đề, wayland chưa ổn định phần tùy chọn menu ở task bar.

Mình test cả cả 2, x11 thì chạy ổn nhất rồi, bên wayland các ứng dụng mình dùng như vscode, chrome, edge thấy gõ tiếng việt ok, nhưng mà một số ứng dụng khác mình sài bên wayland ko ổn định lắm lên mình về x11

**Comment by sys6101** [comment]
mình đang xài 
OS và version: Ubuntu 22.04
Desktop: Gnome
Phiên bản ibus-bamboo: (bản mới nhất là 0.8.4)
Tiếng việt mình gõ bình thường, máy thì  disable wayland
thử export các biến trên rồi vẫn không sử dụng được phím tắt (shift+~) đã thử xài phím tắt khác vẫn không được

**Comment by goatastronaut0212** [comment]
> mình đang xài OS và version: Ubuntu 22.04 Desktop: Gnome Phiên bản ibus-bamboo: (bản mới nhất là 0.8.4) Tiếng việt mình gõ bình thường, máy thì disable wayland thử export các biến trên rồi vẫn không sử dụng được phím tắt (shift+~) đã thử xài phím tắt khác vẫn không được

Bạn mở 1 issue mới nhé mình cảm thấy issue này quá lan man và bị lạc đề rồi nên mình sẽ đóng nó lại
