### ISSUE TITLE
Gõ tiếng Việt với layout bàn phím khác qwerty

### ISSUE THREAD

**Issue by ImKifu** [BambooEngine/ibus-bamboo#47]
em dùng Ubuntu 18.04

Vấn đề là em sài layout bàn phím Colemak, trong khi cài bộ gõ thì nó để mặc định layout là us ( qwerty)

Em muốn chuyển về Colemak dùng có cách nào ko ạ :(

**Comment by luongthanhlam** [comment]
hmm, bạn tham khảo [link này](https://github.com/BoGoEngine/ibus-bogo/issues/235 ) xem có khắc phục được không.

**Comment by ImKifu** [comment]
@luongthanhlam dạ em có thể gõ được rồi ạ, nhưng nó xảy ra một số lỗi sau ạ

- mỗi lần em bật tắt máy thì phải gõ câu lệnh `setxkbmap us -variant colemak` 

- khi gõ nó hay bị tự chuyển từ Egnlish sang Vietnamese ( khi chuyển giữa hai ứng dụng )

- trên Telegram thì nó chưa nhận gõ tiếng việt

**Comment by ndgnuh** [comment]
>  mỗi lần em bật tắt máy thì phải gõ câu lệnh `setxkbmap us -variant colemak`
Bạn có thể dòng đó vào trong `/etc/profile` để nó chạy tự động lỗi khi load môi trg đồ hoạ
```sh
echo "setxkbmap us --variant colemak" | sudo tee -a /etc/profile
```
>     khi gõ nó hay bị tự chuyển từ Egnlish sang Vietnamese ( khi chuyển giữa hai ứng dụng )
Nếu mình nhớ k nhầm thì trong ibus có tùy chọn dùng 1 engine cho tất cả ứng dụng, bạn chạy `ibus-setup` để bật nó lên.
>     trên Telegram thì nó chưa nhận gõ tiếng việt
Bạn thử chạy 
```sh
QT_IM_MODULE=ibus QT4_IM_MODULE=ibus telegram
```
Nếu gõ đc tiếng Việt thì bạn thêm
```sh
export QT_IM_MODULE=ibus
export QT4_IM_MODULE=ibus
```
vào trong file `/etc/profile`

**Comment by ImKifu** [comment]
```
echo "setxkbmap us --variant colemak" | sudo tee -a /etc/profile
```
sau khi em thêm lệnh này thì sau khi reboot lại máy nó báo lỗi ạ. Nó bảo là phải sửa lại file /etc/profile

**Comment by ndgnuh** [comment]
Trời, lệnh đó là để thêm dòng vào trong file `/etc/profile`, bạn thêm thủ công thì chỉ thêm
```setxkbmap us --variant colemak``` thôi

**Comment by ImKifu** [comment]
@ndgnuh em cần nọ tự động bật mỗi khi khởi động máy mà. Em đã thử viết Script, Cho chạy Bash mà vẫn không được :( em muốn có cách nào tự chạy câu lệnh này để không phải mỗi lần mở máy lên gõ câu lệnh này. 

Vì em dùng layout colemak mà mỗi lần bật máy phải gõ câu lệnh thì cơ bắp quá =))))

**Comment by luongthanhlam** [comment]
Bạn đã thêm `setxkbmap us --variant colemak` vào file /etc/profile và khởi động lại máy chưa?

**Comment by ndgnuh** [comment]
Bạn thêm vào như trên nói là nó sẽ tự động chạy mỗi lần khởi động, chỉ cần thêm một lần thôi nhé!

**Comment by ndgnuh** [comment]
Ý mình là bạn chỉ thêm cái dòng kia thôi, và nó sẽ tự chạy khi bạn khởi động

**Comment by ImKifu** [comment]
```
Bạn đã thêm setxkbmap us --variant colemak vào file /etc/profile và khởi động lại máy chưa?
```
em đã thêm, khởi động lại máy và nó báo lỗi ạ. 

Phần gõ tiếng Việt với layout khác, sau khi cài lại hệ điều hành + cài đặt theo hướng dẫn :

https://github.com/BambooEngine/ibus-bamboo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-m%C3%A3-ngu%E1%BB%93n

Em đã có thể gõ tiếng Việt.

Vấn đề thứ hai là sau khi gõ được tiếng Việt thì Telegram không gõ được. Em đã dùng câu lệnh gợi ý ở trên :
```
QT_IM_MODULE=ibus QT4_IM_MODULE=ibus telegram-desktop
```
và kết quả trả về : 
```
Qt: Session management error: None of the authentication protocols specified are supported
```
@ndgnuh @luongthanhlam  các anh xem giúp em với ạ.
em cảm ơn hai anh ạ.

**Comment by ndgnuh** [comment]
Bạn dùng desktop gì, `gnome` đúng k? Bạn gửi nội dung file `/etc/profile` của bạn lên đi

**Comment by ImKifu** [comment]
@ndgnuh  thưa anh đây ạ
```
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
```
em kiểm tra bằng câu lệnh: 
```
imkifu@whoami:~$ echo $XDG_SESSION_TYPE
x11
imkifu@whoami:~$ 
```
vậy nên em đang sử dụng xorg ạ.

em dùng Ubuntu 19.04 ạ.
