### ISSUE TITLE
Không thể sử dụng được ibus-bamboo trên Hyprland

### ISSUE THREAD

**Issue by hoanggbao00** [BambooEngine/ibus-bamboo#471]
**Mô tả lỗi**
Sau khi cài qua bash và chọn yay helper
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/BambooEngine/ibus-bamboo/master/archlinux/install.sh)"`

sau đó mình
`ibus start`
nó có hiện lên thông báo setup nhưng không hiện gì khác, kể cả icon 

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![anh chup man hinh](https://github.com/BambooEngine/ibus-bamboo/assets/78465334/05497656-9593-4731-81bf-26905372da7f)

**Môi trường**
 - OS và version: archlinux 6.8.2-arch2-1
 - Desktop: Wayland (Hyprland)
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.1)

**Comment by goatastronaut0212** [comment]
Đúng hơn là không thể sử dụng Ibus hoàn toàn trên Wayland. Về cơ bản nó vẫn chạy ngầm bạn có thể thấy process của nó nhưng không có icon, không panel không gì cả và chỉ sử dụng được với cái phần mềm chạy backend X11/Xorg thôi và chỉ hoạt động nếu bạn đã setup nút chuyển đổi en sang vn bamboo trước đó. Vả lại cái issue này cũng trùng với lại cái này rồi https://github.com/BambooEngine/ibus-bamboo/issues/44. Chúng ta có thể đóng issue này được rồi đấy.

Mình có lẽ vẫn sống ổn với nó với cả nếu bạn không thấy ổn thì nghĩa là Wayland vẫn chưa chuẩn bị để được sử dụng rộng rãi như những người quá phấn khích hay nói về nó.

Đợi upstream giải quyết thôi mà cũng trong giai đoạn rồi. Mình cũng không biết cách mà sửa đâu trừ khi ai đó nghĩ họ có đủ sức làm việc ở Ibus.
https://github.com/ibus/ibus/pull/2256
https://github.com/ibus/ibus/issues/2182

**Comment by hoanggbao00** [comment]
> Đúng hơn là không thể sử dụng Ibus hoàn toàn trên Wayland. Về cơ bản nó vẫn chạy ngầm bạn có thể thấy process của nó nhưng không có icon, không panel không gì cả và chỉ sử dụng được với cái phần mềm chạy backend X11/Xorg thôi các ứng dụng Wayland khác thì hên xui và chỉ hoạt động nếu bạn đã setup nút chuyển đổi en sang vn bamboo trước đó. Vả lại cái issue này cũng trùng với lại cái này rồi https://github.com/BambooEngine/ibus-bamboo/issues/44. Chúng ta có thể đóng issue này được rồi đấy.
> 
> Mình có lẽ vẫn sống ổn với nó với cả nếu bạn không thấy ổn thì nghĩa là Wayland vẫn chưa chuẩn bị để được sử dụng rộng rãi như những người quá phấn khích hay nói về nó.
> 
> Đợi upstream giải quyết thôi mà cũng trong giai đoạn rồi. Mình cũng không biết cách mà sửa đâu trừ khi ai đó nghĩ họ có đủ sức làm việc ở Ibus.
> https://github.com/ibus/ibus/pull/2256
> https://github.com/ibus/ibus/issues/2182
> 
> À phải rồi, mình không biết là bạn đang có xài Waybar hay không, mình có nhớ là từng có có ai từng hiển thị được cái ibus-panel hay icon trên đó nhưng có lẽ mình không biết cách để làm như vậy đâu hoặc là họ đã không giải quyết được vấn đề.

Thật cảm ơn bạn vì thông tin này, mình mới chuyển qua dùng linux lần đầu nên còn chưa hiểu biết nhiều.
Tuy hơi buồn chút vì không thể gõ tiếng việt. Nhưng mình cũng có thêm kiến thức cần thiết về cách DE của linux hoạt động. Cảm ơn bạn rất nhiều

**Comment by hoanggbao00** [comment]
> >
> > Thật cảm ơn bạn vì thông tin này, mình mới chuyển qua dùng linux lần đầu nên còn chưa hiểu biết nhiều. Tuy hơi buồn chút vì không thể gõ tiếng việt. Nhưng mình cũng có thêm kiến thức cần thiết về cách DE của linux hoạt động. Cảm ơn bạn rất nhiều
> 
> Bạn vẫn có thể gõ tiếng Việt ổn định trên Xorg mà, nếu như không muốn phải vọc trên Wayland còn nếu muốn gõ trên Wayland như mình đã nói hãy chắc chắn ứng dụng bạn có thể chạy nền backend là Xorg/X11 thì ibus-bamboo sẽ gõ được thôi, nó cũng không phải là vấn đề quá nghiêm trọng hay to tát vì Linux cũng có nhiều lần chuyển giao công nghệ mới nên 1 lúc nào đó Wayland sẽ ổn định và chúng ta sẽ sớm gõ tiếng Việt trên Wayland được thôi.
> 
> Nếu bạn không còn thắc mắc gì nữa thì phiền bọn đóng issue lại có được không? Có nhiều issues quá cũng khó mà theo dõi và owner Lâm cũng không thường xuyên rảnh rỗi để quản lý cho lắm.

Mình sẽ tìm hiểu thêm về Xorg, cảm ơn bạn rất nhiều. Mình sẽ đóng issue này

**Comment by zombieconao** [comment]
bạn có thể xài ibus trên hyprland bằng lệnh
```
ibus start --type wayland
```
cơ mà....... ibus-bamboo vẫn không sử dụng được :(, xài ibus-unikey tạm vậy

**Comment by hien-ngo29** [comment]
@zombieconao Hyprland xài fcitx5 (unikey) đi đừng xài ibus. ibus ổn cho Gnome thôi
