### ISSUE TITLE
Replicate VPSKeys keyboard

### ISSUE THREAD

**Issue by minh-v** [BambooEngine/ibus-bamboo#476]
I installed this keybaord as a replacement for VPSKeys (windows) on my Linux box, but am having trouble finding the settings to replicate the keyboard settings. Has anyone figured this out? Thanks

**Comment by goatastronaut0212** [comment]
I don't know what you mean about replicate the keyboard setting. What is that?

**Comment by minh-v** [comment]
https://en.m.wikipedia.org/wiki/VPSKeys

**Comment by goatastronaut0212** [comment]
Well, we do have that. To choose that mode it should be `Kiểu gõ` => `VNI`.

**Comment by goatastronaut0212** [comment]
I think we can close this issue now.
