### ISSUE TITLE
can't type characters when switching to vietnamese input method on debian 12 after update

### ISSUE THREAD

**Issue by U3Vzc3kgQW1vZ3Vz** [BambooEngine/ibus-bamboo#478]
**Mô tả lỗi**

can't tyoe characters when switching to vietnamese on debian 12 after update
**Các bước tái hiện lỗi**

Ví dụ:
1. sudo apt update && sudo apt upgrade
2. reboot
3. switch ibus-bamboo input from english to vietnamese
4. can type numbers and special characters but can't type letter 

**Kết quả mong muốn**
Type out characters and vietnamese characters atter switching to Vietnamese input method

**Ảnh chụp màn hình, hoặc clip quay màn hình**

after entering the below command
```console
ibus-daemon --xim --verbose
```
if the input is english, the terminal receives the keystrokes and displays it to the terminal
![Screenshot from 2024-05-09 11-54-57](https://github.com/BambooEngine/ibus-bamboo/assets/99819877/6efbd709-1b09-467f-992c-a3319058bf4e)
whereas the ibus receives the keystrokes but doesn't display it
![Screenshot from 2024-05-09 11-53-58](https://github.com/BambooEngine/ibus-bamboo/assets/99819877/a5c5b5f1-8cec-4116-9694-d99fb170c40d)

**Môi trường**
 - OS và version: Debian 12 Bookworm/LMDE 6 Faye
 - Desktop: Cinnamon 6.0.4
 - Phiên bản ibus-bamboo: 0.8.3-0
 - Kernel: 6.1.0-21-amd64
 - Display Server: X11

**Thông tin thêm**

- The package breaks after the update, it was working fine before 
- Tried switching "chế độ gõ" doesn't work
- If turned on gõ tắt, even the numbers and special characters stop working
``` console
$ find ~/.config/ibus/bus/
/home/nam/.config/ibus/bus/
/home/nam/.config/ibus/bus/22603bca0b5c4801b4b14521098b8fb3-unix-0
$ cat $(find ~/.config/ibus/bus/)
cat: /home/nam/.config/ibus/bus/: Is a directory
# This file is created by ibus-daemon, please do not modify it.
# This file allows processes on the machine to find the
# ibus session bus with the below address.
# If the IBUS_ADDRESS environment variable is set, it will
# be used rather than this file.
IBUS_ADDRESS=unix:abstract=/home/nam/.cache/ibus/dbus-HIvSWxyq,guid=b8a7d335b5e6512061768e7d663c5c39
IBUS_DAEMON_PID=10329

```

**Comment by kocoten1992** [comment]
Same issue, can type `123456789`, `!@#$%^&*()`, `  `, but can't type any characters...

**Comment by U3Vzc3kgQW1vZ3Vz** [comment]
> sau một bản cập nhật khác của debian, đã gõ tiếng Việt lại được, chẳng hiểu vì sao...

ban co the ke goi ban update la gi khong? minh update nhung minh van bi

**Comment by kocoten1992** [comment]
Mình không chắc lắm bạn, xài debian 12 mặc định, tự nhiên hỏng ibus, sau một bản cập nhật khác, mình restart lại toàn bộ các service (có gdm3) thì tự nhiên work lại :disappointed:

**Comment by U3Vzc3kgQW1vZ3Vz** [comment]
mình update lại thì nó hoạt động lại được rồi. Mình cảm ơn
