### ISSUE TITLE
Không tìm thấy phần cài đặt các loại chế độ gõ như giới thiệu

### ISSUE THREAD

**Issue by minh98** [BambooEngine/ibus-bamboo#48]
Mình đã cái đặt và đã gõ được tiếng việt.
tuy nhiên mình không thấy phần cài đặt ở đâu cả.
và sau khi mình bấm dấu cách để sang từ mới rồi lại xóa dấu cách đi muốn sửa từ cũ thì không sửa dc nữa 
![Screenshot from 2019-07-02 22-21-24](https://user-images.githubusercontent.com/26597466/60111671-9446c580-9798-11e9-983d-66096df65ab6.png)

**Môi trường**
 - OS và version: 18.04.2 mặc định
 - Phiên bản ibus: 1.5.17
 - Phiên bản ibus-bamboo: mình ko biết check version nhưng mới nhất hiện tại là 0.5.0

**Comment by minh98** [comment]
như ảnh màn hình thì chỉ có tùy chọn giữa 2 cái chứ không có phần cài đặt

**Comment by minh98** [comment]
hiện tại sau khi khởi động lại máy thì mình đã nhìn thấy phần cài đặt.
tuy nhiên những từ mình đã viết thì không sửa lại dc nữa

**Comment by luongthanhlam** [comment]
Bạn đang dùng chế gõ gì vậy (nhấn shift+~ để kiểm tra)? Nếu là preedit thì không sửa đc các từ đã commit nhé.

**Comment by minh98** [comment]
![Screenshot from 2019-07-03 20-23-13](https://user-images.githubusercontent.com/26597466/60183437-85bbe500-9850-11e9-9965-d3203cfffc8a.png)
hiện tại mình đang dùng cái thứ 3 thì thấy đã sửa được nhưng mình viết sang dòng mới thì lại có gạch chân và lại ko sửa dc nữa.
thêm 1 lỗi nữa là mình gõ cláss , dấu sắc nó ko bị mất đi

**Comment by minh98** [comment]
bây giờ mình lại sửa dc và mất gạch chân rồi. hình như lúc được lúc không được

**Comment by luongthanhlam** [comment]
Uhm, trên chrome hiện tại chỉ có chế độ thứ 1 hoạt động ổn định thôi
