### ISSUE TITLE
Không thể đặt các nút shortcuts trong mục phím tắt

### ISSUE THREAD

**Issue by goatastronaut0212** [BambooEngine/ibus-bamboo#489]
**Mô tả lỗi**
Không đặt được các được các shortcuts trong phần phím tắt

**Các bước tái hiện lỗi**
Khi đặt các nút cho phím tắt rồi bấm nút save nó sẽ không lưu lại mà thay vào đó tự động ra 1 bộ phím tắt kỳ quặc

**Kết quả mong muốn**
Sẽ phải ra các phím tắt được chọn

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Trước khi đặt phím tắt
![bamboo2](https://github.com/BambooEngine/ibus-bamboo/assets/119769817/fe5d9962-ecee-4d70-a3a1-b6cc5cfd0610)
Sau khi save
![bamboo3](https://github.com/BambooEngine/ibus-bamboo/assets/119769817/5eef7358-d770-4914-865b-18d8fa6eafef)

**Môi trường**
 - OS và version: NixOS
 - Desktop: Qtile (Xorg)
 - Phiên bản ibus-bamboo: ibus-bamboo 0.8.4-rc3

**Comment by ging-dev** [comment]
> **Mô tả lỗi** Không đặt được các được các shortcuts trong phần phím tắt
> 
> **Các bước tái hiện lỗi** Khi đặt các nút cho phím tắt rồi bấm nút save nó sẽ không lưu lại mà thay vào đó tự động ra 1 bộ phím tắt kỳ quặc
> 
> **Kết quả mong muốn** Sẽ phải ra các phím tắt được chọn
> 
> **Ảnh chụp màn hình, hoặc clip quay màn hình** Trước khi đặt phím tắt ![bamboo2](https://private-user-images.githubusercontent.com/119769817/335032270-fe5d9962-ecee-4d70-a3a1-b6cc5cfd0610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjM3NTIsIm5iZiI6MTcxNzE2MzQ1MiwicGF0aCI6Ii8xMTk3Njk4MTcvMzM1MDMyMjcwLWZlNWQ5OTYyLWVjZWUtNGQ3MC1hM2ExLWI2Y2M1Y2ZkMDYxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMzUwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmI4YTA0MTQ2ZTc0YWY2NzM4OGJmODQ2M2U0YWExYmM1ZmQ5YmJlMWMwNzg2MThmMDA5ZDg1NTFlMGQ3YzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jXmxqvgmIzJceQ9XmXR3Zj6qwRbcUC_FvWV1_zJoiRE) Sau khi save ![bamboo3](https://private-user-images.githubusercontent.com/119769817/335032283-5eef7358-d770-4914-865b-18d8fa6eafef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjM3NTIsIm5iZiI6MTcxNzE2MzQ1MiwicGF0aCI6Ii8xMTk3Njk4MTcvMzM1MDMyMjgzLTVlZWY3MzU4LWQ3NzAtNDkxNC04NjViLTE4ZDhmYTZlYWZlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMzUwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWI4YjVlM2JmYTAwODQ0OGI5YTE0MTQ1YTUwZWEwMGNkNzUxM2MxMTk3NzgxYzI0MWUzMTdkOGZhZDZkYTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GD89Zh5-nC5wL3ucnel9kYswntrTEKpuIqDUrix9w9M)
> 
> **Môi trường**
> 
> * OS và version: NixOS
> * Desktop: Qtile (Xorg)
> * Phiên bản ibus-bamboo: ibus-bamboo 0.8.4-rc3

Same issue with ubuntu 24.04.

**Comment by goatastronaut0212** [comment]
> .

Hiện tại mình chỉ có cách fix là dùng cái config ibus-bamboo cũ rồi đè hết trong thư mục `~/.config/ibus-bamboo` thôi thì nó mới quay lại cái config mặc định mà không động vào chứ cũng không ăn thua lắm.

**Comment by luongthanhlam** [comment]
bạn cập nhật bản mới nhất và thử lại nhé!
