### ISSUE TITLE
Không gõ được tiếng việt trong visualcode

### ISSUE THREAD

**Issue by xuandung38** [BambooEngine/ibus-bamboo#49]
**Mô tả lỗi**
Mình gõ tiếng việt trong visual studio code bị lỗi, không thể nào gõ được ra tiếng việt, như kiểu bị tắt vậy./

**Các bước tái hiện lỗi**
Mở Visual Studio Code , tạo file , Viết comment bằng tiếng việt (mình sử dụng cả telex lẫn vni đều không được.
**Kết quả mong muốn**

Phải gõ được tiếng việt trong Visual code

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://drive.google.com/file/d/1ln2CkjzUwBb5XbfhSyWitdmaCcTwxSzm/view?usp=sharing

**Môi trường**
 - OS và version: Ubuntu 19.04
 - Desktop: Gnome
 - Phiên bản ibus: IBus 1.5.19
 - Phiên bản ibus-bamboo: bản mới nhất

**Comment by xuandung38** [comment]
Ví dụ là gõ chữ "Danh mục bài viết" ra "Danh mucj baif vieets"

**Comment by ndgnuh** [comment]
Theo như mình biết thì vscode có 2 bản build, trong đó một bản build bằng flatpak. Bản build bằng flatpak không hoạt động với ibus, nên bạn *không thể dùng bất cứ bộ gõ nào*.

**Comment by xuandung38** [comment]
Mình đã thử với cả hai bản nhưng không có bản nào gõ được cả bạn !

**Comment by ltlam93** [comment]
Bạn đang dùng chế độ gõ nào vậy (nhấn shift ~ để kiểm tra)?

**Comment by xuandung38** [comment]
Mình sử dụng Cấu hình mặc định!

**Comment by ndgnuh** [comment]
vậy bạn đã thử set biến môi trường và chạy ibus như trong mục FAQ ở wiki chưa?

**Comment by ImKifu** [comment]
Em cũng dùng hệ điều hành giống anh ạ, và em tải VSCode trên trang chủ rồi giải nén cài đặt bằng tay thì em thấy vẫn dùng được ạ.

**Comment by ndgnuh** [comment]
Bản trên trang chủ là bản build bình thường, bản trên snap thì mình không biết, còn bản flatpak thì không dùng đc ibus.

Thường thì những lỗi kiểu dạng "gõ tiếng Việt không ra dấu" sẽ là lỗi do ibus chưa đc config, hoặc phần mềm bạn dùng không hỗ trợ ibus gì đó chứ không phải lỗi của engine, các bạn nên đọc faq hoặc gửi issue bên ibus hoặc chính phần mềm đó.

Có vẻ như app từ ubuntu store là snap và k hỗ trợ ibus, bạn nên tải file deb cài ừ trang chủ như bạn ở trên nhé.

**Comment by vuminhcongvmc** [comment]
Mình đang sử dụng Ibus trên VSCode build ra deb trên trang chủ và gõ rất OK, bạn nên tải file deb từ trang chủ rồi cài đặt, nếu bạn không biết cài từ deb thì bạn gõ theo cú pháp:
$sudo apt install -y ./"đường dẫn tới file deb"

**Comment by tuantrinitri** [comment]
![image](https://user-images.githubusercontent.com/32632143/61360423-9a682780-a8a8-11e9-8438-7ebb7ec0eb86.png)

Mình gặp lỗi bỏ dấu của vscode bản mới nhất tải từ trang chủ về. Ad có thế support được không ạ

**Comment by vuminhcongvmc** [comment]
> ![image](https://user-images.githubusercontent.com/32632143/61360423-9a682780-a8a8-11e9-8438-7ebb7ec0eb86.png)
> 
> Mình gặp lỗi bỏ dấu của vscode bản mới nhất tải từ trang chủ về. Ad có thế support được không ạ

Lỗi mà bạn nói không phải lỗi của ibus-bamboo, bạn thử với ibus-unikey sẽ thấy, theo một số người trên ubuntu-vn giải thích thì đây là một lỗi font chữ, bạn cài font mà vscode sử dụng về cài vào máy xem.

**Comment by luongthanhlam** [comment]
@xuandung38 bạn còn gặp vấn đề gõ tiếng Việt trong VS không?

**Comment by xuandung38** [comment]
hiện mình đã chuyển qua MacOs nên không rõ!

**Comment by luongthanhlam** [comment]
Vậy mình sẽ close issue tại đây.

**Comment by drdung1999** [comment]
mình cũng đang sài vs code  trên ubuntu và cũng bị kiểu gõ những từ có dấu không được tắt tieesng việt đi thì lại gõ như bình thường ((

**Comment by luongthanhlam** [comment]
@drdung1999 bạn đang dùng chế độ gõ nào (1/2/3/4/5/6/7)? khi gõ tiếng việt thì xảy ra hiện tượng gì?

**Comment by dephesua** [comment]
do cái extention VScodeVim đấy disable nó đi

**Comment by MrKindess** [comment]
![Screenshot from 2021-03-28 16-55-11](https://user-images.githubusercontent.com/41822445/112748539-6aae7400-8fe6-11eb-9fbb-74e39c6ca12a.png)
mình fix đc bằng cách chọn Vietnamese (bamboo (us layout))
ban đầu chọn Vietnamese (bamboo)) vscode nó k nhận đc

**Comment by PhuongTung** [comment]
CHCP 65001
bảng mã:
Tiếng Việt: 1258
Tiếng Nhật: 10001
Tiếng Trung Quốc: 10002, 10008
Tiếng Thái: 10021
Tiếng Hi lạp: 10006, 737, 869
Unicode: 65000, 65001
ASCII extend: 437

**Comment by phucuongit** [comment]
Mình bị vấn đề tương tự như vậy

**Comment by NhatLam310399** [comment]
> ![Screenshot from 2021-03-28 16-55-11](https://user-images.githubusercontent.com/41822445/112748539-6aae7400-8fe6-11eb-9fbb-74e39c6ca12a.png) mình fix đc bằng cách chọn Vietnamese (bamboo (us layout)) ban đầu chọn Vietnamese (bamboo)) vscode nó k nhận đc

Mình chọn giống bạn vẫn không được :((

**Comment by huynp1999** [comment]
> Mình chọn giống bạn vẫn không được :((
Mình gỡ vscode ra rồi cài lại theo package tại đây thì được https://code.visualstudio.com/download. Bạn thử xem

**Comment by thangkenzy** [comment]
> > Mình chọn giống bạn vẫn không được :((
> 
> Mình gỡ vscode ra rồi cài lại theo package tại đây thì được https://code.visualstudio.com/download. Bạn thử xem

Do mình cài app từ snap, gỡ ra cài lại như bạn này là được, mình mới làm xong.

**Comment by NhanItJAVA1** [comment]
Mình bị mất tiếng việt thì sao ạ ví dụ input của mình là "Xin Chào" thì nó chỉ xuất "Xin Cho". Kiểu chữ nào có dấu là nó đá đi hết

**Comment by KuronNazaki** [comment]
> Mình bị mất tiếng việt thì sao ạ ví dụ input của mình là "Xin Chào" thì nó chỉ xuất "Xin Cho". Kiểu chữ nào có dấu là nó đá đi hết

Mình cũng bị giống bác này luôn này. Gõ bằng tiếng việt là chữ nào có dấu nó mất luôn.

**Comment by xuananh2212** [comment]
![image](https://github.com/BambooEngine/ibus-bamboo/assets/91230849/0d3b15c5-3661-4069-8c64-bdfb92a02f6a)
mình gõ trong vs có không ăn dấu mọi người, ai fix hộ mình với ạ

**Comment by xuananh2212** [comment]
![image](https://github.com/BambooEngine/ibus-bamboo/assets/91230849/28bb63d1-51cd-4ecc-9a41-fcd42e01930f)
mình gõ trong vs toàn không ăn dấu , ai fix bug này hộ m với ạ

**Comment by dzung1nguyen** [comment]
mình download deb từ trang chủ và cái đặt bằng command
sudo apt install -y ./code_1.92.2-1723660989_amd64.deb 
thì chạy oki nha

**Comment by nhtanh94** [comment]
Tải từ store của thằng ubuntu là lỗi xóa cài lại như bác ở trên .

**Comment by LooOnGit** [comment]
em cài bộ gõ trước sau đó cài visual code thì được ạ, mọi người thử xem ạ

**Comment by manhit96** [comment]
Claude Code Vietnamese IME Fix
Fix lỗi gõ tiếng Việt trong Claude Code CLI trên macOS. Hỗ trợ các bộ gõ tiếng Việt phổ biến như OpenKey, EVKey, PHTV, Unikey...

https://github.com/manhit96/claude-code-vietnamese-fix
