### ISSUE TITLE
Không thể gõ tiếng việt trên MS Edge Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by hungluong01** [BambooEngine/ibus-bamboo#490]
**Mô tả lỗi**
Không thể gõ tiếng việt trên MS Edge Ubuntu 24.04 LTS

**Các bước tái hiện lỗi**
1. Mở MS Edge
2. Gõ aa vào thanh tìm kiếm
3. Thấy aa

**Kết quả mong muốn**
Gõ aa phải ra â

**Môi trường**
 - OS và version: Ubuntu 24.04
 - Desktop: GNOME
 - Phiên bản ibus-bamboo: 0.8.4

**Thông tin thêm**

Phần mềm được cài đặt từ trang chủ

**Comment by goatastronaut0212** [comment]
@hungluong01 Bạn đã restart Ibus lại chưa? Bạn đã set các biến môi trường trong wiki [này](https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60) rồi restart máy lại chưa?

**Comment by hungluong01** [comment]
mình đã thử hết rồi

**Comment by goatastronaut0212** [comment]
> mình đã thử hết rồi

Ngoài Edge ra bạn vẫn xài được Ibus-bamboo trên các phần mềm khác phải không? Phiền bạn cung cấp thêm thông tin nữa có được nữa như là bạn có đang xài Wayland không? Nếu bạn cung cấp thông tin hơn thì chúng ta sẽ  càng dễ dàng giải quyết được vấn đề của bạn hơn.

**Comment by hungluong01** [comment]
các phần mềm khác vẫn gõ được tiếng Việt, và mình có dùng Wayland

**Comment by goatastronaut0212** [comment]
> các phần mềm khác vẫn gõ được tiếng Việt, và mình có dùng Wayland

Ibus hiện tại chưa hỗ trợ hoàn toàn Wayland được nên nếu nó xảy ra lỗi thì cũng không thể giải quyết được nhiều. Cái này phụ thuộc vào upstream nhiều như là Wayland input protocol và ibus. Nên mình nghĩ bạn nên sử dụng Xorg sẽ tốt hơn còn, Wayland thì chắc cần thêm 1 thời gian dài nữa mặc dù v3 input protocol chính thức vẫn chưa có. Mặc dù mình cũng có thể gõ tiếng việt trên Edge với Wayland nhưng các phần mềm khác thì lại không may mắn đến vậy.

Nếu bạn muốn chờ đợi thêm thông tin thì có thể đợi cùng mình ở [đây](https://github.com/BambooEngine/ibus-bamboo/issues/44). Còn nếu như bạn muốn mình sửa thì sẽ cần thêm 1 thời gian rất là dài ít nhất là cho đến khi PR này được hoàn thành https://github.com/ibus/ibus/pull/2256 hoặc là mình sẽ tiếp quản công việc dang dở đó.

Phiền bạn đóng issue lại nếu không còn vấn đề gì nữa. Cảm ơn bạn, ad Lâm cũng không thường xuyên không rảnh rỗi để hỗ trợ được nhiều lắm.
