### ISSUE TITLE
Danh sách loại trừ và phím tắt không hoạt động với một số app GTK trên wayland

### ISSUE THREAD

**Issue by ging-dev** [BambooEngine/ibus-bamboo#491]
**Mô tả lỗi**
Một số app GTK như gnome-terminal, nautilus, v.v.. trên wayland vẫn gõ được tiếng Việt mặc dù đã thêm vào danh sách loại trừ. Ngoài ra, phím tắt chuyển chế độ gõ, v.v.. có vẻ không hoạt động với nhưng app này.

**Môi trường**
 - OS và version: Ubuntu 24.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: latest

**Comment by luongthanhlam** [comment]
Wayland/Gnome hiện tại không hỗ trợ lấy ID của cửa sổ đang gõ nên nhiều tính năng sẽ không hoạt động nhé bạn
