### ISSUE TITLE
Ibus không hoạt động với wayland

### ISSUE THREAD

**Issue by langbach364** [BambooEngine/ibus-bamboo#492]
OS: Arch
DE/VM: Hyprland (wayland)
version ibus: IBus 1.5.30
version ibus-bamboo: 0.8.4_RC1-1

Chi tiết lỗi:
- Các ứng dụng như (vscodium, discord) bị lỗi, không biết mấy ứng dụng khác thì sao nhưng máy tui có 2 cái này để test à, các ứng dụng này chạy
- Các ứng dụng này đều chạy electron dựa trên nền tảng là Ozone mình để là auto (tức là nó tự chọn nền tảng wayland, X11 dựa trên môi trường)
- Đã thêm các biến môi trường 
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
DefaultIMModule=ibus
GLFW_IM_MODULE=ibus
vào /etc/enviroment

Trường hợp đặc biệt:
- Firefox là trình duyệt duy nhất không bị ảnh hưởng chạy bởi X11 hay wayland (tui cũng đã tìm hiểu lý do mà không biết tại sao nữa :))) có thông tin thì có thể nói cho tui biết)

Cách khắc phục tạm thời: 
- Chuyển wayland sang x11 là được

cấu hình hyprland của tui
#environment-variables
env = CLUTTER_BACKEND,wayland
env = GDK_BACKEND,x11
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct   
env = QT_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

#xwayland apps scale fix (useful if you are use monitor scaling)
#see https://wiki.hyprland.org/Configuring/XWayland/
#toolkit-specific scale
 env = GDK_SCALE,1

#firefox
env = MOZ_ENABLE_WAYLAND,1

#electron >28 apps (may help)
#env = ELECTRON_OZONE_PLATFORM_HINT,auto(tui tạm tắt nó đi vì hiện tại bị lỗi)

nguồn tham thảo https://wiki.archlinux.org/title/Wayland#Configuration_file

Không biết sao nhưng tự dưng tuần trước cập nhật cái bị lỗi không hiểu sao @@ có khi bên hyprland hay wayland có bản nào hay sao ấy, ông nào đang xài hyprland(Wayland) thì xác nhận giúp tui cái

**Comment by goatastronaut0212** [comment]
Giải pháp hiện tại là đừng dùng Wayland nữa. Nếu có thông tin gì thêm về việc hỗ trợ Wayland trên Ibus thì mình sẽ nói lại ở đây sau.

https://github.com/BambooEngine/ibus-bamboo/issues/44

Phiền bạn hãy đóng issue này lại vì trước đó đã có 3-4 issues tương tự rồi.
