### ISSUE TITLE
Lỗi sever cài đặt cho debian (404 not found)

### ISSUE THREAD

**Issue by Karutovn** [BambooEngine/ibus-bamboo#493]
**Mô tả lỗi**

**Các bước tái hiện lỗi**
Mở termianl và chạy lệnh sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo
**Kết quả mong muốn**
Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Debian nhận server và có thể cài được ibus trên debian
**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://github.com/BambooEngine/ibus-bamboo/assets/73945551/21387fa8-16ad-46cb-9c99-cb5518ba3a8a)

**Môi trường**
 - OS và version: Debian 12 
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: chưa biết
**Thông tin thêm**

**Comment by luongthanhlam** [comment]
Với Debian, bạn phải cài đặt từ OBS https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo chứ không thể add PPA của ubuntu như cách thông thường được nhé

**Comment by Karutovn** [comment]
> Với Debian, bạn phải cài đặt từ OBS https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo chứ không thể add PPA của ubuntu như cách thông thường được nhé

Em thử cài thì nó báo lỗi gpg ạ

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn ở đây nhé https://askubuntu.com/questions/522114/cant-get-rid-of-gpg-error-http-download-opensuse-org
