### ISSUE TITLE
Không gõ được tiếng Việt trên terminal Konsole (terminal mặc định trên môi trường KDE Plasma)

### ISSUE THREAD

**Issue by brianhuster** [BambooEngine/ibus-bamboo#494]
**Mô tả lỗi**
Không gõ được tiếng Việt trên Konsole (terminal mặc định trên môi trường KDE Plasma)

**Các bước tái hiện lỗi**
Ví dụ:
1. Mở Konsole
2. Gõ `Vieetj Nam`
3. Thấy `Vieetj Nam`

**Kết quả mong muốn**
Gõ `Vieetj Nam` thì phải ra `Việt Nam`

**Môi trường**
 - OS và version: Kubuntu 22.04
 - Desktop: KDE Plasma
 - Phiên bản ibus-bamboo: 0.8.4

Lưu ý rằng tôi vẫn có thể gõ tiếng Nhật qua ibus-mozc-jp trên Konsole, vì vậy đây dường như không phải vấn đề của ibus nói chung. Tôi cũng đã thử cả 6 chế độ gõ nhưng không thành

**Comment by brianhuster** [comment]
À, chọn chế độ ForwardKeyEvent I là được

**Comment by goatastronaut0212** [comment]
> À, chọn chế độ ForwardKeyEvent I là được

Bạn có xài Wayland không? Và bạn có các biến trong môi trường chưa?

**Comment by brianhuster** [comment]
Cảm ơn bạn, mình đã khắc phục được rồi. Vấn đề chẳng qua là do mình không biết là khi mình đổi chế độ trong ibus-bamboo thì nó chỉ áp dụng cho app đó thôi

**Comment by goatastronaut0212** [comment]
> Cảm ơn bạn, mình đã khắc phục được rồi. Vấn đề chẳng qua là do mình không biết là khi mình đổi chế độ trong ibus-bamboo thì nó chỉ áp dụng cho app đó thôi

Nếu không còn vấn đề gì nữa thì bạn đóng issue lại có được không?
