### ISSUE TITLE
iBus chỉ chạy trên một số ứng dụng nhất định

### ISSUE THREAD

**Issue by songoffireandice03** [BambooEngine/ibus-bamboo#495]
**Mô tả lỗi**
iBus chỉ gõ tiếng Việt được trên 2 ứng dụng: Firefox và VSCode. Tất cả các ứng dụng khác đều không gõ được tiếng Việt.

Trong .zshrc đã thêm vào tùy chỉnh.

**Kết quả mong muốn**
Trong alacritty, gõ "ngax" thì phải cho ra "ngã" hay "aw" thì "ă" phải xuất hiện (xem video đính kèm).

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://github.com/BambooEngine/ibus-bamboo/assets/90322180/fdd5a0d7-a8a4-481c-b993-4780f9e68956

**Môi trường**
 - OS: Arch Linux
 - Desktop: KDE Plasma 6 X11
 - Phiên bản ibus-bamboo: 0.8.4-RC1
 - Terminal: alacritty + zsh

**Comment by goatastronaut0212** [comment]
Bạn đã thử thêm biến `export GLFW_IM_MODULE=ibus` vào biến môi trường hay .zshrc chưa?

**Comment by songoffireandice03** [comment]
> Bạn đã thử thêm biến `export GLFW_IM_MODULE=ibus` vào biến global của môi trường hay `~/.zshrc` chưa? Bạn có đang xài Wayland hay là Xorg?

Mình đang xài Xorg [KDE Plasma 6 (X11)]. Đây là tùy chỉnh trong `.zshrc`:
```
# IBus config
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
# Dành cho những phần mềm dựa trên qt4
QT4_IM_MODULE=ibus
# Dành cho những phần mềm dùng thư viện đồ họa clutter/OpenGL
CLUTTER_IM_MODULE=ibus
GLFW_IM_MODULE=ibus 
```

Để chắc ăn, mình cũng thêm vào `.zshenv`:

```
# ~/.zshenv
# default apps
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# default folders
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_SCREENSHOTS_DIR="$HOME/Pictures/Screenshots"

#ibus config
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
# Dành cho những phần mềm dựa trên qt4
QT4_IM_MODULE=ibus
# Dành cho những phần mềm dùng thư viện đồ họa clutter/OpenGL
CLUTTER_IM_MODULE=ibus
GLFW_IM_MODULE=ibus 
# lf icons
export LF_ICONS="\
tw=:\
st=:\
ow=:\
dt=:\
```

**Comment by goatastronaut0212** [comment]
> > Bạn đã thử thêm biến `export GLFW_IM_MODULE=ibus` vào biến global của môi trường hay `~/.zshrc` chưa? Bạn có đang xài Wayland hay là Xorg?
> 
> Mình đang xài Xorg [KDE Plasma 6 (X11)]. Đây là tùy chỉnh trong `.zshrc`:
> ```
> # IBus config
> GTK_IM_MODULE=ibus
> QT_IM_MODULE=ibus
> XMODIFIERS=@im=ibus
> # Dành cho những phần mềm dựa trên qt4
> QT4_IM_MODULE=ibus
> # Dành cho những phần mềm dùng thư viện đồ họa clutter/OpenGL
> CLUTTER_IM_MODULE=ibus
> GLFW_IM_MODULE=ibus 
> ```
> 
> Để chắc ăn, mình cũng thêm vào `.zshenv`:
> 
> ```
> # ~/.zshenv
> # default apps
> export EDITOR="nvim"
> export VISUAL="nvim"
> export TERMINAL="alacritty"
> export BROWSER="firefox"
> 
> # default folders
> export XDG_CONFIG_HOME="$HOME/.config"
> export XDG_DATA_HOME="$HOME/.local/share"
> export XDG_STATE_HOME="$HOME/.local/state"
> export XDG_CACHE_HOME="$HOME/.cache"
> export XDG_SCREENSHOTS_DIR="$HOME/Pictures/Screenshots"
> 
> #ibus config
> GTK_IM_MODULE=ibus
> QT_IM_MODULE=ibus
> XMODIFIERS=@im=ibus
> # Dành cho những phần mềm dựa trên qt4
> QT4_IM_MODULE=ibus
> # Dành cho những phần mềm dùng thư viện đồ họa clutter/OpenGL
> CLUTTER_IM_MODULE=ibus
> GLFW_IM_MODULE=ibus 
> # lf icons
> export LF_ICONS="\
> tw=:\
> st=:\
> ow=:\
> dt=:\
> ```
> nó vẫn không chạy :(

Config của bạn không có export cho biến. Bạn thử lại xem

**Comment by songoffireandice03** [comment]
Bây giờ hoạt động tốt rồi. Cảm ơn bạn nhiều.


https://github.com/BambooEngine/ibus-bamboo/assets/90322180/a479ed55-9167-43f6-afce-dd7e4283a9b6

**Comment by goatastronaut0212** [comment]
> Bây giờ hoạt động tốt rồi. Cảm ơn bạn nhiều.
> 
> 
> https://github.com/BambooEngine/ibus-bamboo/assets/90322180/a479ed55-9167-43f6-afce-dd7e4283a9b6
> 
> 

Phiền bạn đóng issue lại được không?

**Comment by TraLeeee** [comment]
Lạ thật, mình cũng bị giống bạn này nhưng nếu chạy ứng dụng từ Konsole (mở konsole lên gõ kate hoặc kwrite) thì nó mới gõ được tiếng Việt, còn nếu bật từ Start menu thì không được. :man_shrugging:
