### ISSUE TITLE
khong the su dung ibus tren chrome ozone wayland

### ISSUE THREAD

**Issue by anhtuan7979** [BambooEngine/ibus-bamboo#499]
**Mô tả lỗi**
k the danh tieng viet tren chrome (wayland)

**Các bước tái hiện lỗi**
su dung chrome, vo cai dat flags 
chinh ozone thanh wayland de net hon
go tieng viet k nhan ( ca telex va vni )

Ví dụ:
1. xai chrome thay chu bi blurry
2. vo chrome://flags/ chinh Preferred Ozone platform thanh wayland de chu net hon
3. khoi dong lai trinh duyet va tieng viet k hoat dong

**Kết quả mong muốn**
go tieng viet bth

**Môi trường**
 - OS và version: ubuntu 24.04 LTS
 - Desktop: mac dinh
 - Phiên bản ibus-bamboo: 0.8.4

**Comment by goatastronaut0212** [comment]
@anhtuan7979 Hỗ trợ thuần Wayland không hoạt động tốt trên Ibus. Mình khuyến khích bạn sử dụng Xorg hoặc nếu xài Wayland hãy chắc chắn rằng các app chạy dưới Xorg để Xwayland có thể tương tác được.

Mình cũng không biết lý do vì sao 1 số app thì gõ được trên Wayland mà không cần thông qua Xwayland nhưng có vẻ cho đến khi Ibus có thể implement được v2 protocol thì mọi thứ có thể sẽ tốt hơn.

Nếu không còn gì nữa thì phiền bạn đóng issue lại.
