### ISSUE TITLE
Lỗi ở thanh URL và gạch chân, tự động gửi phím

### ISSUE THREAD

**Issue by quanpham0805** [BambooEngine/ibus-bamboo#5]
**Mô tả lỗi**
- Lúc ấn địa chỉ web vào và sử dụng gợi ý link của chrome enter trên thanh địa chỉ thì ra kết quả của search engine thay cho việc đi thẳng vào url.
~- Đã tắt gạch chân nhưng vẫn hiện gạch chân.~

**Các bước tái hiện lỗi**

* Lỗi 1:
- B1: Mở Chrome.
- B2: Nhập 1 địa chỉ nào đó nhưng không hoàn thành hết. Ví dụ mở trang "facebook.com" chỉ gõ "fa" "f" hay "face".
- B3: Dễ thấy thanh địa chỉ tự hoàn thành nốt phần url, ấn enter.

~* Lỗi 2:~
~+ Kiểu gõ: Telex 2~
~+ Bảng mã Unicode~
~+ Gõ tắt: off~
~+ Kiểm tra chính tả và từ điển: tắt~
~+ Bỏ dấu tự do, dấu thanh chuẩn, ẩn gạch chân: bật~

* Lỗi 3:
- Trong mục "Cấu hình khác", ấn vào "tự động gửi phím" thì không ra gì

**Kết quả mong muốn**

* Lỗi 1: Đáng ra khi enter thì nó sẽ đi đến địa chỉ thay vì search. Mình thấy là lỗi này có thể do cái tính năng enter, kiểu như lúc mà nó đang hiện ra cái gợi ý url đó, ấn phím mũi tên xuống vẫn thấy lựa chọn là "facebook.com" còn lựa chọn đầu lại là search engine. Phần này hơi trừu tượng, nếu cần ảnh hay video mình sẽ cung cấp.

~* Lỗi 2: Lúc typing thì khi đang viết chữ sẽ hiện ra underline, còn trong terminal thì không có. Mong muốn không hiện ra.~

* Lỗi 3: Ấn vào mục kia thì bảng điều khiển mình nghĩ là sẽ hiện ra các "nút" hay "lựa chọn" thay vì nháy 1 cái rồi biến mất.

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 18.04.1 LTS)
 - Phiên bản ibus-bamboo: (v0.2.5)

Edit: Lỗi gạch chân là chỉ ở trong chrome, mình có đọc qua các bài khác đã thấy nhiều về vấn đề này rồi.

**Comment by luongthanhlam** [comment]
Chào bạn, lỗi 1 và 3 mình đã sửa trong v0.2.7. Lỗi 2 là do chrome không cho phép ẩn gạch chân, bạn có thể cân nhắc chuyển sang backspace giả bằng cách nhấn phím tắt <Shift>+~
