### ISSUE TITLE
Không khôi phục được phím nếu tắt kiểm tra chính tả

### ISSUE THREAD

**Issue by auduongtansang** [BambooEngine/ibus-bamboo#50]
Vì đặc thù công việc nên mình phải tắt kiểm tra chính tả, tuy nhiên dẫn đến vấn đề trong việc khôi phục phím khiến mình khá khó chịu.

1. Tắt kiểm tra chính tả.
2. Gõ "linux"
3. Hiện ra "linũ"
4. Gõ tiếp "x" để khôi phục dấu ngã thành kí tự "x"
5. Nhưng lại hiện ra "linũx" chứ không phải "linux" như mong muốn.

**Môi trường**
 - OS và version: Ubuntu 18.04
 - Phiên bản ibus-bamboo: v0.5.0

**Comment by luongthanhlam** [comment]
cám ơn bạn báo lỗi, mình đã sửa lỗi này trong bản 0.5.1 rồi nhé.
