### ISSUE TITLE
Alt + F4 để thoát window khó ăn + bị giựt mỗi khi click chuột khi dùng chương trình

### ISSUE THREAD

**Issue by hien-ngo29** [BambooEngine/ibus-bamboo#500]
**Mô tả lỗi**
Mỗi khi _ibus-bamboo_ chạy trong background thì mình đều gặp vấn đề bị giựt, đơ chương trình khoảng 100ms khi click chuột. VD như chơi game, khi mình click chuột thì khung hình hiện tại sẽ bị đơ khoảng 100ms và nhảy sang khung hình 100ms sau. Các phần mềm khác cũng vậy, mình dùng Krita để vẽ, mỗi khi click chuột thì cũng gặp vấn đề tương tự. 

Ngoài ra, khi dùng xong chương trình và muốn thoát ra, mình hay dùng alt + F4. Tuy nhiên, cửa sổ không thoát mà lại kêu tiếng ting alert của hệ điều hành, mình phải nhấn 1 lần nữa cửa sổ mới thoát. (Các phím tắt khác có lẽ cũng bị)

Hồi đó mình chưa biết, khi bị như vậy mình tìm cách fix hoài mà không được, sau mới biết là do _ibus-bamboo_ . Vì vậy mỗi khi có vấn đề là mình đều dùng `ibus exit` để thoát, nhưng mỗi khi muốn gõ Tiếng Việt lại đều phải mở Terminal lên rồi chạy lại ibus-bamboo bằng `ibus start`. Khá khó chịu.

Còn 1 điều nữa, lỗi không hẳn lúc nào cũng bị mỗi khi mở _ibus-bamboo_ lên. Mới mở lên thì không bị gì, chỉ khi mình dùng một lúc là bắt đầu bị. Không hiểu vì sao.

**Môi trường**
 - Enviroment: Ubuntu 24.04 LTS
 - Desktop: Gnome
 - Version: IBus 1.5.29-rc2

**Comment by goatastronaut0212** [comment]
@hien-ngo29 phiên bản ibus-bamboo bạng đang dùng la phiên bản bao nhiêu vậy?

**Comment by hien-ngo29** [comment]
Hiện tại phiên bản ibus-bamboo mình đang dùng là phiên bản mới nhất build từ source (version 0.8.4)

**Comment by hien-ngo29** [comment]
Mình phát hiện là vấn đề sẽ xảy ra khi mình bật **Bắt sự kiện chuột**. Chỉ cần tắt nó đi là mọi thứ lại OK.

![image](https://github.com/user-attachments/assets/88b6bdcf-0cb5-4042-a370-85479adf5615)


Thực ra thì mình cũng không biết option này để làm gì nữa nhưng mà tạm thời thì mình biết cội nguồn vấn đề rồi 😀😀😀

**Comment by luongthanhlam** [comment]
Option này giúp chữ đang gõ được commit vào vị trí đang gõ chứ ko phải vị trí click chuột. Tính năng chỉ hữu ích nếu bạn dùng chế độ gõ số 1. Tuy nhiên có vẻ nó đang xung đột với 1 vài OS/DE, nếu nhiều người cũng bị lỗi này thì mình sẽ cho tắt mặc định.
