### ISSUE TITLE
Không thể sử dụng trong ứng dụng Qt6

### ISSUE THREAD

**Issue by vnphat96** [BambooEngine/ibus-bamboo#502]
Không thể gõ tiếng Việt trong phần mềm Texstudio phiên bản sử dụng Qt6 (phiên bản sử dụng nền Qt5 sử dụng bình thường)
![image](https://github.com/user-attachments/assets/948dc4a9-5823-4afa-bb4c-d87fad8b6bd8)

**Comment by goatastronaut0212** [comment]
Bạn xài Wayland hay Xorg?

**Comment by vnphat96** [comment]
> Bạn xài Wayland hay Xorg?

Mình sử dụng Xorg.
OS Manjaro xfce
