### ISSUE TITLE
Xung đột với search suggestions trên trình duyệt firefox

### ISSUE THREAD

**Issue by quan1232004** [BambooEngine/ibus-bamboo#503]
**Mô tả lỗi**
Khi tìm kiếm trên thanh address, phải nhập hết từ rồi bấm dấu cách thì nó mới gợi ý (bàn phím tiếng việt)

**Các bước tái hiện lỗi**
Chuyển sang tiếng Việt và tìm kiếm trên thanh address bar

**Kết quả mong muốn**
Hiển thị search suggestions bình thường và liên tục

**Môi trường**
 - OS và version: Linux Mint 21.3
 - Desktop: Cinnamon
 - Phiên bản ibus-bamboo: 0.8.1

**Comment by goatastronaut0212** [comment]
Phiên bản mới thì sao bạn có bị lỗi đó nữa không? Và bạn có thử chuyển và chọn chế độ gõ khác chưa? (aka `shift` + `~`)

**Comment by quan1232004** [comment]
Mình vẫn gặp lỗi tương tự

**Comment by goatastronaut0212** [comment]
Thực ra thì nếu bảo đây là lỗi thì cũng không hẳn, căn bản hiện tại nó là 1 code hack cho chế độ gõ 1, nó khá là xấu nhưng mà nó hoạt động và cũng đã có các chế độ gõ khác cho từng ứng dụng rồi. Bạn có thể thử chuyển đổi sang chế độ 2 để thử và gợi ý từ thanh tìm kiếm sẽ hiển thị thôi. Bạn xem chỉ cần gõ `Shift` + `~` su đó chọn mode 2 ở dưới. Nếu thấy không được thì cứ thử hết các mode còn lại thôi.

Ad Lâm có vẻ không có nhiều thời gian lắm để document về cái chế độ gõ này lắm nên nhiều người cũng không biết, khi nào rảnh có thể mình sẽ làm nó. Nếu không phiền thì bạn có thể đóng issue lại được không, cảm ơn bạn. Hiện tại thì có vẻ anh ấy đang bận chuyện gì đó nên cũng không xem issues hay là check PR gần đây của mình.

**Comment by luongthanhlam** [comment]
Chế độ gõ số 1 (pre-edit) thực ra rất đơn giản, chỉ là 1 buffer do bộ gõ tự quản lý, sau khi gõ xong mới được bộ gõ gửi vào input của ứng dụng. Một vài ứng dụng (Chrome) có thể đọc dữ liệu trong buffer của bộ gõ và tự động hiện suggestion trên thanh địa chỉ, một số ứng dụng thì không (Firefox). Vì vậy pre-edit không hoạt động với suggestion trên firefox, muốn hiện suggestion bạn cần chuyển sang chế độ gõ khác không dùng buffer (2, 3, 4,..)
