### ISSUE TITLE
Lỗi shortcut không hoạt động & ibus icon delay

### ISSUE THREAD

**Issue by LAM-GIA-THINH** [BambooEngine/ibus-bamboo#505]
**Lỗi short không hoạt động **
Cài đặt phím tắt
![image](https://github.com/user-attachments/assets/10fd1e3b-af33-4e53-b525-48248d4361b9)
Nhấn combo shortcut thì ngôn ngữ ko đổi

**ibus icon delay**
>Khi click chuột phải lên icon thì delay tầm 30s mới load menu
>Sau khi menu đã load
>Hover chuột lên các option để hiện submenu
>submenu ko hiện
>crash giao diện khi nhấn vào option ngẫu nhiên
![image](https://github.com/user-attachments/assets/96ed3e03-4b18-402f-8018-68d931b1b18d)
![image](https://github.com/user-attachments/assets/5d8568ec-0e7a-4ad6-9837-c412b28bc3ce)

**Môi trường**
 - OS và version: Arch linux 6.10.0-arch1-2 
 - Desktop: KDE
 - Phiên bản ibus-bamboo: 0.8.4_RC1-1

**Comment by goatastronaut0212** [comment]
@LAM-GIA-THINH Bạn đang sử dụng Wayland sao?

**Comment by goatastronaut0212** [comment]
Vì không còn tương tác nào tự người báo cáo lỗi nên mình đóng lỗi này nếu bạn vẫn còn vấn đề hãy mở lại 1 báo cáo mới và cung cấp thông tin rõ ràng hơn
