### ISSUE TITLE
Shortcut chuyển input method không hoạt động trên Linux Mint 22

### ISSUE THREAD

**Issue by jdkcoder** [BambooEngine/ibus-bamboo#506]
Mình có chuyển shortcut cho next input method thành Ctrl + Shift & Alt + Z nhưng không cái nào toggle qua lại được giữa Vietnamese & English, khi code mình không sử dụng chuột nên muốn đổi ngôn ngữ về English lại phải dùng đến chuột. Mình cũng đã thử đưa lại về setting mặc định nhưng vẫn không có gì thay đổi

![image](https://github.com/user-attachments/assets/d997a837-c9c8-421b-a056-4ee934964e79)

![image](https://github.com/user-attachments/assets/b5f3460d-a0a5-4d71-a159-1dce7b275909)

![image](https://github.com/user-attachments/assets/3e702cd1-b6f2-4830-8d22-fb0cd52ad966)

![image](https://github.com/user-attachments/assets/b204f81b-af96-413e-ae73-4418d36f7146)

**Môi trường**
 - OS và version: Linux Mint 22 "Wilma"
 - Desktop: Cinnamon
 - Phiên bản ibus-bamboo: IBus 1.5.29-rc2

**Comment by luongthanhlam** [comment]
bạn thử làm theo hướng dẫn ở đây nhé https://superuser.com/questions/1291939/shortcut-to-change-keyboard-layout-in-linux-mint-cinnamon. Mọi DE dựa trên GNOME đều không thể sử dụng settings của ibus để thay đổi shortcut.
