### ISSUE TITLE
Chữ tự chạy trong quá trình set-up Kali Linux

### ISSUE THREAD

**Issue by tonynguyen310** [BambooEngine/ibus-bamboo#507]
**Mô tả lỗi**

**Các bước tái hiện lỗi**
Set-up Kali Linux

Tự động nhảy chữ mà không nhấn phím nào
Không thể gõ chữ
Chữ tự chạy, tự nhập

**Kết quả mong muốn**
Gõ chữ như bình thường

**Comment by goatastronaut0212** [comment]
Bạn có thể cung cấp hơn nhiều thông tin nữa có được không?

**Comment by goatastronaut0212** [comment]
Có vẻ nên đóng issue này vì không còn bất kỳ sự tương tác nào từ người báo cáo lỗi nữa cả.
