### ISSUE TITLE
Lỗi viết tiếng việt trên excel của docs trên web

### ISSUE THREAD

**Issue by tiamo405** [BambooEngine/ibus-bamboo#513]
**Mô tả lỗi**

khi đánh chữ trên https://docs.google.com/spreadsheets bị lỗi nhảy sang ô khác khi viết tiếng việt
**Các bước tái hiện lỗi**

Ví dụ:
1. Mở https://docs.google.com/spreadsheets
2. Gõ tét
3. bị nhảy sang ô khác

**Môi trường**
 - OS và version: Ubuntu 20.04
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.4)
 - kiểu gõ telex
 - Khác: chế độ gõ 4. forwardkeyEvent II

**Comment by tiamo405** [comment]
chuyển sang chế độ 3 thì đã bị hết lỗi, nhưng ad kiểm tra hộ e chế độ 4 xem có bị lỗi như mô tả k ạ

**Comment by goatastronaut0212** [comment]
> chuyển sang chế độ 3 thì đã bị hết lỗi, nhưng ad kiểm tra hộ e chế độ 4 xem có bị lỗi như mô tả k ạ

Vì các phần mềm có các xử lý nhập liệu khác nhau nên bạn mới có các chế độ gõ khác nhau và nó sẽ lưu cấu hình vào `ibus-bamboo.config.json` để bạn có thể sử dụng.

Không nó không phải lỗi đâu vì chế độ 4 của gõ đuợc mà.

**Comment by tiamo405** [comment]
> > chuyển sang chế độ 3 thì đã bị hết lỗi, nhưng ad kiểm tra hộ e chế độ 4 xem có bị lỗi như mô tả k ạ
> 
> Vì các phần mềm có các xử lý nhập liệu khác nhau nên bạn mới có các chế độ gõ khác nhau và nó sẽ lưu cấu hình vào `ibus-bamboo.config.json` để bạn có thể sử dụng nó, sau khi thoát khỏi chương ibus-bamboo sẽ tự chọn chế độ gõ đó.
> 
> Không nó không phải lỗi đâu vì chế độ 4 của bạn gõ được mà.

mình đang hiểu là ví dụ mình đang ở chế độ 4, sang docs thì lỗi nên thử chế độ 3 hết lỗi, sau đó hệ thống lưu lại config cứ khi nào vào docs là nó tự chuyển về 3 cho mình, còn thoát ra thì lại về chế độ 4. k biết mình hiểu vậy có đúng k ạ

**Comment by goatastronaut0212** [comment]
> mình đang hiểu là ví dụ mình đang ở chế độ 4, sang docs thì lỗi nên thử chế độ 3 hết lỗi, sau đó hệ thống lưu lại config cứ khi nào vào docs là nó tự chuyển về 3 cho mình, còn thoát ra thì lại về chế độ 4. k biết mình hiểu vậy có đúng k ạ

Không, nếu ibus-bamboo chỉ có thể chọn chế độ gõ ở mức chọn mặc định cho chương trình chứ không mức web browser mà bạn đề cập tới.

Nếu mình sử dụng alacritty chuyển từ 1 sang 3 thì nó sẽ lưu lại 3.

Còn nếu bạn muốn lưu config cho tab messenger là 1 hay 3 cho google docs thì không thể và chưa có tính năng nào làm như vậy hết căn bản dù bạn lưu cho messenger hay docs thì nó cũng sẽ dùng chung 1 cấu hình cho Web browser mà bạn đang sử dụng.

**Comment by goatastronaut0212** [comment]
Mình không nghĩ là đây là 1 báo cáo lỗi hợp lệ lắm. Tốt hơn là nên đóng nó lại.

**Comment by tiamo405** [comment]
> Mình không nghĩ là đây là 1 báo cáo lỗi hợp lệ lắm. Tốt hơn là nên đóng nó lại.

mình cám ơn. mình sẽ đóng lại
