### ISSUE TITLE
Không gõ được tiếng Việt trong popovers rename của GNOME Files trên Ubuntu 24.04 Wayland

### ISSUE THREAD

**Issue by chilinhnet** [BambooEngine/ibus-bamboo#514]
**Mô tả lỗi**
Không gõ được tiếng Việt trong popovers rename của GNOME files

**Các bước tái hiện lỗi**
Trên Ubuntu 24.04 (Wayland) mở Gnome Files sau đó rename (F2) tên file/folder thì sẽ không gõ được tiếng Việt
![Ubuntu 24 04 Wayland Gnome Files popovers rename](https://github.com/user-attachments/assets/efd57324-c224-4146-acfa-112ee4136e49)

**Môi trường**
 - OS và version: Ubuntu 24.04
 - Desktop: Gnome 46 
 - Display server protocol: Wayland
 - Phiên bản ibus-bamboo: 0.8.4

**Comment by goatastronaut0212** [comment]
Trùng với báo cáo https://github.com/BambooEngine/ibus-bamboo/issues/44
