### ISSUE TITLE
Tình trạng dự án và tương lai?

### ISSUE THREAD

**Issue by goatastronaut0212** [BambooEngine/ibus-bamboo#515]
Gần đây thì mình không còn thấy anh Lâm lên đây thường xuyên nữa, thường thì anh ấy sẽ lên cách nhau khoảng 2-10 ngày gì đó để giúp đỡ các bạn báo cáo lỗi (issues) và đang lên trên mục thảo luận (discussions) cũng như là duyệt và review Pull Requests. Nhưng kể từ sau khi review khoảng hơn 1 tháng với Pull Request https://github.com/BambooEngine/ibus-bamboo/pull/504 thì mình không còn thấy anh ấy nữa. Không biết là có ai có tin tức gì về anh ấy không?

Mặc dù mình còn khá mới với dự án nhưng trong trường hợp anh ấy không còn hứng thú với dự án nữa hay bận nhiều ưu tiên khác trong cuộc sống thì mình vẫn muốn tiếp nhận với vai trò là member phụ của dự án để tiếp tục duy trì cũng như thêm các tính năng mới và cải thiện gõ ibus-bamoo trên Wayland trong tương lai gần.

Thực sự mình không muốn ibus-bamboo sẽ lại kết thúc và bỏ ngõ như các dự án bộ gõ tiếng việt khác ibus-unikey, ibus-teni hay ibus-bogo.

**Comment by luongthanhlam** [comment]
thời gian này mình hơi bận 1 số việc nên không online thường xuyên được. Nếu bạn có khả năng và sẵn lòng đóng góp vào dự án, mình rất vui lòng được thêm bạn vào members và cấp quyền truy cập dự án 😀

**Comment by luongthanhlam** [comment]
@goatastronaut0212 mình vừa gửi thư mời tham gia với vai trò là maintainer của dự án, bạn check mail nhé

**Comment by goatastronaut0212** [comment]
Mình sẽ cố hết sức để duy trì dự án
