### ISSUE TITLE
Không gõ được tiếng Việt trong slack và skype

### ISSUE THREAD

**Issue by tackelua** [BambooEngine/ibus-bamboo#52]
Không gõ được tiếng Việt trong slack và skype

**Môi trường**
 - OS và version: Ubuntu 18.04.2 LTS
 - Phiên bản ibus: IBus 1.5.17
 - Phiên bản ibus-bamboo: mới cài xong ngày 4/7

**Comment by luongthanhlam** [comment]
bạn có cài slack từ skype từ snap không vậy? Nếu có, phiền bạn cài lại từ trang chủ của ứng dụng và thử lại nhé.

**Comment by tackelua** [comment]
@luongthanhlam thanks b nhiều ạ, e làm theo được rồi ^^

**Comment by thaok61** [comment]
bài viết rât hữu ích

**Comment by levanmanh** [comment]
> bạn có cài slack từ skype từ snap không vậy? Nếu có, phiền bạn cài lại từ trang chủ của ứng dụng và thử lại nhé.

tuyệt vời :v:

**Comment by hoangphucITJP** [comment]
> bạn có cài slack từ skype từ snap không vậy? Nếu có, phiền bạn cài lại từ trang chủ của ứng dụng và thử lại nhé.

Có khác biệt gì giữa 2 phiên bản vậy bạn @luongthanhlam  ?

**Comment by luongthanhlam** [comment]
@hoangphucITJP bạn xem ở đây nhé https://github.com/BambooEngine/ibus-bamboo/wiki/T%E1%BA%A1i-sao-kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-Vi%E1%BB%87t-trong-%E1%BB%A9ng-d%E1%BB%A5ng-snap%3F
