### ISSUE TITLE
Trên Ubuntu lỗi gõ Tiếng Việt trong WPS Office phiên bản mới

### ISSUE THREAD

**Issue by justinkingst** [BambooEngine/ibus-bamboo#520]
**Mô tả lỗi**
Gõ Tiếng Việt trong WPS Office mới trên Ubuntu bị lỗi gấp đôi chũ, nhảy ra thêm chữ vừa gõ.

**Comment by goatastronaut0212** [comment]
Ít nhất lần sau bạn cũng hãy viết báo cáo lỗi theo template báo lỗi đầy đủ để có thêm thông tin hữu ích. Còn việc trùng lặp chữ, bạn vui lòng hãy thử chuyển chế độ gõ với `Shift` + `~`. Nếu không được bạn hãy setup theo hướng dẫn ở [đây](https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60)

**Comment by goatastronaut0212** [comment]
Mình sẽ đóng post này lại vậy.
