### ISSUE TITLE
Bị mất chữ có dấu đầu tiên trên telegram web

### ISSUE THREAD

**Issue by clmm865061300** [BambooEngine/ibus-bamboo#523]
không gõ được chữ có dấu đầu tiên trên telegram web.

còn lại test mọi thứ vẫn bình thường.

**Comment by goatastronaut0212** [comment]
@clmm865061300 bạn đã thử chuyển chế độ gõ chưa bằng `Shift` + `~`? Chế độ gõ không phải là kiểu gõ nó sẽ giúp bạn chọn chế độ gõ tương thích cho ứng dụng.

**Comment by clmm865061300** [comment]
![image](https://github.com/user-attachments/assets/145bc8e9-0fea-4cfc-b295-5ede32259c7e)![608a03f854b9f2e7aba8](https://github.com/user-attachments/assets/dface654-e338-4822-bbd3-49f46fc53ad2)

Chữ cái đầu tiên nếu gõ có dấu nó sẽ bị mất. Ví dụ : Đ ( chữ có dấu Đ - Á - Ư - Ó - Ẹ )
đã thử unikey và evkey cái nào cũng bị.  nhưng tất cả ứng dụng khác thì lại sử dụng bình thường.

**Comment by goatastronaut0212** [comment]
> ![image](https://github.com/user-attachments/assets/145bc8e9-0fea-4cfc-b295-5ede32259c7e)![608a03f854b9f2e7aba8](https://github.com/user-attachments/assets/dface654-e338-4822-bbd3-49f46fc53ad2)
> 
> Chữ cái đầu tiên nếu gõ có dấu nó sẽ bị mất. Ví dụ : Đ ( chữ có dấu Đ - Á - Ư - Ó - Ẹ )
> đã thử unikey và evkey cái nào cũng bị.  nhưng tất cả ứng dụng khác thì lại sử dụng bình thường.



Bạn đã thử chuyển chế độ gõ với shift + ~ chưa? Hãy dùng nó vì các ứng dụng tương tác khác nhau.

Bạn đang không trả lời câu hỏi chính trước đó của mình

**Comment by goatastronaut0212** [comment]
Mình cảm thấy nên đóng lỗi này lại mình nhận thấy không thực sự đáng để nó tiếp tục mở thêm
