### ISSUE TITLE
lỗi lúc bắt đầu cài đặt

### ISSUE THREAD

**Issue by steventran2023** [BambooEngine/ibus-bamboo#524]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở terminal
2. Gõ 
3. bash -c "$(curl -fsSL https://raw.githubusercontent.com/BambooEngine/ibus-bamboo/master/archlinux/install.sh)"
4. Thấy 
5. curl: (22) The requested URL returned error: 404

**Môi trường**
 - OS và version: endeavourOS
 - Desktop: Xfce
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.4)

**Thông tin thêm**

**Comment by tranhongs0n** [comment]
có vẻ mã nguồn đã có chút thay đổi.
hãy thử với câu lệnh dưới đây:
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/BambooEngine/ibus-bamboo/master/build/arch/install.sh)"`

**Comment by steventran2023** [comment]
Chọn phiên bản muốn cài:
1. Bản release, cài đặt từ AUR (yay)
2. Bản release, cài đặt từ chaotic-aur (pacman, nếu bạn dùng repo chaotic-aur)
3. Bản release, cài đặt từ AUR (pamac)
4. Bản release, cài đặt từ Open Build Service (pacman)
5. Bản release, cài đặt từ mã nguồn
6. Bản git, cài đặt từ mã nguồn mới nhất lấy từ github
7. Thoát
sau khi chọn số 4. Bản release, cài đặt từ Open Build Service (pacman) 
thì bị tiếp lỗi này:
error: ibus-bamboo: signature from "home:lamlng OBS Project <home:lamlng@build.opensuse.org>" is invalid
:: File /var/cache/pacman/pkg/ibus-bamboo-0.8.4-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

**Comment by goatastronaut0212** [comment]
Có lẽ chuyện gì đó đã xảy ra với OBS của ad Lâm bạn đã thử các option còn lại chưa? @steventran2023

**Comment by steventran2023** [comment]
được mỗi option 1 (lâu rồi không được cập nhật) còn lại đều có lỗi [goatastronaut0212](https://github.com/goatastronaut0212)

**Comment by goatastronaut0212** [comment]
@steventran2023  Mình thực sự không muốn ad Lâm hay bản thân mình khi không còn hứng thú vẫn phải tiếp tục duy trì Arch PKGBUILD và cả OBS lắm. Dạo gần đây mình không còn thấy anh ấy hoạt động nhiều. Mình không biết bạn sẽ cảm thấy thế nào vì nếu không có những giải pháp trên nhưng mình vẫn muốn đưa nó lên các official repo của các distro lớn hơn thay vì để mọi thứ bên third party repo như thế này và mình rất tiếc về việc toàn bộ code đó không còn hoạt động nữa.

Mình có thể sửa được chứ? Có tất nhiên nếu bạn cần mình sẽ sửa nhưng chỉ là mình nghĩ  sẽ tốt hơn nếu chúng ta để cho toàn bộ code build đó chết sớm hơn và chuyển sang tương tác nhiều hơn với các maintainers cũng như developers bên các distro lớn. Nếu bạn muốn đóng góp gì đó có thể thảo luận thêm ở đây https://github.com/BambooEngine/ibus-bamboo/issues/516

**Comment by goatastronaut0212** [comment]
Mình nghĩ nên bắt đầu sớm việc package ibus-bamboo lên các distro lớn thì mới có thể loại bỏ được OBS trong tương lai gần.

**Comment by streetsamurai00mi** [comment]
> option 1 (lâu rồi không được cập nhật)

Vì đây là bản cập nhật theo releases nên chỉ mới tới [v0.8.4-RC1](https://github.com/BambooEngine/ibus-bamboo/releases/tag/v0.8.4-RC1) thôi.


> Bản release, cài đặt từ chaotic-aur (pacman, nếu bạn dùng repo chaotic-aur)

chaotic-aur đã drop `ibus-bamboo` và chỉ còn `ibus-bamboo-git`


@steventran2023 Bạn có thể tự cài `ibus-bamboo-git` từ [trên aur](https://aur.archlinux.org/packages/ibus-bamboo-git) hoặc bằng một `aur helper` như [aura](https://github.com/fosskers/aura), [paru](https://github.com/Morganamilo/paru), yay
