### ISSUE TITLE
Tại sao không test bamboo-core trên repo chính?

### ISSUE THREAD

**Issue by goatastronaut0212** [BambooEngine/ibus-bamboo#525]
@luongthanhlam Mình không hiểu tại sao chúng ta phải lấy test từ bamboo-core rồi bỏ vào trong thư mục `/vendor` của ibus-bamboo. Nó căn bản vẫn hoạt động nhưng mỗi lần phải sử dụng `go mod tidy` và `go mod vendor`, như thường lệ chúng sẽ xóa toàn bộ file test trong thư mục `vendor`. Vẫn như tiêu đề chúng ta không thể chạy test trên chính repo của bamboo-core vì lý do nào? Mình không có quyền truy cập vào bamboo-core để làm điều đó cho lắm.

**Comment by luongthanhlam** [comment]
Ngày trước chưa có go module nên test vẫn chạy được ở vendor. Giờ muốn chạy test trên repo bamboo-core thì thêm ci như bình thường thôi.

**Comment by luongthanhlam** [comment]
Đã add vào repo, bạn check mail nhé
