### ISSUE TITLE
Không gõ được tiếng Việt trong Telegram 

### ISSUE THREAD

**Issue by ImKifu** [BambooEngine/ibus-bamboo#53]
**Mô tả lỗi**
Không gõ được tiếng Việt trong Telegram 

**Môi trường**
 - OS và version:  19.04
 - Desktop: Gnome mặc định
 - Phiên bản ibus: IBus 1.5.19

Em cảm ơn các anh ạ

**Comment by luongthanhlam** [comment]
bạn cài telegram từ snap hay từ apt vậy?

**Comment by ImKifu** [comment]
@luongthanhlam em không nhớ ạ. có cách nào để kiểm tra không ạ ?

**Comment by npthinhdev** [comment]
@ImKifu bạn chạy `snap list` xem có gói của telegram không?

**Comment by ImKifu** [comment]
@luongthanhlam thưa anh đây ạ.
```
Name                  Version                     Rev   Tracking  Publisher         Notes
core                  16-2.39.3                   7270  stable    canonical✓        core
core18                20190704                    1055  stable    canonical✓        base
gnome-3-28-1804       3.28.0-10-gaa70833.aa70833  67    stable/…  canonical✓        -
gnome-calculator      3.32.1                      406   stable/…  canonical✓        -
gnome-characters      v3.32.1+git2.3367201        296   stable/…  canonical✓        -
gnome-logs            3.32.0-4-ge8f3f37ca8        61    stable/…  canonical✓        -
gnome-system-monitor  3.32.1-3-g0ea89b4922        100   stable/…  canonical✓        -
gtk-common-themes     0.1-22-gab0a26b             1313  stable/…  canonical✓        -
htop                  2.2.0                       1168  stable    maxiberta         -
telegram-desktop      1.7.13                      836   stable    telegram.desktop  -
```
vậy là em có tải từ Snap ạ. Vậy bây giờ em phải làm gì tiếp ạ?

**Comment by ImKifu** [comment]
@npthinhdev anh giúp em với ạ

**Comment by luongthanhlam** [comment]
bạn gỡ ra rồi cài lại bằng apt thôi
`sudo snap remove telegram-desktop`
`sudo apt-get install telegram-desktop`

**Comment by ImKifu** [comment]
> @ImKifu bạn chạy `snap list` xem có gói của telegram không?

@npthinhdev dạ đây ạ
```
Name                  Version                     Rev   Tracking  Publisher         Notes
core                  16-2.39.3                   7270  stable    canonical✓        core
core18                20190704                    1055  stable    canonical✓        base
gnome-3-28-1804       3.28.0-10-gaa70833.aa70833  67    stable/…  canonical✓        -
gnome-calculator      3.32.1                      406   stable/…  canonical✓        -
gnome-characters      v3.32.1+git2.3367201        296   stable/…  canonical✓        -
gnome-logs            3.32.0-4-ge8f3f37ca8        61    stable/…  canonical✓        -
gnome-system-monitor  3.32.1-3-g0ea89b4922        100   stable/…  canonical✓        -
gtk-common-themes     0.1-22-gab0a26b             1313  stable/…  canonical✓        -
htop                  2.2.0                       1168  stable    maxiberta         -
telegram-desktop      1.7.13                      836   stable    telegram.desktop  -
```
anh giúp em những bước tiếp theo với ạ

**Comment by ImKifu** [comment]
@luongthanhlam em đã gỡ bản snap, và cài bản từ apt. Em đã gõ được tiếng Việt. Nhưng mà vào menu ứng dụng, em ko tìm thấy Telegram ạ. Tức là em không tìm thấy nó. Nhưng em gõ lệnh 
```
telegram-desktop
``` 
thì nó vẫn hiện lên và hoạt động bình thường ạ

**Comment by ImKifu** [comment]
em add tạm nó vào cái thanh công cụ bên trái của Ubuntu, hay còn gọi là Favorites rồi ạ. Thì em không bị mất công tìm nó hay phải gõ lệnh `telegram-desktop` mỗi khi muốn sử dụng nó. Nhưng có cách nào để hiện nó lên không ạ ?

**Comment by ndgnuh** [comment]
Cái này bạn phải tham khảo hướng dẫn của gnome hoặc unity, hoặc hỏi bạn nào dùng môi trường này thôi.

**Comment by thanhbinh1999** [comment]
cross domaincross

**Comment by thangdc94** [comment]
> bạn gỡ ra rồi cài lại bằng apt thôi
> `sudo snap remove telegram-desktop`
> `sudo apt-get install telegram-desktop`

Đã thử và ko thành công ạ :((
Mình dùng Ubuntu 16.04 và bây giờ telegram chỉ có trên snap thôi nên không cài kiểu `apt-get` được.

**Comment by thangdc94** [comment]
> @thangdc94 bạn thử cài telegram trên trang chủ xem https://desktop.telegram.org/

Download trên trang chủ thì gõ được rồi. Cảm ơn bạn.
