### ISSUE TITLE
Mất menu chế độ gõ

### ISSUE THREAD

**Issue by PhanDungTri** [BambooEngine/ibus-bamboo#530]
**Mô tả lỗi**

Hiện tại mình ko còn thấy menu để chuyển đổi chế độ gõ nữa, cũng không thể dùng `Shift + ~` để chuyển đổi.

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://github.com/user-attachments/assets/304f6f85-b47c-4999-97dc-f70d2a96ca56

**Môi trường**
 - OS và version: Fedora 40
 - Desktop: Gnome 46

**Comment by goatastronaut0212** [comment]
@PhanDungTri bạn hãy thử xem thêm ở phần Phím tắt -> Khác.

Mình sẽ đóng báo cáo lỗi này lại vì nó ngoài lề rồi nếu có lỗi cụ thể phiền bạn hãy mở 1 báo cáo mới.
