### ISSUE TITLE
Khong go duoc tieng viet tren CHrome

### ISSUE THREAD

**Issue by shibuina** [BambooEngine/ibus-bamboo#532]
Em dang dung ubuntu 22.04, va tai ibusbamboo nhung khong dung duoc tren chrome.

**Comment by goatastronaut0212** [comment]
@shibuina Ít nhất bạn hãy cung cấp thông tin thêm việc bạn kiệm lời quá, nó cũng khiến cho mình không biết phải làm gì để giúp bạn.

**Comment by shibuina** [comment]
> @shibuina Ít nhất bạn hãy cung cấp thông tin thêm việc bạn kiệm lời quá, nó cũng khiến cho mình không biết phải làm gì để giúp bạn. Mình có thể gõ trên chrome. Yes, bất ngờ chưa không có lỗi gì ở đây cả
> 
> Bạn đã thử làm theo hướng dẫn ở đây chưa? https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

Mình đã làm hết tất cả các bước nhưng vẫn không chạy được, vậy vấn đề ở đây là gì?

**Comment by goatastronaut0212** [comment]
@shibuina bạn có đang sử dụng Wayland không? Nếu có thì tin buồn là Ibus không hỗ trợ thuần hoặc hỗ trợ Wayland kém và lỗi này đã được báo cáo rồi. Cách duy nhất để hỗ trợ Wayland tốt hơn là hãy gửi 1 PR lại cho Wayland protocol để mọi thứ trở nên tồi tệ ít hơn.

**Comment by shibuina** [comment]
> @shibuina bạn có đang sử dụng Wayland không? Nếu có thì tin buồn là Ibus không hỗ trợ thuần hoặc hỗ trợ Wayland kém và lỗi này đã được báo cáo rồi. Cách duy nhất để hỗ trợ Wayland tốt hơn là hãy gửi 1 PR đóng góp lại cho Wayland protocol hoặc Ibus để mọi thứ trở nên tồi tệ ít hơn. Giải pháp gõ tốt hơn chỉ đơn giản là dùng X11 thôi.

Mình không biết có các nào để check không bạn? Mình đang dùng Ubuntu 22.04

**Comment by goatastronaut0212** [comment]
@shibuina Bạn có thể kiểm tra với việc check trên System Info hệ thống của bạn hoặc trước khi login vào thì có hình bánh răng cho phép bạn chọn DE/WM trước khi vào bạn có thể xem thêm ở đó. Nếu không có Xorg thì nó là Wayland.
