### ISSUE TITLE
Không thể gõ tiếng Việt trên chrome

### ISSUE THREAD

**Issue by sangqle** [BambooEngine/ibus-bamboo#533]
**Mô tả lỗi**

**Các bước tái hiện lỗi**

Ví dụ:
1. Mở Chrome
2. Gõ: Tooi khoong theer gox tieengs vieejt treen chrome, duf cos baatj chees dodoj aanr danh.
4. Thấy: Tooi khoong theer gox tieengs vieejt treen chrome, duf cos baatj chees dodoj aanr danh.

**Kết quả mong muốn**

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Ubuntu 22.04.5 LTS
 - Desktop: Mặc định
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.4)

**Thông tin thêm**

Chỉ mỗi gõ tiếng Việt chrome là không được.

**Comment by goatastronaut0212** [comment]
@sangqle Bạn có đang sử dụng Wayland không? Bạn có setup như hướng dẫn trên Wiki này không?

Đừng xài Wayland ở thời điểm hiện tại vì Ibus (phần mềm upstream của Ibus-bamboo) chưa hỗ trợ thuần Wayland hoàn toàn. Nếu bạn vẫn muốn sử dụng Wayland thì chúc bạn may mắn mình không thể giúp bạn được nhiều, bạn có thể tham khảo thêm ở discussion này các WM/DE hỗ trợ Wayland input protocol v1.

https://github.com/BambooEngine/ibus-bamboo/discussions/521

**Comment by goatastronaut0212** [comment]
Mình cảm thấy khá là kỳ lạ khi lại không gõ được trên Google Chrome. Mình không hiểu sao các bạn luôn đề cập lỗi này nhưng khi mình kiểm tra trên cả trên Wayland và Xorg thì không có lỗi nào như vậy cả. Mình cảm thấy đây không phải là lỗi hợp lệ cho lắm.

Nhưng để chắc chắn hơn bạn có test Chrome trên cả Wayland và Xorg chưa. Bạn có xài Chrome thông qua flatpak hay xài trên snap không ?

**Comment by goatastronaut0212** [comment]
Có lẽ là không. Mình sẽ đóng báo cáo lỗi này lại.

**Comment by sangqle** [comment]
Không, mình không dùng Wayland, desktop mình dùng ubuntu mặt định, và ubuntu on xorg đều không gõ được tiếng Việt.

**Comment by goatastronaut0212** [comment]
Bạn đã setup biến chưa theo hướng dẫn Wiki [này](https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60) chưa?
