### ISSUE TITLE
Lỗi lặp chữ

### ISSUE THREAD

**Issue by QuachNamLuong** [BambooEngine/ibus-bamboo#535]
**Mô tả lỗi**
bị lỗi lặp tự copy chữ đã nhập sau khi nhấp chuột trong Ubuntu 24.04

**Các bước tái hiện lỗi**
Gõ một từ sau khi nhấp chuột thì từ đó bị lặp lại

[Screencast from 2024-09-26 09-39-58.webm](https://github.com/user-attachments/assets/a6d9a7ad-b3c6-45b2-b34a-3e1b9d8220dc)

**Comment by goatastronaut0212** [comment]
Bạn hãy thử chuyển chế độ gõ với `Shift` + `~` các ứng dụng sẽ có cách hoạt động khác nhau nên chế độ gõ có thể tránh việc gõ lặp chữ. Và nếu bạn không dùng `Shift` + `~` được, phiền bạn đọc cách setup thêm tại [đây](https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60)

Trên NixOS thì mọi thứ hoạt động quá tốt nên mình không cần phải setup biến này, mình thì rõ Ubuntu thế nào.

Lần sau bạn hãy tìm các báo cáo lỗi đã đóng trên repo này trước khi mở 1 báo lỗi mới.
