### ISSUE TITLE
Bị kẹt chữ U khi gõ.

### ISSUE THREAD

**Issue by zeromark223** [BambooEngine/ibus-bamboo#536]
**Mô tả lỗi**

Cứ chọn Bamboo xong gõ có chữ U sẽ gạch chân và tự gọi unicode sau khi nhấn space (ví dụ gõ Mua sẽ thành M10)

**Các bước tái hiện lỗi**

1. Install theo huớng dẫn.
2. Chuyển sang bộ gõ Bambo.
3. Dùng bộ gõ bất kỳ (VNI, Telex)
4. Mở Telegram, Text Editor, Firefox, ...

**Kết quả mong muốn**

- Dùng bình thuờng
**Ảnh chụp màn hình, hoặc clip quay màn hình**
![Screenshot from 2024-09-27 00-11-22](https://github.com/user-attachments/assets/ce6ad572-703d-44c1-9eee-56946c0cf033)

**Môi trường**

 - OS và version: Linux Mint 22 x86_64 
 - Desktop: Cinnamon 6.2.9 
 - Protocol: X11
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.4)
- Ibus Version : 1.5.29-rc2
- 
**Thông tin thêm**

Đã thử tất cả 5 chế độ gõ đều bị
Các phần mềm đã thử : Telegram, Firefox, Text-editor, Terminal

**Comment by goatastronaut0212** [comment]
@zeromark223 Ý bạn là cái Unicode không hề hoạt động?

**Comment by goatastronaut0212** [comment]
Khá là kỳ lạ mình không thể nào tái hiện lại lỗi được. Mình viết mọi thứ vẫn bình thường. Bạn có chỉnh bảng mã gì không? Với bảng Unicode thì mọi thứ chỉ hoạt động tốt với mình

**Comment by zeromark223** [comment]
Để mình quay clip từ lúc install tới khi sử dụng cho bạn dễ hiểu, mình không biết phải do OS ko nữa.Cứ bật qua bamboo bấm chữ U là nó underline xong gõ tiếp tới khi bấm space là nó thành số.
https://github.com/user-attachments/assets/9263685d-eb14-4421-8151-ce195fbb79b0

**Comment by goatastronaut0212** [comment]
Nó không nên xảy ra chuyện này. Bạn đã thử các chế độ gõ khác như `Shift` + `~` chưa? @zeromark223

**Comment by zeromark223** [comment]
@goatastronaut0212 Thank bros. Mình có thử lại trên 1 laptop khác cùng version OS (fresh install) thì không bị, để mình thử gỡ các app đang có xem nó bị xung đột với cái nào.

**Comment by goatastronaut0212** [comment]
> @goatastronaut0212 Thank bros. Mình có thử lại trên 1 laptop khác cùng version OS (fresh install) thì không bị, để mình thử gỡ các app đang có xem nó bị xung đột với cái nào.

Bạn có thể thử xóa `~/.config/ibus-bamboo` đi để xem nó có giải quyết được vấn đề đó không?
