### ISSUE TITLE
Không gõ được trong phần mềm Zed 

### ISSUE THREAD

**Issue by kien5436** [BambooEngine/ibus-bamboo#537]
**Mô tả lỗi**

Không gõ được chữ trong [Zed](https://zed.dev/). Chế độ Pre-edit là ít lỗi nhất; các chế độ khác bị lặp chữ, mất chữ

**Các bước tái hiện lỗi**

1. Mở Zed
2. Gõ chữ tiếng Việt bất kì. Ví dụ: "xin chào thế giới"
3. Màn hình hiện: "xin chaoào theêế gioiớ"

**Kết quả mong muốn**

Viết bình thường như trên các phần mềm khác.

**Ảnh chụp màn hình, hoặc clip quay màn hình**

https://github.com/user-attachments/assets/5f0ae541-77fc-45bf-9bc1-3bc4b36464d1

**Môi trường**
 - OS và version: Pop!OS 22.04
 - Desktop: Gnome
 - Protocol: Xorg/X11
 - Phiên bản ibus-bamboo: 0.8.4

**Thông tin thêm**

**Comment by goatastronaut0212** [comment]
Mình có thể confirm lỗi này nhưng mình vẫn chưa rõ nguyên nhân gây ra của nó là gì. Sẽ cần thêm nhiều thông tin nữa nếu chúng ta có thể biết là lỗi của ibus-bamboo hay nó là của Zed hoặc Ibus khi chúng tương tác nhau không?

**Comment by goatastronaut0212** [comment]
Trên Wayland thì mọi thứ hoạt động khá ổn áp. Ít nhất với mình thì không xảy ra hiện tượng phải nhập space 2 lần thì mới cách được như trên Xorg.

**Comment by kien5436** [comment]
để mình đổi qua wayland xem sao

**Comment by kien5436** [comment]
> Trên Wayland thì mọi thứ hoạt động khá ổn áp. Ít nhất với mình thì không xảy ra hiện tượng phải nhập space 2 lần thì mới cách được như trên Xorg. Có vẻ Wayland đã thuyết phục được mình, mình đã thay đổi quan điểm về nó sau khi sử dụng GNOME Wayland.

xác nhận cách này hoạt động ổn, cảm ơn bạn nhé

**Comment by goatastronaut0212** [comment]
@kien5436 Xorg theo mình biết là cũng không còn nhiều phát triển và không cập nhập cũng lâu rồi. Mình nghĩ nên hướng tới sử dụng Wayland vì căn bản GNOME Wayland không hề tệ. Còn về bug trên Xorg thì nghĩ mình không đủ can đảm để tìm hiểu và giải quyết vấn đề và mình cũng có ưu tiên khác nữa.
