### ISSUE TITLE
lỗi bôi đen từ trong kitty terminal

### ISSUE THREAD

**Issue by taitai2107** [BambooEngine/ibus-bamboo#538]
khi mình thêm GLFW_IM_MODULE vào /etc/enviroment thì kitty terminal nó đã gõ được tiếng việt nhưng khi gõ nó toàn bị bôi đen chữ phải tab hay di chuột hoặc . , ' vv... nó mới hết bôi đen chữ ý khiến gõ code nó không hiện gợi ý

**Comment by goatastronaut0212** [comment]
@taitai2107 bạn đã thử chuyển chế độ gõ chưa với `Shift` + `~`? Nghe có vẻ không phải là lỗi hợp lệ với mình lắm và nó cũng đã nằm trong mục câu hỏi thường gặp.

**Comment by goatastronaut0212** [comment]
Yeah, mình cảm thấy không nên để nó mở. Nhưng nếu bạn vẫn cần giúp đỡ thì có thể tiếp tục comment mình sẽ giúp bạn.
