### ISSUE TITLE
IBus Bamboo 0.5.1 không tự khởi chạy sau mỗi lần restart/login phải chọn qua english sau đó chọn lại ibus bamboo mới chạy

### ISSUE THREAD

**Issue by Thinh1999** [BambooEngine/ibus-bamboo#54]
Xubuntu 18.04 Ở các bản ibus bamboo trước thì khi chọn ibus bamboo là cứ mỗi lần khởi động/login là ibus tự hiển thị icon ibus bamboo nhưng sau khi cài bản 0.5.1 cứ khởi động lại nó không nhận ra ibus bamboo ở lần trước và chọn ngay ibus bamboo cũng không đc phải chọn english xong chọn lại ibus bamboo thì mới hiện lên icon ibus bamboo và sử dụng đc

**Comment by luongthanhlam** [comment]
bạn bật ibus-bamboo rồi chạy lệnh này và gửi output giúp mình nhé `ibus-daemon -vxr`

**Comment by luongthanhlam** [comment]
@Thinh1999 ping
