### ISSUE TITLE
Khong hoat dong tren Firefox

### ISSUE THREAD

**Issue by babynghe2003** [BambooEngine/ibus-bamboo#542]
**Mô tả lỗi**
Khong hoat dong tren Arch KDE Plasma 6

**Các bước tái hiện lỗi**

Cai ibus-bamboo qua AUR

```bash
yay -S ibus-bamboo
```

them vao bashrc

```bash
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus
ibus-daemon -drx
```

Va reboot
Sau do mo ibus-setup, them vietnamese vao input method

Lai reboot

**Ket qua thuc te**
Khong chuyen input method bang "Meta + space" duoc, chuyen bang chuot tren system tray cung khong dung duoc tieng viet

**Kết quả mong muốn**
Co the chuyen source bang meta + space, go tieng viet duoc

**Ảnh chụp màn hình, hoặc clip quay màn hình**

![image](https://github.com/user-attachments/assets/d26a31c5-e7b1-4602-beb7-aeb8479e1459)
Da co tren systemtray, nhung khong go tieng viet duoc

**Môi trường**
 - OS và version: Arch Linux
 - Desktop: KDE Plasma 6
 - Protocol: Wayland 
 - Phiên bản ibus-bamboo: (bản mới nhất là 0.8.4)

**Comment by goatastronaut0212** [comment]
@babynghe2003 

KDE plasma có cảnh báo như thế này không?

>    Please unset QT_IM_MODULE and GTK_IM_MODULE environment variables and ‘ibus-daemon --panel disable’ should be executed as a child process of ibus-ui-gtk3 component.

Nếu có thì bạn chỉ việc bỏ QT_IM_MODULE và GTK_MODULE đi thôi. Lần cuối mình thử với KDE Wayland khi bỏ 2 cái này đi thì có vẻ nó hoạt động tốt với mình.
