### ISSUE TITLE
Không gõ được tiếng Việt trong Viber

### ISSUE THREAD

**Issue by pouracc** [BambooEngine/ibus-bamboo#55]
**Mô tả lỗi**
Không gõ được tiếng Việt trong Viber

**Các bước tái hiện lỗi**
Gõ tiếng Việt trong Viber

**Kết quả mong muốn**
Gõ được tiếng Việt

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: Ubuntu 18.04 LTS
 - Desktop: Mặc định
 - Phiên bản ibus: IBus 1.5.17
 - Phiên bản ibus-bamboo: v0.5.1

**Thông tin thêm**

Thanks team for support

**Comment by luongthanhlam** [comment]
bạn cài viber từ snap hay từ đâu vậy?

**Comment by pouracc** [comment]
Mình download file .deb từ trang chủ của Viber.

**Comment by pouracc** [comment]
Mình thử cả bằng bản viber-mtd cài bằng snap cũng lỗi tương tự nhé.

**Comment by luongthanhlam** [comment]
Bạn đã thử nhấn shift+~ và thử chế độ gõ khác chưa? Nếu có ảnh chụp hay
video thì càng tốt.

**Comment by pouracc** [comment]
Nhấn Shift + ~ thì chỉ ra ~ thôi nhé. Mình có thay đổi chế độ gõ rồi nhưng vẫn lỗi.

**Comment by luongthanhlam** [comment]
Bạn đang dùng chế độ gõ nào? Bạn đã mở cài đặt và tắt tùy chọn "Tắt tổ hợp
phím shift+~" chưa?

**Comment by pouracc** [comment]
Mình đã thử cả Telex và VNI đều không được. Tuỳ chọn Tắt tổ hợp phím shift+~" cả bật tắt đều không được.

**Comment by luongthanhlam** [comment]
ý mình là chế độ gõ khi bạn nhấn Shift+~ như hình này ![demo](https://user-images.githubusercontent.com/48562187/55742506-10fbba80-5a5a-11e9-9945-9d54865c8ecf.png)

**Comment by pouracc** [comment]
Trong viber nhấn shift + ~  không được nên mình đã test như sau nhé:
- Mở gedit, dùng tổ hợp shift + ~ để chuyển chế độ
- Quay lại viber gõ tiếng Việt
Các chế độ đều không gõ được tiếng Việt

**Comment by luongthanhlam** [comment]
đây là bản viber mình tải trên trang chủ, vẫn gõ bình thường mà bạn
![Screenshot from 2019-07-25 07-17-30](https://user-images.githubusercontent.com/26364140/61837037-28e23780-aead-11e9-9012-7e5a3499b0ec.png)

**Comment by pouracc** [comment]
Bạn có dùng môi trường giống của mình ko?

**Comment by luongthanhlam** [comment]
bạn gửi mình output 3 lệnh này nhé

`env | grep "IM_MODULE\|XMODIFIERS" `
`dpkg --list|grep viber `
`cat ~/.config/ibus-bamboo/ibus-bamboo.config.json`

**Comment by pouracc** [comment]
Mình gửi output bạn cần xem:

`pouracc@linux:~$ env | grep "IM_MODULE\|XMODIFIERS" 
CLUTTER_IM_MODULE=xim
QT4_IM_MODULE=xim
QT_IM_MODULE=xim
XMODIFIERS=@im=ibus
GTK_IM_MODULE=ibus
`
`pouracc@linux:~$ dpkg --list | grep viber 
ii  viber                                      10.3.0.37                                    amd64        Free Text & Calls.
`
`pouracc@linux:~$ cat ~/.config/ibus-bamboo/ibus-bamboo.config.json
{
  "InputMethod": "Telex",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex 3": {
      "[": "__ươ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_ƯƠ"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode",
  "Flags": 7,
  "IBflags": 23024,
  "AutoCommitAfter": 3000,
  "ExceptedList": [
    "gnome-terminal-server:Gnome-terminal"
  ],
  "PreeditWhiteList": [
    "google-chrome:Google-chrome",
    "skype:Skype"
  ],
  "X11ClipboardWhiteList": null,
  "ForwardKeyWhiteList": null,
  "DirectForwardKeyWhiteList": [
    "gedit:Gedit"
  ],
  "SurroundingTextWhiteList": null
}`

**Comment by luongthanhlam** [comment]
lỗi này là do cấu hình sai biến môi trường, bạn làm theo hướng dẫn trên [wiki](https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60) để cấu hình lại nhé.

**Comment by pouracc** [comment]
Thanks bạn, đã cấu hình lại và gõ được tiếng Việt.
