### ISSUE TITLE
Không gõ được Tiếng Việt trên Kubuntu

### ISSUE THREAD

**Issue by ImKifu** [BambooEngine/ibus-bamboo#58]
**Mô tả lỗi**
Không gõ được tiếng Việt trên Kubuntu 19.04

**Các bước tái hiện lỗi**

1. Cài đặt từ mã nguồn
2. Restart Ibus
3. Add thêm kiểu gõ 

**Kết quả mong muốn**

Gõ được tiếng Việt. Trước em có dùng trên Ubuntu 19.04 thì nó chỉ cần đổi kiểu gõ là nó gõ được luôn, tự nhận layout

**Môi trường**
 - OS và version: (Kubuntu 19.04)
 - Desktop: (KDE)
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.5.2)

**Comment by ImKifu** [comment]
Tiện thể cho xem xin tên service của ibus-bamboo được ko ạ? mỗi lần bật máy nó hỏi muốn chạy cái ibus lên không, em muốn thử `systemctl enable`  tên service để tự động chạy nó mỗi khi mở máy ạ.

**Comment by ndgnuh** [comment]
1. Bạn đã cài biến môi trường với chạy ibus như trong FAQ chưa? Sau khi làm phải logout và login lại để có tác dụng
2. muốn chạy ibus thì thêm vào start up của session, ibus bamboo không cung cấp systemd unit, và nếu muốn/cần thì đó là việc của ibus, không phải gói này.

**Comment by vuminhcongvmc** [comment]
Bạn phải cài Language Support trước:
$sudo apt install -y language-selector-gnome && gnome-language-selector
Để phần mềm cài đặt các thư viện cần thiết rồi chọn mặc định ibus, sau đó mới làm các bước như bạn đã làm.

**Comment by vuminhcongvmc** [comment]
Bạn không cần thiết lập ibus tự khởi động vì gnome-language-selector sẽ làm điều đó cho bạn.
