### ISSUE TITLE
Lỗi khi chuyển input method về english

### ISSUE THREAD

**Issue by huylenguyen806** [BambooEngine/ibus-bamboo#59]
**Mô tả lỗi**
Dialog (hay PopUp gì đấy) hiện lên khi nhấn phím tắt để chuyển input method từ tiếng việt sang tiếng anh không tự tắt.

**Các bước tái hiện lỗi**
1. Mở gedit
2. Gõ "á"
3. Bấm phím tắt chuyển sang next input method là english
4. Dialog các input method hiện lên nhưng không tắt, phải click chuột vào nó mới tắt và bấm phím tắt 1 lần nữa thì nó sẽ tự động hiện rồi tắt (tức là ok)

**Kết quả mong muốn**
Dialog tự động hiện rồi tắt trong lần bấm phím tắt đầu tiên và input method được switch thành công.

**Ảnh chụp màn hình**
![Imgur](https://i.imgur.com/o675doS.png?1)

**Môi trường**
 - OS và version: Ubuntu 18.04
 - Desktop: regolith-desktop (i3-gaps và gnome)
 - Phiên bản ibus-bamboo: bản mới nhất

**Thông tin thêm**
Đối với ibus-hangul, chuyển sang tiếng hàn, gõ vài chữ rồi chuyển sang tiếng anh thì hoạt động bình thường, nên mình nghĩ cái này do ibus-bamboo, ibus-unikey với ibus-teni cũng bị vấn đề tương tự.

**Comment by luongthanhlam** [comment]
bạn đang dùng phím tắt gì? mình thử với Super+Space trên Ubuntu thì hoạt động bình thường.

**Comment by huylenguyen806** [comment]
> bạn đang dùng phím tắt gì? mình thử với Super+Space trên Ubuntu thì hoạt động bình thường.

Phím tắt nào cũng vậy hết bạn. Chắc do desktop environment của mình sử dụng, hình như là gnome-flashback kết hợp với i3-gaps.

**Comment by luongthanhlam** [comment]
bạn cập nhật lên bản v0.5.4 và thử lại xem.

**Comment by huylenguyen806** [comment]
Works perfectly, thank you :smile:
Tính năng mới ngon quá, hy vọng bạn sau này đẩy được lên ubuntu ppa.
Đóng issue tại đây.

**Comment by huylenguyen806** [comment]
> bạn cập nhật lên bản v0.5.4 và thử lại xem.

Bản 0.6.1 bị lại rồi ad ơi

**Comment by luongthanhlam** [comment]
bạn có đang bật Capture mouse events không?

**Comment by huylenguyen806** [comment]
Bỏ Capture mouse events thì hết lỗi rồi ad :+1:

**Comment by ngfuong** [comment]
Hi bác, bác dùng i3 thì Super+Space vẫn chuyển được input method hả bác?
Bác chỉ mình làm sao được không nhỉ? Bên mình không chuyển cả không hiện pop-up luôn.

**Comment by MeowIce** [comment]
> Hi bác, bác dùng i3 thì Super+Space vẫn chuyển được input method hả bác?
> Bác chỉ mình làm sao được không nhỉ? Bên mình không chuyển cả không hiện pop-up luôn.

Bạn đổi từ Super + Space sang Ctrl + Space nhé :>

**Comment by ngfuong** [comment]
> 

Mình đổi shortcut cho Change Input Source trong gnome-control-center thành Ctrl + Space thì không hoạt động bạn ơi :(

**Comment by ngfuong** [comment]
> 

Minh tam thoi bind key bang `bindsym $mod+space exec ibus engine Bamboo` trong i3 config thi tam dung duoc roi cac bac nhe

**Comment by ngfuong** [comment]
> 

Minh tam thoi bind key bang `bindsym $mod+space exec ibus engine Bamboo` trong i3 config thi tam dung duoc roi cac bac nhe

**Comment by ngfuong** [comment]
> 

Minh tam thoi bind key bang `bindsym $mod+space exec ibus engine Bamboo` trong i3 config thi tam dung duoc roi cac bac nhe
