### ISSUE TITLE
ibus-engine-bamboo đột ngột chiếm tài nguyên của CPU khá cao

### ISSUE THREAD

**Issue by huyndnse63331** [BambooEngine/ibus-bamboo#6]
**Mô tả lỗi**
Mình xài bình thường thì đến 1 lúc nào đó process ibus-engine-bamboo chiếm từ 50% - 90% tài nguyên CPU (dùng ibus-teni không có tình trạng này xảy ra), mình phải kill process rồi dùng lại ibus-bamboo nhưng cũng sau 1 thời gian thì process này lại như trên...

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://user-images.githubusercontent.com/25204246/50443619-c8027900-0936-11e9-882a-97e69beb3d52.png)

**Môi trường**
 - OS và version: Ubuntu 16.04.5
 - Desktop: default (Unity)
 - Phiên bản ibus-bamboo: v0.2.6

**Comment by huyndnse63331** [comment]
![image](https://user-images.githubusercontent.com/25204246/50449563-c21e8f00-095a-11e9-9fe8-098dc3616c99.png)

**Comment by huyndnse63331** [comment]
![image](https://user-images.githubusercontent.com/25204246/50449578-d5c9f580-095a-11e9-8450-be6f324eb198.png)
![image](https://user-images.githubusercontent.com/25204246/50449583-dfebf400-095a-11e9-91c1-d67eb70038e3.png)

**Comment by ndgnuh99** [comment]
confirm, mình vừa dính 100% CPU xong.

**Comment by huyndnse63331** [comment]
hi vọng dev fix dc :))) ko thì lại về teni xài

**Comment by luongthanhlam** [comment]
lỗi này mình chưa tái hiện được nhưng có vẻ liên quan đến tính năng mouse tracking, mình sẽ theo dõi thêm

**Comment by huyndnse63331** [comment]
đây là của bản mới released nha bạn

![image](https://user-images.githubusercontent.com/25204246/50469317-74e40100-09de-11e9-82ca-af0109a2c88a.png)

**Comment by huyndnse63331** [comment]
sau thời gian mình up ảnh trước lên đây thì nó đạt tới mốc này rồi 👎 

![image](https://user-images.githubusercontent.com/25204246/50471169-0c008700-09e6-11e9-9581-c8f759340e1d.png)

**Comment by luongthanhlam** [comment]
Mình đã fix bug này trên nhánh dev, nếu có thể nhờ bạn build & test giúp mình.
Thanks!

**Comment by huyndnse63331** [comment]
Mình build theo hướng dẫn buiild từ src của wiki ko được bạn ơi

![image](https://user-images.githubusercontent.com/25204246/50520947-badfb880-0af5-11e9-85c2-ca71d124cc31.png)

**Comment by luongthanhlam** [comment]
bạn chạy giúp mình 3 lệnh dưới và gửi kết quả cho mình nhé

**Comment by luongthanhlam** [comment]
bạn chạy 3 lệnh dưới rồi gửi kết quả cho mình nhé 
```
go version
go env
make build
```

**Comment by huyndnse63331** [comment]
đây nha bạn

[output.txt](https://github.com/BambooEngine/ibus-bamboo/files/2716223/output.txt)

**Comment by luongthanhlam** [comment]
theo log trên thì máy bạn đang cài 2 phiên bản go (1.6 và 1.11), bạn thử gỡ một trong hai xem.

**Comment by huyndnse63331** [comment]
Mình gỡ hết cài lại 1.6 rồi nhưng gặp lỗi này

![image](https://user-images.githubusercontent.com/25204246/50537331-98e74400-0b90-11e9-8eec-4907422738ed.png)

**Comment by huyndnse63331** [comment]
Mình cũng cài được bản dev rồi, đang test 😆 hi vọng hết lỗi :v

**Comment by luongthanhlam** [comment]
@huyndnse63331 👍
@ndgnuh99 lỗi này thường xảy ra khi bạn bật tắt bộ gõ liên tục khiến chương trình không thể theo dõi chuột và rơi vào vòng lặp vô tận. Không nhầm thì ibus-unikey cũng dính lỗi này.

**Comment by huyndnse63331** [comment]
vậy bản dev đã fix chưa bạn? mình vừa build từ src `sudo make install`, nhưng ver hiện ở ibus là v0.2.7 không biết phải bản dev không :(

**Comment by luongthanhlam** [comment]
bản dev là code mới nhất đó bạn

**Comment by huyndnse63331** [comment]
mình đang test bản đó đây, cho tới giờ vẫn ổn, nhưng có vẻ khi gõ chữ "IB" bằng ibus-bamboo thì chữ "B" không ghi hoa được, mình phải back lại EN để gõ chữ B

**Comment by huyndnse63331** [comment]
bug mình report thì không còn thấy nữa, nhưng bug trên khá khó chịu khi muốn gõ 2 chữ hoa kế nhau :( 👎

**Comment by ndgnuh99** [comment]
Mình test nhưng chỉ tắt đi bật lại và gõ chữ thôi, không di chuột hay ấn linh tinh gì cả. Kết quả thì có vẻ khá ổn, mình cũng ko nghĩ có ai bật đi tắt lại 1000 lần trong 1 phiên làm việc :frog: 
![image](https://user-images.githubusercontent.com/33273948/50540139-c8ad4080-0bbe-11e9-9bbf-9cd5b3d2ee82.png)

**Comment by ndgnuh99** [comment]
![image](https://user-images.githubusercontent.com/33273948/50540159-538e3b00-0bbf-11e9-825f-3f5cc5adb437.png)
CPU có vẻ ổn, nhưng mà ibus % MEM nó tốn thế này có bình thường không bạn @luongthanhlam ?

**Comment by luongthanhlam** [comment]
@huyndnse63331 cả 2 lỗi đã được sửa trên v0.2.8, mình sẽ close issue này lại.
@ndgnuh99 MEM vậy là bình thường đó bạn.

**Comment by luongthanhlam** [comment]
@ndgnuh99 sorry, mình nhìn nhầm. Bạn thử bản mới nhất (v0.2.8) xem còn bị tình trạng như vậy không, nếu còn bạn tạo issue mới giúp mình, thanks!

**Comment by ndgnuh99** [comment]
Cái chiếm nhiều RAM kia có lẽ do mình tắt đi bật lại nhiều quá thôi, 1000 lần phi thực tế lắm bạn. Mình dùng bình thường và thử htop một cách ngẫu nhiên đây, không chiếm nhiêu đến thế:
![image](https://user-images.githubusercontent.com/33273948/50641665-44323780-0f9b-11e9-8521-a0173408e92c.png)

**Comment by luongthanhlam** [comment]
dù phi thực tế nhưng case test của bạn khá hay, mình sẽ  xem xét cải tiến trong những version sau 🙃

**Comment by huyndnse63331** [comment]
không biết cái này có bth không @luongthanhlam nhỉ? nó ngốn còn hơn cả chrome

![image](https://user-images.githubusercontent.com/25204246/50683182-c413dc80-1043-11e9-812d-d39d70e4c22a.png)

**Comment by huyndnse63331** [comment]
hiện tại bây giờ nó đã lên 400MB và dg lên từ từ
