### ISSUE TITLE
Hỗ trợ ibus-bamboo cho MX Linux

### ISSUE THREAD

**Issue by tinisntreal** [BambooEngine/ibus-bamboo#60]
**Mô tả lỗi**
Mình không thể cài đặt ibus-bamboo trên MX Linux như Ubuntu.

**Các bước tái hiện lỗi**
Mình cài đặt như Ubuntu nhưng bị kẹt ở bước 
`sudo apt-get install ibus-bamboo -y`

**Kết quả mong muốn**
Mong ibus-bamboo hỗ trợ cho MX Linux

**Ảnh chụp màn hình, hoặc clip quay màn hình**

**Môi trường**
 - OS và version: MX Linux 18
 - Desktop: Xfce
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.5.2)

**Comment by tinisntreal** [comment]
`\trungtin@mx:~
$ sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo
WARNING:root:could not open file '/etc/apt/sources.list'

WARNING:root:could not open file '/etc/apt/sources.list'

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for MX/Continuum
`

**Comment by luongthanhlam** [comment]
bạn tham khảo link này nhé https://askubuntu.com/questions/519154/how-to-solve-the-error-warningrootcould-not-open-file-etc-apt-sources-list

**Comment by tinisntreal** [comment]
Cám ơn bạn đã giúp ạ
