### ISSUE TITLE
Lỗi bị mất chữ khi dùng trên web facebook và chế độ gõ số 5

### ISSUE THREAD

**Issue by ichirou2910** [BambooEngine/ibus-bamboo#61]
Mình vừa tải dùng thử bamboo và thấy khá ưng. Tuy nhiên khi mình gõ tiếng việt trên web facebook thì rất hay bị mất chữ. (Test trên brave và opera, tuy nhiên trên firefox thì chưa gặp lỗi này). Ví dụ gõ "Tôi" nó sẽ thành "T" hoặc "" mất hết. Mình dùng Ubuntu 18.04, test trên libre office với discord hiện tại thấy bình thường.
Đồng thời chế độ gõ số 5 (Foward as commit) không gõ được chữ. Cái này mình thử ở mọi chỗ đều không gõ ra chữ được.

**Comment by luongthanhlam** [comment]
cám ơn bạn đã báo lỗi, tuy nhiên [do hạn chế về kỹ thuật](https://lewtds.github.io/2014/07/31/uoc-mo-bo-go-kieu-unikey/) nên lỗi này chưa thể giải quyết đc. Nếu muốn gõ tiếng việt ổn định trên chrome, opera,... bạn nên dùng kiểu gõ số 1 (preedit).

**Comment by luongthanhlam** [comment]
Update: bản 0.5.4 chế độ Sửa lỗi gạch chân số 4 đã khắc phục được lỗi này.
