### ISSUE TITLE
Không tắt được gạch chân khi gõ tiếng Việt

### ISSUE THREAD

**Issue by quanKM** [BambooEngine/ibus-bamboo#62]
**Mô tả lỗi**
Không tắt được gạch chân khi gõ tiếng Việt

**Các bước tái hiện lỗi**

Ví dụ:
1. Cài đặt từ mã nguồn
2. Restart Ibus
3. Add thêm kiểu gõ
4. Chọn cấu hình khác
5. Tích vào "Ẩn gạch chân"

**Kết quả mong muốn**
Khi gõ tiếng việt không còn dấu gách chân.

**Môi trường**
 - OS và version: Ubuntu 18.04.2
 - Desktop: Gnome
 - Phiên bản ibus-bamboo: bản mới nhất

**Comment by luongthanhlam** [comment]
một vài ứng dụng không hỗ trợ ẩn dấu gạch chân (chrome, opera,...), bạn liên hệ với tác giả ứng dụng đó để báo lỗi nhé

**Comment by ladylazy9x** [comment]
fix đc lỗi này chưa b nhỉ, mình gõ ở đâu cũng bị
