### ISSUE TITLE
làm thế nào để chuyển đổi bàn phím anh- việt

### ISSUE THREAD

**Issue by khanhtungmtp** [BambooEngine/ibus-bamboo#63]
trên ubuntu thì nhấn window + space là chuyển sang anh hoặc việt, còn trên linux lite nhấn phím window nó mở ứng dụng của linux lite chứ ko giống ubuntu được, làm thế nào để gán phím khác cho linux lite ạ, cám ơn admin

**Comment by luongthanhlam** [comment]
bạn chạy `ibus-setup` rồi cấu hình phím tắt trong Keyboard Shortcuts nhé.

**Comment by leanhtuanwru** [comment]
Mình đang sử dụng Deepin 15.11 và iBus-Bamboo v0.6.2. Hiện tại mình đã gõ được Tiếng Việt ở hầu hết các App mình đang sử dụng nhưng mình cũng đang gặp một lỗi là khi mới khởi động máy lên thì không thế sử dụng Shortcuts Super+Space để chuyển bộ gõ (Next input method - Chuyển từ tiếng anh sang tiếng việt và ngược lại) được. Nhưng sau khi vào Preference chọn lại Shortcuts (Vẫn để mặc định phím tắt là Super+Space hoặc đổi Shortcuts khác) rồi OK thì sau đó Shorcuts này lại hoạt động bình thường. Hiện tại mình chưa có các khắc phục. Mỗi lần mở máy lại phải vào chọn lại Shorcuts khá mất thời gian. Rất mong nhận được hướng dẫn Fix của các bạn. Tks !!!

**Comment by luongthanhlam** [comment]
bạn click chuột phải vào biểu tượng bộ gõ trên thanh công cụ, chọn Restart xem

**Comment by leanhtuanwru** [comment]
> bạn click chuột phải vào biểu tượng bộ gõ trên thanh công cụ, chọn Restart xem

Đúng là Click chuột phải vào icon bộ gõ và chọn Restart thì phím tắt Super+Space lại hoạt động bình thường. Nhưng khi mình khởi động lại máy hay tắt máy đi bật lại thì lại không sử dụng được bạn à. Có cách nào mà khi vừa khởi động mà mình sử đụng được phím tắt luôn mà không cần Restart không bạn?

**Comment by luongthanhlam** [comment]
bạn thêm dòng này vào file .profile, logout và login lại xem
sleep 20;ibus restart;

On 11/28/19, Lê Anh Tuấn <notifications@github.com> wrote:
>> bạn click chuột phải vào biểu tượng bộ gõ trên thanh công cụ, chọn Restart
>> xem
>
> Đúng là Click chuột phải vào icon bộ gõ và chọn Restart thì phím tắt
> Super+Space lại hoạt động bình thường. Nhưng khi mình khởi động lại máy hay
> tắt máy đi bật lại thì lại không sử dụng được bạn à. Có cách nào mà khi vừa
> khởi động mà mình sử đụng được phím tắt luôn mà không cần Restart không
> bạn?
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/BambooEngine/ibus-bamboo/issues/63#issuecomment-559335833


-- 


<https://htmlsig.com/t/000001BN5EB6>

Luong Thanh Lam / Web Developer

Add:168 Kim Giang Str, Dist Hoang Mai, Ha Noi

Tel: 0167 666 2048

Email: ltlam93@gmail.com

[image: Twitter]  <https://twitter.com/ltlam93>   [image: Skype]
<http://is.gd/TIQ0EK> [image: Github]  <https://github.com/ltlam93/>

**Comment by luongthanhlam** [comment]
Bạn thêm dòng này vào file `.profile`, logout và login lại nhé
`sleep 20;ibus restart`

**Comment by leanhtuanwru** [comment]
> Bạn thêm dòng này vào file `.profile`, logout và login lại nhé
> `sleep 20;ibus restart`

![DeepinScreenshot_select-area_20191129152418](https://user-images.githubusercontent.com/36043998/69854723-6112e000-12bc-11ea-975d-264714571878.png)

Mình đã thêm như vậy nhưng không có kết quả bạn à

**Comment by ndgnuh** [comment]
Cái Linuxlite này dùng xfce nhỉ, nếu vậy bạn vào phần cài đặt> session and startup > startup > thêm 1 mục, để tiêu đề là ibus, command là `ibus-daemon -rdx`

**Comment by leanhtuanwru** [comment]
> Cái Linuxlite này dùng xfce nhỉ, nếu vậy bạn vào phần cài đặt> session and startup > startup > thêm 1 mục, để tiêu đề là ibus, command là `ibus-daemon -rdx`. Nếu vẫn chưa đc bạn thử để lệnh trên là `ibus-daemon -rdx; sleep 1; ibus-restart` xem sao

Cám ơn bạn. Mình đang sử dụng Deepin Linux. Deepin không có UI cho trình quản lí Startup. Deepin chỉ tích hợp vào Menu chuột phải cho mỗi Application như hình dưới. Nên mình cũng chưa biết thực hiện hướng dẫn của bạn như nào. 
![DeepinScreenshot_dde-desktop_20191129174844](https://user-images.githubusercontent.com/36043998/69864134-e902e500-12d0-11ea-9e93-b13b552f6caf.png)

**Comment by tranducit95** [comment]
Mình gặp tương tự, không biết ai khắc phục được chưa nhỉ?

**Comment by luongthanhlam** [comment]
@leanhtuanwru  sorry mình gõ nhầm, bạn sửa lại như sau nhé
`(sleep 20;ibus restart)&`

**Comment by ndgnuh** [comment]
afaik các vấn đề về phím tắt chủ yếu dính đến 2 việc:
1. xung đột giữa ibus và de/wm.
2. cái chuyển phím tắt của ibus hơi lỗi 

Cái 1 có thể giải quyết bằng việc xoá bớt phím tắt đi (nếu xoá phím tắt ibus thì có thể dùng một script để thay thế). Mình dùng script để điều khiển ibus thì chưa bao h dính lỗi như trên. Cái số 2 thì chịu thôi :P
