### ISSUE TITLE
Thêm tre cho Fedora

### ISSUE THREAD

**Issue by tran184** [BambooEngine/ibus-bamboo#65]
Mình muốn tre chạy trên Fedora. Máy mình chạy Ubuntu không được tốt lắm.

**Comment by ndgnuh** [comment]
Mình nhớ không nhầm thì bạn có thể dùng `alien` để biến gói `.deb` thành gói `.rpm` mà Fedora có thể sử dụng.

**Comment by tran184** [comment]
Mình cám ơn nhé.

**Comment by tran184** [comment]
@ndgnuh Solus thì cài thế nào ạ?

**Comment by tran184** [comment]
@ndgnuh Trên Solus thì làm thế nào ạ?

**Comment by ndgnuh** [comment]
> @ndgnuh Trên Solus thì làm thế nào ạ?

Distro này thì mình không biết, bạn thông cảm. Bạn có thể cài đặt từ nguồn, hoặc tìm hướng dẫn tạo package của package manager mà distro đó dùng rồi tự tạo gói để cài, hoặc hơn nữa thì bạn maintain luôn cái package đó :)

**Comment by luongthanhlam** [comment]
với Fedora bạn có thể cài trực tiếp từ [OpenBuildService](https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo).

**Comment by tran184** [comment]
@luongthanhlam @ndgnuh  Build từ nguồn như thế nào ạ? Có tài liệu nào nói về cách build hầu hết những phần mềm không ạ?

**Comment by luongthanhlam** [comment]
Để build từ source bạn làm theo ở đây https://github.com/BambooEngine/ibus-bamboo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-t%E1%BB%AB-m%C3%A3-ngu%E1%BB%93n. Mỗi ứng dụng sẽ có cách build khác nhau bạn làm theo hướng dẫn là đc
