### ISSUE TITLE
Lỗi trên chế độ thứ 4 (ForwardKeyEvent II) trong thanh địa chỉ của chrome 

### ISSUE THREAD

**Issue by van26101998** [BambooEngine/ibus-bamboo#68]

**Comment by van26101998** [comment]
Khi gõ các từ mà có hai phụ âm ở cuối thì bị lỗi (trong trường hợp gõ dấu ở cuối từ)
ví dụ: gõ "ngành" - nganhf  -------> ngaành
Test trên thanh địa chỉ của Brave. Còn trong các app khác không có lỗi này

**Comment by luongthanhlam** [comment]
Bạn gặp lỗi này trong chrome, brave hay cả hai? Ngoài thanh địa chỉ bạn có gặp lỗi trong các ứng dụng web như facebook, github không?

**Comment by van26101998** [comment]
Mình gặp trên cả chrome và brave, chỉ bị trên thanh địa chỉ, ngoài ra không bị lỗi ở đâu nữa. 
Mình đã thử tắt hay bật các tính năng "bỏ dấu tự do", "dấu thnah chuẩn", "sửa lỗi gạch chân", "ẩn gạch chân" đều không có tác dụng.
Xin lỗi nếu xưng hô không đúng ạ.

**Comment by luongthanhlam** [comment]
bạn đang dùng os nào, chrome phiên bản bao nhiêu? nếu được gửi mình output lệnh này nhé `env | grep "IM_MODULE\|XMODIFIERS"`
P.S. bạn thử khởi động lại máy xem

**Comment by van26101998** [comment]
Mình dùng xubuntu 18.04, chrome Version 76.0.3809.100 (Official Build) (64-bit)
Output:
CLUTTER_IM_MODULE=xim
QT4_IM_MODULE=xim
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
GTK_IM_MODULE=xim


P/s: Mình có mới update bản ibus mới nhất trong ubuntu 19.04 thì không có vấn đề gì.
Hôm qua mình có gỡ đi một số app trong xubuntu sau đó lỡ gỡ mất một số thứ, sau đó phải đọc log cài lại chúng. Chắc là trong quá trình cài lại có vấn đề gì đó nên lỗi.

**Comment by luongthanhlam** [comment]
bạn làm theo hướng dẫn ở đây https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60#ki%E1%BB%83m-tra-bi%E1%BA%BFn-m%C3%B4i-tr%C6%B0%E1%BB%9Dng, khởi động lại máy và thử lại nhé.

**Comment by van26101998** [comment]
Mình làm theo hướng dẫn này thì không gõ được tiếng Việt luôn, ở mọi app.
Mình có cài lại xubuntu thì vẫn bị lỗi ở thanh địa chỉ. 
Nhưng ở ubuntu thì vẫn không bị.

**Comment by luongthanhlam** [comment]
Xubuntu hình như vẫn đang build trên gtk2 thì phải :cry:

**Comment by nopain2110** [comment]
> Xubuntu hình như vẫn đang build trên gtk2 thì phải

xfwm 4.14 build trên gtk3 rồi nhưng xubuntu phải đợi đến bản 19.10 mới có
