### ISSUE TITLE
Gõ mật khẩu bị hiện trong terminal

### ISSUE THREAD

**Issue by ndgnuh99** [BambooEngine/ibus-bamboo#7]
**Mô tả lỗi**
Như tiêu đề

**Các bước tái hiện lỗi**
Trên terminal:
1. sudo abcxyz...
2. Gõ mật khẩu --> hiện tùm lum

**Kết quả mong muốn**
Mật khẩu bị ẩn đi.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![image](https://user-images.githubusercontent.com/33273948/50449041-42db8c00-0957-11e9-80f4-0155e9aaa1d1.png)

**Môi trường**
Trong ảnh.

**Comment by luongthanhlam** [comment]
Đây là lỗi chung của các bộ gõ sử dụng cơ chế pre-edit. Có thể khắc phục bằng các cách sau:
- Sử dụng chế độ backspace giả thích hợp (nhấn Shift+~ để chọn)
- Thêm vào danh sách loại trừ (nhấn Shift+~ để chọn)
- Tắt bộ gõ trước khi gõ mật khẩu
- Bật tùy chọn Tự động gửi buffer nếu sai chính tả. Nhược điểm là một khi bạn đã gõ sai thì buộc phải xóa các kí tự trước đó rồi gõ lại từ đúng, ngoài ra cách này chỉ ẩn được một phần password chứ không ẩn hết.

**Comment by ndgnuh99** [comment]
Trong ảnh mình dùng backspace giả đấy bạn ơi, gõ số cũng bị nữa.

**Comment by luongthanhlam** [comment]
bạn dùng chế độ backspace giả nào vậy? mình cài termite rồi chọn chế độ IBus forward keyevent có bị hiện đâu nhỉ

**Comment by ndgnuh99** [comment]
Có khi issue này mình đăng lúc chưa update đó. Mình vừa thử lại cũng không bị. Còn trước đó mình dùng cái chế độ ibus.
Thôi close được rồi bạn. Sorry báo động giả.
