### ISSUE TITLE
Không hoạt động với WPS office trên manjaro deepin

### ISSUE THREAD

**Issue by ndl23061997** [BambooEngine/ibus-bamboo#70]
Trong wps office ibus không hoạt động

**Comment by luongthanhlam** [comment]
Bạn làm theo hướng dẫn ở đây nhé
https://github.com/BambooEngine/ibus-bamboo/wiki/Kh%C3%B4ng-g%C3%B5-%C4%91%C6%B0%E1%BB%A3c-ti%E1%BA%BFng-vi%E1%BB%87t-tr%C3%AAn-ph%E1%BA%A7n-m%E1%BB%81m-%60abc-xyz%60

**Comment by ndl23061997** [comment]
Mình đã fix được bằng cách start ibus with command ibus-daemon -xdr
