### ISSUE TITLE
Lỗi gõ tiếng Việt ở khung chat/ comment facebook trên chrome,

### ISSUE THREAD

**Issue by maxiqboy** [BambooEngine/ibus-bamboo#71]
**Mô tả lỗi**
Một mô tả ngắn gọn về lỗi đang xảy ra

lỗi gõ tiếng Việt ( chế độ 3 ) trong Messenger và khung chat trên facebook ở chrome:

thử nghieêệm trong messenger 

ưừa

**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
Ví dụ:
Sử dụng chrome và dùng facebook / messenger.com để chat chit

**Kết quả mong muốn**
Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Ví dụ: Gõ abc thì phải thấy abc chứ không phải xyz

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Nếu cần thiết, hãy [đính kèm hình ảnh](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) hoặc gửi link youtube [quay lại màn hình](https://www.youtube.com/watch?v=N8M4zsqTkr4) tái hiện lỗi.

**Môi trường**
 - OS và version: Ubuntu 18.04
 - Desktop: Gnome
 - Phiên bản ibus-bamboo:  v0.5.4)

**Thông tin thêm**
Các nội dung khác có liên quan đến lỗi đang xảy ra.
Ví dụ: Chương trình XYZ được cài đặt từ: (apt-get, snap, flatpak, download từ trang chủ,...)

**Lưu ý**
Trước khi gửi issue lên github, xin bạn hãy đọc lại Hướng dẫn sử dụng và Các vấn đề thường
gặp trên trang chủ ít nhất một lần nữa. Sau khi đọc kỹ hướng dẫn sử dụng và thử mọi cách rồi
mà không được, thì hãy đặt câu hỏi lên đây. Khi gửi câu hỏi xin bạn hãy mô tả chi tiết các
bước bạn đã làm, và chi tiết kết quả bạn nhận được.

**Comment by luongthanhlam** [comment]
Bạn chọn chế độ gõ số 1 hoặc 4 để khắc phục lỗi này nhé.

**Comment by maxiqboy** [comment]
em cảm ơn ạ,
