### ISSUE TITLE
Flag provided but not defined: -test.testlogfile (go 1.13)

### ISSUE THREAD

**Issue by nopain2110** [BambooEngine/ibus-bamboo#73]
**Mô tả lỗi**
Một mô tả ngắn gọn về lỗi đang xảy ra
Sau khi mình update go (go version go1.13 linux/amd64) trên archlinux thì khi make nó báo lỗi
`flag provided but not defined: -test.testlogfile`

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![error](https://i.ibb.co/DzRZnFh/Screenshot-from-2019-09-04-14-08-52.png)

**Môi trường**
 - OS và version: Arch Linux
 - Desktop: i3wm
 - Phiên bản ibus-bamboo: v0.5.5
 - Go version: 1.13
 - Go env
`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nopain/.cache/go-build"
GOENV="/home/nopain/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nopain/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build928738402=/tmp/go-build -gno-record-gcc-switches"
`

**Thông tin thêm**
Mình không biết về go nhưng mình nghĩ là do bug của go vì sau khi upgrade go mình không thể make được cả bản v0.5.4 nữa

**Comment by nopain2110** [comment]
Update: sau khi mình downgrade go xuống 1.12.9 thì lại make được bình thường
Issue này là của go (https://github.com/golang/go/issues/31859)

**Comment by luongthanhlam** [comment]
Đã fix trong https://github.com/BambooEngine/ibus-bamboo/commit/fae74d44b0bc56cfb04c3e66e8ef7589631217ff
Btw, bên Arch update nhanh vãi, mình vẫn đang dùng go1.10 :disappointed:

**Comment by mks1508** [comment]
Hóa ra lỗi ở tại go .... thanks các bác ... thế chỉ cần sửa PKGBUILD go -> gcc-go là ổn.
