### ISSUE TITLE
Donate hoặc Sponsors

### ISSUE THREAD

**Issue by khanhicetea** [BambooEngine/ibus-bamboo#74]
Đầu tiên mình xin cảm ơn tác giả đã bỏ thời gian xây dựng Open Source bộ gõ cho Linux (theo mình biết thì hiện tại đây là repo bộ gõ tiếng Việt còn sót lại đang được phát triển).

Vì vậy, mình và nhiều bạn khác đang sử dụng mong muốn được cảm ơn tác giả thông qua một, hai ly cafe (hoặc bia :smiley: ).

Nếu có thể mong tác giả mở 1 link Donate qua Paypal hay dùng Sponsor của Github.

![image](https://user-images.githubusercontent.com/4528223/64240856-db85cb00-cf2c-11e9-947c-198d1bb6e61d.png)

**Comment by luongthanhlam** [comment]
Hi @khanhicetea, cảm ơn bạn đã ủng hộ bộ gõ. Tuy nhiên trong thời điểm hiện tại, mình hoan nghênh các hình thức đóng góp vì cộng đồng nhiều hơn (như viết hướng dẫn sử dụng, giới thiệu bộ gõ với bạn bè và người thân, thông báo lỗi cho tác giả, đóng gói và maintain cho các distro hoặc tham gia phát triển dự án, etc.) :D

**Comment by nthainguyen** [comment]
Nhờ có bamboo mà mình h có thể gõ tiếng việt trên emacs một cách hoàn hảo, không có popup windows như trước nữa. Perfect.

**Comment by NhatGit** [comment]
@nthainguyen Anh ơi, hiện tại e dùng emacs trên manjaro, cài ibus qua UAR nhưng vẫn có tình trạng popup trong emacs, ứng dụng bên ngoài thì có hiện gạch chân khi gõ tiếng Việt. Không biết a đang dùng trên distro nào vậy ạ?

**Comment by nthainguyen** [comment]
Để ko bị popup thì bạn thay đổi chế độ gõ dấu của bamboo là dc, hình như chế độ thứ 3-4 gì đấy mình ko rõ lắm.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by NhatGit** [comment]
E đổi dc rồi ạ! Quả này học tiếng Trung vs tiếng Nhật trên emacs thì phê lòi :))

**Comment by hnbnh** [comment]
@luongthanhlam cảm ơn anh vì ibus-bamboo, không biết ở thời điểm hiện tại anh có ý định mở 1 link donate không ạ?
