### ISSUE TITLE
Lỗi kí tự khi backspace

### ISSUE THREAD

**Issue by ImKifu** [BambooEngine/ibus-bamboo#76]
**Mô tả lỗi**

Không xóa được kí tự

**Các bước tái hiện lỗi**

1. Mở Telegram, bản tải từ trang web
2. Khi xóa kí tự, ví dụ câu như sau:

```
Ibus Bamboo thật tuyệt zời`|`
```
Con trỏ chuột đang ở chữ i
Sau khi xóa một vài kí tự, con trỏ chuột nhảy bị lỗi và có chữ cái không được xóa, và xóa các chữ cái sau chữ ý
```
Ibus Bamboo thật t z`|`
```
Con trỏ chuột ở chữ z, nhưng nó không xóa chữ z mà xóa các kí tự sau chữ z. Điều này chỉ xảy ra khi gõ chữ tiếng Việt và xóa chữ tiếng Việt bị gõ sai. Ví dụ chữ `zời`, sau khi xóa chữ ơ và i, thì chữ z bị mắc kẹt không xóa được và xóa các chữ đằng sau.

**Kết quả mong muốn**

Xóa kí tự như bình thường

**Môi trường**
 - OS và version: (cả trên Ubuntu 19.04 và Kubuntu 19.04 )
 - Desktop: (KDE **mặc định** của Kubuntu )
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.5.6)

**Thông tin thêm**
- Telegram được tải về từ trang chủ trên web
- Layout bàn phím là colemak, caplock đổi thành backspace.
Tức là khi xóa chữ bị sai, bấm caplock để xóa kí tự, nó tương đương như là backspace.

**Comment by luongthanhlam** [comment]
Cảm ơn bạn! Lỗi này sẽ đc fix trong bản 0.5
6, hiện tại bạn có thể khắc phục bằng cách nhấn Shift+~ chọn chế độ gõ số 2.
