### ISSUE TITLE
lỗi bị mất chữ

### ISSUE THREAD

**Issue by vuvanbac1997** [BambooEngine/ibus-bamboo#77]
chế độ sửa lỗi gạch chân bị mất chữ khi gõ nhanh

**Comment by luongthanhlam** [comment]
Bạn gặp hiện tượng này trong ứng dụng nào, chế độ gõ bạn đang dùng là gì?

**Comment by ddthanh198** [comment]
Mình cũng gặp
Gõ xong ấn space nó mất vài chữ của từ vừa gõ, có khi mất cả từ
Có khi gõ 1 từ xong đang gõ từ tiếp theo rồi xóa đi vài chữ cái là dấu bắt đầu loạn hết lên, nhiều khi phải xóa đi 2-3 từ thì nó mới đúng trở lại được
Gặp trong hầu hết các ứng dụng

**Comment by vuvanbac1997** [comment]
Mình đang gặp lỗi trong Opera. Ứng dụng khác mình chưa thử qua. Chế độ gõ kiểu telex nhé bạn.

**Comment by luongthanhlam** [comment]
@vuvanbac1997 @ddthanh198 bạn gặp lỗi trong ứng dụng nào? Chế độ gõ bạn thiết lập cho ứng dụng đó là gì? Lưu ý: chế độ gõ khác với kiểu gõ: https://github.com/BambooEngine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng
ps2: mình sẽ xem xét

**Comment by Slotheacientone** [comment]
mình bị lôĩ y chang khi dùng chế độ gõ 2 surrounding text vd gõ "chào" sẽ thành "cào" đôỉ qua chế độ khác thì không sao cơ mà lại bị lôĩ khi search trong gnome activity

**Comment by tranphuquy19** [comment]
bị dính lỗi y chang như vậy nếu bật sửa lỗi gạch chân, lúc đầu thì gõ bình thường cho đến một lúc sau thì sẽ bị tình trạng mất chữ khi gõ trên Chrome cũng như các editor khác như VS Code hay IntelliJ ... mình đang sài ver 0.5.7

**Comment by luongthanhlam** [comment]
Bạn cập nhật lên v0.5.8, nhấn Shift+~ chọn chế độ Sửa lỗi gạch chân số 4 hoặc 3 và thử lại nhé.

**Comment by Slotheacientone** [comment]
chế độ 3 4 thì ko sao cơ mà vô search trong gnome activity thì không xóa được chữ

**Comment by luongthanhlam** [comment]
bên gnome đang xử lý lỗi này bạn nhé.
