### ISSUE TITLE
Phím tắt sử dụng với Shift không khả dụng khi trong app chạy bằng wine

### ISSUE THREAD

**Issue by haipham22** [BambooEngine/ibus-bamboo#78]
**Mô tả lỗi**
Mình dùng zalo trên wine khi nhấn shilf và ấn home, end thì ko bôi đen các ký tự

**Các bước tái hiện lỗi**
1. Mở zalo 19.xxx
2. Gõ text khoảng 4-5 ký tự
3. Nhấn giữ shifl
4. Nhấn home hoặc end

**Kết quả mong muốn**
Đoạn text trong input sẽ được bôi đen chứ không phải nhảy cách trong đó

**Môi trường**
 - OS và version: Ubuntu 18.04 kernel 5.0
 - Phiên bản ibus-bamboo: v0.5.6

**Comment by luongthanhlam** [comment]
Bạn có gặp hiện tượng tương tự khi tắt ibus bamboo không?

**Comment by haipham22** [comment]
mình ko, thử đổi qua ibus-teni hoặc unikey thì ko bị, còn thêm lỗi ko dùng được backspace nữa bạn :D

**Comment by luongthanhlam** [comment]
Bạn có đang bật tính năng Sửa lỗi gạch chân không? Nếu có bạn nhấn Shift+~
rồi chuyển sang chế độ gõ khác xem.

**Comment by haipham22** [comment]
mình có thử tắt đi rồi bạn ơi!

**Comment by luongthanhlam** [comment]
Gửi giúp mình output 2 lệnh này nhé
`env | grep "IM_MODULE\|XMODIFIERS"`


`cat ~/.config/ibus-bamboo/ibus-bamboo.config.json`

**Comment by haipham22** [comment]
máy mình để ở nhà rồi, đợi về mình mở lên gửi cho bạn nhé!

**Comment by luongthanhlam** [comment]
Okay.

**Comment by haipham22** [comment]
Gửi bạn!

CLUTTER_IM_MODULE=xim
QT4_IM_MODULE=xim
QT_IM_MODULE=xim
XMODIFIERS=@im=ibus
GTK_IM_MODULE=ibus

{
  "InputMethod": "Telex",
  "InputMethodDefinitions": {
    "Microsoft layout": {
      "!": "_Ă",
      "#": "_Ê",
      "$": "_Ô",
      ")": "_Đ",
      "0": "__đ",
      "1": "__ă",
      "2": "__â",
      "3": "__ê",
      "4": "__ô",
      "5": "DauHuyen",
      "6": "DauHoi",
      "7": "DauNga",
      "8": "DauSac",
      "9": "DauNang",
      "@": "_Â",
      "[": "__ư",
      "]": "__ơ",
      "{": "_Ư",
      "}": "_Ơ"
    },
    "Telex": {
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh"
    },
    "Telex + VNI + VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "~": "DauNga"
    },
    "Telex 2": {
      "[": "__ơ",
      "]": "__ư",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ__Ư",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_Ơ",
      "}": "_Ư"
    },
    "Telex 3": {
      "[": "__ươ",
      "a": "A_Â",
      "d": "D_Đ",
      "e": "E_Ê",
      "f": "DauHuyen",
      "j": "DauNang",
      "o": "O_Ô",
      "r": "DauHoi",
      "s": "DauSac",
      "w": "UOA_ƯƠĂ",
      "x": "DauNga",
      "z": "XoaDauThanh",
      "{": "_ƯƠ"
    },
    "VIQR": {
      "'": "DauSac",
      "(": "A_Ă",
      "*": "UO_ƯƠ",
      "+": "UO_ƯƠ",
      ".": "DauNang",
      "0": "XoaDauThanh",
      "?": "DauHoi",
      "\\": "D_Đ",
      "^": "AEO_ÂÊÔ",
      "`": "DauHuyen",
      "~": "DauNga"
    },
    "VNI": {
      "0": "XoaDauThanh",
      "1": "DauSac",
      "2": "DauHuyen",
      "3": "DauHoi",
      "4": "DauNga",
      "5": "DauNang",
      "6": "AEO_ÂÊÔ",
      "7": "UO_ƯƠ",
      "8": "A_Ă",
      "9": "D_Đ"
    },
    "VNI Bàn phím tiếng Pháp": {
      "\"": "DauHuyen",
      "\u0026": "XoaDauThanh",
      "'": "DauHoi",
      "(": "DauNga",
      "-": "DauNang",
      "_": "UO_ƯƠ",
      "à": "D_Đ",
      "ç": "A_Ă",
      "è": "AEO_ÂÊÔ",
      "é": "DauSac"
    }
  },
  "OutputCharset": "Unicode",
  "Flags": 7,
  "IBflags": 31216,
  "AutoCommitAfter": 3000,
  "ExceptedList": null,
  "PreeditWhiteList": null,
  "X11ClipboardWhiteList": null,
  "ForwardKeyWhiteList": null,
  "SLForwardKeyWhiteList": null,
  "DirectForwardKeyWhiteList": null,
  "SurroundingTextWhiteList": null
}

**Comment by haipham22** [comment]
cảm ơn bạn, quên mất hôm nay mới rep lại bạn, mình thử các chế độ `Shift` + `~` thì gặp lỗi dupplicate từ hoặc ko dùng được phím backspace :D, mình thấy có giống với 1 issue đang open, nếu trùng issue thì bạn đóng luôn hộ mình nhé!

**Comment by luongthanhlam** [comment]
Bạn đã thử hết các chế độ gõ chưa? Không có cái nào hoạt động hả bạn?

**Comment by haipham22** [comment]
mình đã thử hết các chế độ, có chế độ thứ 3 và 4 có chạy được nhưng bị dupplicate text và ko nhấn được backspace

**Comment by luongthanhlam** [comment]
Uhm, các chế độ sửa lỗi gạch chân hoạt động nhờ API của hệ điều hành nên sẽ có cái hoạt động có cái không. Nếu bạn không gặp vđ gì với các chế độ khác thì bạn có thể đóng issue này lại.

**Comment by luongthanhlam** [comment]
@haipham22 bạn test giúp mình còn lỗi với Shift trên bản 0.5.7 không nhé
