### ISSUE TITLE
Lỗi ngỡ ngẩn khi click vào suggestions trên chrome

### ISSUE THREAD

**Issue by anhskohbo** [BambooEngine/ibus-bamboo#79]
**Mô tả lỗi**
Xem mô tả hình ảnh

![Peek 2019-09-14 11-33](https://user-images.githubusercontent.com/1529454/64903465-ba1e9f00-d6e3-11e9-8c05-bdf90750ed8e.gif)

**Các bước tái hiện lỗi**
Mở chrome, bật bamboo nhập thanh địa chỉ.

Gõ `vn` -> chrome sẽ sugests `vnexpress.net` click vào thì bị nhẩy chữ sang `vnvnvnvnvnvn`

**Kết quả mong muốn**

Lỗi này ko bị trên ibus-unikey và khi ko bật bamboo.

**Môi trường**
 - OS và version: Majanro 
 - Desktop: Cinnamon
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.5.6)

**Comment by luongthanhlam** [comment]
Mình vừa fix lỗi này trong https://github.com/BambooEngine/ibus-bamboo/commit/792535d4d5ebdcb112bd8d6f55cd2ac5ad7f2cca, bạn thử build từ source xem đã hết lỗi chưa?

**Comment by anhskohbo** [comment]
Mình vừa test thấy đã chạy ok rồi. Tuy nhiên thi thoảng đã gõ quay lại từ xóa đi gõ sai sẽ lại duplicate từ như vậy (mình gặp 1 lần nhưng chưa thể làm để gặp lại).

**Comment by luongthanhlam** [comment]
Bạn bị duplicate khi gõ trong chế độ mặc định (Preedit) hay chế độ Sửa lỗi gạch chân vậy?

**Comment by anhskohbo** [comment]
chế độ preedit bạn nhé. mình sẽ tiếp tục sài để theo dõi vấn đề này.
