### ISSUE TITLE
Lỗi khi gõ trên firefox

### ISSUE THREAD

**Issue by ndgnuh** [BambooEngine/ibus-bamboo#8]
**Mô tả lỗi**
Lỗi 1: Bảng gợi ý không hiện trên thanh url, nó hiên ra rồi mất luôn. 
Lỗi 2: Thỉnh thoảng gõ chữ bị lỗi. Mỗi chế độ xóa gạch chân lôi mot kiểu, kiêu ibus thì thi thoang mất dấu. Cheé độ X11 thì thiỉh thoảng nó ra thừa hoặc thiếu kí tự. Surrounding text thì nếu dùng backspace xóa kí tự nó sẽ xóa từ chữ cái thứ 2 sau trước trỏ, hơn nữa thi thoảng gõ dấu là nó xóa luôn chữ đằng trước.

**Các bước tái hiện lỗi**
1. Mở firefox
2. Chỉnh sang chế độ xoá gạch chân, 
3. Nhập vào thanh URL (Cách để tái hiên cả 2 lôĩ dễ nhất là dùng thanh URL)

**Kết quả mong muốn**
Firefox hiện gợi ý. Và gõ bình thường như chế độ preedit.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
![ảnh gif](https://i.imgur.com/fXDB3hp.gif)

**Môi trường**
 - OS và version: Archlinux, Linux - 4.14.90-1-lts
 - Desktop: i3wm.
 - Phiên bản ibus-bamboo: v0.2.6

**Comment by luongthanhlam** [comment]
Hi bạn,
Lỗi 1 hiện tại chỉ xảy ra trên Firefox và bên ibus cũng đã có patch (https://github.com/ibus/ibus/issues/1980), khi nào được release mình sẽ cập nhật lại
Lỗi 2 đã được fix trong phiên bản v0.3.0 cho chế độ gõ Surrounding Text, nhờ bạn kiểm tra lại giúp

**Comment by ndgnuh99** [comment]
Cào bạn, sau khi test thì mình thấy trên thanh url của firefox gõ khá là ok rồi. Tuy nhiên thì lỗi vẫn xảy ra trên các trang như kiểu  github. Hai lỗi dễ tái hiện nhất là bị mất một chữ khi gõ một số từ   và lỗi khi xóa kí tự.
Mình --> ình
Chào --> cho mình viết từ "Chào" rồi  từ này bằng phím backspace, nhưng kí tự 'o' không bị xóa mà con trỏ sẽ nhảy về phía trước đó và xóa đi kí tự 'a', cuối cùng thì con trỏ nằm nguyên ở đó luôn..

Cái này mình test thì nó xảy ra trên Surrounding Text, còn những chế độ còn lại thì mình chưa gặp.

**Comment by luongthanhlam** [comment]
Hiện tại chrome và các ứng dụng dựa trên nền chromium như vscode, slack,... chưa hỗ trợ surrounding text nhé bạn. Trên firefox surrounding text cũng hoạt động không ổn định, nếu không phải gõ tiếng anh nhiều bạn có thể cập nhật lên phiên bản mới nhất (v0.3.4) và tắt tính năng Kiểm tra chính tả sẽ khắc phục được các lỗi trên hoặc chuyển qua Preedit (khuyên dùng).

**Comment by luongthanhlam** [comment]
Bản v0.4.0 đã khắc phục đc lỗi surrounding text trên firefox nhé :v

**Comment by ndgnuh** [comment]
Bạn ơi sau khi test thì mình thấy rằng:
- Surrounding text vẫn bị lỗi trên ff, cách dễ nhất tái hiện là lên facebook viết một cái stt
- Lỗi trên thanh url (lỗi gõ chữ) đã được khắc phục cho chế độ ForwardKeyEvent. 
- Chế độ XTestFakeKeyEvent thì ban đầu gõ bình thường, sau tầm 3 - 4 từ thì khung nhập text sẽ bị đơ vài giây, sau đó sẽ có kí tự lỗi.
Chế độ ForwardKeyEvent hoạt động khá tốt. Mình vẫn dùng nó từ các bản trước tới giờ, có lẽ bạn nên đưa nó làm chế độ mặc định.

**Comment by manhnt9** [comment]
Mình đang dùng mode số 3, gõ bình thường trên bản 0.4.5.

**Comment by ndgnuh** [comment]
Thôi lỗi này close được rồi, đã có những chế độ dùng khá ổn định trên firefox.

**Comment by luongthanhlam** [comment]
lỗi không hiện thanh gợi ý trên firefox sẽ được xử lý trong bản 0.4.6

**Comment by ndgnuh** [comment]
> lỗi không hiện thanh gợi ý trên firefox sẽ được xử lý trong bản 0.4.6

![image](https://user-images.githubusercontent.com/33273948/56502914-41edec00-653e-11e9-965a-bc587228d0c0.png)
