### ISSUE TITLE
ibus-bamboo bị frozen (unresponsive) khi switch giữa 2 windows (telegram sử dụng vi, firefox sử dụng vi)

### ISSUE THREAD

**Issue by minimal-dev** [BambooEngine/ibus-bamboo#81]
**Mô tả lỗi**
Một mô tả ngắn gọn về lỗi đang xảy ra

**Các bước tái hiện lỗi**
1. Mở Telegram với language là vi
2. Mở Firefox với language là vi
3. Quay trở lại Telegram thì không thể gõ được chữ, tổ hợp (Shift + ~) cũng không hoạt động.
4. Chuyển đổi Telegram sang en rồi quay lại vi thì gõ bình thường.

**Môi trường**
 - Ubuntu 19.04
 - Desktop: Mặc địnhđịnh
 - Phiên bản ibus-bamboo: v0.5.6

**Thông tin thêm**
- telegram & firefox được cài đặt từ trang chủ & download về

**Comment by luongthanhlam** [comment]
Có vẻ trùng với #82 ?

**Comment by luongthanhlam** [comment]
Fixed https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1844853
