### ISSUE TITLE
Không dùng được với telegram

### ISSUE THREAD

**Issue by ductm54** [BambooEngine/ibus-bamboo#82]
Sử dụng với telegram-desktop trong ubuntu 18.04 không được. dùng ở các chương trình khác bình thường

**Comment by thuandt** [comment]
Ubuntu mới update ibus, lỗi này không phải của bản thân engine :)

**Comment by thanhngch** [comment]
mình cũng bị lỗi này, cả skype bản mới cũng không sử dụng được. bản skype cũ thì gõ được bình thường.

**Comment by mrskyit6** [comment]
Mình cũng đang bị lỗi này, ức chế quá

**Comment by huyndnse63331** [comment]
up vote luôn =))) ức chế thật, @ltlam93 bạn có cách nào fix cho phiên bản sau không vậy?

**Comment by luongthanhlam** [comment]
Trong thời gian đợi ibus đc fix, mọi người tạm thời downgrade xuống bản
1.5.19-1ubuntu2

sudo apt-get install ibus=1.5.19-1ubuntu2 gir1.2-ibus-1.0=1.5.19-1ubuntu2

reboot

**Comment by thanhngch** [comment]
> Trong thời gian đợi ibus đc fix, mọi người tạm thời downgrade xuống bản 1.5.19-1ubuntu2 sudo apt-get install ibus=1.5.19-1ubuntu2 gir1.2-ibus-1.0=1.5.19-1ubuntu2 reboot

Mình không cài được trên bản ubuntu 18.04

```
ibus is already the newest version (1.5.17-3ubuntu5.1).
Selected version '1.5.17-3ubuntu5.1' (Ubuntu:18.04/bionic-security, Ubuntu:18.04/bionic-updates [amd64]) for 'ibus'
Selected version '1.5.17-3ubuntu5.1' (Ubuntu:18.04/bionic-security, Ubuntu:18.04/bionic-updates [amd64]) for 'gir1.2-ibus-1.0'
```

Khi cài bản 1.5.19 thì báo lỗi

```
E: Version '1.5.19*' for 'ibus' was not found
E: Version '1.5.19*' for 'gir1.2-ibus-1.0' was not found
```

**Comment by thanhngch** [comment]
Riêng Skype có một cách fix đơn giản là thay vì tải skype từ snap thì download file .dep skype từ trang chủ rồi cài đặt.

```
sudo snap remove skype
sudo dpkg -i skypeforlinux-64.deb
```

**Comment by luongthanhlam** [comment]
@thanhngch với ubuntu 18.04 bạn thay 1.5.19-1ubuntu2 bằng 1.5.17-3ubuntu5 nhé

**Comment by luongthanhlam** [comment]
Fixed https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1844853
