### ISSUE TITLE
Không gõ được tiếng việt trên ứng dụng Qt

### ISSUE THREAD

**Issue by vuminhcongvmc** [BambooEngine/ibus-bamboo#83]
**Mô tả lỗi**
Mình không thể gõ tiếng việt trên phần mềm viết bằng Qt 

**Các bước tái hiện lỗi**
Mở chương trình Kate, Texmaker, Texstudio, Konsole, LibreOffice...hay các

 ứng dụng viết bằng Qt và gõ thì không thể gõ được tiếng việt.

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Ảnh chụp màn hình:
![image](https://user-images.githubusercontent.com/45608242/65316160-9b2c7b00-dbc3-11e9-8151-5160eb59b6e1.png)
Video tái hiện lỗi:
https://drive.google.com/file/d/1-z7h7ndJ5aBUT_JLSV4K4jrvd9KB3M8v/view?usp=sharing

**Môi trường**
 - OS và version: Kubuntu 19.04
 - Desktop: KDE
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.5.7)

**Comment by chidihn** [comment]
Mình dùng viber và mindmaster cũng tự nhiên không viết được nữa , mặc dù hôm qua viết bình thường

**Comment by luongthanhlam** [comment]
Tạm thời các bạn downgrade ibus xuống bản 1.5.19-1ubuntu2

```
sudo apt-get install ibus=1.5.19-1ubuntu2 gir1.2-ibus-1.0=1.5.19-1ubuntu2
```
rồi khởi động lại máy.

>
