### ISSUE TITLE
Ứng dụng Qt lại không gõ được như trước (Telegram)

### ISSUE THREAD

**Issue by manhnt9** [BambooEngine/ibus-bamboo#84]
**Mô tả lỗi**
Mình không chuyển được chế độ gõ sang tiếng Việt trong Telegram.

**Môi trường**
    OS và version: Ubunty 18.04
    Desktop: XFCE 4.12
    Phiên bản ibus: IBus 1.5.17
    Phiên bản ibus-bamboo: v0.5.7

**Comment by luongthanhlam** [comment]
Bạn gửi giúp mình output lệnh này `apt list --installed|grep ibus`

**Comment by manhnt9** [comment]
apt list --installed|grep ibus

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gir1.2-ibus-1.0/bionic-updates,bionic-security,now 1.5.17-3ubuntu5.1 amd64 [installed,automatic]
ibus/bionic-updates,bionic-security,now 1.5.17-3ubuntu5.1 amd64 [installed,automatic]
ibus-bamboo/bionic,now 0.5.7-0~201909190536~ubuntu18.04.1 amd64 [installed]
ibus-teni/bionic,now 1.5.2-1~ubuntu18.04.1 amd64 [installed]
ibus-unikey/bionic,now 0.6.1-1.1 amd64 [installed]
libibus-1.0-5/bionic-updates,bionic-security,now 1.5.17-3ubuntu5.1 amd64 [installed,automatic]
libibus-1.0-dev/bionic-updates,bionic-security,now 1.5.17-3ubuntu5.1 amd64 [installed,automatic]
libusageenvironment3/bionic,now 2018.02.18-1 amd64 [installed,automatic]
libusb-1.0-0/bionic,now 2:1.0.21-2 amd64 [installed]
libusbmuxd4/bionic,now 1.1.0~git20171206.c724e70f-0.1 amd64 [installed]
libusbredirparser1/bionic,now 0.7.1-1 amd64 [installed,automatic]

**Comment by luongthanhlam** [comment]
Ibus 1.5.17-3ubuntu5.1 đang bị lỗi, bạn nên upgrade lên bản mới hơn, hoặc
downgrade xuống 1.5.17-3ubuntu5
`sudo apt-get install ibus=1.5.17-3ubuntu5 gir1.2-ibus-1.0=1.5.17-3ubuntu5`

**Comment by manhnt9** [comment]
Thanks bạn, mình thư thì gặp lỗi này:
```
sudo apt-get install ibus=1.5.17-3ubuntu5 gir1.2-ibus-1.0=1.5.17-3ubuntu5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.5.17-3ubuntu5' for 'ibus' was not found
E: Version '1.5.17-3ubuntu5' for 'gir1.2-ibus-1.0' was not found
```

**Comment by luongthanhlam** [comment]
Bạn thử đổi server xem

**Comment by manhnt9** [comment]
Đã thử server nhân hòa nhưng cũng không được. Gõ trong Skype cũng đang bị lỗi bạn ạ.

**Comment by manhnt9** [comment]
Shift ~ không có tác dụng trong Skype mặc dù chuyển được mode gõ tiếng Việt. Trong Skype bị lỗi dấu, lặp chữ.

**Comment by luongthanhlam** [comment]
Bạn nên thử với US server hoặc Main server, server ở VN thường cập nhật chậm hơn.

**Comment by luongthanhlam** [comment]
nếu vẫn chưa thấy bản vá cho ibus bạn có thể báo lỗi ở đây https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1844853, mình nghĩ có thể đóng issue này lại được rồi.
