### ISSUE TITLE
không gõ được trong wps-writer

### ISSUE THREAD

**Issue by huuthang99** [BambooEngine/ibus-bamboo#88]
**Mô tả lỗi**
em dùng ibus-bamboo gõ trong wps-writer gõ xong enter hay space đều nó hiện lên thêm 2 trang trắng nữa , còn trong wps Spreadsheets thì gõ được bình thường ạ , em dùng kde plasma

**Comment by luongthanhlam** [comment]
bạn có thể đính kèm ảnh hoặc video để mô tả rõ hơn không? lỗi này có xảy ra khi tắt bộ gõ không bạn?
