### ISSUE TITLE
Không gõ tiếng việt được trong Notepadqq, goldendict (dùng QT library) 

### ISSUE THREAD

**Issue by Hassenky** [BambooEngine/ibus-bamboo#89]
Hi Anh Em phát triển,

Tình hình là không gõ tiếng Việt được trên Notepadqq và goldendict (dùng qt 5) nhé anh em. Hệ điều hành đang sử dụng là Manjaro 18.10.

**Comment by luongthanhlam** [comment]
Bên ibus đang tích cực fix lỗi này, bạn theo dõi ở đây nhé https://github.com/ibus/ibus/issues/2137

**Comment by Hassenky** [comment]
Thanks luongthanhlam nhé.

**Comment by ndgnuh** [comment]
Mình nghĩ họ fix ở những bản sau rồi. Mình đang dùng ibus 1.5.21 và gõ trên ứng dụng QT khá bình thường (falcon, liri-browser)

**Comment by phamlenhan** [comment]
Mình đang xài ibus 1.5.21 đây mà. Bạn thử notepadqq với goldendict thử có được với.

**Comment by ndgnuh** [comment]
![image](https://user-images.githubusercontent.com/33273948/67377335-b2d69500-f5af-11e9-9a98-92e9c015ad44.png)

Mình gõ trong golden dict đây bạn ơi. Bình thường mà.

Desktop mình đang dùng là Sway, biến môi trường:
```sh
~/ > env | grep QT
QT4_IM_MODULE=ibus
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=qt5ct
```
Thêm nữa bạn thử set engine một cách thủ công rồi gõ thử xem. Vì GUI không hoạt động trên Wayland nên mình dùng script để chuyển Engine
```sh
ibus engine Bamboo
```

**Comment by Hassenky** [comment]
Phải set egine thủ công để để gõ trên qt app mới được. Giờ dùng ngon lành rồi. Thanks ndgnuh nhé. Mình dùng Xfce (chạy X server chứ không phải Wayland).

**Comment by ndgnuh** [comment]
Cái GUI đổi engine đôi lúc buggy nên mình viết cái script để chuyển giữa các engine. Nếu dùng các engine khác thì các bạn thêm vào biến `engines` ở dưới, cách nhau bởi dấu ','. Để xem danh sách các engine có thể dùng `ibus list-engine`.

Chỉ cần xóa phím tắt trong ibus-setup và gắn phím tắt đó để chạy script này thì các bạn sẽ chuyển giữa các bộ gõ như bình thường.

```sh
#!/bin/sh
engines="xkb:us::eng,Bamboo"
first_engine=$(echo $engines | cut -d ',' -f 1)
cur_next_engines=$(echo $engines \
	| tr ',' '\n' \
	| grep  $(ibus engine) -A 1 \
)
# echo $cur_next_engines
next_engine=$(echo $cur_next_engines \
	| tr ' ' '\n' \
	| tail -n 1 \
)

if [ "$cur_next_engines" = "$next_engine" ]; then
	next_engine=$first_engine
fi

# echo $next_engine
ibus engine $next_engine
```

**Comment by phamlenhan** [comment]
Lỗi được fix rồi hay sao đó anh em. Chạy ngon lành rồi.
