### ISSUE TITLE
khong cai dat duoc tren deepin linux base on debian

### ISSUE THREAD

**Issue by vietvuong302** [BambooEngine/ibus-bamboo#90]
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Deepin/stable

nhap lenh 
sudo apt-get install ibus-bamboo
bao E: Unable to locate package ibus-bamboo

linux deepin moi truong mac dinh

hinh minh hoa https://ibb.co/rthLtmx

xin loi cac ban, minh moi chuyen sang dung linux va van chua tim ra cach de go tieng viet!
Mong nhan duoc su giup do

**Comment by anphn** [comment]
bạn add repo bị lỗi rồi.
/usr/share/python-apt/templates/Deepin.info sửa Suilte thành stable.
chạy lại lệnh sudo 
``` bash
add-apt-repository ppa:bamboo-engine/ibus-bamboo
```

**Comment by vietvuong302** [comment]
> bạn add repo bị lỗi rồi.
> 
> ```shell
> vim /usr/share/python-apt/templates/Deepin.info 
> sửa Suilte thành stable.
> ```
> 
> chạy lại lệnh sudo
> 
> ```shell
> add-apt-repository ppa:bamboo-engine/ibus-bamboo
> ```

mình đã làm theo, tới lệnh thì lỗi như sau, search google mà vẫn chưa giải quyết được, bạn giúp mình với!!!
 
sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo
 IBus Bamboo - Bộ gõ tiếng Việt cho Linux
===================================

### Sơ lược tính năng
* Hỗ trợ tất cả các bảng mã phổ biến:
  - Unicode, TCVN (ABC)
  - VIQR, VNI, VPS, VISCII, BK HCM1, BK HCM2,…
  - Unicode UTF-8, Unicode NCR - for Web editors.
* Nhiều kiểu gõ:
  - Simple Telex, Telex 2, Telex 3
  - VNI, VIQR, Microsoft layout
  - Telex + VNI + VIQR
* Nhiều tính năng hiện đại:
  - Kiểm tra chính tả (sử dụng từ điển/luật ghép vần)
  - Dấu thanh chuẩn và dấu thanh kiểu mới
  - Bỏ dấu tự do, Gõ tắt (macro), Emoji,...
* Sử dụng phím tắt <Shift> + ~ để loại trừ ứng dụng không dùng bộ gõ, chuyển qua lại giữa các chế độ gõ:
  - Preedit (default)
  - Surrounding text, IBus ForwardKeyEvent, XTestFakeKeyEvent,... 
 More info: https://launchpad.net/~bamboo-engine/+archive/ubuntu/ibus-bamboo
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpft6m2qgf/pubring.gpg' created
gpg: /tmp/tmpft6m2qgf/trustdb.gpg: trustdb created
gpg: key 36ED424E9659D014: public key "Launchpad PPA for bamboo-engine" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'

**Comment by luongthanhlam** [comment]
Cài từ obs thì sao bạn https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo

**Comment by vietvuong302** [comment]
> Cài từ obs thì sao bạn https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo

Cảm ơn anh đã hỗ trợ, em đã cài được. Nhưng lại không gõ được tiếng việt. Hiện tại em đang dùng fcitx-unikey để gõ, bộ gõ này bị lỗi trên chrome rất khó chịu, mong anh hỗ trợ để bộ gõ ibus-bamboo hoạt động trên deepin 15.11.
Không hiểu sao em cài bộ gõ ibus-unikey cũng không gõ được tiếng việt.
Cam on anh da ho tro.
Em moi go cai dat fcitx-unikey de cai ibus-bamboo, nen khong go duoc tieng viet nua mong anh thong cam.
Em da them
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus
vao file /etc/bash.bashrc va /etc/profile, khoi dong lai may, kiem tra bang lenh 
env | grep "IM_MODULE\|XMODIFIERS"
ket qua tra ve la 
CLUTTER_IM_MODULE=ibus
QT4_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
GTK_IM_MODULE=ibus
nhung van khong go duoc tieng viet. Mong anh giup do a!

**Comment by ndgnuh** [comment]
Nếu phần mềm bạn dùng là gói snap hay flatpak thì có khả năng ibus không hoạt động với nó.

**Comment by vietvuong302** [comment]
> Nếu phần mềm bạn dùng là gói snap hay flatpak thì có khả năng ibus không hoạt động với nó.

em khong go duoc tieng viet tren tat ca cac phan mem a!

**Comment by luongthanhlam** [comment]
khi bạn chạy `ibus-daemon -vxr` có xuất hiện lỗi gì không? phiên bản ibus bạn đang dùng là gì (kiểm tra bằng lệnh `dpkg -s ibus|grep Version`)?

**Comment by vietvuong302** [comment]
> khi bạn chạy `ibus-daemon -vxr` có xuất hiện lỗi gì không? phiên bản ibus bạn đang dùng là gì (kiểm tra bằng lệnh `dpkg -s ibus|grep Version`)?
Em dang dung ibus 1.5.14-3
dpkg -s ibus|grep Version
Version: 1.5.14-3
con lenh ibus-daemon -vxr thi no ra the nay a!

(ibus-ui-gtk3:9346): IBUS-WARNING **: panel.vala:221: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:9346): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
2019/10/27 19:43:49 FocusIn.
Enable.WM_CLASS=(deepin-terminal:Deepin-terminal)
RECORD extension for local server is version 1.13
ButtonPress: /t1, rootX=538, rootY=58, recording=1ButtonPress: /t1, rootX=736, rootY=767, recording=1ButtonPress: /t1, rootX=830, rootY=718, recording=1ButtonPress: /t1, rootX=333, rootY=386, recording=1ButtonPress: /t1, rootX=333, rootY=386, recording=1ButtonPress: /t1, rootX=551, rootY=749, recording=1ButtonPress: /t5, rootX=827, rootY=380, recording=1ButtonPress: /t5, rootX=827, rootY=380, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t5, rootX=813, rootY=224, recording=1ButtonPress: /t1, rootX=874, rootY=170, recording=1ButtonPress: /t1, rootX=766, rootY=222, recording=1ButtonPress: /t1, rootX=711, rootY=192, recording=1ButtonPress: /t1, rootX=711, rootY=192, recording=1ButtonPress: /t1, rootX=455, rootY=601, recording=1ButtonPress: /t1, rootX=455, rootY=601, recording=1ButtonPress: /t1, rootX=527, rootY=755, recording=1ButtonPress: /t1, rootX=868, rootY=245, recording=1ButtonPress: /t1, rootX=762, rootY=214, recording=1ButtonPress: /t1, rootX=430, rootY=588, recording=1ButtonPress: /t1, rootX=430, rootY=588, recording=1ButtonPress: /t1, rootX=898, rootY=347, recording=1ButtonPress: /t1, rootX=848, rootY=371, recording=1ButtonPress: /t1, rootX=848, rootY=371, recording=1ButtonPress: /t1, rootX=796, rootY=415, recording=1ButtonPress: /t1, rootX=523, rootY=578, recording=1ButtonPress: /t1, rootX=574, rootY=622, recording=1ButtonPress: /t5, rootX=574, rootY=622, recording=1ButtonPress: /t5, rootX=574, rootY=622, recording=1ButtonPress: /t5, rootX=574, rootY=622, recording=1ButtonPress: /t5, rootX=574, rootY=622, recording=1ButtonPress: /t4, rootX=574, rootY=622, recording=1ButtonPress: /t4, rootX=574, rootY=622, recording=1ButtonPress: /t1, rootX=611, rootY=572, recording=1ButtonPress: /t4, rootX=611, rootY=572, recording=1ButtonPress: /t4, rootX=611, rootY=572, recording=1ButtonPress: /t5, rootX=611, rootY=572, recording=1ButtonPress: /t4, rootX=611, rootY=572, recording=1ButtonPress: /t4, rootX=611, rootY=572, recording=1ButtonPress: /t1, rootX=560, rootY=565, recording=1ButtonPress: /t5, rootX=391, rootY=566, recording=1ButtonPress: /t5, rootX=391, rootY=566, recording=1ButtonPress: /t1, rootX=599, rootY=581, recording=1ButtonPress: /t5, rootX=650, rootY=559, recording=1ButtonPress: /t5, rootX=650, rootY=559, recording=1ButtonPress: /t5, rootX=650, rootY=559, recording=1ButtonPress: /t1, rootX=650, rootY=559, recording=1ButtonPress: /t4, rootX=650, rootY=559, recording=1ButtonPress: /t4, rootX=650, rootY=559, recording=1ButtonPress: /t1, rootX=604, rootY=610, recording=1ButtonPress: /t1, rootX=585, rootY=425, recording=1ButtonPress: /t1, rootX=451, rootY=639, recording=1ButtonPress: /t1, rootX=451, rootY=639, recording=12019/10/27 19:45:03 FocusOut.
2019/10/27 19:45:03 FocusIn.
WM_CLASS=(google-chrome-stable:Google-chrome-stable)
Reset.2019/10/27 19:45:03 FocusOut.
2019/10/27 19:45:03 FocusIn.
WM_CLASS=(google-chrome-stable:Google-chrome-stable)
ButtonPress: /t1, rootX=499, rootY=564, recording=1ButtonPress: /t5, rootX=499, rootY=564, recording=1ButtonPress: /t5, rootX=499, rootY=564, recording=1ButtonPress: /t1, rootX=548, rootY=747, recording=1ButtonPress: /t1, rootX=821, rootY=232, recording=1ButtonPress: /t1, rootX=767, rootY=223, recording=1ButtonPress: /t1, rootX=369, rootY=542, recording=1ButtonPress: /t1, rootX=526, rootY=701, recording=1ButtonPress: /t1, rootX=337, rootY=590, recording=1ButtonPress: /t1, rootX=388, rootY=562, recording=1ButtonPress: /t1, rootX=431, rootY=561, recording=1ButtonPress: /t4, rootX=431, rootY=561, recording=1ButtonPress: /t4, rootX=431, rootY=561, recording=1ButtonPress: /t1, rootX=328, rootY=559, recording=1ButtonPress: /t1, rootX=547, rootY=748, recording=1ButtonPress: /t1, rootX=766, rootY=159, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t4, rootX=835, rootY=262, recording=1ButtonPress: /t5, rootX=835, rootY=262, recording=1ButtonPress: /t1, rootX=779, rootY=392, recording=1ButtonPress: /t5, rootX=994, rootY=426, recording=1ButtonPress: /t5, rootX=994, rootY=426, recording=1ButtonPress: /t5, rootX=1089, rootY=410, recording=1

**Comment by luongthanhlam** [comment]
bạn gõ 1, 2 từ tiếng Việt vào màn hình terminal trên rồi gửi log cho mình nhé

**Comment by vietvuong302** [comment]
terminal khong go duoc tieng viet a. Va lam sao de em gui duoc file log cho anh?

**Comment by ndgnuh** [comment]
> No global engine

set engine lại fail rồi. Bạn chạy `ibus engine Bamboo` rồi gõ thử xem.

Thêm nữa, bạn đăng output của cái này cho mình với.

```sh
echo $XDG_SESSION_TYPE
```

**Comment by vietvuong302** [comment]
day la khi khong bat ibus
ibus engine Bamboo

(process:13976): IBUS-CRITICAL **: ibus_bus_set_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
Set global engine failed.
con khi bat ibus nhap lenh nay khong hien ra gi ca
![DeepinScreenshot_20191027200422](https://user-images.githubusercontent.com/23705062/67635043-0b31cd80-f8f5-11e9-8547-c3c983183bef.png)

**Comment by luongthanhlam** [comment]
chrome và opera đang có lỗi với ibus, tạm thời khi nào gặp lỗi bạn khởi động lại chrome/opera nhé

**Comment by vietvuong302** [comment]
Em vua khoi dong lai may tinh, tat ca van nhu the, tru chrome va opera. Em cam on anh da ho tro a. Khong biet con cach nao de sua loi khong a?

**Comment by luongthanhlam** [comment]
Dùng tạm AVIM đi bạn:disappointed:  https://chrome.google.com/webstore/detail/avim-vietnamese-input-met/opgbbffpdglhkpglnlkiclakjlpiedoh?utm_source=chrome-ntp-iconcry

Tính năng Ẩn gạch chân phải do ứng dụng implement, bộ gõ không làm gì đc bạn nhé. Nếu thấy khó chịu bạn có thể thử tính năng  [Sửa lỗi gạch chân](https://github.com/BambooEngine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng)

**Comment by vietvuong302** [comment]
Em cảm ơn anh đã hỗ trợ ạ, hy vọng team mình sẽ sớm khắc phục được lỗi này ạ. Chúc anh buổi tối vui vẻ, cảm ơn anh và team đã đóng góp cho cộng đồng linux Việt ạ!

**Comment by anphn** [comment]
https://bbs.deepin.org/archiver/?tid-166710.html&fbclid=IwAR0gRNXxDkct3yh1-25oCEMsR_CSwJQvk8dmcVVgWLZg3Fcc48xAF0YI5kU  
@vietvuong302 bạn cài thêm các gói cần thiết mới dùng được cho deepin nhá. Không cần phải đặt biến env gì đâu

**Comment by vietvuong302** [comment]
> https://bbs.deepin.org/archiver/?tid-166710.html&fbclid=IwAR0gRNXxDkct3yh1-25oCEMsR_CSwJQvk8dmcVVgWLZg3Fcc48xAF0YI5kU
> @vietvuong302 bạn cài thêm các gói cần thiết mới dùng được cho deepin nhá. Không cần phải đặt biến env gì đâu

Quá tuyệt vời, cảm ơn anh, từ nay có thể xài linux làm hệ điều hành chính được rồi.
Chân thành cảm ơn nhóm tác giả của ibus-bamboo, các anh thật tuyệt vời!
Tóm tắt hướng dẫn lại cho bạn nào từ google cũng đang đi tìm cách gõ tiếng việt trên Deepin Linux


Đầu tiên cài ibus-bamboo, có thể làm theo hướng dẫn từ github bamboo hoặc tải về từ open sure 
https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo
Tiếp theo chạy lệnh sudo apt install ibus dconf-editor từ Terminal, nhập mật khẩu vào rồi enter.
Tiếp theo im-config -a, 
(nếu kết quả trả về là zenty not found thì nhập lệnh sudo apt-get install zenity
chạy lại lệnh im-config -a)
chọn ibus từ cửa sổ mới hiện ra.
tiếp theo nhập lệnh dconf-editor
tìm tới desktop->ibus->general sau đó chuyển dòng "enable-by-default" từ false thành true.
sau đó reboot. Nếu vẫn chưa gõ được tiếng việt thì làm tiếp
sudo apt install ibus
sudo apt install ibus-gtk
sudo apt install ibus-gtk3
sudo apt install ibus-qt1
sudo apt install ibus-qt4
sudo apt install ibus-pinyin
sudo apt install im-config
gỡ bỏ các tệp thừa của ibus
sudo rm -f /usr/share/im-config/data/23_ibus.*
Khởi động lại và tận hưởng.
Nếu thành công, vui lòng quay lại đây và cảm ơn nhóm tác giả ibus-bamboo đặc biệt là anh @luongthanhlam, @anphn đã hỗ trợ giúp chúng ta!
Chúc các bạn may mắn!
