### ISSUE TITLE
Lỗi gõ tiếng Anh

### ISSUE THREAD

**Issue by thanhngch** [BambooEngine/ibus-bamboo#91]
**Mô tả lỗi**
Lỗi gõ tiếng Anh khi bật kiểm tra chính tả.

**Các bước tái hiện lỗi**

Gõ `base` ra `base` (đúng)
`position` ra `position` (đúng)
`arranged` ra `aranged` (sai)
`office` ra `ofice` (sai)

**Kết quả mong muốn**
Bật chế độ kiểm tra chính tả thì gõ từ nào thì ra từ đó.

**Môi trường**
 - OS và version: (ví dụ: Xubuntu 18.04 LST)
 - Desktop: (Xfce)
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.5.8)

**Comment by luongthanhlam** [comment]
Hiện tại ibus bamboo chỉ hỗ trợ kiểm tra chính tả cho tiếng Việt thôi bạn =))
Khi bạn gõ `of` bộ gõ sẽ cố gắng chuyển thành tiếng Việt là `ò`, gõ tiếp `f` bộ gõ sẽ hiểu rằng bạn muốn gõ tiếng anh và hoàn tác phím `f` thành `of`. Muốn gõ `off` bạn buộc phải gõ phím `f` 3 lần
