### ISSUE TITLE
Bamboo không gõ được tiếng việt khi chuyển cửa sổ

### ISSUE THREAD

**Issue by voxvanhieu** [BambooEngine/ibus-bamboo#93]
**Mô tả lỗi**
Bamboo sẽ không hoạt động nữa sau khi chuyển sang cửa sổ khác rồi chuyển về lại cửa sổ đang làm việc. Phải chuyển sang bộ gõ tiếng anh (win + space) và chuyển về bamboo thì mới gõ được.

**Các bước tái hiện lỗi**
1. Bật bamboo
2. Bật firefox và gõ tiếng việt -> bình thường
3. Mở một của  sổ khác lên.
4. Về lại firefox -> không còn gõ được nữa.

**Thông tin khác**
- Ubuntu 19.10
- Lỗi khi xuất hiện khi không.

**Comment by luongthanhlam** [comment]
Bạn cập nhật lên bản 0.6.1 và kiểm tra lại giúp mình nhé!

**Comment by voxvanhieu** [comment]
Đã hết lỗi ạ!
