### ISSUE TITLE
Khi dùng kiểu gõ Telex thì không nhập số trực tiếp vào ô của Google Spreadsheets được

### ISSUE THREAD

**Issue by harn2412** [BambooEngine/ibus-bamboo#94]
**Mô tả lỗi**
Không thể nhập số trực tiếp vào ô của Google Spreadsheets được khi dùng kiểu gõ Telex.

**Các bước tái hiện lỗi**
- Mở Google Chrome và truy cập vào Google Spreadsheets, tạo mới một bảng tính bất kỳ.
- Click chuột vào một ô bất kì.
- Nhập liệu số bằng dãy phím số ở phía dưới các phím function sẽ không được.
- Muốn gõ được thì phải nhấn mồi phím F2 hoặc Enter.

**Thông tin thêm**
- Kiểm tra khi mở Google Spreadsheets với Firefox thì không bị tình trạng trên.
- Kiểm tra nhập liệu bằng phím số của bàn phím numlock thì vẫn được.

**Thông tin hệ thống**
- Linux Mint 19.2 Cinnamon
- Linux Kernel 4.15.0-66-generic
- Chrome Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by maxiqboy** [comment]
Hình như có lỗi với Google Sheet thì phải, mình còn không gõ được chữ nữa cơ, tắt đi thì được,

**Comment by luongthanhlam** [comment]
Cám ơn bạn, lỗi đã được fix ở bản 0.6.1 rồi nhé!

**Comment by harn2412** [comment]
lỗi này lại bị lại với phiên bản 0.6.2 nhưng chỉ bị với chế độ gõ mặc định (Pre-edit) các chế độ gõ khác không bị.
Không biết mình có cần tạo Issues mới không?

**Thông tin hệ thống**
Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Linux Mint 19.02 Cinnamon
Kenel 4.15.0-70-generic

**Comment by luongthanhlam** [comment]
bạn cài từ mã nguồn và thử lại xem

**Comment by harn2412** [comment]
mình xác nhận là cài đặt từ source thì không gặp vấn đề nữa
