### ISSUE TITLE
Lỗi gõ dấu mũ cho chữ o, e

### ISSUE THREAD

**Issue by Trieste96** [BambooEngine/ibus-bamboo#95]
**Mô tả lỗi**
Lỗi gõ dấu mũ cho chữ bắt đầu bằng o.

**Các bước tái hiện lỗi**
1. Chọn một trong các chế độ gõ 2 (Surrounding Text), kiểu gõ VNI.
2. Gõ chữ o rồi gõ dấu bất kỳ.

**Kết quả mong muốn**
ó ò ỏ õ ọ ô ơ 

**Kết quả thực tế**
oó oò oỏ oõ oọ oô oơ

**Môi trường**
 - OS và version: Linux Mint 19.2 Tina
 - Desktop: mặc định
 - Phiên bản ibus-bamboo: v0.6.1

**Thông tin thêm**
Cài đặt từ apt-get, test trên google chrome.

**Comment by luongthanhlam** [comment]
hiện tại chrome chưa hỗ trợ gửi phím backspace qua api surrounding text bạn nhé, xem thêm https://github.com/bambooengine/ibus-bamboo#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng
