### ISSUE TITLE
Khi gõ hay bị thêm nhân đôi chữ cái đầu tiên.

### ISSUE THREAD

**Issue by maiphuc96** [BambooEngine/ibus-bamboo#96]
**Mô tả lỗi**
Chữ cái đầu tiên bị nhân đôi lên nhưng lúc bị lúc không, thường hay bị khi gõ trên d-menu, terminal(xterm), firefox. Thường xảy ra là khi vừa mở chương trình lên 

**Kết quả mong muốn**
gõ 'abc' thì nó lại ra là 'aabc'

**Comment by luongthanhlam** [comment]
bạn thử cài từ mã nguồn xem còn bị lỗi này không?

**Comment by maiphuc96** [comment]
@luongthanhlam ukm để mình thử

**Comment by maiphuc96** [comment]
@luongthanhlam  
Mình cài lại từ mã nguồn rồi vô https://10fastfingers.com/typing-test/vietnamese gõ liên tục là nó văng lỗi ra liên tục luôn bạn

**Comment by luongthanhlam** [comment]
lỗi gì vậy bạn?

**Comment by maiphuc96** [comment]
hmm, m ngồi thử lại ngồi gõ mấy trăm chữ vô terminal thì có vài chữ nó mới bị nhân đôi cái chứ đầu tiên (nó cứ bất thường thế nào ấy), ngồi test trên cái trang 10fastfighers thì gõ hay bi nhân đôi cái chữ đầu.
- mình hay gõ lên thanh địa chỉ firefox để tìm kiếm thì nếu để chế độ mặc định nó sẽ không hiện gợi ý (phải phát sinh các phím kiểu chấm, ctrl, space,.. gì đó thì mới hiện gợi ý), mình chuyển qua chế độ surrounding text thì nó hiện gợi ý bt nhưng khi nhấn phím 'ctrl+a' rồi gõ chữ 'a' là nó thành 'â' (mình thử cái chế độ này trên libreoffice cũng bị vậy)

**Comment by luongthanhlam** [comment]
- bạn dùng hệ điều hành và trình duyệt web nào? chế độ gõ bạn dùng trên terminal và 10fastfighers là gì?
- sau khi cài đặt, bạn đã khởi động lại ibus chưa?

**Comment by maiphuc96** [comment]
Mình dùng arch, trình duyệt thì chromium và firefox, mình dùng kiểu gõ mặc định trên chromium thử thì lỗi ra rất thường xuyên, firefox cũng bị . Mình đều thử trên trang 10fastfingher đó

**Comment by luongthanhlam** [comment]
bạn có đang tắt tùy chọn "Share the same input method among all applications" không? nếu có bạn cài lại từ mã nguồn và thử lại giúp mình nhé!

**Comment by maiphuc96** [comment]
mình vẫn mở tuỳ chọn đó.

**Comment by luongthanhlam** [comment]
bạn chạy lệnh `cat ~/.config/ibus-bamboo/ibus-bamboo.config.json` rồi gửi output cho mình nhé.

**Comment by maiphuc96** [comment]
[http://codepad.org/fzcw6kYx](url)

**Comment by maiphuc96** [comment]
Hôm qua mình vừa cập nhật lại bộ gõ thì nó văng ra cái lỗi mới này khó chịu quá.
Mình gõ chữ ở thanh địa chỉ firefox xong khi gọi dmenu gõ thì cái chữ đầu nó bay ra ô pre-edit thế là mất chữ đầu luôn.
![photo_2019-11-22_19-43-20](https://user-images.githubusercontent.com/10755106/69426689-61f9be00-0d60-11ea-9bd5-247fd0a35562.jpg)

**Comment by luongthanhlam** [comment]
hmm, gửi thêm cho mình output 2 lệnh này nhé:
  - ps -ef|grep ibus
  - env | grep "IM_MODULE\|XMODIFERS"

**Comment by maiphuc96** [comment]
![image](https://user-images.githubusercontent.com/10755106/69488597-2402b400-0e9e-11ea-8542-7471198893d4.png)

**Comment by maiphuc96** [comment]
![image](https://user-images.githubusercontent.com/10755106/69488681-61b40c80-0e9f-11ea-91fd-a891189aa359.png)

**Comment by huyhoang8398** [comment]
cùng issue
```
    OS và version: Archlinux 5.8.1-arch1-1
    Desktop: i3wm
    Phiên bản ibus-bamboo: 0.6.5-1 AUR

```

**Comment by goatastronaut0212** [comment]
Mình sẽ tạm đóng lại báo cáo lỗi này. Các phiên bản mới cũng có hỗ trợ chế độ gõ rồi nên hãy thử chuyển đổi. Nếu không được thì vui lòng bạn mở 1 báo cáo lỗi mới.
