### ISSUE TITLE
Không gõ được tiếng Việt sau khi chuyển cửa sổ

### ISSUE THREAD

**Issue by kuroni** [BambooEngine/ibus-bamboo#97]
**Mô tả lỗi**
Tương tự như #93, bamboo không gõ nữa khi chuyển qua cửa sổ mới. Minh phải chuyển qua tiếng Anh rồi về lại tiếng Việt thì mới gõ được lại.

**Các bước tái hiện lỗi**
1. Mở Firefox
2. Gõ được tiếng Việt bình thường
3. Alt-tab qua cửa sổ mới (ví dụ như Discord)
4. Quay lại Firefox thì không gõ được nữa

**Môi trường**
 - OS: Arch Linux
 - Desktop: GNOME
 - Phiên bản ibus-bamboo: v0.6.1

**Comment by luongthanhlam** [comment]
bạn cài từ mã nguồn rồi khởi động lại ibus là hết lỗi nhé `ibus restart`

**Comment by kuroni** [comment]
Mình clone từ repo chính rồi cài lại vẫn bị bạn nhé.

**Comment by kuroni** [comment]
Mình nhận thấy chuyện này xảy ra khi mình không để "Share the same input method among all applications" và cả Firefox + cửa sổ mình chuyển qua (ở đây là Discord) đều dùng Bamboo. Khi mình chỉ để Firefox dùng Bamboo, Discord dùng Eng thì lỗi không xảy ra.

**Comment by luongthanhlam** [comment]
bạn cài lại từ mã nguồn và thử lại giúp mình nhé!

**Comment by kuroni** [comment]
Mình test thử và được bạn nhé, nhưng mà bây giờ có lỗi mới. Mình có nên open issue khác không hay mình comment vào đây luôn?

**Comment by luongthanhlam** [comment]
bạn tạo giúp mình issue mới nhé, thanks!
