### ISSUE TITLE
Mình đang dùng ubuntu19.10, hiện tại mình viết tiếng việt nó không hiện chữ lên, chỉ khi nào mình space hoặc chấm câu thì chữ cái mới được hiện ra. Không biết đây là lỗi của Ibus hay là của hệ thông ubuntu?

### ISSUE THREAD

**Issue by tankhausd123** [BambooEngine/ibus-bamboo#98]
**Mô tả lỗi**
Một mô tả ngắn gọn về lỗi đang xảy ra

**Các bước tái hiện lỗi**
(Mở chương trình gì, click chỗ nào, gõ những gì, điều gì xảy ra,...)
Ví dụ:
1. Mở gedit
2. Gõ abc
...
4. Thấy xyz

**Kết quả mong muốn**
Mô tả điều đáng ra phải xảy ra thay vì phát sinh lỗi bên trên.
Ví dụ: Gõ abc thì phải thấy abc chứ không phải xyz

**Ảnh chụp màn hình, hoặc clip quay màn hình**
Nếu cần thiết, hãy [đính kèm hình ảnh](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) hoặc gửi link youtube [quay lại màn hình](https://www.youtube.com/watch?v=N8M4zsqTkr4) tái hiện lỗi.

**Môi trường**
 - OS và version: (ví dụ: Ubuntu 19.04)
 - Desktop: (Xfce, KDE, Gnome,... hoặc **mặc định**)
 - Phiên bản ibus-bamboo: (bản mới nhất là v0.6.0)

**Thông tin thêm**
Các nội dung khác có liên quan đến lỗi đang xảy ra.
Ví dụ: Chương trình XYZ được cài đặt từ: (apt-get, snap, flatpak, download từ trang chủ,...)

**Lưu ý**
Trước khi gửi issue lên github, xin bạn hãy đọc lại Hướng dẫn sử dụng và Các vấn đề thường
gặp trên trang chủ ít nhất một lần nữa. Sau khi đọc kỹ hướng dẫn sử dụng và thử mọi cách rồi
mà không được, thì hãy đặt câu hỏi lên đây. Khi gửi câu hỏi xin bạn hãy mô tả chi tiết các
bước bạn đã làm, và chi tiết kết quả bạn nhận được.

**Comment by ndgnuh** [comment]
Bạn  đã đọc hướng dẫn sử dụng chưa? Mình thấy đây là hành vi bình thường của chế độ pre-edit.
