### ISSUE TITLE
Lỗi gõ tiếng việt trong PhpStorm

### ISSUE THREAD

**Issue by vinhtq115** [BambooEngine/ibus-bamboo#99]
**Mô tả lỗi**
Lỗi gõ chữ trong PhpStorm

**Các bước tái hiện lỗi**
Lỗi 1
1. Mở PhpStorm tạo file mới
2. Gõ xyz:
3. Thấy :xyz

**Kết quả mong muốn**
Gõ xyz: thì phải thấy xyz: chứ không phải :xyz

**Các bước tái hiện lỗi**
Lỗi 2
1. Mở PhpStorm tạo file mới
2. để trống line 1
3. Gõ xyz ở line 2
4. Bấm phím mũi tên trên
5. Thấy xyz nhảy lên line 1

**Kết quả mong muốn**
Gõ xyz ở line 2, khi bấm mũi tên trên thì phải thấy xyz vẫn ở line 2 chứ không phải line 1

**Ảnh chụp màn hình, hoặc clip quay màn hình**
N/A

**Môi trường**
 - OS và version: Ubuntu 19.10
 - Desktop: **mặc định**
 - Phiên bản ibus-bamboo: 0.6.2 (commit từ master@bc445e3)

**Thông tin thêm**
PhpStorm: https://www.jetbrains.com/phpstorm/
Lỗi 1 áp dụng cho cả các ký tự như ; : ' " < , > . / ? ` ~ - _ = +
Lỗi 2 áp dụng cho các nút mũi tên trên dưới trái phải
Bản Ubuntu 19.10 mình mới cài, đã test cả package trên repo và compile từ source ra thì cả 2 đều bị lỗi này.

**Comment by luongthanhlam** [comment]
Lỗi thứ nhất đã được fix ở bản 0.6.2, lỗi thứ hai là lỗi của upstream bạn nhé https://github.com/ibus/ibus/issues/2156#issuecomment-555473174. Tạm thời có thể khắc phục bằng cách nhấn Shift+~, chọn chế độ gõ 3 hoặc 4.
